### ISSUE TITLE
[TimePicker] 24h input pressing delete does not delete digits from input

### ISSUE THREAD

**Issue by Robert-Schirmer** [mui/mui-x#5743] opened 2022-08-09 16:20 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Focusing the time input and pressing delete on the keyboard does not delete the digits from the time in the input. Instead, digits that should have been deleted are replaced with 0.

https://user-images.githubusercontent.com/73501078/183703652-fae9db7e-0e2e-437f-9e2e-7cc0601ae4a5.mov

.

### Expected behavior 🤔

Focusing the time input and pressing delete on the keyboard should remove digits from the time in the input. Same as the date + time picker works.

### Steps to reproduce 🕹

Link to live example:
https://mui.com/x/react-date-pickers/localization/#12h-24h-format

Steps:
1. Click on the 24 hour time input at the end of the last digit
2. Press delete on the keyboard

### Context 🔦

As a user this behavior feels unexpected, I would expect the time digits in the input to be deleted.

### Your environment 🌎

<details>
Google Chrome (Version 103.0.5060.134)
</details>

**Comment by LukasTy** [comment] 2022-08-11 05:54
Duplicate of #5643

**Closed** 2022-08-11 05:54 UTC
Labels: duplicate
