### ISSUE TITLE
[YearCalendar]: Reset YearCalendar container's height

### ISSUE THREAD

**Issue by plaknight** [mui/mui-x#9313] opened 2023-06-13 09:11 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://stackblitz.com/edit/react-ycrix5?file=demo.tsx

Steps:
1. set YearCalendar container's height 

https://github.com/mui/mui-x/assets/52069851/bebdc651-b6c5-4bf7-a81c-0a4adfaad43d

2. switch to "year" view when the "day" view and the "year" view are not the same direction
3. select any year, then it will close.

### Current behavior 😯

it's close when you selected years

### Expected behavior 🤔

it should't be close when you selected years

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment] 2023-06-13 09:49
This looks like a duplicate of https://github.com/mui/mui-x/issues/9288.
@alexfauquette, could you confirm? 🤔

**Closed** 2023-06-13 11:39 UTC
Labels: status: needs triage
