### ISSUE TITLE
[DataGrid] Row hover styles not getting properly applied with pinned columns

### ISSUE THREAD

**Issue by Melrov** [mui/mui-x#10176] opened 2023-08-30 13:29 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/jovial-gauss-frqf44?file=/src/App.js
Issue can also be found on https://mui.com/x/react-data-grid/column-pinning/#pinning-the-checkbox-selection-column

Steps:
1. Have a table with a column pinned and row selection enabled
2. Hover over a rows value under the pinned column
3. Select the row then deselect the row ( without moving your mouse )
4. You should notice that for the row all non pinned columns do not have the hovered style

This can also be replicated for selecting non pinned columns
1. Have a table with a column pinned and row selection enabled
2. Hover over a rows value under a non pinned column
3. Select the row then deselect the row ( without moving your mouse )
4. You should notice that for the row all pinned columns do not have the hovered style

The bug also corrects it self when re hovering the the row where the hover style is not applied or un hovering the whole row and re hovering the whole row.

### Current behavior 😯

Row hover styles get removed after row selection and deselection.
If you select the row from an unpinned column the pinned columns will not have the hovered styles applyed.
If you select the row from a pinned column the unpinned columns will not have the hovered styles applyed.

### Expected behavior 🤔

Row hover styles will be applyed to both pinned and unpinned columns after row selection and deselection.

### Context 🔦

I use custom theming on your table which has more dramatic color differences between the unhovered and hovered row state. So when some columns do not style it can be very noticeable.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Bug found in chrome
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.17.1 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Chrome: 116.0.5845.140
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
```
</details>

**Comment by DanailH** [comment] 2023-09-06 10:43
@Melrov thanks for reporting this. The issue is clearly visible.

**Comment by cherniavskii** [comment] 2023-09-06 10:48
Duplicate of https://github.com/mui/mui-x/issues/7883?
We can add a recipe to https://mui.com/x/react-data-grid/style/

**Comment by DanailH** [comment] 2023-09-06 10:52
Nice, it seems that it's already handled. At that point adding a recipe would be nice.
That being said even tho there is a workaround it might be good to fix the issue from within.

**Closed** 2023-09-22 08:30 UTC
Labels: bug 🐛, component: data grid, plan: Pro, feature: Column pinning
