### ISSUE TITLE
[DateTimePicker] Cancel button doesn't work on mobile

### ISSUE THREAD

**Issue by Hock-David** [mui/mui-x#4438] opened 2022-03-29 13:07 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Changes are not canceled when the CANCEL button is pressed.
Selecting a date will fire onChange, and the date will be updated.

It has already been fixed in the DatePicker variant ( mui/material-ui#30731 )

### Expected behavior 🤔

Make the firing timing of onChange only when the OK button is pressed.

### Steps to reproduce 🕹

Steps:
It can be simply reproduced even in the component demo

1. visit https://mui.com/components/date-time-picker/#responsiveness
2. change the date in the top field
3. hit 'cancel'
4. the date will still update

**Comment by flaviendelangle** [comment] 2022-04-11 12:58
@Hock-David  can you reproduce it with the new packages `@mui/x-date-pickers` ?
I tried but without success

**Comment by kennydifiore** [comment] 2022-04-11 16:53
@Hock-David @flaviendelangle See the linked CodeSandBox above, it is using the latest mui x-date-pickers package and still reproduces the issue for me there.

**Comment by flaviendelangle** [comment] 2022-04-12 07:33
https://user-images.githubusercontent.com/3309670/162905688-4471a1ee-a5c5-4137-8dd0-5e19d551cd39.mp4

I must be missing something
Because when I hit cancel in the mobile or the responsive component, the date seems to be resetted

**Comment by yamila-fraiman** [comment] 2022-04-12 10:44
Same issue. Please provide a fix

**Comment by kennydifiore** [comment] 2022-04-14 02:31
@flaviendelangle Your video doesn't play for some reason.  However, check out the console logs...the onChange event gets fired twice, once when a date is selected in the dialog and then again when the dialog is canceled.  And the onAccept event gets fired when the dialog is canceled.  That is the issue: onAccept should definitely NOT be fired when the dialog is canceled.  I'm not sure what's best to do about onChange since it is fired twice, once with the newly selected date and then again when canceled with the original date.  Since onChange is a required prop and the most used way to trigger application logic based upon a change in date, it would make sense to me that it would only be fired after the "OK" button is clicked.  However, if onAccept behaved correctly, then one could use onAccept instead and simply provide a blank handler for onChange if one decides not to listen to each onChange event and only cares about the final result.

**Comment by flaviendelangle** [comment] 2022-04-14 07:56
OK, this relates to #4408
I think we can do two things:

- only call `onAccept` if the date we want to accept is different from the last accepted date

- only call `onChange` if the date we want to accept is different from the one we currently have in committed

_____

A few concrete examples:

If some seems weird to you I would be interested in discussing the details.

#### Scenario 1 (MobileDatePicker)

1. Open the picker (no log)
2. Click on a date (onChange)
3. Click on 'Cancel' (onChange, onClose)

#### Scenario 2 (MobileDatePicker)

1. Open the picker (no log)
2. Click on a date (onChange)
3. Click on another date (onChange)
4. Click on 'OK' (onClose, onAccept)
5. Open the picker (no log)
6. Click on 'Cancel' (onClose) 

#### Scenario 3 (MobileDateTimePicker)

1. Open the picker (no log)
2. Click on a date (onChange)
3. Click on a hour (onChange)
4. Click on a minute (onChange)
5. Click on 'OK' (onClose, onAccept)

#### Scenario 4 (MobileDateTimePicker)

1. Open the picker (no log)
2. Click on a date (onChange)
3. Click on a hour (onChange)
4. Click on a minute (onChange)
5. Click on 'Cancel' (onChange, onClose)

#### Scenario 5 (DesktopDatePicker)

1. Open the picker (no log)
2. Click on a date (onChange, onClose, onAccept)

#### Scenario 6 (DesktopDateTimePicker)

1. Open the picker (no log)
2. Click on a date (onChange)
3. Click on a hour (onChange)
4. Click on a minute (onChange, onClose, onAccept)


____

Side note, you should always provide a real `onChange` callback
Otherwise the picker might reset to the "initial" value you are providing in `props.value`.
We have a prop => state sync to let users change the value from the outside.

You can have an internal state in your component just here to pass to `props.value` + `props.onChange` and another one with the last accepted date which listens to `onAccept`.

**Comment by yamila-fraiman** [comment] 2022-04-14 09:34
Please remember there is a Clear button that should algo trigger onchange

**Comment by flaviendelangle** [comment] 2022-04-14 09:50
The behavior should be the same for `onClear`
If your current committed date is equal to the empty value, then it will not call `onChange`, otherwise it will call it.

**Comment by yamila-fraiman** [comment] 2022-04-14 12:16
But in my opinion it is a change from a value to empty. Only cancel button is not a change. If you dont trigger onchange at least I need an onclear because I need to know that a non Required field has been cleared

**Comment by yamila-fraiman** [comment] 2022-04-14 12:24
Perfecto. Thank you

**Comment by kennydifiore** [comment] 2022-04-14 15:03
> OK, this relates to #4408 I think we can do two things:
> 
> * only call `onAccept` if the date we want to accept is different from the last accepted date
> * only call `onChange` if the date we want to accept is different from the one we currently have in committed
> 
> A few concrete examples:
> 
> If some seems weird to you I would be interested in discussing the details.
> 
> #### Scenario 1 (MobileDatePicker)
> 1. Open the picker (no log)
> 2. Click on a date (onChange)
> 3. Click on 'Cancel' (onChange, onClose)
> 
> #### Scenario 2 (MobileDatePicker)
> 1. Open the picker (no log)
> 2. Click on a date (onChange)
> 3. Click on another date (onChange)
> 4. Click on 'OK' (onClose, onAccept)
> 5. Open the picker (no log)
> 6. Click on 'Cancel' (onClose)
> 
> #### Scenario 3 (MobileDateTimePicker)
> 1. Open the picker (no log)
> 2. Click on a date (onChange)
> 3. Click on a hour (onChange)
> 4. Click on a minute (onChange)
> 5. Click on 'OK' (onClose, onAccept)
> 
> #### Scenario 4 (MobileDateTimePicker)
> 1. Open the picker (no log)
> 2. Click on a date (onChange)
> 3. Click on a hour (onChange)
> 4. Click on a minute (onChange)
> 5. Click on 'Cancel' (onChange, onClose)
> 
> #### Scenario 5 (DesktopDatePicker)
> 1. Open the picker (no log)
> 2. Click on a date (onChange, onClose, onAccept)
> 
> #### Scenario 6 (DesktopDateTimePicker)
> 1. Open the picker (no log)
> 2. Click on a date (onChange)
> 3. Click on a hour (onChange)
> 4. Click on a minute (onChange, onClose, onAccept)
> 
> Side note, you should always provide a real `onChange` callback Otherwise the picker might reset to the "initial" value you are providing in `props.value`. We have a prop => state sync to let users change the value from the outside.
> 
> You can have an internal state in your component just here to pass to `props.value` + `props.onChange` and another one with the last accepted date which listens to `onAccept`.

Those scenarios make sense to me.  Thanks for looking into this.

**Closed** 2022-04-29 12:15 UTC
Labels: bug 🐛, component: pickers, component: date time picker
