### ISSUE TITLE
[data grid] re-renders causing menu in Toolbar to lose anchor

### ISSUE THREAD

**Issue by DCMattyG** [mui/mui-x#4385] opened 2022-04-07 05:01 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the Data Grid Toolbar (a feature of the Material-UI Data Grid component) if you add a menu item in the form of an IconButton with a Menu that opens when clicked, when you click said button, the Toolbar appears to re-render, which causes the Menu to lose its anchor and render in the upper left.

### Expected behavior 🤔

Menu will be able to retain its anchor point and properly display.

### Steps to reproduce 🕹

```
  function CustomToolbar() {
    return (
      <GridToolbarContainer>
        <Box
          height="65px"
          width="100%"
          display="flex"
          flexDirection="row"
          justifyContent="center"
        >
          <Box width="300px" display="flex" justifyContent="flex-start" alignItems="center">
            <GridToolbarColumnsButton sx={{ ml: 2 }} />
          </Box>
          <Box width="100%" alignSelf="center" textAlign="center">
            <Typography sx={{ flex: "1 1 100%" }} variant="h6" component="div">
              Title Goes Here
            </Typography>
          </Box>
          <Box width="300px" display="flex" justifyContent="flex-end" alignItems="center">
            <Tooltip title="Filter">
              <IconButton
                color="primary"
                component="span"
                disabled={loading}
                sx={{ mr: 2 }}
                onClick={handleMenuClick}
              >
                <FilterList />
              </IconButton>
            </Tooltip>
            <Menu
              id="basic-menu"
              anchorEl={anchorEl}
              open={open}
              onClose={() => handleClose(menuState, filters)}
              transformOrigin={{ horizontal: "right", vertical: "top" }}
              anchorOrigin={{ horizontal: "right", vertical: "bottom" }}
              PaperProps={MenuProps}
            >
              <MenuItem /> //Clipped
              <MenuItem /> //Clipped
              <MenuItem /> //Clipped
             </Menu>
          </Box>
        </Box>
      </GridToolbarContainer>
    );
  }
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
npx: installed 2 in 2.088s

  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 16.13.2 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.6 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 98.0.2
```
</details>

**Comment by alexfauquette** [comment] 2022-04-07 08:08
I tried to reproduce your problem without success. Here is an implementation base on the code you provided. I had to imagine how you set the `anchorEl` and all the menu props. Maybe that's where the difference is.

I let you modify this code sandbox to sho the problem

https://codesandbox.io/s/exportdefaulttoolbar-material-demo-forked-3od6gz?file=/demo.js

**Comment by DCMattyG** [comment] 2022-04-07 18:02
@alexfauquette, THANK YOU for this. It seems I tracked the issue to when the "rows" field on the DataGrid is set to a value of a React State.

const [tempData, setTempData] = React.useState([]);

<DataGrid
rows={tempData}
/>

This causes a re-render of the Grid every time the Filter IconButton is clicked. Any idea why that would be?

**Comment by alexfauquette** [comment] 2022-04-08 07:20
If you do not provide a full example with your bug, I can only make assumptions

Please, modify this code sandbox https://codesandbox.io/s/exportdefaulttoolbar-material-demo-forked-3od6gz?file=/demo.js such that we could talk about the same piece of code

**Comment by fgulsoy24** [comment] 2023-01-23 15:44
I have a similar problem. For example, When we have a complex component that includes custom hooks. After row[] updates It re-rendering a grid. That's why the toolbar also re-renders. Somehow It loses its internal state.
Below you can see the scenario

![mui grid](https://user-images.githubusercontent.com/14309228/214082774-f555e955-111b-4983-862b-595b9c675fcc.gif)

**Comment by alexfauquette** [comment] 2023-01-24 08:02
@fgulsoy24 would you have a reproduction example? 

I tried to reproduce your problem, but it does not seem to be the update of `rows` the problem. In the following example, I update `rows` every second, and I'm still able to use a controlled input

https://codesandbox.io/s/exportdefaulttoolbar-material-demo-forked-3od6gz?file=/demo.js

Could you provide a minimal reproduction of your code? For example a controled textfield and a button to reset rows. Such that we can investigate further?

**Comment by elInfidel** [comment] 2023-02-01 03:37
We're getting this as well. At-least using

`"@mui/x-data-grid-pro": "^5.0.1"`

It appears to also be related to changing the rows, because there's so many props it's hard to say if any prop mixing with the change in rows is causing the remount though.

I'll see if I can fork and repro and post back here with any success in doing so.

**Comment by bruno-agileengine** [comment] 2023-04-17 14:12
Has someone got around this issue?
I'm having the exact same issue with the `rows` prop. I'm filtering the array based on a Search Field, which is causing a re-render of the entire component, which then clears the state of the Search Field.

**Comment by alexfauquette** [comment] 2023-04-17 14:30
@bruno-agileengine Could you provide a minimal reproduction of your bug?

**Comment by bruno-agileengine** [comment] 2023-04-18 19:50
> @bruno-agileengine Could you provide a minimal reproduction of your bug?

@alexfauquette Here's the reproduction on codesandbox: https://codesandbox.io/s/datagrid-forked-jd3zr8?file=/src/App.tsx
It happens when the controlled input is inside `slots` props of Data Grid.
You can test it by typing in the TextField and then blurring the field, which triggers the setState on the outer component and re-renders it.

**Comment by bruno-agileengine** [comment] 2023-04-19 14:00
Thanks @alexfauquette, that solved my issue. Using quick filter was also a great idea, missed that on the documentation.

**Comment by alexfauquette** [comment] 2023-04-19 14:59
Nice 👍

Assuming the other issues are similar, I'm closing the issue. Don't hesitate to send a message with a minimal reproduction if it's not the case

**Closed by alexfauquette** 2023-04-19 14:59 UTC
Labels: component: data grid, status: needs more information

**Comment by sushilkumar2007** [comment] 2025-10-30 15:20
Reder component outside the customtoolbar , then it will work , suppose i have <popover in cutomertoolbar function then if any change in popover textfield then customtoolbar re-render , so use that popover as main ui part , then problem will be resolved
