### ISSUE TITLE
[DataGrid] NoRowsOverlay doesn't seem to work - cannot get anything to display on screen, even though component loads

### ISSUE THREAD

**Issue by aquanow-eric** [mui/mui-x#5567] opened 2022-07-22 00:31 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

No overlay shown, even though in React debugger I can see NoRowsOverlay is rendered

### Expected behavior 🤔

NoRowsOverlay rendering should show

### Steps to reproduce 🕹

Link to live example:

Steps:
1. rows prop with empty array
2. components prop:
components={{
            NoRowsOverlay: () => {
              return (
                <Box>
                  <Typography>No data</Typography>
                </Box>
              );
            }
          }}
4.          rowHeight={27}
          headerHeight={32}
          getRowId={r => r.username}
          apiRef={apiRef}
5.

### Context 🔦

Want to show some react rendering when there are no rows to display.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  latest firefox
  Output from `npx @mui/envinfo` goes here.
not getting any output from script command above. First run asks me permission to install @mui/envinfo, when I press y and enter, it just hangs.

```
</details>

theme overrides:
```

MuiDataGrid: {
      defaultProps: {
        hideFooter: true,
        disableColumnMenu: true
      },
      styleOverrides: {
        root: {
          color: "inherit",
          border: `1px solid ${colors.darkNavy}`,
          borderRadius: 0,
          fontSize: "0.75em"
        },
        cell: {
          borderBottom: `1px solid ${colors.darkNavy}`
        },
        columnHeaders: {
          backgroundColor: colors.darkNavy,
          borderBottom: `1px solid transparent`
        },
        columnHeaderTitle: {
          fontWeight: "inherit"
        },
        columnHeaderTitleContainer: {
          color: colors.lightGrey,
          fontWeight: "700"
        },
        iconSeparator: {
          color: colors.navy
        },
        virtualScroller: {
          backgroundColor: colors.blackBlue,
          "&::-webkit-scrollbar": {
            height: "12px"
          },
          "&::-webkit-scrollbar-thumb": {
            outline: "none"
          }
        }
      }
    },
```

**Comment by DanailH** [comment] 2022-07-22 09:25
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by aquanow-eric** [comment] 2022-07-22 17:12
Hi,

I cannot reproduce on codesandbox.io, which is not surprising. The code I put in works just fine there, and somehow the overlay got clobbered. The question is, how can theme or other settings clobber the overlay functionality. That I need help with since I have no idea how this can happen.

It's not just noRowsOverlay that doesn't display. Loading overlay doesn't display either

**Comment by aquanow-eric** [comment] 2022-07-25 17:05
Turns out theme.js is the issue, this one area:

```
virtualScroller: {
// setting backgroundColor causes the issue
          backgroundColor: colors.blackBlue,
          "&::-webkit-scrollbar": {
            height: "12px"
          },
          "&::-webkit-scrollbar-thumb": {
            outline: "none"
          }
        }
```

**Comment by alexfauquette** [comment] 2022-07-26 07:09
@aquanow-eric I'm closing the issue since the problem seems to be solved

**Closed by alexfauquette** 2022-07-26 07:09 UTC
Labels: component: data grid, status: needs triage
