### ISSUE TITLE
[charts] Support UTC date formatting in tooltip

### ISSUE THREAD

**Issue by monaye** [mui/mui-x#11787] opened 2024-01-22 19:41 UTC
### Summary

Currently chart accept scaleType `utc`, `time` and value to be in Date object. Could we allow `Dayjs` to be in the type? 

```
export type DatasetType<T = number | string | Date | null | undefined> = DatasetElementType<T>[];
```
https://github.com/mui/mui-x/blob/b733c3c217f32ebed9c7ac2171f7884ceb77bb86/packages/x-charts/src/models/seriesType/config.ts#L83

### Examples

I've create a simple chart using Date object vs Dayjs for the UTC time
https://codesandbox.io/p/sandbox/infallible-turing-kwvfdm?file=%2Fsrc%2FDemo.tsx%3A37%2C13-37%2C17

### Motivation

UTC time are not correctly display in the axisContent when using the Date object.

**Search keywords**: chart, dayjs, typescript

**Comment by flaviendelangle** [comment] 2024-01-23 07:27
If we support `dayjs` in the charts, we would need to support `moment` and `luxon` as well for parity.
It is something we are doing on the Date and Time Pickers but I don't think the benefit are quite the same for the charts, especially at this stage of the development.

Now it seems that `dayjs` object are working correctly in your demo. @alexfauquette will know better than me if it's safe to pass them, since we don't support them officially, we could break the support without seeing it tomorrow.

**Comment by monaye** [comment] 2024-01-23 13:36
Thank you for quick response. My bad here, looks like x-scale is plotting correctly and only tooltip content display incorrectly when using the Date object with the option "utc", which I assume is generated by the MUI, I think I should've open the defects. 
I can dig into little bit further to see if I can spot the code.

**Comment by alexfauquette** [comment] 2024-01-23 13:44
If I hunderstand correctly your point, the issue is that here the x value is `"2024-01-05T00:05:00Z"` and the x axis correctly display it as a utc, but the tooltip shows locale time (As you can see I'm in UTC+1 timezone 🇫🇷)

![image](https://github.com/mui/mui-x/assets/45398769/b620b8ec-090d-45ac-951d-39de6c349834)

That's because the tooltip is calling the value formatter which  by default is `.toLocaleString()`. I assume dayjs manages it.

A fix would be to improve the axis value formatter such that with `utc` timezone to display date at utc timezone

**Comment by shaharyar-shamshi** [comment] 2024-02-05 15:17
hello @alexfauquette I am willing to take up this issue after intial look into the code I found 

https://github.com/mui/mui-x/blob/af046548d4534dcf690efe423e1be0d2acdb91fd/packages/x-charts/src/ChartsTooltip/DefaultChartsAxisTooltipContent.tsx#L21

this code part need to changed to fix this issue.

If you can kindly assign this to me.

**Closed** 2024-02-06 12:48 UTC
Labels: bug 🐛, component: charts
