### ISSUE TITLE
[data grid] GridColDef valueGetter method's value parameter is always never

### ISSUE THREAD

**Issue by hkfi** [mui/mui-x#12927] opened 2024-04-26 22:54 UTC
### Steps to reproduce

Link to live example: (required)

https://codesandbox.io/p/sandbox/quizzical-elbakyan-yhcy5p

Steps:
1. Go to Demo.tsx
2. Look at valueGetter method's value parameter. It is typed `never`, but we should expect the type of the value of the field.

### Current behavior

The valueGetter method's value parameter is `never`.

### Expected behavior

We should expect the type of the value of the field instead of `never`. In this case we should expect a `number`.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: GridColDef, valueGetter, never

**Comment by michelengelen** [comment] 2024-04-27 11:28
related to #12914 

cc @cherniavskii

**Comment by michelengelen** [comment] 2024-04-29 10:15
possible fix for this: https://github.com/mui/mui-x/issues/12914#issuecomment-2082328462

**Comment by michelengelen** [comment] 2024-04-30 07:54
I will close this issue, as it is basically a duplicate of #12914 ... just for a different method.

**Closed by michelengelen** 2024-04-30 07:54 UTC
Labels: component: data grid, typescript, status: waiting for maintainer
