### ISSUE TITLE
"Stop grouping by..." creates uncaught error with checkboxSelection with multiple grouping criteria

### ISSUE THREAD

**Issue by stem-ui** [mui/mui-x#9405] opened 2023-06-21 04:38 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/festive-jones-2ylnxn?file=/demo.tsx

(This is the same as the first demo [here](https://mui.com/x/react-data-grid/row-grouping/) but with checkboxSelection added.)

Steps:
1. Add an additional grouping criteria, e.g. "Group by director"
2. Remove the added grouping criteria, e.g. "Stop Grouping by director"
3. Error message: Cannot read properties of undefined (reading 'depth')

### Current behavior 😯

Uncaught error

### Expected behavior 🤔

Expecting no error to be thrown

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

58632

**Comment by romgrk** [comment] 2023-06-21 05:30
Duplicate of #9402

**Closed by romgrk** 2023-06-21 05:30 UTC
Labels: duplicate
