### ISSUE TITLE
[DataGridPro] Unable to use 3rd party drag and drop over the grid

### ISSUE THREAD

**Issue by alexankin** [mui/mui-x#4841] opened 2022-05-11 10:13 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When drag any elements with draggable={true} over the grid then rows flicker. 
It happens even if rowReordering={false}

### Expected behavior 🤔

if rowReordering is disabled, grid should not react on dragging any elements over it.

### Steps to reproduce 🕹

Steps:

1. I prepared an example: https://codesandbox.io/s/restless-forest-1f35e1?file=/src/App.tsx
2. Drag a grid row or green box over grid. 

### Context 🔦

We implemented drag and drop from one grid to another using [react-dnd](https://react-dnd.github.io/react-dnd/about). In version 5.10.0 it is broken. It is working in 5.8.0

### Your environment 🌎

<details>
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    @mui/material: ^5.4.4 => 5.4.4
    @mui/private-theming:  5.5.3
    @mui/styled-engine:  5.5.2
    @mui/system:  5.5.3
    @mui/types:  7.1.3
    @mui/utils:  5.5.3
    @mui/x-data-grid-generator: ^5.8.0 => 5.8.0
    @mui/x-data-grid-pro: ^5.10.0 => 5.10.0
    @mui/x-license-pro:  5.7.0
    @types/react: ^17.0.39 => 17.0.39
    react:  17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.4.4 => 4.4.4

Browser: Edge
</details>

**Comment by alexfauquette** [comment] 2022-05-11 14:21
Sound like it has already been fixed in another PR maybe #4735

I tried to reproduce it with the package generated by the last commit, and the bug is not here

https://codesandbox.io/s/dawn-grass-qfy5dh?file=/src/App.tsx

@DanailH I'm wondering if we should not do the following modification, because if rows can not be reordered, the `draggableEventHandlers` should do nothing

https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid-pro/src/components/GridRowReorderCell.tsx#L81-L93
```diff
  const draggableEventHandlers = {
    onDragStart: publish('rowDragStart'),
    onDragOver: publish('rowDragOver'),
    onDragEnd: publish('rowDragEnd'),
  };


  return (
    <div 
		className={classes.root} 
		draggable={isDraggable} 
-		{...draggableEventHandlers}
+		{...(isDraggable ? draggableEventHandlers: {})}
	>
      <rootProps.components.RowReorderIcon />
      <div className={classes.placeholder}>{cellValue}</div>
    </div>
  );
};
```

**Comment by DanailH** [comment] 2022-05-11 14:31
> 

@alexfauquette I don't think this is needed as these events are only fired if you can actually drag the element. If the `draggable=false` then the drag events won't fire.

This is what the spec says -> https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations

> The [draggable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-draggable) attribute is set to "true", so this element becomes draggable. If this attribute were omitted or set to "false", the element would not be dragged, and instead the text would be selected.

**Comment by alexfauquette** [comment] 2022-05-11 14:47
@DanailH In this issue, they add `draggable={true}` to the row parent such that they are able to drag the row from a grid to another

```jsx
function DragRow(props: PropsWithChildren<GridRowProps>) {
  return (
    <div draggable={true}>
      <GridRow {...props} />
    </div>
  );
}
```

If we do not remove the listener, at least the row reorder handlers should explicitly have an early return when  `rowReordering===false`

I suspect this bug to be fixed because the outside element does not have an initial index.

**Comment by DanailH** [comment] 2022-05-11 14:53
Then in that case we can disable the handlers when the feature is disabled. I'll add it. The same will apply to the column reorder.

**Closed** 2022-05-23 06:41 UTC
Labels: bug 🐛, component: data grid
