### ISSUE TITLE
Scrolling with touch doesn't work if we clicked on the chart

### ISSUE THREAD

**Issue by CzarOfScripts** [mui/mui-x#15064] opened 2024-10-23 06:43 UTC
### Steps to reproduce

Link to live example:

![Animation](https://github.com/user-attachments/assets/1aea902d-5b1a-4082-8723-d04ee0d9a9fb)

Steps:
1. While scrolling, click on the graph
2. Trying to scroll
3. Can't scroll

(Works here too https://mui.com/x/react-charts/lines/)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 21.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 130.0.6723.59
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.0
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.6
    @mui/icons-material: ^5.15.19 => 5.15.19
    @mui/material: ^5.16.6 => 5.16.6
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system:  5.16.6
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-charts: ^7.12.0 => 7.12.0
    @mui/x-charts-vendor:  7.12.0
    @mui/x-date-pickers: ^7.7.0 => 7.7.0
    @types/react: ^18.2.66 => 18.2.78
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.5.4 => 5.5.4
```
</details>

**Search keywords**: none

**Comment by alexfauquette** [comment] 2024-10-23 07:40
Thanks for reporting this issue. I'm closing it because it's a duplicate of #13885 Will be easier for us to track only one issue with all the feedback in it.

TLTR: It's a trade-off between the two possible effect a touch move could have on the chart: "scrolling the view" or "interacting with the chart". If you have a precise expected behavior could you share it in #13885 ?

**Closed by alexfauquette** 2024-10-23 07:40 UTC
Labels: duplicate, component: charts
