### ISSUE TITLE
Dayjs type removed from Datepicker value

### ISSUE THREAD

**Issue by sepehr707** [mui/mui-x#13327] opened 2024-05-31 14:28 UTC
### Steps to reproduce

Link to live example: (required)

Steps:
1. Use a Datepicker in a component.
2. Set a Dayjs value on datepicker value

### Current behavior

You will find an error said type Dayjs is not assignable to undefined | null

### Expected behavior

Dayjs value should be acceptable

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Dayjs, DatePicker, value

**Comment by flaviendelangle** [comment] 2024-05-31 14:31
It may be a duplicate of #12640, you can have a look at the fix proposed their.
And if it solves your problem, I'd be curious to have more info about your setup, that would help us write the best doc possible.

**Comment by sepehr707** [comment] 2024-06-01 11:45
Thanks a lot @flaviendelangle. The issue was LocalizationProvider. Actually I had wrong setup. Now it's OK.

**Closed** 2024-06-03 06:16 UTC
Labels: status: waiting for maintainer, component: pickers
