### ISSUE TITLE
[question] Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SAMBIT20** [mui/mui-x#9529] opened 2023-06-30 11:06 UTC
### Order ID

62159

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

<img width="1675" alt="image" src="https://github.com/mui/mui-x/assets/50833547/a59e6265-863c-4a8b-aad5-f8a92637d446">

Hey team in data grid PRO Uncaught RangeError: Maximum call stack size exceeded throwing 

Browser : Chrome

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by SAMBIT20** [comment] 2023-06-30 11:07
System:
    OS: macOS 13.4
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.122 
    @mui/core-downloads-tracker:  5.11.14 
    @mui/icons-material: ^5.11.11 => 5.11.11 
    @mui/material: ^5.11.13 => 5.11.14 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.14 
    @mui/types:  7.2.3 
    @mui/utils:  5.12.0 
    @mui/x-data-grid:  6.3.0 
    @mui/x-data-grid-premium: ^6.2.1 => 6.3.0 
    @mui/x-data-grid-pro: ^6.0.1 => 6.3.0 
    @mui/x-license-pro: ^6.0.1 => 6.0.4 
    @types/react: ^17.0.0 => 18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    styled-components:  5.3.9 
    typescript: ^5.0.2 => 5.0.2

**Comment by cherniavskii** [comment] 2023-06-30 11:10
Duplicate of https://github.com/mui/mui-x/issues/9510
The fix is merged and we plan to include it in today's release.
Thanks for opening the issue!

**Closed by cherniavskii** 2023-06-30 11:10 UTC
Labels: status: needs triage, support: commercial

**Comment by SAMBIT20** [comment] 2023-06-30 11:40
@cherniavskii Thanks man

**Comment by cherniavskii** [comment] 2023-06-30 13:55
This issue should be fixed in https://github.com/mui/mui-x/releases/tag/v6.9.1
