### ISSUE TITLE
[pickers][DesktopDatePicker] entering date with keyboard breaks after timezone prop changed

### ISSUE THREAD

**Issue by PRe-SON** [mui/mui-x#15628] opened 2024-11-27 10:30 UTC
### Steps to reproduce

Steps:
1. Open this link to live example: (required)
https://codesandbox.io/p/sandbox/quizzical-bush-vqslzr
2. click button
3. try to enter a date with the keyboard

### Current behavior

While writing the number for the year, the number for the day shifts by 1.

### Expected behavior

Date should remain the way it was typed.

### Context

This seems to happen when the value passed to the timezone prop changes: In this example, it starts off as undefined, and then changes to "Europe/Berlin". Note that this all happens before the date is ever entered, and the bug only seems to occur only the first time the date is being entered.

**Search keywords**: DesktopDatePicker timezone keyboard date

**Comment by michelengelen** [comment] 2024-11-28 10:29
duplicate of #9653

**Closed** 2024-11-28 10:30 UTC
Labels: bug 🐛, duplicate, component: pickers
