### ISSUE TITLE
Treeview content isn't scrolled when navigating with keyboard arrow down / arrow up

### ISSUE THREAD

**Issue by ilbrando** [mui/mui-x#10355] opened 2023-09-16 14:05 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-treeview-scroll-sfv7v7?file=/Demo.tsx

Steps:
1. Select an item in the treeview
2. Press arow down multiple times
3. When the focused item is out of view the items arent scrolled
4. If you manually scroll you can scrolle down to the focused item and see that it has focus

### Current behavior 😯

The items arent scrolled

### Expected behavior 🤔

The items to be scrolled

### Your environment 🌎

Forked sandbox from the documentation

**Comment by oliviertassinari** [comment] 2023-09-16 14:50
Duplicate of #9961?

**Comment by ilbrando** [comment] 2023-09-16 15:16
Yeah you’re right. I must have made a bad search, sorry.

**Closed** 2023-09-18 12:16 UTC
Labels: status: needs triage, component: tree view
