### ISSUE TITLE
[pickers] slots not working properly while using onchange in mui-pickers

### ISSUE THREAD

**Issue by Haridharan20** [mui/mui-x#10560] opened 2023-10-03 12:02 UTC
Hi,
I'm using react mui-x v6, i tried to use both onchange and slots props but the dropdown is not placed correctly on second touch

```
 const handleEventDateChange = (event) => {
    setInputEventDate(event);
  };

  const renderDateInputTextField =
    (showDateTooltip = false) =>
    (props) => {
      if (props && props.label === 'Time') {
        const timeToDisplay = props?.value + ' ' + timeZone;
        props = {
          ...props,
          value: timeToDisplay,
        };
      }

      return <TextField {...props} size="small" fullWidth />;
    }; 
<TimePicker
          label="Time"
          value={inputEventDate}
          onChange={(e) => handleEventDateChange(e)}
          slots={{
            textField: renderDateInputTextField(false),
          }}
  />
```

<img width="634" alt="Screenshot 2023-10-03 at 5 28 21 PM" src="https://github.com/mui/mui-x/assets/66022257/6020e276-ca66-4ddb-983f-219b28c9cc54">
<img width="458" alt="Screenshot 2023-10-03 at 5 26 59 PM" src="https://github.com/mui/mui-x/assets/66022257/76dc9549-e4df-4f84-a1dc-0698eea372ae">

in the second image, it is not relative to its parent  if I remove the onchange its works fine

_Originally posted by @Haridharan20 in https://github.com/mui/mui-x/issues/8322#issuecomment-1744822522_
            

**Search keywords**:

**Comment by alexfauquette** [comment] 2023-10-03 12:14
The `slots` props expects components and not renderer. I assume this is the source of your bug.

You can find more details about this problem [here](https://mui.com/x/react-date-pickers/custom-components/#recommended-usage)

If you only need to modify textField props, you can use the `slotProps` for that.

Does it solves your issue? If not, please send a codesandbox

**Comment by Haridharan20** [comment] 2023-10-03 14:15
Thanks @alexfauquette 
https://codesandbox.io/s/gallant-lamarr-6ydkrx?file=/Demo.tsx
in this if i change a time next time its overlap

**Comment by alexfauquette** [comment] 2023-10-03 14:32
> in this if i change a time next time its overlap

I do not manage to reproduce. Could you be more explicit, with a screen recording of the bug, or a step by step explanation, about where you click, which key you press?

https://codesandbox.io/s/gallant-sutherland-pqv646?file=/Demo.tsx

You are still using a renderer which is an incorrect way of using `slots`. And I'm not sure about what you're trying to achieve. But if it is only to add `IST` at the end of the field, you can simplify your code by using `format` [props](https://mui.com/x/react-date-pickers/adapters-locale/#custom-formats)

**Comment by Haridharan20** [comment] 2023-10-03 16:31
Video: https://github.com/mui/mui-x/assets/66022257/ef86da2a-c526-4cc8-bfd0-cab1673e3b89
May I know the reason why it's happening like this?

Code: https://codesandbox.io/s/serverless-meadow-ngk5ss?file=/Demo.tsx
I mention my actual use case in the code like I want the custom input to accept arguments and props

**Comment by LukasTy** [comment] 2023-10-03 21:26
> May I know the reason why it's happening like this?

Alex has already[ linked the documentation](https://mui.com/x/react-date-pickers/custom-components/#recommended-usage) section where we explain the reason why this is happening.
![Screenshot 2023-10-04 at 00 09 04](https://github.com/mui/mui-x/assets/4941090/8c083c79-6f46-4f9a-bb8d-4bc367b0f450)

It's the same reason, why you should always define components outside of one another.
Maybe in some instances you do not notice the problem, but the least thing that is happening is a loss of performance, because in such case React is remounting more DOM than it could if function reference wouldn't change.

Also, please avoid tampering with the `value` in such an intrusive way as it might cause all sorts of issues even if it would seem to work "on the surface".
Alex has suggested a good option of providing a custom format, which in your case would be something like `hh:mm aa 'IST'`.

As for your described use case, have you considered using [`helperText` prop](https://mui.com/x/react-date-pickers/date-picker/#helper-text) instead of wrapping the whole `TextField` in a `Tooltip` component. IMHO, such approach is both a bad UX and hardly an accessible (a11y) behavior.
Another option could be to look into [using an `inputAdornment`](https://mui.com/material-ui/react-text-field/#input-adornments) with an icon that could reveal the tooltip.

**Comment by Haridharan20** [comment] 2023-10-04 13:05
Thanks @LukasTy 
I have a doubt once we use the custom text field we can't able to edit the time by free typing without the custom text field I am able to edit I didn't find any resources related to that.

**Comment by LukasTy** [comment] 2023-10-04 13:56
> I have a doubt once we use the custom text field we can't able to edit the time by free typing without the custom text field I am able to edit I didn't find any resources related to that.

Could you confirm if I understand you correctly?
Do you want the `TimePicker` to be editable as any generic `TextField` somewhere else in the app? 🤔 
If that's correct, then it hurts our hearts 💙 😆 as we've put so much effort into making the [field components](https://mui.com/x/react-date-pickers/fields/) as powerful and easy to use for the end user as possible. 🙈 
Are you finding any problems with it?

**Comment by LukasTy** [comment] 2023-10-04 15:34
[Here is a codesandbox](https://codesandbox.io/s/keen-christian-lyn695?file=/Demo.tsx) with your requirements implemented without overriding a slot.
If for some reason you still need to override the `textField` slot, a working solution is commented out.

I'm closing this issue as it seems that there is no issue with the mentioned functionality after correcting its usage.

**Closed by LukasTy** 2023-10-04 15:34 UTC
Labels: support: question, component: pickers

**Comment by Haridharan20** [comment] 2023-10-04 16:47
Thanks @LukasTy for your help :)
