### ISSUE TITLE
[DateTimePicker] Scrollbar overlapped

### ISSUE THREAD

**Issue by koooge** [mui/mui-x#10868] opened 2023-11-01 11:45 UTC
### Steps to reproduce

Hi, there I encountered an stylistic issue of DateTimePicker.

Link to live example: (required)

Steps:
1. Visit https://mui.com/x/react-date-pickers/date-time-picker/
2. Open DateTimePicker with Desktop
3. Scroll mouse AM/PM
4. hover on the scorllbar

### Current behavior

The scrollbar overlaps on the AM/PM.

https://github.com/mui/mui-x/assets/7419215/b975b0ab-220b-401f-9ed1-94508900c2a3

### Expected behavior

The scrollbar should not be overlapped, or does not show the scrollbar.

### Context

uncomfortable UX

### Your environment
v6.17.0 with google chrome Version 118.0.5993.117 (Official Build) (arm64)

![Screenshot 2023-11-01 at 12 46 28](https://github.com/mui/mui-x/assets/7419215/be8a43fe-b81f-458d-92c2-01e478ddf53d)

**Search keywords**: picker scrollbar

**Comment by LukasTy** [comment] 2023-11-01 13:10
Thank you for creating this issue! 🙏 
This looks like a duplicate of https://github.com/mui/mui-x/issues/9311.
I'm closing this issue as a duplicate.
Please feel free to follow the linked issue to get notified about its progress. 😉

**Closed by LukasTy** 2023-11-01 13:10 UTC
Labels: status: waiting for maintainer
