### ISSUE TITLE
Translating page in Edge make calendar show March when not March

### ISSUE THREAD

**Issue by MagnusSN-TV2** [mui/mui-x#13810] opened 2024-07-11 08:33 UTC
### Steps to reproduce

Link to live example: https://mui.com/x/react-date-pickers/date-calendar/

Steps:
1. Open Edge
2. Go to any page with an MUI calendar, such as the documentation
3. Translate page to another language, tested with danish
4. Start going through the months
5. A lot of the months will be translated into March, not just March

### Current behavior

Months are translated into March in the respective language

### Expected behavior

The months should translate into the correct month

### Context

Must admit that I have not created a bug before so sorry if something is incorrectly filled
Have checked and could not find a duplicate

Small bug, but thought you would like to be informed of it

Could not get the bug in Chrome, only Edge

OS is Windows 11 Pro

Translation language: Danish (da-DK)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  <summary>OS: Windows 11 Pro</summary>
  <summary>Browser: Edge 64bit version 126.0.2592.87</summary>
</details>

**Search keywords**: Calendar, Month, Translate

**Search keywords**:

**Comment by LukasTy** [comment] 2024-07-12 11:35
Thank you for reporting this problem @MagnusSN-TV2! 🙏 
I was able to reproduce it on Edge on MacOS.
It looks like a very interesting issue on Edge Translator logic, could you report this problem to the Edge team? 🤔 

The problem seems to happen whenever you are switching to a month, which translated to the selected language equals the original value.
For Danish it is:
- April === April
- August === August
- September === September
- November === November
- December === December

I'm not sure why it gets stuck on Marts though, even when navigating to the right of months to trigger "September" equality. 🤷 
Given that it is only reproducible in Edge and only with languages, that have some months being translated to the same values, I think that there is nothing we can do here. 🙈 

I'm closing this issue because of the above reasons.

If you think that there is something that we could do here, feel free to comment or reopen the issue. 😉

**Closed by LukasTy** 2024-07-12 11:35 UTC
Labels: status: waiting for maintainer, component: pickers

**Comment by MagnusSN-TV2** [comment] 2024-07-15 09:52
Hi @LukasTy, thanks for looking at the problem 😊

I have reported the issue to Edge.

In case I get a response, would you like me to post an update here?

**Comment by MagnusSN-TV2** [comment] 2024-07-15 09:56
Will do 😊👍

**Comment by MagnusSN-TV2** [comment] 2024-09-19 08:36
Hi again @LukasTy 
The 22nd of July Edge Feedback Team 2 said that they were actively looking into it and that they would keep me posted.

While I have not heard from them I tried testing it again and it seems to have been fixed now 😊

I suspect that I will not receive any update from the Edge team, but I thought I would just post an update here to let you know that it seems to be fixed 😄
