### ISSUE TITLE
DataGrid Menu item steals focus from input

### ISSUE THREAD

**Issue by shunyun-bp** [mui/mui-x#4117] opened 2022-03-08 00:37 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have created a custom column menu item which pops up a dialog with text input.  In the text input, I cannot enter any character for which a menu item has as its first character; that is, the menu items steal focus from the text input component.  This is the same behavior seen in [https://stackoverflow.com/questions/64646173/react-js-input-field-losing-focus-when-typing-letters-c-or-n](https://stackoverflow.com/questions/64646173/react-js-input-field-losing-focus-when-typing-letters-c-or-n) 
In my case, I have menu items "Filter", "Hide", "Pin-right", "Pin-left", "Clone", "Delete", and "Insert" (the first four being the MUI GridFilterMenuItem, HideGridColMenuItem, and GridColumnPinningMenuItems components).  So then in the Dialog's text input I cannot use f,h,p,c,d, or i; the menu items steal the focus.  I've tried everything; useRef, separating the Dialog into a separate component with it's own state, nothing makes a difference.

Attaching one of my menu components.
[GridColumnInsertMenuItem.jsx.zip](https://github.com/mui/mui-x/files/8201491/GridColumnInsertMenuItem.jsx.zip)

### Expected behavior 🤔

I should be able to mouse-click on the Insert menu, the dialog should pop up with a text field, and I should be able to type in all alphanum characters.  If I use a key to choose a menu item (in this example, F for filter, H for hide, or I for my custom Insert item) then the user should be able to then press the Enter key and focus should shift to the interactive dialog's text input field.  That is, once the menu item's child component is popped up, it should give up focus and not "steal" it back.

### Steps to reproduce 🕹

Here is a codesandbox link to see this working:  [https://codesandbox.io/s/datagridpro-v5-quick-start-forked-ylic43?file=/src/App.tsx](https://codesandbox.io/s/datagridpro-v5-quick-start-forked-ylic43?file=/src/App.tsx)
Steps:
(note, I'm using chrome browser)
1. Select the column menu elipsis
2. Select "Insert Column"
3. Type the F or H characters (the text input will lose focus). Any other character will work.
4. If you quickly type "asdf" then focus will be maintained, but if you pause and then type the "f" key, focus will be lost.

### Context 🔦

Creating a custom Menu Item per documentation at [https://mui.com/components/data-grid/components/#column-menu](https://mui.com/components/data-grid/components/#column-menu)
I want to interact with the user upon selecting a column menu item, to collect some text for further action.  This issue prevents me from doing this.  There is a workaround, which is to insert a character like &#8288; into the menu item text but this only works for custom menu items (meaning I'm prevented from including MUI-provided menu items) and it conflicts with accessibility (ie prevents users from using a key to select a menu item before the dialog appears.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 12.2.1
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Edge: Not Found
    Firefox: 97.0.1
    Safari: 15.3
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.62 
    @mui/icons-material: ^5.2.5 => 5.2.5 
    @mui/material: ^5.2.5 => 5.2.6 
    @mui/private-theming:  5.2.3 
    @mui/styled-engine:  5.2.6 
    @mui/styles: ^5.2.3 => 5.2.3 
    @mui/system: ^5.2.5 => 5.2.6 
    @mui/types:  7.1.0 
    @mui/utils:  5.2.3 
    @mui/x-data-grid-pro: ^5.2.0 => 5.2.1 
    @mui/x-license-pro:  5.2.1 
    @types/react:  17.0.38 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript:  4.5.4 
```
</details>

**Comment by alexfauquette** [comment] 2022-03-09 12:00
That's a duplicate of #4083

The easiest solution is to stop the key down propagation in your component such that the `<menu />` does not modify its focus

See the related issue in material-ui
https://github.com/mui/material-ui/issues/19096

**Closed** 2022-03-14 14:48 UTC
Labels: duplicate
