### ISSUE TITLE
Line chart legend overlap with the rest of the chart

### ISSUE THREAD

**Issue by panfiva** [mui/mui-x#11359] opened 2023-12-09 18:34 UTC
### Steps to reproduce

Link to live example: (required)

https://stackblitz.com/edit/react-5sbzfm?file=Demo.js

Steps:
1. See how in both charts legend overlaps with axis and chart area

### Current behavior

Labels overlap with axis and chart area:

![image](https://github.com/mui/mui-x/assets/48455289/7a6fa558-1908-4b9d-9fa6-b532a2e09588)

### Expected behavior

In the top chart, chart should be shifted below the legend

In the bottom chart, the chart should be shifted to the right of the legend

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: legend overlap

**Comment by alexfauquette** [comment] 2023-12-11 08:30
Sounds like a duplicate of #11359

@panfiva If you see specific points that are missing in the initial issue, could you please add them to it, so that the one who will take care of that issue has all the details in mind when starting?

**Closed by alexfauquette** 2023-12-11 08:30 UTC
Labels: duplicate

**Comment by panfiva** [comment] 2023-12-11 15:43
@alexfauquette , you mean https://github.com/mui/mui-x/issues/10928?

**Comment by alexfauquette** [comment] 2023-12-11 16:08
Yes, sorry for the bad copy/past 🙈
