### ISSUE TITLE
[DateRangePicker] Picker closes after selecting start date.

### ISSUE THREAD

**Issue by conorstew** [mui/mui-x#6298] opened 2022-09-26 20:56 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

DateRangePicker closes after selecting start date which is not what I want.
This happens when the selected start date is a date that is disabled as an end date and if you click it fast.

Video demonstration
https://www.youtube.com/watch?v=32MjXSlB6KY&ab_channel=ConorStewart

### Expected behavior 🤔

I expect the date picker to remain open after selecting the start date.
 

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/sparkling-wave-032t9f 

Steps:
1. Use Google Chrome.
2. Choose start date 1 day after the disabled date, and do a quick click on it.

### Context 🔦

I am working with reservations (similarly to airBnb). In my application, a reservation has to cover a minimum of one night. Therefore, I always have to prevent (by disabling) the selected start date from being selected as an end date.

### Your environment 🌎

  System:
    OS: macOS 12.6
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.1 - ~/Desktop/easycampsite/server/client/node_modules/.bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: Not Found
    Firefox: 105.0.1
    Safari: 16.0
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled:  11.9.3 
    @mui/base:  5.0.0-alpha.91 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/material: ^5.9.2 => 5.9.2 
    @mui/private-theming:  5.9.1 
    @mui/styled-engine:  5.8.7 
    @mui/system:  5.9.2 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.3 
    @mui/x-data-grid: ^5.17.1 => 5.17.1 
    @mui/x-date-pickers:  5.0.2 
    @mui/x-date-pickers-pro: ^5.0.2 => 5.0.2 
    @mui/x-license-pro:  5.17.0 
    @types/react:  18.0.15 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  4.7.4

**Comment by alexfauquette** [comment] 2022-09-27 14:33
Thanks for the nice reproduction

The problem seems to come from [here](https://github.com/mui/mui-x/blob/0a245b86cbb9080aba94cd00379afcdf23a04171/packages/x-date-pickers/src/internals/components/wrappers/DesktopTooltipWrapper.tsx#L28-L39). The ide being that the focus should stay in the popper or the input. When the focus move somewhere else, it dismiss the component.

The problem here is that with quick click the focus is lost to `<body/>` which close the element.

Should have a deeper look to understand why the focus is lost, and what we can do, because date range picker behavior with focus is not well specified right now.

**Comment by alexfauquette** [comment] 2022-09-28 13:13
After some investigation this is why the focus behave differently

### quick click
1. on `mouse down` the focus move from the previously focused button to the new one
2. on `mouse up` the click is triggered and so day button is now disabled which moves the focus to `<body/>`
3. next event loop called: observe focus is on `<body/>` close the popper

### slow click

1. on `mouse down` the focus move from the previously focused button to the new one
2. next event loop called: observe focus is on the "clicked" button, keep the popper
3. on `mouse up` the click is triggered and so day button is now disabled which moves the focus to `<body/>`

Notice that having the button moving to `disabled` remove the focus without calling `onBlur`

**Closed** 2022-10-05 14:13 UTC
Labels: bug 🐛, plan: Pro, component: DateRangePicker
