### ISSUE TITLE
[data grid]  Change a cell with a type of 'number' to a type of 'singleSelect' based on value in another cell

### ISSUE THREAD

**Issue by hutchhicken** [mui/mui-x#6052] opened 2022-09-06 20:15 UTC
### Order ID 💳

50090

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I would like to change a cell with a type of 'number' to a type of 'singleSelect' (as well as setting an appropriate valueOptions) depending on the value set in another cell on the same row.  Is this possible?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /usr/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 104.0.1
  npmPackages:
    @emotion/react: ^11.10.0 => 11.10.0 
    @emotion/styled: ^11.10.0 => 11.10.0 
    @mui/base:  5.0.0-alpha.94 
    @mui/core-downloads-tracker:  5.10.2 
    @mui/icons-material: ^5.10.2 => 5.10.2 
    @mui/material: ^5.10.2 => 5.10.2 
    @mui/private-theming:  5.9.3 
    @mui/styled-engine:  5.10.2 
    @mui/system:  5.10.2 
    @mui/types:  7.1.5 
    @mui/utils:  5.9.3 
    @mui/x-data-grid: ^5.16.0 => 5.16.0 
    @mui/x-data-grid-pro: ^5.16.0 => 5.16.0 
    @mui/x-license-pro: ^5.16.0 => 5.16.0 
    @types/react:  18.0.17 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  4.8.2 

```
</details>

**Comment by m4theushw** [comment] 2022-09-07 22:47
Yes, you can check the example in https://mui.com/x/react-data-grid/editing/#linked-fields

**Comment by cherniavskii** [comment] 2022-09-19 12:17
> What I need is to be able to change the type of the cell from 'number' to 'singleSelect'.

The cell type is derived from the column type, so you cannot change the type of specific cell.
You can only change the type of the column (and therefore all cells in it).

**Comment by hutchhicken** [comment] 2022-09-19 12:23
Cell A is a singleSelect of a set of two enumerated types.  Cell B is a price.  Type 1 of Cell A allows any arbitrary price.  Type 2 of Cell A requires specific prices in a list of allowable prices (from the Apple App store in this case).  When Cell A is set as Type 1, I'd like a 'number' cell.  When it is set to Type 2, I need a singleSelect of defined values.

Could perhaps a custom component fed through renderCellEdit do the trick?

**Comment by m4theushw** [comment] 2022-09-19 13:04
The principle from https://mui.com/x/react-data-grid/recipes-editing/#linked-fields kind of still apply here. Instead of `valueOptions` you change what is returned in `renderEditCell`. The problem is that `GridEditInputCell` sets the input type based on the column definition, so we can't reuse it here. Instead, a custom component must be provided. Additionally you also need to pass custom value parser and formatter that should only work when the cell is of number type.

https://github.com/mui/mui-x/blob/daa545a01413457489f518dde9e086199377d206/packages/grid/x-data-grid/src/colDef/gridNumericColDef.ts#L7-L14

> Could perhaps a custom component fed through renderCellEdit do the trick?

Yes, if you don't mind providing a custom component it works.

Here's a oversimplified example.

```tsx
const columns: GridColDef[] = [
  {
    field: 'cellB',
    renderEditCell: ({ row }) => {
      return row.cellA = 'Type 1' ? <input type="number" /> : <select />;
    },
  },
];
```

**Comment by hutchhicken** [comment] 2022-09-19 16:16
Ok.  I'd like to rebuild custom components that match the UI of the native singleSelect component so that it matches the look of other cells in the grid.  Do you know where I can find those pattern components?

**Comment by cherniavskii** [comment] 2022-09-20 09:56
@hutchhicken you can reuse `GridEditSingleSelectCell` component - https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx

**Comment by hutchhicken** [comment] 2022-09-20 14:31
Do you happen to have any examples of that component being used with a renderEditCell function?

**Comment by cherniavskii** [comment] 2022-09-21 16:55
It's being used in Linked fields demo: https://mui.com/x/react-data-grid/recipes-editing/#linked-fields
Although in your case you'll probably want to use it conditionally depending on other field value.

I'm closing this issue for now, as it looks like there's no actions for us here.

**Closed by cherniavskii** 2022-09-21 16:55 UTC
Labels: component: data grid, support: commercial, customization: extend
