### ISSUE TITLE
Week days name in jalali calendar

### ISSUE THREAD

**Issue by saeedhemmati** [mui/mui-x#5330] opened 2022-06-27 10:00 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi
As you see week day name use of day number with ش character which in the datepicker just display first letter of the week day name.

![image](https://user-images.githubusercontent.com/29829502/175915440-fe9e285f-00e5-4e5c-877a-9b6a9b1a2ef5.png)

### Expected behavior 🤔

I want to config the `@date-io/date-fns-jalali` for change default week day names to full name. for example convert:

- ش to شنبه
- ۱ to یکشنبه
- ۲ to دوشنبه
.
.
.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by Oz90** [comment] 2022-06-27 11:33
Hello @saeedhemmati, [see this issue](https://github.com/mui/mui-x/issues/4605) and specifically the comment from 18th May which explains why this happens and I think also provides a possible solution to the issue. 
I believe this isn't only a jalali calendar issue but the same in all languages.

**Comment by alexfauquette** [comment] 2022-06-27 15:53
Thanks, @ozgurbaserdem for the explanation. This is a duplicate of #4605 because as long as `day.charAt(0).toUpperCase()` is here, their is no workaround

**Comment by saeedhemmati** [comment] 2022-06-28 09:16
@ozgurbaserdem 
Thanks for the guide

**Closed** 2022-08-04 12:31 UTC
Labels: duplicate, l10n, component: date picker
