### ISSUE TITLE
[picker][nextjs][ssr] Warning: A props object containing a "key" prop is being spread into JSX

### ISSUE THREAD

**Issue by SiarheiLazakovich** [mui/mui-x#7546] opened 2023-01-13 16:28 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/p/sandbox/optimistic-feather-opygzp

### Current behavior 😯

```
Warning: A props object containing a "key" prop is being spread into JSX:
  let props = {key: someKey, day: ..., isAnimating: ..., disabled: ..., autoFocus: ..., today: ..., outsideCurrentMonth: ..., selected: ..., disableHighlightToday: ..., showDaysOutsideCurrentMonth: ..., onKeyDown: ..., onFocus: ..., onBlur: ..., onDaySelect: ..., tabIndex: ..., role: ..., aria-selected: ..., aria-current: ...};
  <ForwardRef(PickersDay) {...props} />
React keys must be passed directly to JSX without using spread:
  let props = {day: ..., isAnimating: ..., disabled: ..., autoFocus: ..., today: ..., outsideCurrentMonth: ..., selected: ..., disableHighlightToday: ..., showDaysOutsideCurrentMonth: ..., onKeyDown: ..., onFocus: ..., onBlur: ..., onDaySelect: ..., tabIndex: ..., role: ..., aria-selected: ..., aria-current: ...};
  <ForwardRef(PickersDay) key={someKey} {...props} />
    at renderChildrenArray (/project/sandbox/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8340:7)
    at div
    at Transition (webpack-internal:///(sc_client)/./node_modules/react-transition-group/cjs/Transition.js:135:30)
    at Fade (webpack-internal:///(sc_client)/./node_modules/@mui/material/node/Fade/Fade.js:35:39)
    at div
    at TransitionGroup (webpack-internal:///(sc_client)/./node_modules/react-transition-group/cjs/TransitionGroup.js:57:30)
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at PickersFadeTransitionGroup (webpack-internal:///(sc_client)/./node_modules/@mui/x-date-pickers/node/CalendarPicker/PickersFadeTransitionGroup.js:54:43)
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at div
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at CalendarPicker (webpack-internal:///(sc_client)/./node_modules/@mui/x-date-pickers/node/CalendarPicker/CalendarPicker.js:117:40)
    at main
    at LocalizationProvider (webpack-internal:///(sc_client)/./node_modules/@mui/x-date-pickers/node/LocalizationProvider/LocalizationProvider.js:40:43)
    at renderElement (/project/sandbox/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8071:5)
    at ThemeProvider (webpack-internal:///(sc_client)/./node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:39:5)
    at ThemeProvider (webpack-internal:///(sc_client)/./node_modules/@mui/system/ThemeProvider/ThemeProvider.js:38:5)
    at EmotionCacheProvider (webpack-internal:///(sc_client)/./app/EmotionCacheProvider.tsx:22:13)
    at Home (webpack-internal:///(sc_client)/./app/page.tsx:27:74)
    at Lazy
    at ScrollAndFocusHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:142:1)
    at InnerLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:170:30)
    at RedirectErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:317:9)
    at RedirectBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:323:29)
    at NotFoundErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:349:9)
    at NotFoundBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:355:29)
    at LoadingBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:277:32)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:39:26)
    at RenderFromTemplateContext (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/render-from-template-context.js:10:34)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:18:30)
    at Lazy
    at body
    at html
    at ReactDevOverlay (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:58:9)
    at HotReload (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:18:22)
    at Router (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:92:23)
    at ErrorBoundaryHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:28:9)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:39:26)
    at AppRouter
    at Lazy
    at Lazy
    at ServerComponentWrapper (/project/sandbox/node_modules/next/dist/server/app-render.js:377:28)
    at ServerComponentWrapper (/project/sandbox/node_modules/next/dist/server/app-render.js:377:28)
    at InsertedHTML (/project/sandbox/node_modules/next/dist/server/app-render.js:1069:33)
Warning: PrivatePickersSlideTransitionRoot: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at PickersSlideTransition (webpack-internal:///(sc_client)/./node_modules/@mui/x-date-pickers/node/CalendarPicker/PickersSlideTransition.js:117:5)
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at div
    at renderChildrenArray (/project/sandbox/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8340:7)
    at div
    at Transition (webpack-internal:///(sc_client)/./node_modules/react-transition-group/cjs/Transition.js:135:30)
    at Fade (webpack-internal:///(sc_client)/./node_modules/@mui/material/node/Fade/Fade.js:35:39)
    at div
    at TransitionGroup (webpack-internal:///(sc_client)/./node_modules/react-transition-group/cjs/TransitionGroup.js:57:30)
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at PickersFadeTransitionGroup (webpack-internal:///(sc_client)/./node_modules/@mui/x-date-pickers/node/CalendarPicker/PickersFadeTransitionGroup.js:54:43)
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at div
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at CalendarPicker (webpack-internal:///(sc_client)/./node_modules/@mui/x-date-pickers/node/CalendarPicker/CalendarPicker.js:117:40)
    at main
    at LocalizationProvider (webpack-internal:///(sc_client)/./node_modules/@mui/x-date-pickers/node/LocalizationProvider/LocalizationProvider.js:40:43)
    at renderElement (/project/sandbox/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8071:5)
    at ThemeProvider (webpack-internal:///(sc_client)/./node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:39:5)
    at ThemeProvider (webpack-internal:///(sc_client)/./node_modules/@mui/system/ThemeProvider/ThemeProvider.js:38:5)
    at EmotionCacheProvider (webpack-internal:///(sc_client)/./app/EmotionCacheProvider.tsx:22:13)
    at Home (webpack-internal:///(sc_client)/./app/page.tsx:27:74)
    at Lazy
    at ScrollAndFocusHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:142:1)
    at InnerLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:170:30)
    at RedirectErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:317:9)
    at RedirectBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:323:29)
    at NotFoundErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:349:9)
    at NotFoundBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:355:29)
    at LoadingBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:277:32)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:39:26)
    at RenderFromTemplateContext (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/render-from-template-context.js:10:34)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:18:30)
    at Lazy
    at body
    at html
    at ReactDevOverlay (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:58:9)
    at HotReload (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:18:22)
    at Router (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:92:23)
    at ErrorBoundaryHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:28:9)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:39:26)
    at AppRouter
    at Lazy
    at Lazy
    at ServerComponentWrapper (/project/sandbox/node_modules/next/dist/server/app-render.js:377:28)
    at ServerComponentWrapper (/project/sandbox/node_modules/next/dist/server/app-render.js:377:28)
    at InsertedHTML (/project/sandbox/node_modules/next/dist/server/app-render.js:1069:33)
```

### Expected behavior 🤔

no warnings

**Comment by alexfauquette** [comment] 2023-01-17 11:47
Thanks for the report. For a reason I ignore, I do not manage to reproduce in in local environement.

The only `key` spreading I see is here
```jsx
<PickersDay key={pickersDayProps.key} {...pickersDayProps} />
```

Will see if inverting the order fix the warning

**Comment by flaviendelangle** [comment] 2023-02-01 14:09
@alexfauquette I don't know why Github did not close this issue after your PR was merged.

**Comment by alexfauquette** [comment] 2023-02-01 14:16
because it was merged on `master`, and the main branch is `next`

**Comment by flaviendelangle** [comment] 2023-02-01 14:22
Closing it then :D

**Closed** 2023-02-01 14:23 UTC
Labels: bug 🐛, component: pickers
