### ISSUE TITLE
We are getting exceptions for DataGrid keyboard navigation.  Is there anyway we can get this prioritized? 

### ISSUE THREAD

**Issue by jthom330** [mui/mui-x#10071] opened 2023-08-17 16:53 UTC
### Order ID or Support key 💳 (optional)

51218

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

This is an existing issue: https://github.com/mui/mui-x/issues/6446

Using the DataGrid keyboard navigation to press arrow down and page down on an empty grid throws exception.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Using Google Chrome
  
  System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.5.2
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-alpha.118 
    @mui/core-downloads-tracker:  5.11.9 
    @mui/icons-material:  5.11.9 
    @mui/lab:  5.0.0-alpha.120 
    @mui/material:  5.11.10 
    @mui/private-theming:  5.11.9 
    @mui/styled-engine:  5.11.9 
    @mui/styles:  5.11.9 
    @mui/system:  5.11.9 
    @mui/types:  7.2.3 
    @mui/utils:  5.14.1 
    @mui/x-data-grid:  5.17.25 
    @mui/x-data-grid-pro:  5.17.25 
    @mui/x-date-pickers:  6.10.2 
    @mui/x-date-pickers-pro:  6.10.2 
    @mui/x-license-pro:  5.17.12 
    @types/react:  17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript:  4.7.4 
```
</details>

**Comment by romgrk** [comment] 2023-08-17 19:17
Duplicate of #6446

Please add your comment to the existing issue.

**Closed by romgrk** 2023-08-17 19:17 UTC
Labels: duplicate, support: commercial
