### ISSUE TITLE
[data grid] Remove Unsort from the column menu if sortingOrder is ['asc', 'desc']

### ISSUE THREAD

**Issue by Valentin1918** [mui/mui-x#7103] opened 2022-12-06 09:12 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

Column menu is not reacted on sortingOrder property passed to grid component

### Expected behavior 🤔

Column menu sorting items (Unsort, Sort by ASC, Sort by DESC) should be filtered by sortingOrder passed in a data grid component as well as in each column separately 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment] 2022-12-06 11:31
Hey @Valentin1918 
Thanks for reporting this, it looks like a bug.
I can reproduce it with this demo: https://codesandbox.io/s/gallant-lederberg-3n3hx1?file=/demo.tsx
<img width="249" alt="Screenshot 2022-12-06 at 12 27 55" src="https://user-images.githubusercontent.com/13808724/205899844-6193a50b-6d47-436a-8017-eeb6fb36afbc.png">

By the way, we are working on the new version of the column menu https://github.com/mui/mui-x/pull/6619
We should avoid this issue in the new column menu if possible. cc @MBilalShafi

**Comment by cherniavskii** [comment] 2022-12-06 11:45
For the current column menu implementation, the fix would look like this:

```diff
diff --git a/packages/grid/x-data-grid/src/components/menu/columnMenu/SortGridMenuItems.tsx b/packages/grid/x-data-grid/src/components/menu/columnMenu/SortGridMenuItems.tsx
index ac345d2..d4380dc 100644
--- a/packages/grid/x-data-grid/src/components/menu/columnMenu/SortGridMenuItems.tsx
+++ b/packages/grid/x-data-grid/src/components/menu/columnMenu/SortGridMenuItems.tsx
@@ -6,11 +6,13 @@ import { gridSortModelSelector } from '../../../hooks/features/sorting/gridSorti
 import { GridSortDirection } from '../../../models/gridSortModel';
 import { useGridApiContext } from '../../../hooks/utils/useGridApiContext';
 import { GridFilterItemProps } from './GridFilterItemProps';
+import { useGridRootProps } from '../../../hooks/utils/useGridRootProps';
 
 function SortGridMenuItems(props: GridFilterItemProps) {
   const { column, onClick } = props;
   const apiRef = useGridApiContext();
   const sortModel = useGridSelector(apiRef, gridSortModelSelector);
+  const rootProps = useGridRootProps();
 
   const sortDirection = React.useMemo(() => {
     if (!column) {
@@ -33,17 +35,42 @@ function SortGridMenuItems(props: GridFilterItemProps) {
     return null;
   }
 
+  const sortingOrder: GridSortDirection[] = column.sortingOrder ?? rootProps.sortingOrder;
+
   return (
     <React.Fragment>
-      <MenuItem onClick={onSortMenuItemClick} disabled={sortDirection == null}>
-        {apiRef.current.getLocaleText('columnMenuUnsort')}
-      </MenuItem>
-      <MenuItem onClick={onSortMenuItemClick} data-value="asc" disabled={sortDirection === 'asc'}>
-        {apiRef.current.getLocaleText('columnMenuSortAsc')}
-      </MenuItem>
-      <MenuItem onClick={onSortMenuItemClick} data-value="desc" disabled={sortDirection === 'desc'}>
-        {apiRef.current.getLocaleText('columnMenuSortDesc')}
-      </MenuItem>
+      {sortingOrder.map((direction) => {
+        if (direction === 'asc') {
+          return (
+            <MenuItem
+              onClick={onSortMenuItemClick}
+              data-value="asc"
+              disabled={sortDirection === 'asc'}
+            >
+              {apiRef.current.getLocaleText('columnMenuSortAsc')}
+            </MenuItem>
+          );
+        }
+        if (direction === 'desc') {
+          return (
+            <MenuItem
+              onClick={onSortMenuItemClick}
+              data-value="desc"
+              disabled={sortDirection === 'desc'}
+            >
+              {apiRef.current.getLocaleText('columnMenuSortDesc')}
+            </MenuItem>
+          );
+        }
+        if (direction === null) {
+          return (
+            <MenuItem onClick={onSortMenuItemClick} disabled={sortDirection == null}>
+              {apiRef.current.getLocaleText('columnMenuUnsort')}
+            </MenuItem>
+          );
+        }
+        return null;
+      })}
     </React.Fragment>
   );
 }

```

**Comment by hanbin9775** [comment] 2022-12-06 13:02
Hi! Seems like @cherniavskii already suggested fix for this issue, but could I create a pr for this issue with a bit of code refactoring?

**Comment by hanbin9775** [comment] 2022-12-07 16:00
Hi @MBilalShafi, saw [your commit](https://github.com/MBilalShafi/mui-x/commit/1ea8c4e11ea3fa4d64e8645add49ab6bbbf03d3e) about this issue's fix and have a question about it.
It seems that, it would render the menu items in a different order than the code suggested by @cherniavskii.
Are there any specific rules with ordering menu items?

**Comment by Valentin1918** [comment] 2022-12-07 17:33
Hello @hanbin9775 , according to this PR, looks like the order will be according sortingOrder. Order of IF statements inside a map is not important. So it looks good )

**Comment by Valentin1918** [comment] 2022-12-08 10:18
Sorry, I was speaking about this code snippet https://github.com/mui/mui-x/issues/7103#issuecomment-1339198933 -- it looks good. Concerning [PR](https://github.com/MBilalShafi/mui-x/commit/1ea8c4e11ea3fa4d64e8645add49ab6bbbf03d3e) -- it doesn't take into account an order of sortingOrder

**Comment by MBilalShafi** [comment] 2022-12-08 12:51
>  Are there any specific rules with ordering menu items?

Yes, we need to have a specific order of the column menu items irrespective of the order in `sortingOrder`. `sortingOrder` determines the order in which sorting should be applied not the positioning of items in the menu. As a side effect of changing the order of items unnecessarily, you had to change the test [here](https://github.com/mui/mui-x/pull/7125/files#diff-aecf6c42ff150f1cc861e63b4b1673d61d084435d7722519b4bdab73324de851R237-R238) too.

This should be the order of sort items in the simple column menu:
1. Unsort
2. Ascending
3. Descending

You can use something similar to [this](https://github.com/mui/mui-x/blob/b7e58a0b5371f14fc00b80bab311ab14859b49bc/packages/grid/x-data-grid/src/components/menu/columnMenu/simple/GridColumnMenuSortItemSimple.tsx#L44-L64) to achieve that.

**Closed** 2022-12-27 06:56 UTC
Labels: bug 🐛, component: data grid, good first issue, feature: Sorting
