### ISSUE TITLE
categoryGapRatio & barGapRatio is not a known property of ChartXAxis of Mui-X Barchart.

### ISSUE THREAD

**Issue by deyvinz** [mui/mui-x#13601] opened 2024-06-23 08:39 UTC
### Related page

https://mui.com/x/react-charts/bars/

### Kind of issue

Unclear explanations

### Issue description

Adding the **categoryGapRatio and barGapRatio** properties to the MUI-X bar chart throws an error and prevents application from successful build
![Screenshot 2024-06-23 at 4 33 59 AM](https://github.com/mui/mui-x/assets/11481290/4c493156-851e-4810-9046-f1413464c723)
![Screenshot 2024-06-23 at 4 33 37 AM](https://github.com/mui/mui-x/assets/11481290/111fdaa4-b15a-4a58-8c91-a7a5329647d2)

### Context

I added a MUI-X bar chart to a react component and I need the bar size to be customizable. I found out there is a property to do that, called categoryGapRatio. Whenever I add the **categoryGapRatio and barGapRatio** properties, I keep getting an error but whenever it's removed the bar chart works correctly.

**Search keywords**: categoryGapRatio

**Comment by deyvinz** [comment] 2024-06-23 15:51
The MUI-X documentation did not provide information on how to correctly configure this or fix the issue. I was able to fix this by following these steps:

1. You'll need to add this import `import { AxisScaleConfig } from '@mui/x-charts/internals';` then create a custom axisConfig of type <AxisScaleConfig> which is the interface that has the categoryGapRatio property. The custom axis config should have all the different scale type and should look like this: <img width="596" alt="Screenshot 2024-06-23 at 11 27 51 AM" src="https://github.com/mui/mui-x/assets/11481290/74537ddb-da8e-4f3c-861f-7dfff7fac061">
2. The next step is updating the xAxis props of the BarChart element with the custom config we created in step 1 and it should like this (take note of the highlighted part): 
<img width="446" alt="Screenshot 2024-06-23 at 11 31 18 AM" src="https://github.com/mui/mui-x/assets/11481290/27c2a60d-6176-4eb0-a9df-1f901590d2de">

**Comment by alexfauquette** [comment] 2024-06-24 07:56
Hi @deyvinz thanks for reporting this issue. It looks like a duplicate of #10334 can you confirm?

**Comment by deyvinz** [comment] 2024-06-24 11:04
> Hi @deyvinz thanks for reporting this issue. It looks like a duplicate of #10334 can you confirm?
> 
> 

Yes this is correct

**Comment by michelengelen** [comment] 2024-06-24 12:43
closing this in favor of #10334 then! Thanks for raising this @deyvinz 👍🏼

**Closed by michelengelen** 2024-06-24 12:43 UTC
Labels: status: waiting for maintainer, support: docs-feedback, component: charts
