### ISSUE TITLE
[docs] Improve the "Getting Started" page to avoid passing the wrong adapter to `LocalizationProvider`

### ISSUE THREAD

**Issue by gmumdzhiev** [mui/mui-x#8327] opened 2023-03-22 09:11 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

It is pretty straight forward i use `moment` instead of `dayjs` because i saw that was from the supported libraries : 

https://www.npmjs.com/package/@mui/x-date-pickers
" Then install the date library of your choice (if not already installed). We currently support 4 different date-libraries:
- [date-fns](https://date-fns.org/)
- [Day.js](https://day.js.org/)
- [Luxon](https://moment.github.io/luxon/#/)
- [Moment.js](https://momentjs.com/)"

``` 
"dependencies": {
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/material": "^5.11.13",
    "@mui/styled-engine-sc": "^5.11.11",
    "@mui/x-date-pickers": "^6.0.2",
    "dayjs": "^1.11.7",
    "styled-components": "^5.3.9"
}
```

```
import { DateCalendar } from '@mui/x-date-pickers';
import moment from 'moment';
...
const [currentDate, setCurrentDate] = useState<moment.Moment | null>(null)
const [selectedDate, setSelectedDate] = useState<moment.Moment | null>(null)
...
const handleDateChange = (newDate: moment.Moment | null) => {
setSelectedDate(newDate)
}
...
return (
...
   <DateCalendar
      disablePast={true}
      defaultValue={currentDate}
      onChange={(newDate: any) =>
      handleDateChange(moment(newDate))}
    />
```

But when i do the whole chrome window freezes. No errors to see , nothing. 
Example seems to be doing fine : `  const initialValue = dayjs('2023-03-22')`
But if i try : `const initialValue = moment('2023-03-22')`

Again i have the same issue. So i am wondering am i doing something wrong or just `moment` isn't supported at all.? 

```
  Chrome Version 111.0.5563.64 (Official Build) (arm64) 🌐 
```
</details>

**Comment by flaviendelangle** [comment] 2023-03-22 09:21
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by gmumdzhiev** [comment] 2023-03-22 10:29
Okay , so yeah this fix my issue . Thanks 
But maybe would be a good idea you guys to update the documentation and mention if you want to use another library than `dayjs` you need to import it from the provider first

**Comment by LukasTy** [comment] 2023-03-22 10:43
Everything related to adapter and localization [can be found here](https://mui.com/x/react-date-pickers/adapters-locale/).
We have plans to document the adapters even more elaborately to reduce the friction and increase awareness. 😉

**Comment by gmumdzhiev** [comment] 2023-03-22 10:49
Sounds good to me. Keep up with the good job guys !!! Cheers 🍻

**Comment by flaviendelangle** [comment] 2023-03-22 10:53
> This component receives your chosen date library's adapter and makes it accessible to all the Date and Time Pickers component using React context.

In the link you sent, we are saying to use the right adapter.
Maybe we could add a comment on the example below:


```tsx
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'

function App({ children }) {
  return (
    // Replace with your
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      {children}
    </LocalizationProvider>
  );
```

**Comment by gmumdzhiev** [comment] 2023-03-22 11:03
@flaviendelangle To be honest for me wasn't clear enough with the adapters, and that's why i came across my issue. 
On my opinion will be better if you guys include an example on **_Gettings started_** how can you use different adaptors.
Like you have written  👉  [here](https://mui.com/x/react-date-pickers/adapters-locale/)

**DayJS :_** 
```
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterLuxon';

<LocalizationProvider dateAdapter={AdapterDayjs} >
  {children}
</LocalizationProvider>
```

**_Luxon :_** 
```
import { AdapterLuxon } from '@mui/x-date-pickers/AdapterLuxon';

<LocalizationProvider dateAdapter={AdapterLuxon} >
  {children}
</LocalizationProvider>;
```
**_Moment :_**
```
import { AdapterMoment } from '@mui/x-date-pickers/AdapterMoment';
import 'moment/locale/de';

<LocalizationProvider dateAdapter={AdapterMoment} >
  {children}
</LocalizationProvider>;
```

**Comment by flaviendelangle** [comment] 2023-05-19 07:42
@LukasTy @joserodolfofreitas 

We have a demo just above saying 

> Before trying to render any component, you have to make sure that there is a LocalizationProvider upper in the React tree. This component receives your chosen [date library's adapter](https://mui.com/x/react-date-pickers/#date-library) (the doc uses AdapterDayjs which is based on [dayjs](https://day.js.org/)) and makes it accessible to all the Date and Time Pickers component using React context.

I don't think putting 4 basic examples in "Render your first component" is the way to go.
Because even if we do so, we would have the same problem with people just going to the "Date Picker" page for example and not checking "Getting Started".

I would more be in favor of adding a warning in "Render your first component" saying something like

> If you are using another date library than `dayjs`, makes sure to [setup the right adapter](/x/react-date-pickers/getting-started/#setup-your-date-library-adapter)

**Comment by LukasTy** [comment] 2023-05-19 07:47
> I would more be in favor of adding a warning in "Render your first component" saying something like
> 
> > If you are using another date library than `dayjs`, makes sure to [setup the right adapter](/x/react-date-pickers/getting-started/#setup-your-date-library-adapter)
> 
> And potentially to improve the "Setup your date library adapter" section.

That is a really great suggestion! I'm in favor of having a small un-intrusive callout or even a paragraph section linking to the right documentation page. 👍

**Comment by LukasTy** [comment] 2024-06-27 14:33
@flaviendelangle @gmumdzhiev Given the current state of [Getting started—Installation](https://mui.com/x/react-date-pickers/getting-started/#installation) and [Getting started—Setup your date library adapter](https://mui.com/x/react-date-pickers/getting-started/#setup-your-date-library-adapter) do you still think that we are missing some clarity in this documentation? 🤔
Or is the documentation sufficient and we can close this issue as completed? 🤔

**Comment by flaviendelangle** [comment] 2024-06-27 18:43
I think we can close it :ok_hand:

**Closed** 2024-06-28 06:08 UTC
Labels: docs, component: pickers
