### ISSUE TITLE
[pickers] Add style override for sub components

### ISSUE THREAD

**Issue by AsemK** [mui/mui-x#4669] opened 2021-08-10 13:20 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

After migrating pickers to emotion (v4 to v5), I lost the ability to modify the styling of some subcomponents. I think this is due to the fact that `styled` is used without providing the `name` option as can be seen in

https://github.com/mui/mui-x/blob/ebb0e3b1a4d940b02ca20abd61ade86fce9b6e94/packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx#L31

## Expected Behavior 🤔
I should be able to style the subcomponents of pickers. For instance, in RTL view, the `TimeContainer` component of `DateTimePickerToolbar` used in `MobileDateTimePicker` shows the time with `direction: rtl`. I want to change this behavior so that the time is always `ltr` even if the theme is `rtl`. Previously, with JSS, this worked:
```javascript
const theme = createTheme({
  direction: rtl,
  components: {
      MuiDateTimePickerToolbar: {
        styleOverrides: {
          timeContainer: {
            flip: false,
            direction: "ltr",
          },
        },
      },
    },
});
```
Now, with emotion, I would expect the following to work, but it doesn't:
```javascript
const theme = createTheme({
  direction: rtl,
  components: {
      MuiDateTimePickerToolbar: {
        styleOverrides: {
          root: {
            "& .MuiDateTimePickerToolbar-timeContainer": {
              direction: "/* @noflip */ ltr",
            },
          },
        },
      },
    },
});
```

Also, when inspecting the element, the class name is not `MuiDateTimePickerToolbar-timeContainer` or anything similar, but `muirtl-1lomthf`.

Is there currently a work around for this?

**Comment by m4theushw** [comment] 2022-05-02 15:36
During the migration to emotion we missed to properly convert some internal components. We decided to leave this task for the community. There're a few components where the slot name and overrides resolver is missing. Feel free to open a pull request converting any of the components from the list below. You can use #4672 as example.

Checklist:

- [ ] Set the name, slot and `overridesResolver` in `styled`
- [ ] Generate `classes` using `generateUtilityClasses`
- [ ] Pass the appropriate `classes.XXX` to the `className` prop of the internal components (use `clsx` to merge with user-provided `className` prop, if available)

Components whose slot name is missing:

- [ ] packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx
- [ ] packages/x-date-pickers/src/CalendarPicker/PickersCalendarHeader.tsx
- [ ] packages/x-date-pickers/src/CalendarPicker/PickersFadeTransitionGroup.tsx
- [ ] packages/x-date-pickers/src/ClockPicker/Clock.tsx
- [ ] packages/x-date-pickers/src/ClockPicker/ClockNumber.tsx
- [ ] packages/x-date-pickers/src/ClockPicker/ClockPointer.tsx
- [ ] packages/x-date-pickers/src/DatePicker/DatePickerToolbar.tsx
- [ ] packages/x-date-pickers/src/DateTimePicker/DateTimePickerTabs.tsx
- [ ] packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx
- [ ] packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx
- [ ] packages/x-date-pickers/src/YearPicker/PickersYear.tsx
- [ ] packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx
- [ ] packages/x-date-pickers/src/internals/components/PickersPopper.tsx
- [ ] packages/x-date-pickers/src/internals/components/PickersToolbar.tsx
- [ ] packages/x-date-pickers/src/internals/components/PickersToolbarButton.tsx
- [ ] packages/x-date-pickers/src/internals/components/PickersToolbarText.tsx
- [ ] packages/x-date-pickers/src/internals/components/CalendarOrClockPicker/CalendarOrClockPicker.tsx
- [x] ~packages/x-date-pickers/src/internals/components/PickerViewRoot/PickerViewRoot.tsx~ (not needed)

@flaviendelangle Is there any component you would like to remove from the list? I did a search for all `styled` with a single argument.

**Comment by flaviendelangle** [comment] 2022-05-11 11:46
`ClockPointer` has the following comment

```ts
/**
 * @ignore - internal component.
 * TODO: Remove class
 */

I did not look at it before, but I would avoid to make it customizable for now.
```


___

`PickersModalDialog` may be removed soon if we want to unify the tooltip / modal behavior between the non-range and range pickers.
So I would avoid to make it customizable for now.

**Comment by m4theushw** [comment] 2022-05-11 12:17
About the "Remove class" comment, I think it refers to converting the class component into a functional component. This component is responsible for the arrow pointing to the selected hour/minute, it can't be removed.

**Comment by flaviendelangle** [comment] 2022-05-11 12:22
Right, I am so unused to class components nowadays :laughing:

**Comment by flaviendelangle** [comment] 2022-05-12 09:21
List for the pro components

- [ ]  packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerInput.tsx
- [ ]  packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerToolbar.tsx
- [ ]  packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerViewDesktop.tsx
- [ ]  packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerDay.tsx

I am taking care of all the picker toolbars (to correctly do the `DateRangePickerToolbar` I have to do `PickersToolbar`).
I will do all the pro components in a follow up PR.

**Comment by m4theushw** [comment] 2022-05-13 14:02
@flaviendelangle I was tracking the Pro components in #4673

**Comment by vamsivemp** [comment] 2022-07-08 05:56
Hey Guys...we are facing some challenges in trying to style the AM/PM button in the TimePicker...there are no css classes to distinguish a selected AM/PM button from a non selected button like how we have for the Clock...is there an expected timeline when will the style overrides be resolved...is there any solution you guys would recommend...

**Comment by LukasTy** [comment] 2022-09-16 06:55
All the mentioned issues should be fixed with the release of #6156 (should be today).
If any other styling issues are encountered - please open a new issue. 👌

**Closed by LukasTy** 2022-09-16 06:55 UTC
Labels: new feature, good first issue, component: pickers, custom: css

**Comment by LukasTy** [comment] 2022-10-25 08:39
Hello @kellyndassler 
Thank you for mentioning this issue.
Are you having trouble styling it via MUI create or regular CSS approach?
If it's MUI theme overrides—maybe [such approach](https://codesandbox.io/s/blue-https-n4kege?file=/demo.tsx) would suffice?

**Comment by Konstantin-Ushakov** [comment] 2022-10-27 04:26
Hello. I have same troubles with styles of `TimePicker` on `DateTimePicker` with `MuiClockPointer-thumb` component.
The problem is I want to change color of this component but either lost dot in selection minutes (when time not divide by 5), or this point appear default color both on hours and minutes (when minutes divide by 5).
Both times it have className like
- `MuiClockPointer-thumb css-12t0dn4-MuiClockPointer-thumb`
- `MuiClockPointer-thumb css-eg3pzz-MuiClockPointer-thumb`
How I should determine and styling this?

**Comment by LukasTy** [comment] 2022-10-27 06:31
Hello @Konstantin-Ushakov 
Would [this sandbox](https://codesandbox.io/s/divine-http-sh3iwc?file=/demo.tsx) be of any help in solving your styling needs?
