### ISSUE TITLE
[XGrid] Column Header Spacing

### ISSUE THREAD

**Issue by jamintz** [mui/mui-x#2875] opened 2021-10-14 18:42 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

DataGrid column headers currently have a lot of their width taken up by the menu button and the asc / desc sort switch. This means that even for a column with decent width there is not much room to display the column title text:
<img width="167" alt="Screen Shot 2021-10-14 at 2 39 55 PM" src="https://user-images.githubusercontent.com/3538254/137376711-a89f00aa-1bd3-481d-afc3-c3bf92b600f2.png">

An alternative would be to let the title take up the full width, and turn the title into a dropdown menu that you can then filter / sort from

### Examples 🌈

Examples here from similar program:

<img width="100" alt="Screen Shot 2021-10-14 at 2 40 43 PM" src="https://user-images.githubusercontent.com/3538254/137376934-7ba79e32-d15a-4e23-8de8-7e20f03665fc.png"

<img width="304" alt="Screen Shot 2021-10-14 at 2 40 49 PM" src="https://user-images.githubusercontent.com/3538254/137376940-0b5a58ea-7bdb-4f8b-b19c-8f393063de7d.png">
>

### Motivation 🔦

Better readability / usability of many-column grids

### Order ID 💳 (optional)

21172

**Comment by DanailH** [comment] 2021-10-15 13:09
Hi @jamintz, thanks for raising this but it seems to be a duplicate of https://github.com/mui-org/material-ui-x/issues/2460. You can use the solution provided on the linked issue or you can upgrade and get that functionality OOTB. It's included in `v5.0.0-beta.2`

**Closed as completed** 2021-10-15 13:42 UTC
Labels: duplicate, scope: data grid
