### ISSUE TITLE
Datagrid stops scrolling intermittently until mouse move

### ISSUE THREAD

**Issue by samfweb** [mui/mui-x#5153] opened 2022-06-09 04:57 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Datagrid stops scrolling at certain intervals. Moving the mouse fixes this.

### Expected behavior 🤔

Datagrid should continue scrolling without needing to move the mouse

### Steps to reproduce 🕹

Steps:

1. Go to https://mui.com/x/react-data-grid/demo/
2. Hover the mouse over a row
3. Scroll down
4. Notice scrolling halts before the last row

### Context 🔦

N/A

### Your environment 🌎

N/A

### Order ID 💳 (optional)

30466

**Comment by cloughney** [comment] 2022-06-09 17:43
I'm also seeing this behavior, but only on Chrome/Edge on Windows. Chrome and Safari on Mac, and Firefox seem to behave normally.

**Comment by DanailH** [comment] 2022-06-10 10:00
Hmm interesting. @m4theushw can you reproduce the issue (I remember that you are using Windows).

On another note - it seems that the scrollbar doesn't go all the way to the bottom (at last on Mac).
![Screenshot 2022-06-10 at 11 57 35](https://user-images.githubusercontent.com/5858539/173041641-b2753bf9-9bf2-4c98-b76b-ef104d829c75.png)

**Comment by SailorStat** [comment] 2022-06-10 14:32
A similar problem in Chrome OS Linux Ubuntu. Scrolling does not work with a mouse or touchpad. If you move the cursor or wait a bit without triggering the scroll, then you can scroll for a while

**Comment by m4theushw** [comment] 2022-06-10 14:50
To give an update, I managed to reproduce it in Windows. We only need to investigate where's the problem.

**Comment by m4theushw** [comment] 2022-06-10 20:21
This bug can also be reproduced with primitives: https://codesandbox.io/s/data-grid-community-forked-9u2ypd?file=/src/App.tsx

If you scroll inside the green area it works, but try to scroll in the yellow area and it stops scrolling after some time. In the console, you can see that, when the scroll stops, the `scroll` event also stops being fired, but `wheel` continues.

My hypothesis is that Chrome is trying to scroll the row and not the main container. Searching a bit I found a similar problem being related in https://www.bennadel.com/blog/3544-trapping-the-wheel-event-may-prevent-chrome-browser-bug-in-which-the-scroll-wheel-stops-working-in-overflow-container.htm

I noticed that if the content div (the green area) has `pointerEvents: none`, then the scroll works. I propose to use this as solution, only during scroll.

**Comment by hikotq** [comment] 2022-06-13 07:14
I had the same problem on my environment with Chrome on Windows, but not with Chrome Canary.
Probably https://bugs.chromium.org/p/chromium/issues/detail?id=1330045&q=scroll&can=2 is the corresponding Chrome issue.

**Comment by BrokerDB** [comment] 2022-06-14 06:52
It works for me after adding the following code inside DataGrid component: sx={{
            ".MuiDataGrid-virtualScrollerContent": {
              pointerEvents: "none",
            },
          }}

**Comment by m4theushw** [comment] 2022-06-17 18:11
I also tested in Chrome Canary and I couldn't reproduce it. That means it's already fixed and soon will be available in the stable version. The only workaround I can recommend is to add `pointer-events: none` to `.MuiDataGrid-virtualScroller`. Unfortunately this also blocks any selection or click inside the rows. Another alternative is to detect the scroll in this element and only disable the pointer events during scroll. Not ideal but we don't have much to do here. Using the scrollbar to scroll might also be an option.

**Comment by m4theushw** [comment] 2022-09-01 14:54
I'm closing because I can't reproduce it anymore. Probably the new Chrome release fixed it.

**Closed by m4theushw** 2022-09-01 14:54 UTC
Labels: bug 🐛, component: data grid, feature: Rendering layout
