### ISSUE TITLE
[docs] Tree View: check children, uncheck parents

### ISSUE THREAD

**Issue by johnnyreilly** [mui/mui-x#13246] opened 2024-05-24 21:06 UTC
### Related page

https://mui.com/x/react-tree-view/rich-tree-view/selection/

### Kind of issue

Missing information

### Issue description

I'm not sure if this is a component issue or a docs issue. Essentially the treeview component has default behaviours which differ from that which you typically find in a treeview component. I'm speaking about node selection. I'm used to a treeview component that, when a parent node is selected, auto selects the child nodes underneath. And by turn, when nodes are deselected, the parent nodes get deselected.

I've found out that it's possible to implement this manually and have blogged about it here:

https://johnnyreilly.com/mui-react-tree-view-check-children-uncheck-parents

Would it be useful to add this directly to the documentation, for those that might not happen on my blog?  I'd be happy to submit a PR. Or if you're happy linking to my blog, please feel free to.

### Context

See above 

**Search keywords**: Treeview

**Comment by oliviertassinari** [comment] 2024-05-25 14:16
This looks like a duplicate of #12883 to me

**Closed** 2024-05-27 09:20 UTC
Labels: status: waiting for maintainer, component: tree view, support: docs-feedback
