### ISSUE TITLE
[Data Grid] Filter toolbar button tooltip shows [Object Object]

### ISSUE THREAD

**Issue by konrazem** [mui/mui-x#5496] opened 2022-07-14 15:03 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Setting filter item value as object shows [Object Object] in filter tooltip. This is because tooltip value is converted to string: https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx#L88. 
![2](https://user-images.githubusercontent.com/19363700/179011424-1a0d548f-a982-4a14-bf50-5d522b0916ef.PNG)

### Expected behavior 🤔

I would like to change filter tooltip values or hide tooltip.

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/initialfilters-demo-mui-x-forked-zdx6mj?file=/demo.tsx

Steps:
1. Go to demo https://mui.com/x/react-data-grid/demo/ 
2. Set filter for Country "Argentina"
3. Hover over filter button you will see "AR" and not "Argentina"

Or set film filter in a given codesandbox example.

### Context 🔦

I want to show custom tooltip value. For example:
- in case of selected id's or enums (like in your example with countires) I do not want to show those but coresponding values. 
- in case of filter item value set as object I want to show its properties
- when there are many filter items (in case of "is any of" operator) I want to show i.e "one, two, +34" and not a full list of 36 items.

### Your environment 🌎

System:
OS: Windows 10 10.0.19043
CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Memory: 11.26 GB / 39.78 GB
Binaries:
Node: 16.14.0
Yarn: 1.22.15
npm: 8.3.1
Utilities:
Git: 2.34.1.
Virtualization:
Docker: 20.10.12
IDEs:
VSCode: 1.69.1
Languages:
Bash: 4.4.20
Browsers:
Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)
Internet Explorer: 11.0.19041.1566

### Order ID 💳 (optional)

46820

**Comment by m4theushw** [comment] 2022-07-15 19:26
Duplicate of #5492

**Closed by m4theushw** 2022-07-15 19:26 UTC
Labels: status: needs triage
