### ISSUE TITLE
[DataGrid] Error when action buttons changes number of actions

### ISSUE THREAD

**Issue by bjornarvh** [mui/mui-x#4682] opened 2022-04-28 08:51 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If an action button causes the buttons to change, and the new amount of buttons is less than the index of the button that triggered the change, the grid crashes. Looks like it caused by the grid trying to put focus on the button at the same index.

### Expected behavior 🤔

Should not crash, and the last action button should get focus.

### Steps to reproduce 🕹

Steps:

1. Codepen: https://codesandbox.io/s/fullfeaturedcrudgrid-material-demo-forked-7d2q7m?file=/demo.js
2. Click edit button on a row
3. When in edit mode, click the cancel edit button
4. 💥

### Your environment 🌎

  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: Not Found
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.4.0 => 11.9.0 
    @emotion/styled: ^11.3.0 => 11.8.1 
    @mui/base:  5.0.0-alpha.78 
    @mui/icons-material: ^5.6.2 => 5.6.2 
    @mui/lab: ^5.0.0-alpha.78 => 5.0.0-alpha.79 
    @mui/material: ^5.6.2 => 5.6.3 
    @mui/private-theming:  5.6.2 
    @mui/styled-engine:  5.6.1 
    @mui/system:  5.6.3 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-data-grid:  5.10.0 
    @mui/x-data-grid-pro: ^5.10.0 => 5.10.0 
    @mui/x-date-pickers:  5.0.0-alpha.0 
    @mui/x-license-pro:  5.10.0 
    @types/react: ^18.0.5 => 18.0.8 
    react: ^18.0.0 => 18.1.0 
    react-dom: ^18.0.0 => 18.1.0 
    typescript: ^4.6.2 => 4.6.3 

### Order ID 💳 (optional)

#41348

**Comment by m4theushw** [comment] 2022-04-29 00:22
Duplicate of #4675

**Closed** 2022-04-29 00:22 UTC
Labels: status: needs triage
