### ISSUE TITLE
[charts] Infinite height if LineChart component prop height is not set and there is an another element in the div

### ISSUE THREAD

**Issue by smarandaparincu** [mui/mui-x#12263] opened 2024-02-29 14:32 UTC
### Related page

https://next.mui.com/x/react-charts/lines/

### Kind of issue

Broken demo

### Issue description

If my component is as follows:
```ts
<LineChart
      dataset={dataEntries}
      xAxis={[{ ...xAxis }]}
      series={series}
      grid={{ horizontal: true, vertical: true }}
      sx={{
        [`& .${axisClasses.left} .${axisClasses.label}`]: {
          transform: 'translateX(-40px)',
        },
        [`& .${chartsGridClasses.line}`]: { strokeDasharray: '5 3' },
      }}
      yAxis={[{ ...yAxis }]}
      slotProps={{ legend: { hidden: true } }}
      colors={blueberryTwilightPalette}
    />
```
Everything works as expected. As soon as that is wrapped in a div with a `p` element, the chart's height increase infintely

### Context

I want my LineChart component to take the available space as well as add another component on top of it

**Search keywords**: height Mui/x-charts LineChart

**Comment by michelengelen** [comment] 2024-03-01 11:43
Hey @smarandaparincu,

I cannot reproduce your issue. I did test it with this code:

```tsx
import * as React from 'react';
import { LineChart } from '@mui/x-charts/LineChart';
import { axisClasses, chartsGridClasses } from '@mui/x-charts';

export default function BasicLineChart() {
  return (
    <div style={{ height: '300px' }}>
      <p>Basic Line Chart</p>
      <LineChart
        xAxis={[{ data: [1, 2, 3, 5, 8, 10] }]}
        series={[
          {
            data: [2, 5.5, 2, 8.5, 1.5, 5],
          },
        ]}
        grid={{ horizontal: true, vertical: true }}
        sx={{
          [`& .${axisClasses.left} .${axisClasses.label}`]: {
            transform: 'translateX(-40px)',
          },
          [`& .${chartsGridClasses.line}`]: { strokeDasharray: '5 3' },
        }}
        slotProps={{ legend: { hidden: true } }}
      />
    </div>
  );
}
```

[Codesandbox here](https://codesandbox.io/p/sandbox/recursing-smoke-plsfmy)

Could you check this with your implementation to see if this is what you want to achieve and if there are differences?

**Comment by smarandaparincu** [comment] 2024-03-01 12:00
If you set the height like this: `style={{ height: '100%' }}`, you will get the behaviour I am describing

**Comment by michelengelen** [comment] 2024-03-01 12:16
I still cannot reproduce the issue you are describing.
Just note that the charts do need **some** form of intrinsic dimension to calculate correctly. This can be a container that restricts the dimensions (can be fluid as well), or on the chart itself using the `width` and `height` props.

This is the related docs page: [Composition - Responsive](https://mui.com/x/react-charts/composition/#responsive)

This is with `style={{ height: '100%' }}` on the `div`:
<img width="2484" alt="Screenshot 2024-03-01 at 13 10 55" src="https://github.com/mui/mui-x/assets/32863416/436e7d4e-b376-45bf-ba72-a5430ee5f2bc">

I could not reproduce any scenario where the chart would have infinite height.

**Comment by smarandaparincu** [comment] 2024-03-01 14:21
Could you wrap it in a Grid? For example:
```ts
<Grid container spacing={2} sx={{ width: '100%', height: '100%' }}>
      <Grid item xs={12}> 
      <p>Basic Line Chart</p>
      <LineChart
        xAxis={[{ data: [1, 2, 3, 5, 8, 10] }]}
        series={[
          {
            data: [2, 5.5, 2, 8.5, 1.5, 5],
          },
        ]}
        grid={{ horizontal: true, vertical: true }}
        sx={{
          [`& .${axisClasses.left} .${axisClasses.label}`]: {
            transform: 'translateX(-40px)',
          },
          [`& .${chartsGridClasses.line}`]: { strokeDasharray: '5 3' },
        }}
        slotProps={{ legend: { hidden: true } }}
      />
      </Grid>
    </Grid> 
   ```

**Comment by michelengelen** [comment] 2024-03-01 14:56
@alexfauquette I can confirm this bug now.
For some reason it expands endlessly. This is the code snippet i used for it:

```tsx
import * as React from 'react';
import { LineChart } from '@mui/x-charts/LineChart';
import { Grid } from '@mui/material';
import { axisClasses, chartsGridClasses } from '@mui/x-charts';

export default function ChartsOverviewDemo() {
  return (
    <Grid container spacing={2} sx={{ width: '100%', height: '100%' }}>
      <Grid item xs={12}>
        <p>Basic Line Chart</p>
        <LineChart
          xAxis={[{ data: [1, 2, 3, 5, 8, 10] }]}
          series={[
            {
              data: [2, 5.5, 2, 8.5, 1.5, 5],
            },
          ]}
          grid={{ horizontal: true, vertical: true }}
          sx={{
            [`& .${axisClasses.left} .${axisClasses.label}`]: {
              transform: 'translateX(-40px)',
            },
            [`& .${chartsGridClasses.line}`]: { strokeDasharray: '5 3' },
          }}
          slotProps={{ legend: { hidden: true } }}
        />
      </Grid>
    </Grid>
  );
}
```

I am not so sure if this can be considered a bug though . 🤔 WDYT?

**Comment by alexfauquette** [comment] 2024-03-01 21:42
Looks like the parent size depends on the children, and of course when the chart set its height, the parent increase, then the chart adapt, and we enter an infinite loop. 

Not sure we can do something for that

**Comment by michelengelen** [comment] 2024-03-04 10:24
@smarandaparincu as @alexfauquette described we cannot do something about this. 
Depending on what you are trying to achieve it should be possible to do it without using a fully fluid container using `flex`.

Let us know if we can assist you in that.
I will close the issue for now, but feel free to reopen. Thanks! 🙇🏼

**Closed by michelengelen** 2024-03-04 10:24 UTC
Labels: status: waiting for maintainer, support: docs-feedback, component: charts

**Comment by isdisd2** [comment] 2024-06-07 10:08
same problem...
