### ISSUE TITLE
Trimming trailing space filter not working

### ISSUE THREAD

**Issue by simbahandiane** [mui/mui-x#5693] opened 2022-08-03 16:36 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Trimming of trailing space filter is not working with  valueFormatter and valueParser. Also, it is not working with serverside filtering.

### Expected behavior 🤔

Trimming of trailing space filter is should work with  valueFormatter and valueParser. Should work with server side filtering

### Steps to reproduce 🕹

Link to live example:

Steps:
1. use valueFormatter and valueParser to format value and display of the column
2. Tried filtering with spaces before and after the word
3. filter returns no result
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

33625

**Comment by cherniavskii** [comment] 2022-08-03 16:47
Hey @simbahandiane 
Can you provide a minimal example reproducing the issue?
You can create one starting from demos in our docs: https://mui.com/x/react-data-grid/filtering/
Thanks!

**Comment by simbahandiane** [comment] 2022-08-03 18:13
See https://codesandbox.io/s/controlledfilters-demo-mui-x-forked-m0i9o2?file=/demo.tsx

**Comment by simbahandiane** [comment] 2022-08-03 18:39
For the trimming of trailing space on server side filtering, I can't make a sample code.

**Comment by cherniavskii** [comment] 2022-08-04 09:16
> See [codesandbox.io/s/controlledfilters-demo-mui-x-forked-m0i9o2?file=/demo.tsx](https://codesandbox.io/s/controlledfilters-demo-mui-x-forked-m0i9o2?file=/demo.tsx)
> 
> On our project, only valueFormatter and valueParser can be used for a specific column/filter

What are the steps to reproduce the issue?
I see there's `filterModel` commented out with a filter value "Jon ", but I'm not sure if that's what you mean since it targets column without `valueFormatter`/`valueParser`

**Comment by simbahandiane** [comment] 2022-08-04 10:22
I just put the valueFormatter and valueParser there. So the scenario for the column is this,

The value of the column is enum like 1, 2.
If the value of column is 1, display 'Page' else 'Field'. Then try to filter it with 'Page', it return results but if you filter it with trailing space like '  Page', returns no result.

**Comment by cherniavskii** [comment] 2022-08-04 10:52
@simbahandiane I don't think I understand what you mean

> So the scenario for the column is this

Which column?

> The value of the column is enum like 1, 2.
> If the value of column is 1, display 'Page' else 'Field'.

I don't see anything like that in the linked demo.

Can you double check the demo and link it again with step by step instructions to reproduce the issue?
Thank you!

**Comment by simbahandiane** [comment] 2022-08-04 14:42
I have updated the demo. See the type column. Thank you!

**Comment by cherniavskii** [comment] 2022-08-04 16:02
For the `valueParser` - you get the original input value in there. That's expected behavior.
You can do `value.trim()` if you want to trim spaces.

But wouldn't `singleSelect` column type be a better choice for this kind of data?
See this demo: https://codesandbox.io/s/controlledfilters-demo-mui-x-forked-rhjybe?file=/demo.tsx

**Comment by cherniavskii** [comment] 2022-08-04 16:03
I'm closing the issue, since that's expected behavior and there's no action to be done on our side

**Closed by cherniavskii** 2022-08-04 16:03 UTC
Labels: support: question, component: data grid, plan: Pro, feature: Filtering
