### ISSUE TITLE
[DataGrid] Dimension computation issue with Grow transitions

### ISSUE THREAD

**Issue by LeoLozes** [mui/mui-x#1101] opened 2021-02-22 08:35 UTC
I have a Data Grid rendering inside a Popper. The container has a fixed width of 945px. 
However the `MuiDataGrid-viewport` has these calculated values in his style attribute:

```
min-width: 708.75px;
max-width: 708.75px;
min-height: 416px;
max-height: 416px;
```

The parent MuiDataGrid-dataContainer has these:

```
min-height: 433px;
min-width: 940px;
```

The result is this rendering:

![image](https://user-images.githubusercontent.com/11133817/108681616-a8077980-74ef-11eb-9275-603a1bc0afa2.png)

Anytime I open something else in the popper before, or resize (basically, re-render the grid), it displays correctly:

![image](https://user-images.githubusercontent.com/11133817/108681736-c9686580-74ef-11eb-8556-73d58690c4f0.png)

I've tried changing the column width, putting fixed width in the grid, changing styles, nothing I tried fixed it.

The project structure is rather big so creating a codepen that reproduces it is not easy, though I get that with the current information it might be really difficult to reproduce. 

This is the dataGrid code:

```javascript
const columns = (intl: IntlShape, setAvailabilityParameters: (parameters: AvailabilityParameters) => void): ColDef[] => [
  { field: 'searchItem', headerName: formatMessage(intl, 'searcher.selector.main.label'), disableColumnMenu: true, width: 250 },
  { field: 'dateFrom', headerName: formatMessage(intl, 'general.dateFrom'), disableColumnMenu: true, width: 115 },
  { field: 'dateTo', headerName: formatMessage(intl, 'general.dateTo'), disableColumnMenu: true, width: 115 },
  { field: 'distribution', headerName: formatMessage(intl, 'searcher.selector.distribution.label'), disableColumnMenu: true, width: 250 },
  { field: 'mealPlan', headerName: formatMessage(intl, 'general.mealPlan'), disableColumnMenu: true, width: 150 },
  {
    field: 'action', headerName: ' ', disableColumnMenu: true, width: 60,
    renderCell: (params: CellParams) => (
      <IconButton
        size="small"
        style={{ marginRight: 8 }}
        onClick={() => { setAvailabilityParameters(params.value! as AvailabilityParameters) }}
      >
        <SearchIcon color="primary" />
      </IconButton>
    ), },
];

const rows = (recentSearches: AvailabilityParameters[], intl: IntlShape): RowData[] => {
  let id = 0;
  const rows: RowData[] = [];
  for (const search of recentSearches) {
    rows.push({
      id: id++,
      searchItem: search.selectedItem.name,
      dateFrom: formatDate(intl, search.dateFrom),
      dateTo: formatDate(intl, search.dateTo),
      distribution: getDistribution(search, intl),
      mealPlan: search.mealPlan?.name,
      action: search
    })
  }
  return rows;
};

export interface Props {
  onSearch?: () => void;
  setAvailabilityParameters: (parameters: AvailabilityParameters) => void;
}

function RecentSearches(props: Props) {
  const classes = useStyles();
  const intl = useIntl();

  const recentSearches = getRecentSearches();

  return (
    <DataGrid
      className={classes.grid}
      rows={rows(recentSearches, intl)}
      columns={columns(intl, props.setAvailabilityParameters, props.onSearch)}
      autoHeight
      hideFooter
    />
  );
}

```
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Right now, the grid almost always has a calculated viewport smaller than its parent container.

You can see it in action here: https://drive.google.com/file/d/14XOxRZfYGeRWhdmaYPaU61rBvQt7VXBV/view

## Expected Behavior 🤔
The viewport shouldn't truncate the content. 

## Steps to Reproduce 🕹
I think that embedding the grid in a Popper is basically what triggers this behaviour. 

The behaviour is exactly the same in the latest Edge & Firefox releases.

**Comment by oliviertassinari** [comment] 2021-02-23 01:51
Please provide a minimal reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by LeoLozes** [comment] 2021-02-23 07:41
Sorry @oliviertassinari, I must be really dumb, but I can't get the simple codesandbox to work, I'm always getting a "_interopRequireDefault is not a function", I tried adding / removing a couple packages and playing with different versions, but nothing works.

**Comment by dtassone** [comment] 2021-02-23 13:25
The issue comes from the usage of the transition in `Popper`. I believe the calculation are done before the transition is done which creates the issue.
As a workaround, you can either disable the transition or trigger a resize event in your `grid.tsx`

```tsx
  React.useLayoutEffect(()=> {
      window.dispatchEvent(new Event('resize'));
   }, [])
```

**Comment by LeoLozes** [comment] 2021-02-23 13:38
I also thought it was related to the Popper, however if you change in the `Header.tsx` file:

`import RecentSearchesPanel from "./RecentSearchesPanel";`
to
`import RecentSearchesPanel from "./Grid";`

you can see that the problem doesn't happen. 
But I'm sure you are understanding better than me what is happening.

**Comment by oliviertassinari** [comment] 2021-02-27 23:59
@LeoLozes Interesting, it's an issue with the width computation of the data grid and the Grow transition. I have first seen this bug with the Tabs 4 years ago: https://github.com/mui-org/material-ui/issues/9337.

The [workaround](https://github.com/mui-org/material-ui-x/issues/1101#issuecomment-784201029) proposed by @dtassone is also one we have been proposing with the Tabs. The root cause is very likely with this module:

https://github.com/mui-org/material-ui-x/blob/c1e4f779c3f46d34a509f227544a4e943ac89682/packages/grid/_modules_/grid/components/GridAutoSizer.tsx#L4-L5

I think that we can:

1. Fix https://github.com/mui-org/material-ui/issues/22519 in the core.
2. Use resize observer when available, it's still an issue with older versions of iOS.
3. Later, remove `createDetectElementResize`.

**Comment by ZLevine** [comment] 2021-04-23 19:07
> The [workaround](https://github.com/mui-org/material-ui-x/issues/1101#issuecomment-784201029) proposed by @dtassone is also one we have been proposing with the Tabs.

Unfortunately that workaround isn't working for me (even with a `setTimeout`); but I can confirm that not wrapping `<XGrid>` in `<Grow>` fixes it. Obviously, that isn't a solution, but your theory is correct. The current workaround just isn't. :)

**Comment by goppi0** [comment] 2021-11-06 06:30
@ZLevine Have you found a solution using Grow? Thanks

**Comment by ZLevine** [comment] 2021-11-08 21:18
> @ZLevine Have you found a solution using Grow? Thanks

No, unfortunately--we just chose to stop using Grow to wrap this component.

**Comment by m4theushw** [comment] 2022-06-30 11:40
The virtualization engine received a lot of changes since this bug was opened. But because we don't have a reproduction, we can't check if it still exists. However, I can say that the combination of DataGrid + Grow is working now. I created an example: https://codesandbox.io/s/datagridprodemo-demo-mui-x-forked-d35i8b?file=/demo.tsx

I'll close this issue but we can reopen it if the bug persists.

**Closed by m4theushw** 2022-06-30 11:40 UTC
Labels: bug 🐛, component: data grid, feature: Rendering layout
