### ISSUE TITLE
[Next.js 14.x] Error: MUI: Can not find the date and time pickers localization context.

### ISSUE THREAD

**Issue by mtr1990** [mui/mui-x#10841] opened 2023-10-30 10:24 UTC
### Steps to reproduce

Link to live example: (required)

https://codesandbox.io/p/sandbox/agitated-thompson-hs25c3

### Current behavior

Show error warning. Cannot build.

```sh
 ⨯ node_modules/@mui/x-date-pickers/internals/hooks/useUtils.js (8:0) @ useLocalizationContext
 ⨯ Error: MUI: Can not find the date and time pickers localization context.
It looks like you forgot to wrap your component in LocalizationProvider.
This can also happen if you are bundling multiple versions of the `@mui/x-date-pickers` package
null
```

### Expected behavior

No warnings are displayed.

### Context

`"next": "^14.0.0"` and `"@mui/x-date-pickers": "^6.17.0"` => Show Error

`"next": "^13.5.6"` and `"@mui/x-date-pickers": "^6.17.0"` => Not Show Error

**Search keywords**: date pickers localization context.

**Comment by alexfauquette** [comment] 2023-10-31 09:02
Effectively that's strange. I don't know what they changed in v14 about the support of context.


I even tried to modify the example to be as direct as possible, but does not work  https://codesandbox.io/p/sandbox/elated-cookies-tm4g22?file=%2Fapp%2Fpage.tsx%3A143%2C1-151%2C1
```jsx

export default function Page() {
  return (
    <MuiLocalizationProvider dateAdapter={AdapterDateFns}>
      <PickerDate />
    </MuiLocalizationProvider>
  );
}

```

Will try to see if I can reproduce it with just contexts

**Comment by alexfauquette** [comment] 2023-11-09 09:39
Sounds like it's a Next.js bug, and they are aware of it since it's resolved with `"next": "^14.0.2-canary.25"`. It let appearx a new warning. I assume it is also due to some next internal behavior.

Don't hesitate to add comments if you see such a thing again. Maybe a good idea to report the bug on Next.js at the same time

**Closed by alexfauquette** 2023-11-09 09:39 UTC
Labels: status: waiting for maintainer, component: pickers

**Comment by student1060632fpt** [comment] 2024-02-28 15:53
I still got this problem, I already downgrade to `"next": "^14.0.2-canary.25"` like you said and wrap my component in LocalizationProvider. Still stuck in this problem

> Sounds like it's a Next.js bug, and they are aware of it since it's resolved with `"next": "^14.0.2-canary.25"`. It let appearx a new warning. I assume it is also due to some next internal behavior.
> 
> Don't hesitate to add comments if you see such a thing again. Maybe a good idea to report the bug on Next.js at the same time

**Comment by kameshdhana** [comment] 2024-02-29 13:26
> I still got this problem, I already downgrade to `"next": "^14.0.2-canary.25"` like you said and wrap my component in LocalizationProvider. Still stuck in this problem because of `Module not found: Can't resolve 'dayjs'` Then I install `npm i dayjs`, and I could fix it. So with this bug, you could fix like this:
> 
> 1. Wrap in LocalizationProvider like Alex said
> 
> ```
>         <LocalizationProvider dateAdapter={AdapterDayjs}>
>           <DemoContainer components={["DatePicker"]}>
>             <DatePicker label="Basic date picker" />
>           </DemoContainer>
>         </LocalizationProvider>
> ```
> 
> 2. Try `npm i dayjs`

AdapterDayjs is needed if you're going to use DateTimePicker and AdapterDatFns for DatePicker component. "dayjs" is a dependency for AdapterDayJs. Use the date in this format on value arrtibute like

For DateTimePicker it'll be like this
```
        <LocalizationProvider dateAdapter={AdapterDayjs}>
            <DateTimePicker label="Basic date time picker" value={dayjs(yourdate)} />
        </LocalizationProvider>
```
        
For DatePicker it'll be like this
Import all Adapter from "@mui/x-date-pickers"
```
        <LocalizationProvider dateAdapter={AdapterDateFns}>
            <DatePicker label="Basic date time picker" value={yourDate} />
        </LocalizationProvider>
```
yourDate should be in format of javascript date new Date().

**Comment by LukasTy** [comment] 2024-02-29 13:34
Guys, all of it is documented in the [getting started page](https://mui.com/x/react-date-pickers/getting-started/).
All the relevant imports and dependencies (to install - depending on your setup) are listed there. 👌
