### ISSUE TITLE
Building `@mui/x-data-grid` breaks due to deprecated `csstype.Property.ColorAdjust`

### ISSUE THREAD

**Issue by victor-grajski** [mui/mui-x#4128] opened 2022-03-08 18:03 UTC
Related to this [issue](https://github.com/mui/material-ui/issues/31296) that was patched in `@mui/base`, type checking on `@mui/x-data-grid` 5.6.0 fails:

```
node_modules/@mui/x-data-grid/hooks/features/virtualization/useGridVirtualScroller.d.ts:117:54 - error TS2694: Namespace '"node_modules/@mui/material/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.

117             colorAdjust?: import("csstype").Property.ColorAdjust | undefined;
                                                         ~~~~~~~~~~~

node_modules/@mui/x-data-grid/hooks/features/virtualization/useGridVirtualScroller.d.ts:625:65 - error TS2694: Namespace '"node_modules/@mui/material/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.

625             WebkitPrintColorAdjust?: import("csstype").Property.ColorAdjust | undefined;
```

**Comment by flaviendelangle** [comment] 2022-03-09 10:44
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.

If updating the core packages solves the problem, then I just merged https://github.com/mui/mui-x/pull/4095 :+1:

**Comment by victor-grajski** [comment] 2022-03-09 16:29
Thank you for the quick response! I imagine updating the core packages will fix the issue in DataGrid since that was the fix in `@mui/base`. Those updated core packages will be included in the next release of `@mui/x-data-grid`, correct?

**Comment by flaviendelangle** [comment] 2022-03-09 17:22
Exactly yes

**Comment by flaviendelangle** [comment] 2022-03-11 13:39
@victor-grajski did the version `5.6.1` of our x packages solves your problem ?

**Comment by victor-grajski** [comment] 2022-03-11 17:35
No I originally saw the issue on `5.6.1`

**Comment by flaviendelangle** [comment] 2022-03-14 08:44
@victor-grajski it was `5.6.0` most likely
`5.6.0` has been released 2 days after you created this issue, see [the release notes](https://github.com/mui/mui-x/releases/tag/v5.6.1)

**Comment by sheuertz** [comment] 2022-03-14 16:30
I'm still seeing this issue with 5.6.1.

**Comment by victor-grajski** [comment] 2022-03-14 21:35
Same here

**Comment by victor-grajski** [comment] 2022-03-14 21:39
> I'm still seeing this issue with 5.6.1.

I thought I was as well and then I realized the error was coming from `@mui/x-data-grid-pro`! Upgrading that to `5.6.1` solved it. Hope that works for you too!

**Comment by sheuertz** [comment] 2022-03-14 22:26
I was able to find the issue, was caused by a bad transitive dependency on old csstype. This is working. Thanks!

**Comment by flaviendelangle** [comment] 2022-03-15 07:51
Great ! I am closing this one

**Comment by jonathan-rws** [comment] 2022-03-25 23:45
I have same problem

**Comment by flaviendelangle** [comment] 2022-03-28 06:59
Which version are you running for each of our libraries ? (run `npx @mui/envinfo` to have them)

**Comment by Neuromancer93** [comment] 2022-05-02 20:20
I am still having this issue on `"@mui/x-data-grid-pro": "^5.10.0",`

**Comment by flaviendelangle** [comment] 2022-05-03 07:06
If someone can provide a reproduction case I will take a look

**Comment by cherniavskii** [comment] 2023-07-04 15:03
Please provide a reproduction example for this issue

**Closed** 2023-07-11 15:23 UTC
Labels: component: data grid, status: needs more information
