### ISSUE TITLE
Datagrid Horizontal Scrollbar appears on screen resizing

### ISSUE THREAD

**Issue by ronaklalwaniii** [mui/mui-x#4931] opened 2022-05-19 06:48 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Scrollbar appears on resizing the screen. 

When I change from tablet portrait mode to landscape mode scrollbar appears.

I guess flex property is causing this.

Here's my code:
![image](https://user-images.githubusercontent.com/44769573/169218310-1e9a6c7a-2dd2-454a-a2b4-f5856de052ed.png)

Result:
![image](https://user-images.githubusercontent.com/44769573/169218018-e11bd26d-22ce-48b6-8f3c-1fd0c58b92c4.png)

### Expected behavior 🤔

There shouldn't be a scrollbar while changing/resizing screens.

### Steps to reproduce 🕹

Steps:

1. Create custom columns with flex property.
2. Resize the window or change screen size.

### Context 🔦

I was just testing my table and the scrollbar appeared on changing/resizing screen.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
```
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1.0), Chromium (101.0.1210.47)
  npmPackages:
    @emotion/react: ^11.7.0 => 11.9.0 
    @emotion/styled: ^11.6.0 => 11.8.1 
    @mui/base:  5.0.0-alpha.81 
    @mui/lab: ^5.0.0-alpha.80 => 5.0.0-alpha.82 
    @mui/material: ^5.6.4 => 5.8.0 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.0 
    @mui/types:  7.1.3
    @mui/utils:  5.8.0
    @mui/x-data-grid: 5.10.0 => 5.10.0
    @mui/x-date-pickers:  5.0.0-alpha.0
    @types/react: ^18.0.8 => 18.0.9
    react: ^18.1.0 => 18.1.0
    react-dom: ^18.1.0 => 18.1.0
    typescript: ^4.6.4 => 4.6.4
```
</details>

  I  am using the chrome browser

**Comment by m4theushw** [comment] 2022-05-23 12:38
It might be a duplicate of #4253

Does the workaround in https://github.com/mui/mui-x/issues/4253#issuecomment-1075788388 work for you?

**Comment by m4theushw** [comment] 2022-05-24 21:42
#4253 has the explanation of why you see the scrollbar: https://github.com/mui/mui-x/issues/4253#issuecomment-1075788388

If it's the same situation from the comment we can't do anything at this moment. The workaround with CSS is a way to force the scrollbar to be hidden. If you still want to display it on smaller screens (I suppose mobile), then you can use a media query and not apply `overflow: hidden` on some screens.

If it's not the same situation, could you provide a minimum reproduction? The screenshots don't show the scrollbar.

**Closed** 2022-06-03 18:29 UTC
Labels: bug 🐛, component: data grid, status: needs more information, feature: Rendering layout
