### ISSUE TITLE
[charts] slotProps error

### ISSUE THREAD

**Issue by jared-craig-cse** [mui/mui-x#10132] opened 2023-08-24 21:01 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Updated from x-charts alpha 6 to alpha 7.

### Current behavior 😯

I get a console error after updating to alpha 7:

> React does not recognize the `slotProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `slotprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

I am currently not using the slots or slotProps properties.

### Expected behavior 🤔

There shouldn't be a console error for the new feature.

### Context 🔦

I'm currently displaying a few line charts that were working with no errors on alpha 6. They continue to work but with the mentioned console error.

### Your environment 🌎

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 116.0.5845.98
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.203)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.12
    @mui/core-downloads-tracker:  5.14.6
    @mui/icons-material: ^5.14.3 => 5.14.3
    @mui/material: ^5.14.6 => 5.14.6
    @mui/private-theming:  5.14.6
    @mui/styled-engine:  5.14.6
    @mui/system:  5.14.6
    @mui/types:  7.2.4
    @mui/utils:  5.14.6
    @mui/x-charts: ^6.0.0-alpha.7 => 6.0.0-alpha.7
    @mui/x-data-grid:  6.11.2
    @mui/x-data-grid-pro: ^6.11.2 => 6.11.2
    @mui/x-date-pickers:  6.11.1
    @mui/x-date-pickers-pro: ^6.11.1 => 6.11.1
    @mui/x-license-pro:  6.10.2
    @types/react: ^18.0.21 => 18.2.17
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.9.5 => 4.9.5

**Comment by LukasTy** [comment] 2023-08-25 05:41
Thank you for reporting the issue and using the freshly baked charts package! 🙏 💯 
This seems to be a duplicate of #10072 and has already been resolved with https://github.com/mui/mui-x/pull/10105.
We ought to release a new package today. 😉

**Closed by LukasTy** 2023-08-25 05:41 UTC
Labels: status: needs triage
