### ISSUE TITLE
[pickers] TextField loose focus when we type the year in the field in case of customTextField through slots.

### ISSUE THREAD

**Issue by knnemade99** [mui/mui-x#9578] opened 2023-07-05 11:29 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Add CustomTextField through slots props.
2. Type in the year section
3. It will loose focus after first character typed.
Code Demo: https://codesandbox.io/s/nifty-cloud-ylwwqp?file=/demo.tsx
If we enable line 29 and comment 28 and type year field, it works.
If we enable line 28 and comment 29 and type in year field, ti will loose focus after first keypress.

Could you please help with some solution to it.

### Current behavior 😯

Looses focus after first keypress in year section

### Expected behavior 🤔

focus should remain when we type the entire year like 1994

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment] 2023-07-06 06:59
Is this a duplicate of #8850?

**Comment by flaviendelangle** [comment] 2023-07-06 09:26
I did not check #8850
But for this one, the problem is simple, you should never define a slot component inside another component. Those are components, not rendered function, so if you recreate one on each render, React will remount it and you will loose its internal state

[Updated codesandbox](https://codesandbox.io/s/nostalgic-leaf-dhwrcw)

**Closed** 2023-07-06 09:27 UTC
Labels: component: pickers

**Comment by knnemade99** [comment] 2023-07-08 05:11
> Looks lile a diplicate of #8850 indeed
> 
> The problem is simple, you should never define a slot component inside another component. Those are components, not rendered function, so if you recreate one on each render, React will remount it and you will loose its internal state
> 
> [Updated codesandbox](https://codesandbox.io/s/nostalgic-leaf-dhwrcw)

Thanks @flaviendelangle , it worked. :)
