### ISSUE TITLE
[pickers] AM/PM field is not disabled when validation fails for the minTime and maxTime properties.

### ISSUE THREAD

**Issue by A-s-h-o-k** [mui/mui-x#15410] opened 2024-11-14 03:26 UTC
### Steps to reproduce

Steps:
```tsx
import * as React from 'react';
import { DemoContainer } from '@mui/x-date-pickers/internals/demo';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { TimePicker } from '@mui/x-date-pickers/TimePicker';
import dayjs from 'dayjs'

export default function BasicTimePicker() {
  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DemoContainer components={['TimePicker']}>
        <TimePicker label="Basic time picker" minTime={dayjs().add(8, 'h')}/>
      </DemoContainer>
    </LocalizationProvider>
  );
}
```

<img width="1510" alt="snip timpicker issue" src="https://github.com/user-attachments/assets/5475dada-eeeb-45cd-8098-7743287dd1c4">

### Current behavior

When the AM/PM (12-hour format) option is selected in the time picker, the AM/PM field is not disabled, even if the minTime is set to a later time. This allows users to select 'AM,' even if that time has already passed, while the other fields are working properly.

### Expected behavior

When the AM/PM (12-hour format) is selected in the time picker, the AM/PM field should be disabled.

### Context

this issue occurs when you pass the ampm prop true to the timepicker

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: timepicker

**Comment by michelengelen** [comment] 2024-11-14 14:28
Thanks for opening an issue for this @A-s-h-o-k ... I could not find a quick solution for this so I will add it to the board for the team to estimate. 👍🏼

**Comment by LukasTy** [comment] 2024-11-15 09:25
This issue looks like an already estimated duplicate of https://github.com/mui/mui-x/issues/12159.
Closing this one as duplicate in favor of the mentioned issue. 😉

**Closed by LukasTy** 2024-11-15 09:25 UTC
Labels: bug 🐛, component: pickers
