### ISSUE TITLE
Column order resets after new rendering

### ISSUE THREAD

**Issue by Mexanik2003** [mui/mui-x#5812] opened 2022-08-16 16:41 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When column order set by initialState prop, it works only at the first render. Next renders reset column order to default (as in columns prop).

### Expected behavior 🤔

Column order corresponds to initialState prop in every render.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/basiccolumnsgrid-demo-mui-x-forked-h0w3wf?file=/demo.tsx

Steps:
1. Open the example and wait for the first render. Everything will be ok (column order is as set in InitialState
2. Change the string in console.log command (it triggers new render)
3. Column order will be reseted to default

console.log command is just for example, this behavior can be demonstrated with another actions (polling, pressing buttons, etc.)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

37162

**Comment by alexfauquette** [comment] 2022-08-17 11:10
This issue sounds to be a duplicate of #5418. I'm closing it to avoid duplicated content.

If there is a difference I missed, feel free to reopen it

**Closed by alexfauquette** 2022-08-17 11:10 UTC
Labels: status: needs triage

**Comment by cherniavskii** [comment] 2022-08-19 11:13
Hey @Mexanik2003 
I've created this demo to use state to trigger rerender: https://codesandbox.io/s/basiccolumnsgrid-demo-mui-x-forked-gkpvy4?file=/demo.tsx

But the behavior you see there is expected.
Note, that the `columns` reference is not memoized, which triggers column order change on subsequent render.
We warn about this in our docs https://mui.com/x/react-data-grid/column-definition/
<img width="849" alt="Screenshot 2022-08-19 at 13 10 50" src="https://user-images.githubusercontent.com/13808724/185606326-3e9fdd87-68bf-44b1-8cba-f9f6c6edb629.png">

Once `columns` is memoized, the columns order is persisted, see this demo:
https://codesandbox.io/s/basiccolumnsgrid-demo-mui-x-forked-nstbu4?file=/demo.tsx
