### ISSUE TITLE
[datagrid] Autosize Columns - Headers being cut off

### ISSUE THREAD

**Issue by DevPowers** [mui/mui-x#10570] opened 2023-10-04 00:05 UTC
### Steps to reproduce

Link to live example: [(MUI Docs Example)](https://mui.com/x/react-data-grid/column-dimensions/#system-ColumnAutosizing.js)

Steps:
1. Using autosize options:

```
    autosizeOnMount={true},
    autosizeOptions: { includeOutliers: true, includeHeaders: true }
```
2. On a mobile device or using dev tools mobile screen size - see the column header being cut off:

<img width="317" alt="Screenshot 2023-10-03 at 8 03 21 PM" src="https://github.com/mui/mui-x/assets/17171875/31f3b9b2-0d02-4e05-8890-f7e502ea0227">

### Current behavior

The column headers are unreadable on mobile using autosizing

### Expected behavior

For the column headers to be readable

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.1
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.94
    Edge: Not Found
    Safari: 17.1
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.38 
    @mui/core-downloads-tracker:  5.15.12 
    @mui/icons-material: ^5.15.12 => 5.15.12 
    @mui/lab: 5.0.0-alpha.167 => 5.0.0-alpha.167 
    @mui/material: ^5.15.12 => 5.15.12 
    @mui/private-theming:  5.15.12 
    @mui/styled-engine:  5.15.11 
    @mui/styles: ^5.15.12 => 5.15.12 
    @mui/system: ^5.15.12 => 5.15.12 
    @mui/types:  7.2.13 
    @mui/utils: ^5.15.12 => 5.15.12 
    @mui/x-data-grid:  7.0.0-beta.5 
    @mui/x-data-grid-premium: 7.0.0-beta.5 => 7.0.0-beta.5 
    @mui/x-data-grid-pro:  7.0.0-beta.5 
    @mui/x-license:  7.0.0-beta.2 
    @mui/x-license-pro: 7.0.0-beta.0 => 7.0.0-beta.0 
    @types/react: ^18.2.63 => 18.2.63 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.3.3 => 5.3.3 
```
</details>

**Search keywords**: datagrid column autosizing
**Order ID**: 56883

**Comment by DanailH** [comment] 2023-10-05 10:57
I was able to reproduce it but for me, the first column is the one that breaks.

**Comment by romgrk** [comment] 2023-10-05 22:42
Mobile has always-visible 3-dots menus. We'll need to add space to the headers to account for that.

**Comment by gitstart** [comment] 2023-10-06 18:14
@DevPowers @zannager @DanailH we would like to pick this up

**Comment by DanailH** [comment] 2023-10-07 10:34
@gitstart ok, we are happy for you to try it out, but because this bug is related to a Premium feature we would need you to sign a CLA before we are able to merge it. Once you open the PR we can send you the standard agreement.
You can check more about it here: https://mui-org.notion.site/CLA-Contributor-License-Agreement-92ece655b1584b10b00e4de9e67eedb0
and here: https://drive.google.com/file/d/1muE5-mtJus_kwkSwn-d7biHsMTqQetd6/view

**Comment by gitstart** [comment] 2023-10-09 09:44
> @gitstart ok, we are happy for you to try it out, but because this bug is related to a Premium feature we would need you to sign a CLA before we are able to merge it. Once you open the PR we can send you the standard agreement. You can check more about it here: https://mui-org.notion.site/CLA-Contributor-License-Agreement-92ece655b1584b10b00e4de9e67eedb0 and here: https://drive.google.com/file/d/1muE5-mtJus_kwkSwn-d7biHsMTqQetd6/view

Thanks for the response @DanailH, we are fine with signing the CLA agreement.

**Comment by mauro-ni** [comment] 2023-10-09 14:46
Please do also consider sorted columns: extra space for the sort direction arrow icon has to be added.

**Comment by DevPowers** [comment] 2023-10-31 14:20
@gitstart Are you able to get eyes on the PR again ?? This is a priority fix I need for this feature to be production ready 🙏

**Comment by gitstart** [comment] 2023-11-01 09:04
> @gitstart Are you able to get eyes on the PR again ?? This is a priority fix I need for this feature to be production ready 🙏

@DevPowers We are sorry for the delay 🙏. The PR has been updated.

**Comment by DevPowers** [comment] 2024-01-14 18:26
@zannager @DanailH  Is this really fixed and tested? The docs on MUI website are still not responsive when I test it in dev console ?

**Comment by DevPowers** [comment] 2024-02-10 18:02
Is anybody able to pick this up? I see numerous other bugs opened against this new autosize feature, is it possible to make this a priority on fixing all the autosize bugs in upcoming new v7 release?

**Comment by romgrk** [comment] 2024-02-10 20:22
Autosizing has been reworked in the v7 branch, it seems to work fine there: https://next.mui.com/x/react-data-grid/column-dimensions

Is it possible for you to use v7?

**Comment by DevPowers** [comment] 2024-02-10 20:28
@romgrk Hi! Testing autosize for mobile with the page URL you sent looks to be working. I will close this ticket then, I can switch to V7 thanks!

**Comment by DevPowers** [comment] 2024-02-11 19:35
@romgrk Hi, I just completed V7 migration. Unfortunately autosize is still buggy.  

- [Laptop view] - Pinned column on the left does not autosize and fit the column data 
- [ Mobile view] - Same issue as laptop view, but also column header labels are not fitting

**Comment by romgrk** [comment] 2024-02-12 09:42
Let's test again once #12013 is merged.

**Comment by DevPowers** [comment] 2024-03-02 17:47
@romgrk Retested and still completely broken on mobile and desktop

**Comment by romgrk** [comment] 2024-03-05 20:10
Can you provide a clear reproduction case? I have tried modifying the docs example you link above to pin left one of the columns, and add the autosize options you list. The video below shows the result I observe. I get the same results in mobile emulation mode, let me know if you tested on a real mobile device.

You also haven't filled the environment section in your report. It's important because it also tells us which OS and browser versions you're using, which are important to reproduce a bug.

[Kooha-2024-03-05-15-06-38.webm](https://github.com/mui/mui-x/assets/1423607/5db73f98-3b9e-4a0e-9030-d2a6050d6c34)

**Closed** 2024-03-12 20:11 UTC
Labels: bug 🐛, component: data grid, status: waiting for author, plan: Premium
