### ISSUE TITLE
[DateRangePicker] Problem when typing on desktop

### ISSUE THREAD

**Issue by MarcioVb** [mui/mui-x#4541] opened 2022-02-28 17:59 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi guys!

I'm encountering problems after migrating to version 5. In the current version, when desktop, typing and pressing tab to confirm the date is cleared, while in the previous version it worked fine. Selecting from calendars works fine.

Any idea how to get around the problem?

Thanks a lot!

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment] 2022-04-18 17:34
I can reproduce the issue here https://mui.com/x/react-date-pickers/date-range-picker/#basic-usage

https://user-images.githubusercontent.com/13808724/163848695-749112ed-3308-4a3b-8d63-9359c4ec5912.mov

**Comment by MarcioVb** [comment] 2022-04-18 20:13
Hi! This is the problem. Thanks!

**Comment by alexfauquette** [comment] 2022-04-21 10:34
What appends is the following. The wrapper calls `onDismiss` when blurred and so set values back to their initial state.

https://github.com/mui/mui-x/blob/f0df5c5f3d16e2df8a27848f1a8a322a4fb97f1e/packages/x-date-pickers/src/internals/hooks/usePickerState.ts#L119

It's indirectly linked to PR #4408. For example with this PR if I add `disableCloseOnSelect` to the dateRange Picker it will work because the `onDismiss` will set the last committed value instead of the value before starting editing the component

https://codesandbox.io/s/basicdaterangepicker-material-demo-forked-oyudim?file=/demo.tsx

**Comment by flaviendelangle** [comment] 2022-04-21 10:37
Every issue in the world is linked to #4408 :laughing: 

Would we still have the bug with https://github.com/mui/mui-x/pull/4408#issuecomment-1104832909 ?

**Comment by alexfauquette** [comment] 2022-04-21 10:44
If instead of resetting to the initial value, closing the view keep the value, the problem should be solved

**Closed** 2022-04-29 12:15 UTC
Labels: bug 🐛, plan: Pro, component: pickers, component: date range picker
