### ISSUE TITLE
[DataGrid] Add other sub-states to the `initialState` prop 

### ISSUE THREAD

**Issue by cq-ubaid-khan** [mui/mui-x#3448] opened 2021-12-10 13:59 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently the datagrid only support few properties as initial state one example `pinnedColumns`, We want it to receive `columnsOrders`, `columnsSizes`, `pagination`, `columnVisibility` as an initial state of grid.

Support for this configuration will be useful where we save all of the datagrid settings in persistent location and later when visited on the same page we get the same settings applied on the grid automatically.

Currently in order to achieve this behavior we have to interact with the `apiRef`.

Thanks.

### Examples 🌈

```
const savedInitialState = {
   columnsSizes: { fieldName: { width: 30 }, otherField: { width: 50 } },
   columnsOrders: { fieldName: { orderIndex: 4 } },
   pagination: { size: 20, ... },
   columnsVisibility: { fieldName: { visible: false } },
   ...
}

<DataGrid 
   initialState={savedInitialState}
   ...
/>

```

**Comment by alexfauquette** [comment] 2021-12-17 12:19
It sounds like it is a duplicate of #820

**Comment by flaviendelangle** [comment] 2021-12-22 12:59
#820 is mainly about the new methods to imperatively store and restore the state.
But we can keep this one to discuss which state keys should be added to the `initialState` (most of the time I think those should also be added to the store / restore methods).

@cq-ubaid-khan as you saw we started small with some sub-states we knew were needed. The idea being to avoid adding to much complexity right from the start.

The `pagination` (`pageSize` and `page`) could very easily be added and for me it totally make sense.
For the columns related data it is slightly more complicated and I think we should do it in a second run. You can pre-process your column objects to provide custom initial order / sizes / visibility but we will have to think of a clean implementation on our side.

**Comment by cq-ubaid-khan** [comment] 2021-12-23 08:55
Hmm. Thanks for you response, I understand your thoughts about the complexity as I've gone through the same kind problem in the past.

However, I've implemented the solution from my own way by implementing a middle state mapping object which I can easily persist and reuse.

Pasting here so anyone in the future can get some help from this.

 ```
const layout = {
  layoutSettings: {
    field1: {
        orderIndex: 1,
        hidden: true,
        locked: false,
        ....
     }
    field2: ....,
    ....
  }
}

const layoutSettingFields = Object.keys(layout.layoutSettings);
if (layoutSettingFields.length) {
  layoutSettingFields.forEach((field) => {
    dtApi.setColumnIndex(field, layout.layoutSettings[field].orderIndex);
    dtApi.setColumnVisibility(field, !layout.layoutSettings[field].hidden);
    if (layout.layoutSettings[field].locked) dtApi.pinColumn(field, DataTablePinnedPosition.left);
    else dtApi.unpinColumn(field);
  });
}
```

**Comment by tielushko** [comment] 2022-02-09 16:10
@flaviendelangle, do you happen to know if there is a plan to work on additional states features, such as width and order? Is it something that serves as the priority for the team?

**Comment by flaviendelangle** [comment] 2022-02-09 16:26
It's under progress, see #3816
But the exact API is being discussed in the team so it will probably take a few weeks before the release.

**Comment by tielushko** [comment] 2022-02-10 14:14
Thanks for linking that PR, @flaviendelangle! I will keep an eye on it, looking forward to seeing updates regarding it!

**Closed** 2022-03-14 09:38 UTC
Labels: component: data grid, enhancement
