### ISSUE TITLE
[data grid] bug using firefox

### ISSUE THREAD

**Issue by kanzaki337** [mui/mui-x#15936] opened 2024-12-19 07:34 UTC
### Steps to reproduce

**1. Create a DataGridPro with the following setup:**

```
const configDataGrid: GridColDef[] = [
  { field: 'first_ip', headerName: 'First Ip', flex: 1 },
];

const App = () => (
  <DataGrid
    rows={[]} // Empty array
    columns={configDataGrid}
  />
);

```

**2. Run the application in Firefox.
3. Observe the error in the console.**

### Current behavior

When using DataGrid with a column configuration that includes flex: 1 and an empty rows array (rows={[]}), Firefox throws the following error:

> **Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.**

### Expected behavior

The DataGridPro should gracefully handle empty rows with flex-based column widths without throwing errors, regardless of the browser.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: mui, x-data-grid

**Order ID**: aass

**Comment by michelengelen** [comment] 2024-12-19 13:12
Which version of the data grid are you using?
there was a bug we fixed and released in `7.23.2` ... for reference: #15721

**Comment by kanzaki337** [comment] 2024-12-19 17:40
> Which version of the data grid are you using? there was a bug we fixed and released in `7.23.2` ... for reference: #15721

I am using `7.23.0` data grid,,
Ok fine, I'll try to upgrade to the latest version, thank you in advance..

**Comment by cherniavskii** [comment] 2024-12-19 18:38
I can't reproduce it in Firefox or Chrome with this demo: https://codesandbox.io/p/sandbox/mystifying-archimedes-75vlqw
@kanzaki337 Can you?

**Comment by kanzaki337** [comment] 2024-12-19 20:12
> I can't reproduce it in Firefox or Chrome with this demo: https://codesandbox.io/p/sandbox/mystifying-archimedes-75vlqw @kanzaki337 Can you?

Now the problem is clear, I think after I upgraded to version 7.23.3 there was still a cache that caused the problem not to be clear..
thanks a lot for your help..

**Comment by michelengelen** [comment] 2024-12-20 07:09
All right ... I'll close the issue since the problem seems to be resolved! Thanks @cherniavskii !

**Closed by michelengelen** 2024-12-20 07:09 UTC
Labels: bug 🐛, component: data grid, status: waiting for maintainer
