### ISSUE TITLE
[data grid] Apostrophe added to numbers on export

### ISSUE THREAD

**Issue by dorpe** [mui/mui-x#13790] opened 2024-07-10 09:03 UTC
### Steps to reproduce

Steps:
1. Export a table to CSV

### Current behavior

When exporting to CSV, an apostrophe appears before any negative number in Excel. For example, -20 shows up as '-20. This issue occurs only for numbers with fewer than five digits.

### Expected behavior

When exporting to CSV, the number should be exactly like the number in the frontend table.

### Context

Export a table to CSV.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Apostrophe adds when export
**Order ID**: 90144

**Comment by arminmeh** [comment] 2024-07-10 13:38
Hello @dorpe 

Thanks for reporting the issue.
Can you check the [support page](https://mui.com/x/introduction/support) and provide a link to the sandbox with the issue you are mentioning?

**Comment by dorpe** [comment] 2024-07-11 08:33
Hey @arminmeh 
Our product is protected behind MFA, so we created this snippet. Just press on "EXPORT," and you can see that some negative numbers are exported with an apostrophe before the number (especially zeros and negative numbers up to 6 digits). For example, see rows 9, 25, and 26.

Link: 
https://stackblitz.com/edit/react-rmcqtb?file=Demo.js

**Comment by DanailH** [comment] 2024-07-11 11:01
This is weird. I can confirm that it also happens in Preview on Mac. It does look like a bug on our end.

**Comment by dorpe** [comment] 2024-07-16 09:19
Hey, team, any estimation of when it will be fixed?

**Comment by AviDuda** [comment] 2024-07-16 17:23
This was introduced in #13115. Wouldn't always quoting the value instead of doing [this check](https://github.com/mui/mui-x/blob/45facf87e7b86072c26ce8ffd71b26d256bc3c24/packages/x-data-grid/src/hooks/features/export/serializers/csvSerializer.ts#L19-L21) be better, as negative values and also values starting with e.g. `@` are a completely normal thing?

**Comment by jonnylink** [comment] 2024-07-17 14:53
License holder here asking the same. This bug has generated helpdesk issues for our team (so it's a production bug).

**Comment by arminmeh** [comment] 2024-07-18 13:23
hey @dorpe 
I see that in your example you are setting `escapeFormulas` to `false` to disable escaping.
Thing is that this should be added to the `slotProps` rather to `slots` to be picked up by the toolbar.

So, instead of
```
slots={{
  toolbar: {
    ...GridToolbar,
    csvOptions: {
      escapeFormulas: false,
    },
  },
}}
```
have
```
slots={{
  toolbar: GridToolbar,
}}
slotProps={{
  toolbar: {
    csvOptions: {
      escapeFormulas: false,
    },
  },
}}
```

After that, exports should be generated as you expect.

If the expectation is that the exception should be made in processing of the negative numbers even when `escapeFormulas` is `true` I can keep the issue open, but then it will be treated as an improvement rather than a bug since the way it is working now is described [here](https://owasp.org/www-community/attacks/CSV_Injection)

**Comment by dorpe** [comment] 2024-07-18 13:28
Thank you, everyone. The issue has been resolved.

**Comment by arminmeh** [comment] 2024-07-18 13:37
Thanks for the fast response.
I will close this issue then.

If the change that I have posted does not work out for other people that have facing the same issue, feel free to re-open the issue with the additional info.

**Closed by arminmeh** 2024-07-18 13:37 UTC
Labels: bug 🐛, component: data grid, status: waiting for maintainer, feature: Export, support: premium standard

**Comment by arminmeh** [comment] 2024-07-18 13:49
@jonnylink 
change happened because escaping was introduced and has been turned on by default (check the [PR comment](https://github.com/mui/mui-x/pull/13115#discussion_r1603813917))
@cherniavskii we have probably missed to announce it better here
https://github.com/mui/mui-x/releases/tag/v7.5.1

**Comment by jonnylink** [comment] 2024-07-18 13:58
Got it! Thank you for the clarification.
