### ISSUE TITLE
Module not found: Package path ./_lib/format/longFormatters is not exported from package date-fns in version v6.18.6

### ISSUE THREAD

**Issue by ngoquoctoandev** [mui/mui-x#11517] opened 2023-12-26 02:02 UTC
### Steps to reproduce

yarn dev
>>
yarn run v1.22.21
$ next dev -p 8082
   ▲ Next.js 14.0.4
   - Local:        http://localhost:8082
   - Environments: .env

 ✓ Ready in 7.4s
 ○ Compiling / ...
 ⨯ ./node_modules/@mui/x-date-pickers/AdapterDateFns/AdapterDateFns.js:59:0
Module not found: Package path ./_lib/format/longFormatters is not exported from package D:\Dev\Projects\Javascript\next-ts\node_modules\date-fns (see exports field in D:\Dev\Projects\Javascript\next-ts\node_modules\date-fns\package.json)

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@mui/x-date-pickers/AdapterDateFns/index.js
./src/locales/localization-provider.tsx
 ⨯ ./node_modules/@mui/x-date-pickers/AdapterDateFns/AdapterDateFns.js:59:0
Module not found: Package path ./_lib/format/longFormatters is not exported from package D:\Dev\Projects\Javascript\next-ts\node_modules\date-fns (see exports field in D:\Dev\Projects\Javascript\next-ts\node_modules\date-fns\package.json)

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@mui/x-date-pickers/AdapterDateFns/index.js
./src/locales/localization-provider.tsx
 ⨯ ./node_modules/@mui/x-date-pickers/AdapterDateFns/AdapterDateFns.js:59:0
Module not found: Package path ./_lib/format/longFormatters is not exported from package D:\Dev\Projects\Javascript\next-ts\node_modules\date-fns (see exports field in D:\Dev\Projects\Javascript\next-ts\node_modules\date-fns\package.json)

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@mui/x-date-pickers/AdapterDateFns/index.js
./src/locales/localization-provider.tsx

**Search keywords**: @mui/x-date-pickers

**Comment by LukasTy** [comment] 2023-12-27 07:59
Closing as this is a duplicate of https://github.com/mui/mui-x/issues/11454

**Closed by LukasTy** 2023-12-27 07:59 UTC
Labels: status: waiting for maintainer, component: pickers
