### ISSUE TITLE
Grid loading overlay is rendered behind the contents

### ISSUE THREAD

**Issue by mjomble** [mui/mui-x#5538] opened 2022-07-19 12:08 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If I render a grid with both rows and `loading: true`, the overlay is rendered behind the cell contents, row borders/dividers, etc:

![image](https://user-images.githubusercontent.com/2202751/179745641-51be5ca3-0066-44dc-b15b-a166e9a59cd0.png)

### Expected behavior 🤔

The overlay should be rendered in front of the contents, like this:

![image](https://user-images.githubusercontent.com/2202751/179746033-c62ae5c5-ff47-4b06-9241-41276662af69.png)

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/infiniteloadinggrid-demo-mui-x-forked-v882y1

### Your environment 🌎

I was able to reproduce the issue at the given live example link with Chrome 103 on Windows 10

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment] 2022-07-20 10:20
Hi, @mjomble thanks for raising this. It seems to be a duplicate of #3650. Ultimately the reason seems to be the place where the overlay is being rendered.
I'll close this issue. You can track the progress of this in the other linked issue.

**Closed** 2022-07-20 10:20 UTC
Labels: bug 🐛, duplicate, component: data grid

**Comment by cherniavskii** [comment] 2022-07-20 14:16
@DanailH I think it's a valid issue.
I've noticed before that loading overlay is rendered behind the rows, but as soon as I tried to set zIndex and render it in front of the rows I realised that scrolling doesn't work when the loading overlay is visible. So I didn't proceed with this change.

But on the second thought, we can fix that with `pointer-events: none`:

```diff
diff --git a/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx b/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
index ce3a618e5..3233becdd 100644
--- a/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
+++ b/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
@@ -44,6 +44,8 @@ function GridOverlayWrapper(props: React.PropsWithChildren<{}>) {
         position: 'absolute',
         top: headerHeight,
         bottom: height === 'auto' ? 0 : undefined,
+        zIndex: 3, // should be above pinned columns and detail panel
+        pointerEvents: 'none',
       }}
       {...props}
     />
```

**Comment by cherniavskii** [comment] 2022-07-20 14:20
Note, that it does not look like a duplicate of #3650, since this issue is only about zIndex, while #3650 is about whether rows should be rendered when `loading={true}`

**Comment by DanailH** [comment] 2022-07-20 14:24
It seems to me that It's related to how the overlat is being rendered. The z-index fix works because it brings the overlay in front but because it is transparent you can see what is behind it. Maybe I misread #3650 then.

**Comment by cherniavskii** [comment] 2022-07-20 14:37
Ok, on a second thought I think it was me who misread #3650
I'll leave a comment there.

**Comment by DanailH** [comment] 2022-07-21 10:14
@cherniavskii I've opened a PR with the proposed change.

**Comment by MetaMmodern** [comment] 2023-01-11 09:23
@DanailH can you link PR here? And why both mentioned issues are closed? The issue still persists (at least in DataGridPro component). I think it'd be better to reopen this one.

**Comment by MetaMmodern** [comment] 2023-01-11 13:13
@cherniavskii how about this one? https://codesandbox.io/s/grid-loading-overlay-bug-mui-x-forked-zj35yc?file=/demo.tsx

I'm trying to use linear loading instead of standard circular using `components` prop. And if the cell background is not transparent the progress bar is not visible behind that cell.

Am I doing this wrong? Is there another way to have linear progress?

**Comment by cherniavskii** [comment] 2023-01-11 13:44
@MetaMmodern yes, it doesn't work with custom overlay out-of-the-box.
You can fix it with:
```tsx
componentsProps={{
  loadingOverlay: {
    style: { zIndex: 4 }
  }
}}
```
See the demo: https://codesandbox.io/s/grid-loading-overlay-bug-mui-x-forked-pn9bom?file=/demo.tsx:710-812

The grid overlays layout has been reworked in v6 (https://github.com/mui/mui-x/pull/5808)
No workaround is needed for this to work in v6 - see this demo https://codesandbox.io/s/grid-loading-overlay-bug-mui-x-forked-590jlk?file=/demo.tsx

**Comment by MetaMmodern** [comment] 2023-01-11 14:02
@cherniavskii amazing, thanks a lot!
