### ISSUE TITLE
[DataGridPro]: Clicking inside checkbox for rowSelection fires onRowClick

### ISSUE THREAD

**Issue by pkuzhel** [mui/mui-x#3897] opened 2022-02-09 03:25 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In Data Grid Pro >v5.3, a click on selection checkbox (which appears with `checkboxSelection`) now also fires `onRowClick`

This seems like a regression. Couldn't find anything in docs or changelog around this change

### Expected behavior 🤔

In Data Grid Pro <v5.3 with option `checkboxSelection`, clicking on checkbox, would only select the row, but not fire the `onRowClick`

I don't expect `onRowClick` to fire on `rowSelection` (using the dedicated checkbox)

### Steps to reproduce 🕹

Example for v5.3 [expected behaviour]: https://codesandbox.io/s/disableclickselectiongrid-material-demo-forked-4fj2j?file=/demo.js

Click on checkbox and observe console.log (nothing should happen)

Example for v5.5 [latest]: https://codesandbox.io/s/disableclickselectiongrid-material-demo-forked-3w6jo?file=/package.json
Click on checkbox and see the onRowClick executing in console

### Context 🔦

We have a data-grid-pro license and this introduced a bug into site.
We have to pin the version to 5.3.0 for now until this is fixed.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>
This bug is reproducible in Chrome/Firefox Windows/Mac OS X

### Order ID 💳 (optional)

#31725

**Comment by cherniavskii** [comment] 2022-02-09 09:05
Duplicate of #3805
You may find https://github.com/mui/mui-x/issues/3805#issuecomment-1026999591 useful.
Does it solve your issue?

**Comment by pkuzhel** [comment] 2022-02-09 15:50
Yep, the workaround works.

I am concerned that if `__check__` was ever to change, it would cause another breaking change for our application.

It seems like both options would be useful.

Would it be possible to add an option (similar to `disableSelectionOnClick` to call `event.stopPropogation`)?

Another options would be to add rigid definition of the type of click?
Similar to how the `onClose` of modal works with the `reason`
https://mui.com/api/modal/#main-content

But for now, thanks for solving my immediate issue.

**Comment by m4theushw** [comment] 2022-02-09 19:03
It seems that the change we did to fix the focus caused problems. I propose that we use `cellClick` for the selection and only fire `rowClick` when the target is not the checkbox column or any other column that contains interactive elements (row grouping columns, actions column and master/detail toggle column).

https://github.com/mui/mui-x/blob/23cf2fe41a2141c42c6258daec28e73df3b78aee/packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts#L441

**Closed** 2022-03-03 13:06 UTC
Labels: duplicate, component: data grid
