### ISSUE TITLE
Page Broke in React Bar Chart.

### ISSUE THREAD

**Issue by Vansh1190** [mui/mui-x#13793] opened 2024-07-10 10:44 UTC
### Steps to reproduce

Link to component: https://mui.com/x/react-charts/bars/#layout

when I click on Expand code under this Bar Chart the page brokes.
and this message appears in console
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Page Broke in React Bar Chart

**Comment by JCQuintas** [comment] 2024-07-10 11:41
Oh, that is new. Thanks for reporting @Vansh1190

**Comment by JCQuintas** [comment] 2024-07-10 11:45
@alexfauquette it seems related to the "tab data" feature. 

Maybe an out-of-sync version between ours and core? 

It is working properly locally.

**Comment by LukasTy** [comment] 2024-07-10 11:53
@JCQuintas this looks like a duplicate of https://github.com/mui/mui-x/issues/13773. 😉

**Comment by JCQuintas** [comment] 2024-07-10 11:55
Oops, didn't see that. I'll close this then 😅

**Closed by JCQuintas** 2024-07-10 11:55 UTC
Labels: bug 🐛, docs, component: charts
