### ISSUE TITLE
[question] latest lighthouse is complaining about mui pro data grid toolbar 

### ISSUE THREAD

**Issue by Nonetail** [mui/mui-x#9506] opened 2023-06-28 04:27 UTC
### Order ID or Support key 💳 (optional)

e18419d244547c196f9d2ac52b709eebTz02ODc3MixFPTE3MTg0ODc4NDQwMjQsUz1wcm8sTE09c3Vic2NyaXB0aW9uLEtWPTI=

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

<img width="1179" alt="image" src="https://github.com/mui/mui-x/assets/42922659/f41b2590-3762-49dd-bab8-0c64e8d7aba7">
latest lighthouse is complaining about mui pro data grid toolbar, haven't seen these errors previously, not sure if due to the a11y guidelines updates, wondering if you have a plan of fixing it

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by romgrk** [comment] 2023-06-28 05:09
Duplicate of #9307

**Closed by romgrk** 2023-06-28 05:09 UTC
Labels: duplicate, support: commercial
