### ISSUE TITLE
[question] How to swap row in data grid

### ISSUE THREAD

**Issue by Arata-Yoshida** [mui/mui-x#13784] opened 2024-07-10 01:12 UTC
### The problem in depth

We are now making table that can be able to swap row by drag and drop.
Now, we can be able to swap row that shows in the display but, cannot swap row outside this display window.

For example, it is possible to swap row No.3 and 4 in following table. But we cannot swap row No.6 and  row under no.9 because scroll bar will not go down under row 8.

**Could you help us how to solve this problem?**

![image](https://github.com/mui/mui-x/assets/167494248/f12f6d15-7a23-4bc9-89d3-8ce01fa3724a)

### Your environment

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/PN79129/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/PN79129/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

OS | Linux(Debian10)
-- | --
development   language | Next.js(TypeScript)
x-data-grid-pro   Version | 7.2.0

</body>

</html>

**Search keywords**: data grid
**Order ID**: 86901

**Comment by arminmeh** [comment] 2024-07-10 08:54
Hi @Arata-Yoshida 
It looks like that this is a duplicate of #11672

There is a workaround (that still does not work on Safari) in the comments

I will close this ticket and you can follow the referenced ticket and give it 👍 to increase the chance of it being picked up sooner

Thanks for your patience

**Closed by arminmeh** 2024-07-10 08:54 UTC
Labels: component: data grid, status: waiting for maintainer, support: commercial

**Comment by Arata-Yoshida** [comment] 2024-07-11 02:17
Thank you!
We were able to fix the problem
