### ISSUE TITLE
[charts] Misconception about default axis ids

### ISSUE THREAD

**Issue by NerdCowboy** [mui/mui-x#12531] opened 2024-03-21 18:31 UTC
### Steps to reproduce

Link to live example: (required)
[CodeSandbox](https://codesandbox.io/p/sandbox/hopeful-dew-x96f9q?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu1jny0100073b6mwoi2y2c3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu1jny0100033b6mp0gxo7el%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu1jny0100043b6mdfqxmvkc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu1jny0100063b6mycmorgzh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu1jny0100033b6mp0gxo7el%2522%253A%257B%2522id%2522%253A%2522clu1jny0100033b6mp0gxo7el%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu1jny0100063b6mycmorgzh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu1jny0100053b6m1vaffwm7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu1jny0100063b6mycmorgzh%2522%252C%2522activeTabId%2522%253A%2522clu1jny0100053b6m1vaffwm7%2522%257D%252C%2522clu1jny0100043b6mdfqxmvkc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu1jny0100043b6mdfqxmvkc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1. Add a BarChart component
2. Try to reverse the axis position per [this example](https://mui.com/x/react-charts/axis/#axis-customization)
3. Note the axis labels disappear entirely
![image](https://github.com/mui/mui-x/assets/757960/398150f6-1f68-4a09-a59d-9e3d5d141532)

### Current behavior

Axis customization for BarChart hides axis labels

### Expected behavior

Axis customization should show axis labels and act exactly like the ScatterChart

### Context

Still trying to do a reverse horizontal bar chart per my [previous ticket](https://github.com/mui/mui-x/issues/11890)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: bar chart, axis, reverse
**Order ID**: 70251

**Comment by alexfauquette** [comment] 2024-03-22 09:14
The issue come from the `DEFAULT_X_AXIS_KEY` which is the id of the axis we put by default if you provide nothing.

Since you provide an axis with `xAxis={[{ reverse: true }]}`, it will get the id `defaultized-x-axis-0`, because we allow the creation of multiple axes without id by generating ids `defaultized-[x|y]-axis-[axis index]`

Using `topAxis="defaultized-x-axis-0"` should solve your issue.

For a long term fix. I think we could go with the `DEFAULT_X_AXIS_KEY` being used for the first axis defined  if no other id is provided . But that would be a breaking change

**Comment by NerdCowboy** [comment] 2024-03-22 15:17
@alexfauquette apologies, I somehow managed to link to the wrong sandbox. I've updated my post with the [correct link](https://codesandbox.io/p/sandbox/hopeful-dew-x96f9q?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu1jny0100073b6mwoi2y2c3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu1jny0100033b6mp0gxo7el%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu1jny0100043b6mdfqxmvkc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu1jny0100063b6mycmorgzh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu1jny0100033b6mp0gxo7el%2522%253A%257B%2522id%2522%253A%2522clu1jny0100033b6mp0gxo7el%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu1jny0100063b6mycmorgzh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu1jny0100053b6m1vaffwm7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu1jny0100063b6mycmorgzh%2522%252C%2522activeTabId%2522%253A%2522clu1jny0100053b6m1vaffwm7%2522%257D%252C%2522clu1jny0100043b6mdfqxmvkc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu1jny0100043b6mdfqxmvkc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

For reference, this is what I previously had (I've since updated the sandbox to the working version)
``` Typescript
<BarChart
  dataset={dataset}
  yAxis={[{ scaleType: "band", dataKey: "month" }]}
  series={[
    { dataKey: "seoul", label: "Seoul rainfall", valueFormatter },
  ]}
  layout="horizontal"
  leftAxis={null}
  bottomAxis={null}
  topAxis={DEFAULT_X_AXIS_KEY}
  rightAxis={DEFAULT_Y_AXIS_KEY}
  margin={{ top: 30, bottom: 10 }}
  xAxis={[{
    label: "rainfall (mm)"
  }]}
  width={500}
  height={400}
/>
```

I was copying exactly what Scatter chart does to move the axis, so I didn't initially add `reverse`, but you're correct I need that for what I want to accomplish. The confusion for me is why moving the axes doesn't work exactly the same for Bar chart and Scatter chart. 

I tried your suggestion and it gave me this error. looks like there's a typo.
> MUI-X-Charts: id used for top axis "defaultized-x-axis-0" is not defined.
Available ids are: deaultized-x-axis-0, DEFAULT_X_AXIS_KEY.

Removing "f" from "defaultized" fixed it.
 
For those that want the correct code, here is what I ended up having to use
``` Typescript
<BarChart
  dataset={dataset}
  yAxis={[{ scaleType: "band", dataKey: "month" }]}
  series={[
    { dataKey: "seoul", label: "Seoul rainfall", valueFormatter },
  ]}
  layout="horizontal"
  leftAxis={null}
  rightAxis="deaultized-y-axis-0"
  margin={{ bottom: 90 }}
  slotProps={{
    legend: {
      position: {
        horizontal: "middle",
        vertical: "bottom",
      },
    },
  }}
  xAxis={[
    {
      label: "rainfall (mm)",
      reverse: true,
    },
  ]}
  width={500}
  height={400}
/>
```
![image](https://github.com/mui/mui-x/assets/757960/074f1bef-e955-441f-be88-73d5f1faa363)

**Comment by alexfauquette** [comment] 2024-03-22 16:54
> I was copying exactly what Scatter chart does to move the axis, so I didn't initially add reverse

You don't use reverse, but the y-axis is defined

```
yAxis={[{ scaleType: "band", dataKey: "month" }]}
```

I should update the demo because the axis ids are too confusing. Or at list I should add a comment to explain its limitation.

> Removing "f" from "defaultized" fixed it.

Yes, that's a typo that got fixed in the v7 https://github.com/mui/mui-x/pull/12461

> I somehow managed to link to the wrong sandbox

No wories. For a reason I ignore most of the codesandbox I open today have the error "Invalid left-hand side in assignment" So I'm running the provided code in local env which is imperfect. That's why you are in a version with the typo and not me

**Comment by MRanjith26** [comment] 2024-04-13 11:18
I have a similar problem right now and I want to hide the ticks and axis lines but not the month. any suggestions?

**Comment by alexfauquette** [comment] 2024-04-13 21:42
> I have a similar problem

What did you try?

**Comment by MRanjith26** [comment] 2024-04-15 10:42
used the styling for axis lines and ticks 
sx={{
          // bottomAxis Line Styles
            "& .MuiChartsAxis-bottom .MuiChartsAxis-line": {
              strokeWidth: 0,
            },
            // Ticks
            "& .MuiChartsAxis-tick": {
              strokeWidth: 0,
            },
}}

> I have a similar problem right now and I want to hide the ticks and axis lines but not the month. any suggestions?

**Comment by alexfauquette** [comment] 2024-04-15 11:39
It seems to be working: https://stackblitz.com/edit/react-pbjrbl?file=Demo.tsx

@MRanjith26 since your issue is not directly related to this one, could you please open a new one with a minimal reproduction example (the stackblitz link above should be a good starting point) and an explanation about what is not working as expected in your example

**Closed** 2024-04-15 11:39 UTC
Labels: breaking change, dx, component: charts
