### ISSUE TITLE
[data grid] Cannot transpile since latest update v7.0.0

### ISSUE THREAD

**Issue by sicknesz** [mui/mui-x#12612] opened 2024-03-29 15:42 UTC
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/mui-bug-reproduction?file=.vscode%2Fsettings.json
PS :  the node version is wrong im sorry im totally new to stackblitz but i've manage to make it reproducible 
Steps:
1. Within stackblitz run npm run dev with the version 7.0.0 (because of the wrong node version the command needs to be `NODE_OPTIONS=--openssl-legacy-provider npm run dev`
2. the code won't compile throwing error on each line using an optionnal chaining or a Nullish coalescing operator (see pictures) 
3. Downgrade all 7.0.0 version to 6.19.8, and step 2 goes through successfully 

With 6.19.8 
![ISSUE_Success](https://github.com/mui/mui-x/assets/3835626/7ebb1ca8-7893-4ec9-a182-2d55b4219245)

With 7.0.0 (optionnal chaining)
![ISSUE_Fail_#1](https://github.com/mui/mui-x/assets/3835626/51fffe27-51d9-4a2c-9e1f-48e4aacc7809)

With 7.0.0
![ISSUE_Fail_#2](https://github.com/mui/mui-x/assets/3835626/a1620038-be68-4b99-a8fc-f052a89a3f9f)
 (nullish coalescing operator)

### Current behavior

The code sitting inside node_modules breaks the transpilation process and the application will not build anymore

### Expected behavior

Code should transpile successfully 

### Context

Trying to update from v6.19.8 to v7.0.0 inside our codebase

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Linux 6.6 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.9.2 
  Browsers:
    Chrome: 119.0.6045.105
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/material: ^5.14.18 => 5.14.18 
    @mui/x-data-grid: ^6.18.5 => 6.18.5 
    @mui/x-data-grid-pro: ^7.0.0 => 7.0.0 
    @mui/x-date-pickers: ^7.0.0 => 7.0.0 
    @mui/x-date-pickers-pro: ^7.0.0 => 7.0.0 
    @types/react: 17.0.2 => 17.0.2 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
```
</details>

**Search keywords**: Unexpected Token, Bug, optionnal chaining
**Order ID**: 86843

**Comment by michelengelen** [comment] 2024-04-02 11:39
@MBilalShafi have we encountered this before? It feels like this could potentially be a problem with the build process and not the package, WDYT?

**Comment by LukasTy** [comment] 2024-04-02 12:45
@flaviendelangle could this be because the `legacy` bundle has been removed on v7?
The environment setup is somewhat ancient, an old webpack and `webpack-dev-server` are used. 🤔 🙈 

No offense @sicknesz, but your setup looks pretty ancient, especially in webpack department. 🙈 
I've [played around](https://stackblitz.com/edit/mui-bug-reproduction-tpibqy?file=package.json) with your example and made it run by upgrading webpack.

P.S. Is there any reason why your dependencies include `@material-ui/pickers` and `@mui/x-date-pickers` at the same time? 🤔 
If the example dependencies are the ones you use in your application, In general, it seems that you are trying to use the legacy `@material-ui` packages and the recent `@mui` icons at the same time.
If that's the case—please consider checking if that is necessary. 😉

**Comment by flaviendelangle** [comment] 2024-04-02 12:51
> @flaviendelangle could this be because the legacy bundle has been removed on v7?

This is the only bundling change I'm seeing between v6 and v7 yes

**Comment by sicknesz** [comment] 2024-04-02 19:59
@LukasTy 

First of all, Thanks for the quick reply. I'll will answer 

> Is there any reason why your dependencies include @material-ui/pickers and @mui/x-date-pickers at the same time? 🤔

It's just that i forgot to remove it, we use the pickers from @mui/@mui-pro (range picker)  now.

> it seems that you are trying to use the legacy @material-ui packages and the recent @mui packages at the same time. 

Yes we are 😔👉👈, i know it's most likely unsupported and certainly recommended against, im using the datagrid (v6.19.8) inside a mostly material v4 based application, I first matched all version (material v4 => datagrid v4 => all v4) but find options i needed to use that were only available on more recent version, 

so i tried upgrading the datagrid only almost certain that it will crash and that i will have to downgrade 
but it worked so as of today we are mixing material v4 and the datagrid v6 until we can rewrite/upgrade everything with the greatest and latest version of everything. 

I know that our setup is very outdated, but I was hoping there would still be a solution without having to upgrade webpack, 

Last time i tried upgrading the build process, it led to me re-writing all server imports from commonJS (require)to ESM (import/export) but that broke everything, so we postponed it once again because we were late on schedule for releasing new  features.

**Comment by LukasTy** [comment] 2024-04-03 08:47
@sicknesz Thank you for explaining your setup.
I've tested if the removal of the `legacy` bundle is the cause and concluded that it is not to blame.
Adding `NODE_OPTIONS=--openssl-legacy-provider` to the start of your `dev` script seems to solve the error on start.
But at least in StackBlitz, the compilation fails after that due to the inability to parse [Nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) and [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operators.

Could you please test on your local setup if adding the mentioned option helps?
Does it also produce compilation errors after the dev server starts?

My main question would be: do you have any feature that forces you to upgrade to v7 of our libraries?
If not, I'd first encourage you to update the development setup. 😉 

P.S. Don't forget that v7 of X packages has a peer dependency on `"@mui/material": "^5.15.14"`. 😉

**Comment by sicknesz** [comment] 2024-04-05 18:45
Hey @LukasTy  sorry for the late response on my end, actually i haven't found any features that would require us to update, it's more that we use the headerFilter feat which is labelled "unstable" on our version so I thought it would be best to get it to "stable" before going to production but that's mostly it, that and being able to benefit from new version.

So I'll recommend to my boss to keep on v6 and push for the upgrade, Thanks for the quick reply

PS: the options does not help, it's needed because i've choosen the wrong node version for the stackblitz and im not familiar enough with it to change it, the problem is the compilation error triggered by optionnal chaining and nullish coalescing operators. 

Sicknesz.

**Comment by LukasTy** [comment] 2024-04-08 07:47
Without manually asserting, I'm pretty sure that the main change that impacted this behavior is https://github.com/mui/mui-x/pull/12521.
With it, we dropped support for iOS <15.4, and that in turn allowed us to no longer ship poly-filled mentioned modern operators.

I don't know if there is anything we can do here.
If the development setup can not support it, then it's time to update it. 🙈 
WDYT @flaviendelangle @cherniavskii @michelengelen? Can we close this issue with this resolution?

**Comment by cherniavskii** [comment] 2024-04-08 13:47
Interesting, we didn't think much about bundlers when updating browserlist (although there was a note about webpack 4 in https://github.com/mui/mui-x/pull/12521/files#diff-43302d1852d8010ee012aab4dda2d01abb664e11f73617fe625f2ba112a958edL12).

One workaround for webpack 4 is to add Babel plugins to `webpack.config.js`:

```diff
module: {
    rules: [
      {
        test: /\.[jt]sx?$/,
-       exclude: /node_modules/,
+       exclude: [
+         {
+           test: path.resolve(__dirname, 'node_modules'),
+           exclude: [
+             path.resolve(__dirname, 'node_modules/@mui/x-data-grid'),
+             path.resolve(__dirname, 'node_modules/@mui/x-license'),
+           ],
+         },
+       ],
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env', '@babel/preset-react'],
              plugins: [
                ['@babel/plugin-transform-runtime', { regenerator: true }],
                require.resolve('react-refresh/babel'),
+               '@babel/plugin-proposal-nullish-coalescing-operator',
+               '@babel/plugin-transform-optional-chaining',
              ],
            },
          },
        ],
      },
```

Here is the working demo: https://stackblitz.com/edit/mui-bug-reproduction-qkmoda (use `npm start` to run)
 
Given that [webpack 5 was released almost 4 years ago](https://webpack.js.org/blog/2020-10-10-webpack-5-release/), this solution seems reasonable to me.

@sicknesz @deependrasingh17 Please let me know if this works for you.

**Comment by flaviendelangle** [comment] 2024-04-08 14:07
Nice workaround
We should probably add a note about webpack 4 in the migration guides

**Closed** 2024-04-17 03:06 UTC
Labels: component: data grid, status: waiting for author, external dependency, support: pro standard
