### ISSUE TITLE
[data grid] Header Filters overlap with data in compact density

### ISSUE THREAD

**Issue by lukedukeus** [mui/mui-x#14072] opened 2024-08-01 12:58 UTC
### Steps to reproduce

Link to [live example](https://stackblitz.com/edit/react-scfkja?file=Demo.tsx)

Steps:
1. Type in a header filter
2. See how it overlaps: 
![image](https://github.com/user-attachments/assets/29505be9-e049-45eb-a440-672aeccf9649)

### Current behavior

Currently, the textbox's filter label overlaps with the column header, and the bottom of the textbox overlaps with the datagrid rows.

### Expected behavior

I would expect the header filters to be `<TextInput size='small' />` when the density is compact

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.4
    @emotion/styled: ^11.11.0 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.6
    @mui/icons-material: ^5.16.6 => 5.16.6
    @mui/lab: ^5.0.0-alpha.173 => 5.0.0-alpha.173
    @mui/material: ^5.16.6 => 5.16.6
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system: ^5.16.6 => 5.16.6
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-data-grid: ^7.11.1 => 7.11.1
    @mui/x-data-grid-premium: ^7.11.1 => 7.11.1
    @mui/x-data-grid-pro:  7.11.1
    @mui/x-date-pickers:  7.11.1
    @mui/x-date-pickers-pro: ^7.11.1 => 7.11.1
    @mui/x-internals:  7.11.1
    @mui/x-license: ^7.11.1 => 7.11.1
    @mui/x-tree-view: ^7.11.1 => 7.11.1
    @types/react: ^18.0.28 => 18.2.74
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.0.4 => 5.4.3
```
</details>

**Search keywords**: headerFilters density

**Search keywords**:

**Comment by michelengelen** [comment] 2024-08-02 12:00
Hey @lukedukeus ... that's a nice workaroud. There is an issue already about this, so I'll close this as a duplicate! Thanks for raising it and sharing your workaround!

**Comment by michelengelen** [comment] 2024-08-02 12:01
Closing as duplicate of #13048

**Closed by michelengelen** 2024-08-02 12:01 UTC
Labels: bug 🐛, component: data grid, status: waiting for maintainer, feature: Filtering on header
