### ISSUE TITLE
[license] Expired license key

### ISSUE THREAD

**Issue by ASMalakhovv** [mui/mui-x#13138] opened 2024-05-15 08:38 UTC
### Steps to reproduce

Link to live example: (required)
[Exmaple](https://codesandbox.io/p/devbox/mnwm24?migrateFrom=4wsvhh&embed=1&file=%2F.codesandbox%2Ftasks.json&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw7i3zbs00063587cz67eyto%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw7i3zbr00023587yiahebrx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw7i3zbs00043587vv2exsjv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw7i3zbs00053587akc4fio0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw7i3zbr00023587yiahebrx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw7i3zbr00013587yzz250xv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%257D%255D%252C%2522id%2522%253A%2522clw7i3zbr00023587yiahebrx%2522%252C%2522activeTabId%2522%253A%2522clw7i3zbr00013587yzz250xv%2522%257D%252C%2522clw7i3zbs00053587akc4fio0%2522%253A%257B%2522id%2522%253A%2522clw7i3zbs00053587akc4fio0%2522%252C%2522activeTabId%2522%253A%2522clw7i4h14005i3587jh2xdhy3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clw7i4h14005i3587jh2xdhy3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clw7i3zbs00043587vv2exsjv%2522%253A%257B%2522id%2522%253A%2522clw7i3zbs00043587vv2exsjv%2522%252C%2522activeTabId%2522%253A%2522clw7i3zbs00033587h2ccej5a%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw7i3zbs00033587h2ccej5a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clw7i40cd000ddgf8fqucc2sb%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clw7i4cs7004h35873tbuj1u8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
Steps:
1. Import the LicenseInfo method from @mui/x-license and call the setLicenseKey() function with mine license key.
2. Open developer tools and look for errors in the console

### Current behavior

1. An error message appeared in the developer tools in the console: MUI X: Expired license key. Your annual license key to use MUI X Pro in non-production environments has expired.
![Annual](https://github.com/mui/mui-x/assets/89951198/83ec7cf3-0d2f-40b2-ae50-c3b30153c36f) 
2. An error has appeared that blocks the operation of the application, containing the following text: The above error occurred in the <ForwardRef(DesktopDateRangePicker)> component.
![ForwarRef](https://github.com/mui/mui-x/assets/89951198/dfd0e4b6-463d-42dd-b74e-d9ed47807963)

### Expected behavior

An error indicating that the license key has expired in development mode, but does not block work with the component.

### Context

The version of the mui -x package that I added to myself was released during the validity period of my license, based on the documentation I should be able to use it, but in practice I get a blocking error.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 Browsers:
    Chrome: Not Found
    Edge: Chromium (123.0.2420.81)
  npmPackages:
    @emotion/react:  11.11.4 
    @emotion/styled:  11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.17 
    @mui/icons-material: 5.11.9 => 5.11.9 
    @mui/material: 5.15.15 => 5.15.15 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/styled-engine-sc: 5.11.11 => 5.11.11 
    @mui/styles: 5.11.9 => 5.11.9 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  6.2.0
    @mui/x-data-grid-premium: 6.2.0 => 6.2.0
    @mui/x-data-grid-pro:  6.2.0
    @mui/x-date-pickers:  7.1.1
    @mui/x-date-pickers-pro: 7.1.1 => 7.1.1
    @mui/x-license:  7.1.1
    @mui/x-license-pro: 6.0.4 => 6.0.4
    @mui/x-tree-view: 6.17.0 => 6.17.0
    @types/react: 17.0.6 => 17.0.6
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    styled-components: 5.3.5 => 5.3.5
    typescript: 5.2.2 => 5.2.2

```
</details>

**Search keywords**: ForwardRef, expired, license, key

**Comment by flaviendelangle** [comment] 2024-05-15 09:19
Hi,

Your annual license is valid for one year in development, regardless of the version used.
See the following description in our pricing page:

![image](https://github.com/mui/mui-x/assets/3309670/ccf94d2f-6913-48f1-86f7-0db02cbf9e5a)

**Comment by LukasTy** [comment] 2024-05-16 12:04
We're closing the issue as the problem seems to have been clarified.
If you feel that the issue is not resolved yet, feel free to reopen it. 😉

**Closed by LukasTy** 2024-05-16 12:04 UTC
Labels: status: waiting for maintainer, package: x-license
