### ISSUE TITLE
 [MultiInputDateRangeField] doesn't work as [StaticDateRangePicker] custom toolbar

### ISSUE THREAD

**Issue by Jontii** [mui/mui-x#10436] opened 2023-09-22 19:19 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-date-pickers-pro-d6dfl4

Steps:
1. I copied the example from https://mui.com/x/react-date-pickers/custom-components/#component-3
2. I used the example from MultiInputDateRangeField - https://mui.com/x/react-date-pickers/fields/#system-ControlledSelectedSectionsMultiInputRangeField.tsx
3. I expect it to work together as MultiInputDateRangeField in a custom toolbar component and being able to select different fields with the Year/Month/Day buttons.

### Current behavior 😯

Nothing happens when I click Year/Month/Day buttons or I manage to select one field but I can't enter any input. The fields also seems to not work at all when sent in as a custom toolbar.

### Expected behavior 🤔

I expect them to work as the separate examples but together.

### Context 🔦

I want to recreate airbnb's calendar. It looked likes using a custom toolbar like my example would do the trick. 
<img width="770" alt="image" src="https://github.com/mui/mui-x/assets/19165426/279c2049-c989-4143-a2a1-55da9d3bc4d8">

### Your environment 🌎

  System:
    OS: macOS 13.4
  Binaries:
    Node: 18.17.1 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 3.6.3 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Edge: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.16
    @mui/core-downloads-tracker:  5.14.10
    @mui/icons-material: ^5.6.0 => 5.14.8
    @mui/lab: ^5.0.0-alpha.142 => 5.0.0-alpha.145
    @mui/material: ^5.14.0 => 5.14.10
    @mui/private-theming:  5.14.10
    @mui/styled-engine:  5.14.10
    @mui/system:  5.14.10
    @mui/types:  7.2.4
    @mui/utils:  5.14.10
    @mui/x-date-pickers:  6.14.0
    @mui/x-date-pickers-pro: ^6.14.0 => 6.14.0
    @mui/x-license-pro:  6.10.2
    @mui/x-tree-view:  6.0.0-alpha.1
    @types/react: ^18.2.14 => 18.2.21
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.2.2

### Order ID or Support key 💳 (optional)

75069

**Comment by alexfauquette** [comment] 2023-09-25 07:54
It's mostly because you define your custom component inside the main one whereas you should never define a component inside another one.

Here is a solution.
https://codesandbox.io/s/mui-x-date-pickers-pro-forked-x6lsc8?file=/src/App.tsx

**Comment by Jontii** [comment] 2023-09-26 07:27
Thank you ! Works great !

Is there a way to know which one's of the fields in MultiInputDateRangeField is selected ? 

Currently I'm using `document.activeElement === startInputRef.current` to know which one is selected. I was wondering if there was a better way.

**Comment by LukasTy** [comment] 2023-09-26 07:51
> Is there a way to know which one's of the fields in MultiInputDateRangeField is selected ?
> 
> Currently I'm using `document.activeElement === startInputRef.current` to know which one is selected. I was wondering if there was a better way.

It's not a bad option. If you were to use the picker instead of the field, then you could use the [`onRangePositionChange` callback](https://codesandbox.io/s/optimistic-kowalevski-yt5ply?file=/Demo.tsx).

I'm closing the issue as it seems that the root cause has been resolved.
If you still think that the issue is relevant - feel free to reopen it or create a new issue.

**Closed by LukasTy** 2023-09-26 07:51 UTC
Labels: support: question, component: pickers
