### ISSUE TITLE
Pagination by server is causing issues when trying to filter on a different page.

### ISSUE THREAD

**Issue by stertheweb** [mui/mui-x#2321] opened 2021-08-10 21:06 UTC
I am getting this bug where I move to the second or higher page of a grid and try to apply a filter, but the pagination does not send me back to the first page. The pagination works fine if I stay on the first page and try to apply it.

For example: I have 60 rows in one of my grids and am only showing 50 per page. I click to go to page 2 and filter the ID column for only rows containing "14". In my table I should have 10 rows, however the filter behavior is keeping me on page 2 and not showing any rows. Sometimes, I click to go back to the first page and the 10 rows that are supposed to appear are there. However other times, they do not show. The behavior is inconsistent.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

On second or higher page, filter does not work. I stay on the same page and the row total remains the same.

## Expected Behavior 🤔

On second or higher page, I should be redirected to first page and the row total should match the number of filtered rows.

## Steps to Reproduce 🕹
1. Go to second page.
2. Apply a filter to any column.

## Context 🔦
```
<XGrid
  pageSize={pageSize}
  page={page}
  rowsPerPageOptions={[25, 50, 100]}
  rowCount={handleRowCount}
  onPageChange={onHandlePageChange}
  onPageSizeChange={onHandlePageSizeChange}
  rows={rows}
  columns={columns}
  paginationMode="server"
  pagination
  disableColumnResize={true}
  hideFooterSelectedRowCount={true}
/>
```

Here is a working sandbox example (https://codesandbox.io/s/material-demo-forked-dcumy?file=/demo.js), but this is not working in my local development environment.

## Your Environment 🌎

I am using Google Chrome v92.0.4515.131.

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
 System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.20.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.67)   
  npmPackages:
    @material-ui/core: ^4.12.1 => 4.12.3
    @material-ui/data-grid: ^4.0.0-alpha.24 => 4.0.0-alpha.35 
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.58 => 4.0.0-alpha.60
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.12.1
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: ^4.0.0-alpha.25 => 4.0.0-alpha.35
    @material-ui/x-license:  4.0.0-alpha.35
    @types/react:  17.0.15
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript:  2.9.2
```
</details>

**Comment by DanailH** [comment] 2021-08-11 10:10
Hi, @stertheweb thanks for raising this. I check the example but that is quite different from the code you pasted in the description. If you are in fact use that code snipped then the fact that you are not moved back to the first page of the pagination is because you are controlling the pagination via the `page` prop. You would have to either not control the pagination or react to the `filterModel` change and set the `page` prop accordingly.

**Comment by stertheweb** [comment] 2021-08-11 13:17
I am being required to control pagination with the sizes 25, 50, and 100. Is there a way for me to control pagination without using the `page` prop?

**Comment by stertheweb** [comment] 2021-08-11 13:35
I read the documentation and found this example: https://codesandbox.io/s/0k5t3?file=/demo.js.

To replicate:
1. Click the right arrow to go to the 2nd page.
2. Click the 3 dots next to the "Commodity" column.
3. Select "Filter".
4. Set Columns to "Commodity", set Operator to "contains", and set Value to "rice".

There are no rows showing and the page is still set to page 2. I have to manually click to go back to page 1.

What I want is that when I follow these steps, I want the filter to automatically send me back to page 1 and the total number of rows to match the filter. I hope this makes sense.

**Comment by oliviertassinari** [comment] 2021-08-14 21:53
@stertheweb In `paginationMode="server"` you are also responsbiel for updating rowCount.

**Comment by oliviertassinari** [comment] 2021-08-14 22:07
Interesting, so the bug can be reproduced here https://material-ui.com/components/data-grid/pagination/#server-side-pagination. The `rowCount` prop takes precedence over the filtering. The test case itself is a bit weird. End-users can only filter inside the loaded rows of the page, not on the whole data set.

I assume that it's `visibleRo
wCount` that should process `props.rowCount`, so we should ignore it here:

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts b/packages/grid/_modules_/grid/hooks/features/pagination/useGridPa
ge.ts
index 53044339..f6d11564 100644
--- a/packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
+++ b/packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
@@ -65,7 +65,7 @@ export const useGridPage = (

   React.useEffect(() => {
     setGridState((state) => {
-      const rowCount = props.rowCount !== undefined ? props.rowCount : visibleRowCount;
+      const rowCount = visibleRowCount;
       const pageCount = getPageCount(rowCount, state.pagination.pageSize);

       const page = props.page == null ? state.pagination.page : props.page;
diff --git a/packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx b/packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
index 8f89b7a9..14a4ad2f 100644
--- a/packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
+++ b/packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
@@ -488,9 +488,9 @@ describe('<DataGrid /> - Pagination', () => {

   it('should react to an update of rowCount', () => {
     const { setProps } = render(
-      <BaselineTestCase rowCount={5} pageSize={1} page={0} rowsPerPageOptions={[1]} />,
+      <BaselineTestCase rowCount={20} pageSize={1} page={0} rowsPerPageOptions={[1]} />,
     );
-    expect(document.querySelector('.MuiTablePagination-root')).to.have.text('1-1 of 5');
+    expect(document.querySelector('.MuiTablePagination-root')).to.have.text('1-1 of 20');
     setProps({ rowCount: 21 });
     expect(document.querySelector('.MuiTablePagination-root')).to.have.text('1-1 of 21');
   });
```

It seems to work, we would need to add a new test case.

**Comment by ZeeshanTamboli** [comment] 2021-08-17 11:30
@oliviertassinari 
The `rowCount` definition we have is `Set the total number of rows, if it is different than the length of the value rows prop.`

So considering that if `rowCount` is provided, now since number of `rows` passed is different, should it only show those many rows with `rowCount` limit?

eg:
20 rows, but rowCount is 5 so show only 5 rows and display that many in footer. 

So the test above there seems correct. But it does not make sense.
I think `rowCount` should only be set and allowed if `paginationMode` is server.

**Comment by m4theushw** [comment] 2021-11-18 18:57
I tried solving this bug by ignoring `rowCount` when filtering. However, this brings another problem. Once it changes to the first page, `onPageChange` is called again which makes new rows to be loaded. I don't see a simple solution than suggesting the when server-side pagination is used, server-side filtering should also be used.

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts b/packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
index 8eef13c04..b333f53b1 100644
--- a/packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
+++ b/packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
@@ -14,6 +14,7 @@ import { GridPaginationState } from './gridPaginationState';
 import { gridVisibleTopLevelRowCountSelector } from '../filter';
 import { useGridStateInit } from '../../utils/useGridStateInit';
 import { gridPageSelector } from './gridPaginationSelector';
+import { GridFeatureModeConstant } from '../../../models/gridFeatureMode';
 
 const getPageCount = (rowCount: number, pageSize: number): number => {
   if (pageSize > 0 && rowCount > 0) {
@@ -41,7 +42,7 @@ const applyValidPage = (paginationState: GridPaginationState): GridPaginationSta
  */
 export const useGridPage = (
   apiRef: GridApiRef,
-  props: Pick<GridComponentProps, 'page' | 'onPageChange' | 'rowCount'>,
+  props: Pick<GridComponentProps, 'page' | 'onPageChange' | 'rowCount' | 'filterMode'>,
 ) => {
   const logger = useGridLogger(apiRef, 'useGridPage');
 
@@ -57,6 +58,7 @@ export const useGridPage = (
   const [, setGridState, forceUpdate] = useGridState(apiRef);
 
   const visibleTopLevelRowCount = useGridSelector(apiRef, gridVisibleTopLevelRowCountSelector);
+  const rowIds = useGridSelector(apiRef, gridRowIdsSelector);
 
   apiRef.current.unstable_updateControlState({
     stateId: 'page',
@@ -84,7 +86,12 @@ export const useGridPage = (
 
   React.useEffect(() => {
     setGridState((state) => {
-      const rowCount = props.rowCount !== undefined ? props.rowCount : visibleTopLevelRowCount;
+      const hasFilterApplied = rowIds.length !== visibleTopLevelRowCount;
+      const ignoreRowCount =
+        props.rowCount == null ||
+        (props.filterMode === GridFeatureModeConstant.client && hasFilterApplied);
+      const rowCount = !ignoreRowCount ? props.rowCount! : visibleTopLevelRowCount;
+
       const pageCount = getPageCount(rowCount, state.pagination.pageSize);
       const page = props.page == null ? state.pagination.page : props.page;

```

**Comment by joserodolfofreitas** [comment] 2022-02-16 10:03
I'm closing this issue and opening another one (#3966) to improve our documentation and better explain what are the expected behaviors in such situations.

**Closed by joserodolfofreitas** 2022-02-16 10:03 UTC
Labels: component: data grid, feature: Filtering, feature: Pagination
