### ISSUE TITLE
[pickers] Integration with Storybook, LocalizationProvider error

### ISSUE THREAD

**Issue by grzabrodskiy** [mui/mui-x#10611] opened 2023-10-08 16:15 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I am using MUI MonthPicker (MUI v5.x), it works okay in the code, but when I use the component in the storybook, it gives me the following error:

`MUI: Can not find utils in context. It looks like you forgot to wrap your component in LocalizationProvider, or pass dateAdapter prop directly.`

My simplified code for the component is
```jsx
export const MyMonthPicker = ({ value, onChange }) => (
    <Paper>
      <MonthPicker
        onChange={(newDate) => {
          onChange(newDate);
        }}
        date={value}
        disableFuture
      />
    </Paper>
  );
```
My story is:
```jsx
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";

const meta: Meta<typeof MonthYearPicker> = {
  title: "MyProject/components/MyMonthPicker",
  component: MyMonthPicker,
  args: { value: new Date(), onChange: (value) => {} },
  decorators: [
    (Story) => (
      <LocalizationProvider dateAdapter={AdapterDateFns} localeText={{}}>
        <Box sx={{ position: "relative" }}>
          <Story />
        </Box>
      </LocalizationProvider>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof MonthYearPicker>;

export const Default: Story = {};
```
I tried using other dateAdaptors with the same result (AdapterDayjs, AdapterLuxon, AdapterMoment).

  

### Current behavior 😯

Error: `MUI: Can not find utils in context. It looks like you forgot to wrap your component in LocalizationProvider, or pass dateAdapter prop directly.`

### Expected behavior 🤔

Work without an error

### Context 🔦

I am not able to use storybook for my new component

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**:

**Comment by noraleonte** [comment] 2023-10-09 14:57
Hey @grzabrodskiy 👋 

I've tried setting up a simple project using storybook and the v5 pickers, but I am not able to reproduce the issue. It would really help if you could give a more specific example/reproduction 🤔 It might be related to how your custom component is implemented, but it's just a hunch.

**Comment by grzabrodskiy** [comment] 2023-10-09 15:01
Hi Nora, thank you for your reply. I ended up using StaticDatePicker with
view props value of “month” and “year” instead of MonthPicker and
YearPicker and it solved the problem.

**Comment by noraleonte** [comment] 2023-10-09 17:32
Glad to hear you managed to find a solution. 🎉 Closing this issue now, but feel free to reopen or create another issue in the future if you hit another roadblock 👍

**Closed** 2023-10-09 17:33 UTC
Labels: status: needs triage, component: pickers

**Comment by ibanezht** [comment] 2024-07-07 22:05
If anyone comes across this, this seems to be working so far.

Wrap your component in a localization provider:
```
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import React from "react";

import { OrderSearchFilter, OrderSearchFilterProps } from "../components";

const WrappedOrderSearchFilter = (props: OrderSearchFilterProps) => {
  return (
    <LocalizationProvider dateAdapter={AdapterDateFns}>
      <OrderSearchFilter {...props} />
    </LocalizationProvider>
  );
};

export default WrappedOrderSearchFilter;
```

Use the wrapped version when building the story:
```
const meta = {
  title: "OrderSearchFilter",
  component: WrappedOrderSearchFilter,
} satisfies Meta<typeof OrderSearchFilter>;
```

**Comment by LukasTy** [comment] 2024-07-08 06:28
@ibanezht Storybook seems to have a way of [adding code to every story](https://storybook.js.org/docs/configure/story-rendering#running-code-for-every-story).
Have you tried going that route?
In general, I guess the idea would be to have something like this:
```tsx
import { Preview } from '@storybook/react';
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
 
const preview: Preview = ({ children }) => (
  <LocalizationProvider dateAdapter={AdapterDateFns}>
    {children}
    // or <Preview /> — I'm not sure about this internal API
  </LocalizationProvider>
);
 
export default preview;
```
