### ISSUE TITLE
Responsive and mobile datepicker needs two click to open

### ISSUE THREAD

**Issue by troussema** [mui/mui-x#5649] opened 2022-07-29 09:44 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When we try the responsive Datepicker on mobile, we need two click to open the picker.
If the value is set to **null** 

### Expected behavior 🤔

The Responsive Datepicker should open directly the picker on the first click.

### Steps to reproduce 🕹

[Link](https://codesandbox.io/s/responsivedatepicker-bug-double-click-l9i7yi?file=/demo.tsx) to live example with the bug

[Link](https://codesandbox.io/embed/date-picker-material-ui-7jnjo?file=/src/App.js&codemirror=1) to working example with old package **@mui/lab/DatePicker**

**You Need to try this with a real mobile** ( example: i used two phones, Iphone 13 pro max and android ),
mobile view with desktop works fine.

Steps:
1. First Click on the Date input => Focus
2. Second Click => Open the picker

### Context 🔦

With a real mobile, am trying to open the picker from the first click ( not focus then second click to open ).

I noticed if we click on the right of the input, the picker open with only one click
( where icon should be in desktop version , i know that the icon don't exist for mobile version )

If the value is not null the click works fine, but if the value is null and we click in center of input or anywhere else it's focus so we need a second click to open the picker.

Sometimes its open from first click, please try several times the input with null value in the live example from your mobile it will focus the input sometimes and not open.

### Your environment 🌎

@mui/material 5.9.2 and @mui/x-date-pickers 5.0.0-beta.2

**Comment by LukasTy** [comment] 2022-07-29 10:58
Closing as this is a duplicate of issue #5395

**Closed by LukasTy** 2022-07-29 10:58 UTC
Labels: duplicate
