### ISSUE TITLE
When using header filters with density compact UI is not looking good

### ISSUE THREAD

**Issue by akashranaspraxa** [mui/mui-x#10688] opened 2023-10-16 09:25 UTC
### Steps to reproduce

Steps:
1.use datagrid pro or premium
2.set density as compact
3.enable header filters and click on a header filter

When i am using header filter option with density set as compact the UI looks too dense and it is breaking

![image](https://github.com/mui/mui-x/assets/131777972/c6db1956-fba5-4aae-b134-ae687338221b)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: header filters issue

**Comment by MBilalShafi** [comment] 2023-10-16 11:37
Hey @akashranaspraxa, thank you for reporting, the issue is [known](https://github.com/mui/mui-x/issues/9034) and should be fixed in coming days.

Please subscribe to the original [issue](https://github.com/mui/mui-x/issues/9034) for updates.

**Closed by MBilalShafi** 2023-10-16 11:37 UTC
Labels: component: data grid, design

**Comment by akashranaspraxa** [comment] 2023-10-16 11:45
Thanks for the response, will subscribe the original issue updates.

**Comment by masbaehr** [comment] 2023-10-25 13:37
I also stumbled across this. Please let us also disable the placeholder which goes to top. Also the outline is not always needed.

This is my temporary workaround to make it look better until it's fixed :)

```
.MuiDataGrid-columnHeader:focus-within{
  outline: none !important;
}
.MuiDataGrid-columnHeader .MuiInputLabel-shrink{
  display: none;
}
```

<img width="153" alt="image" src="https://github.com/mui/mui-x/assets/38694044/e3587336-383e-4ccf-ab29-6d0cf4e3df9f">
