### ISSUE TITLE
[DatePicker] The `autoFocus` prop doesn't assign focus on the view

### ISSUE THREAD

**Issue by mtusk** [mui/mui-x#6376] opened 2022-10-03 22:00 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When DatePicker's `autoFocus` prop is set to `true`, focus is not assigned to the DatePicker's text input right away.

### Expected behavior 🤔

When DatePicker's `autoFocus` prop is set to `true`, focus should be assigned to the DatePicker's text input right away.

### Steps to reproduce 🕹

Link to live example: https://stackblitz.com/edit/react-qpgf7q?file=demo.tsx%3AL19

Steps:
1. Set DatePicker's `autoFocus` prop to `true`
2. Load the page
3. (focus is not assigned)

### Context 🔦

For reference, my assumptions on how DatePicker's autoFocus should behave are based on TextField's autoFocus behavior:

> `autoFocus`
> If `true`, the `input` element is focused during the first mount.
> https://mui.com/material-ui/api/text-field/#props

([example](https://stackblitz.com/edit/react-1bglyf?file=demo.tsx%3AL8))

### Your environment 🌎

[A StackBlitz session modified only slightly from ](https://stackblitz.com/edit/react-qpgf7q?file=demo.tsx%3AL19) modified slightly from [the StackBlitz session linked to from DatePicker's docs](https://mui.com/x/react-date-pickers/date-picker/#basic-usage).

**Comment by alexfauquette** [comment] 2022-10-05 09:23
I only see one problem which is when the picker is open from the beginning. In such a case, the input and the calendar will both ask for focus.

**Comment by flaviendelangle** [comment] 2022-10-05 09:55
How about having one single `autoFocus` props on the pickers, that is passed to the input if the picker is not opened on mount and passed to the views otherwise ?
If it's doable if feel like it would be the expected behavior.

As of today behavior, I guess the `autoFocus` prop should not have leaked to the non-static picker interfaces.

**Comment by eglitobias** [comment] 2023-03-22 09:41
I created an issue for this problem today (maybe) in the wrong repository (https://github.com/mui/material-ui/issues/36609). For us it is very important that when you set the autoFocus on the Date Field the user can directly enter a date and does not have to make an unnecessary click first.
Is this issue still being solved and what is its priority for you?

**Comment by flaviendelangle** [comment] 2023-03-22 09:55
I transferred your issue :+1: 

I'm closing this issue because now the field does have the focus when `autoFocus={true}`

**Closed by flaviendelangle** 2023-03-22 09:55 UTC
Labels: component: pickers, dx

**Comment by Sathishkumar1072** [comment] 2024-02-28 13:08
How to i set always focused, because i need to show the label on top left of the container
