### ISSUE TITLE
[data grid] TypeError: apiRef.current.getAllRowIds is not a function

### ISSUE THREAD

**Issue by hartmatt** [mui/mui-x#11636] opened 2024-01-10 08:27 UTC
### The problem in depth

Hey, I'm a MUI beginner, and have an issue that may be easily solvable, but I'm stuck. I don't currently have a live example, hopefully the following code / context is a start. I'm trying to run this code in a component that renders a data grid, with an array of countries (`selectedCountries`) as a prop. The data grid updates when the `selectedCountries` array updates:

```
import {
   DataGridPro,
   GridToolbarContainer,
   GridToolbarFilterButton,
   GridToolbarDensitySelector,
   useGridApiRef,
} from '@mui/x-data-grid-pro';

// ...

useEffect(() => {
      // When a country is added
      selectedCountries.forEach((country) => {
         const countryExists = apiRef.current.getRow(
            country.code || country.name,
         );

         if (!countryExists) {
            const newRow = {
               id: country.code || country.name,
               country: country.name,
               start: null,
               end: null,
               window: null,
            };
            apiRef.current.updateRows([newRow]);
         }
      });

      // When a country is removed
      apiRef.current.getAllRowIds().forEach((rowId) => {
         const countryExists = selectedCountries.find(
            (country) => country.code === rowId || country.name === rowId,
         );

         if (!countryExists) {
            apiRef.current.updateRows([{ id: rowId, _action: 'delete' }]);
         }
      });

      // Update prevSelectedCountries
      setPrevSelectedCountries(selectedCountries);
   }, [selectedCountries]);

// ...

return (

// ...

<DataGridPro
     apiRef={apiRef}
     rows={rows}
     columns={columns}
     editMode="row"
     pageSize={5}
     getRowId={(row) => row.id}
     density="compact"
     onColumnResizeCommitted={() => setRows([...rows])}
     components={{
        Toolbar: () => <CustomToolbar />,
     }}
     pagination
 />

//...

);
```

The error I get is - "Unhandled Runtime Error TypeError: apiRef.current.getAllRowIds is not a function". I understand from the docs that this method, as well as `updateRows` are Pro plan features, so I'm wondering whether there is something wrong with my license installation? Any help would be gratefully received! Thank you, Matt

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 12.7.2
  Binaries:
    Node: 21.5.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.199
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @emotion/react:  11.11.3 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.29 
    @mui/core-downloads-tracker:  5.15.3 
    @mui/icons-material: latest => 5.15.2 
    @mui/lab: ^5.0.0-alpha.158 => 5.0.0-alpha.158 
    @mui/material: ^5.15.3 => 5.15.3 
    @mui/private-theming:  5.15.3 
    @mui/styled-engine:  5.15.3 
    @mui/system:  5.15.3 
    @mui/types:  7.2.12 
    @mui/utils:  5.15.3 
    @mui/x-data-grid:  6.18.7 
    @mui/x-data-grid-pro: ^6.18.7 => 6.18.7 
    @mui/x-date-pickers:  6.18.7 
    @mui/x-date-pickers-pro: ^6.18.7 => 6.18.7 
    @mui/x-license-pro:  6.10.2 
    @types/react:  18.2.45 
    react: latest => 18.2.0 
    react-dom: latest => 18.2.0 
    typescript: 5.3.3 => 5.3.3 
```
</details>

**Search keywords**: apiRef.current.getAllRowIds is not a function
**Order ID**: 81795

**Comment by Laxman2015** [comment] 2024-01-10 10:23
I think you should use apiRef.current.getSortedRows() instead

**Comment by evgeniiarts** [comment] 2024-01-10 13:50
@hartmatt Not sure where your issue exactly is, a codesandbox with a reproduction would certainly help to find it.
I have created a small example where it works, maybe you can get started from here?
https://codesandbox.io/p/sandbox/getallrowids-3g74vr

It seems to m that your lookup for all row ids might actually be fine, but the approach how you attempt to use it here:
`
const countryExists = selectedCountries.find(
            (country) => country.code === rowId || country.name === rowId,
         );
`
seems a little bit odd to me, as you are comparing country codes and names to an id.

**Comment by michelengelen** [comment] 2024-01-10 16:01
@evgeniiarts is correct. That error most likely comes from the `apiRef.current` being undefined, since on mount `uesEffect` will run once. If you add a guard this won't happen.

If you are using Typescript you can just use `apiRef.current?.getAllRowIds()`.

On a side note: Your operation might potentially be very compute expensive. Just imagine doing this on a dataset of 500K rows and more. Running over every row and executing expensive array methods can be impacting the performance quite heavily.

**Comment by hartmatt** [comment] 2024-01-10 21:05
@evgeniiarts @michelengelen thanks both, addition of the optional chaining operator `?` still throws same error, but based on your suggestion I came up with a (more verbose) workaround that checks if `apiRef.current` is defined before calling its methods, which works. 

Separately, I also added a `Set` to store ids of selected countries, and hope the `Set.has()` method is more efficient than the `Array.find()` method I used before.

```
if (apiRef.current && typeof apiRef.current.getAllRowIds === 'function') {
         const allRowIds = apiRef.current.getAllRowIds();
         const selectedCountryIds = new Set(
            selectedCountries.map((country) => country.code || country.name),
         );

         allRowIds.forEach((rowId) => {
            if (!selectedCountryIds.has(rowId)) {
               if (
                  apiRef.current &&
                  typeof apiRef.current.updateRows === 'function'
               ) {
                  apiRef.current.updateRows([{ id: rowId, _action: 'delete' }]);
               }
            }
         });
      }
```

**Comment by michelengelen** [comment] 2024-01-11 08:31
Ok, that should work as well.

In the meantime I will close this. Feel free to reopen if there is something else we can help you with @hartmatt. Thanks! 🙇🏼

**Closed by michelengelen** 2024-01-11 08:31 UTC
Labels: component: data grid, status: waiting for maintainer, support: commercial, support: pro standard
