### ISSUE TITLE
I am looking for filtering field for each column. current dialog design is bad.

### ISSUE THREAD

**Issue by alexk345** [mui/mui-x#7150] opened 2022-12-08 22:14 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

My users  are simple minded people.  They need filter field under each column. do you have way to do it now? i searched i cant find.  i think bootstrap datatable has it. please add that feature . tks much.

**Comment by cherniavskii** [comment] 2022-12-09 10:31
Duplicate of https://github.com/mui/mui-x/issues/4934?

**Closed** 2022-12-16 11:17 UTC
Labels: component: data grid, status: needs more information, feature: Filtering
