### ISSUE TITLE
[pickers] some props from textField slotProps are ignored

### ISSUE THREAD

**Issue by aizerin** [mui/mui-x#9856] opened 2023-07-31 13:28 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/unruffled-leaf-8lskvp?file=/Demo.tsx

```jsx
import { DatePicker } from "@mui/x-date-pickers/DatePicker";

<DatePicker
          label="Basic date picker"
          slotProps={{
            textField: {
              // this is ok
              size: "small",
              // this is ignored
              InputProps: { endAdornment: <div>test</div> }
            }
          }}
/>
```

### Current behavior 😯

InputProps from textField slot are ignored

### Expected behavior 🤔

every prop from textField slot should be passed to TextField component. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment] 2023-07-31 13:53
I'm pretty sure that this is a duplicate of https://github.com/mui/mui-x/issues/9844.
Could you double-check if you are still experiencing this issue on a codesandbox from [the PR deployment](https://deploy-preview-9849--material-ui-x.netlify.app/x/react-date-pickers/date-picker/)? 🤔

**Comment by LukasTy** [comment] 2023-07-31 14:35
Thank you for the confirmation, closing as duplicate. 👌

**Closed by LukasTy** 2023-07-31 14:35 UTC
Labels: component: pickers
