### ISSUE TITLE
[data grid] Autosize columns with includeHeaders does not factor in icon widths

### ISSUE THREAD

**Issue by bwilzen-pilotdesk** [mui/mui-x#15854] opened 2024-12-11 20:46 UTC
### Steps to reproduce

Steps:
1. See Autosizing demo https://mui.com/x/react-data-grid/column-dimensions/#autosizing
2. Hover over Brand ID column

<img width="363" alt="Screenshot 2024-12-11 at 3 39 21 PM" src="https://github.com/user-attachments/assets/597b8973-b4f3-4ba0-b7c7-664ac73cd6ee" />

### Current behavior

When autosizing determines the width of a field it does not consider the width of the sorting icon or the menu icon.

### Expected behavior

Autosizing should factor in the width of the icons when applicable.  In fact the code seems to try to do it here https://github.com/mui/mui-x/blob/46c46ff829ed601387048d5da99d156967226980/packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx#L222

but it uses clientWidth (which is 0).  if scrollWidth is used, this would work as expected.

### Context

I want the column header text to be visible and not obscured by the icons when you hover over it

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.3.1
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.109
    Edge: Not Found
    Safari: 17.3.1
  npmPackages:
    @emotion/react:  11.11.4 
    @emotion/styled:  11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.16.4 
    @mui/icons-material:  5.16.4 
    @mui/lab:  5.0.0-alpha.172 
    @mui/material:  5.16.4 
    @mui/private-theming:  5.16.4 
    @mui/styled-engine:  5.16.4 
    @mui/system:  5.16.4 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.4 
    @mui/x-charts:  6.19.8 
    @mui/x-data-grid:  7.11.0 
    @mui/x-date-pickers:  6.20.2 
    @mui/x-internals:  7.11.0 
    @types/react:  18.3.3 
    react:  18.3.1 
    react-dom:  18.3.1 
    typescript:  5.5.3 
```
</details>

**Search keywords**: DataGrid Autosize includeHeaders

**Comment by k-rajat19** [comment] 2024-12-12 06:28
> ### Expected behavior
> Autosizing should factor in the width of the icons when applicable. In fact the code seems to try to do it here
> 
> https://github.com/mui/mui-x/blob/46c46ff829ed601387048d5da99d156967226980/packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx#L222
> 
> but it uses clientWidth (which is 0). if scrollWidth is used, this would work as expected.

Hi 
You can see the related discussion here https://github.com/mui/mui-x/pull/10666#discussion_r1358678677
there is one more similar issue opened https://github.com/mui/mui-x/issues/15388
I've already been working on how column header width is calculated in this PR https://github.com/mui/mui-x/pull/15292, I'll address these issues as well there.
As you also said, we can use `scrollWidth` here to consider the width of icons for both mobile (icons visible all times) and desktop(icons visible on hover or sort icon visible when sorting is applied ).
I'll let someone from the core team to decide whether we should use scroll width here or not

**Comment by michelengelen** [comment] 2024-12-12 11:20
Duplicate of #15388 

Thanks for pointing that out @k-rajat19 👍🏼

**Closed by michelengelen** 2024-12-12 11:20 UTC
Labels: bug 🐛, duplicate, component: data grid
