### ISSUE TITLE
[docs] Demo LocalizationDayjs crashes

### ISSUE THREAD

**Issue by n0c-turn3** [mui/mui-x#9591] opened 2023-07-06 09:46 UTC
- [ ] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20LocalizationDayjs%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-date-pickers/adapters-locale/
2. Click one of the options (EN, EN-GB, ZH-CN, DE) twice
3. demo *LocalizationDayjs* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.9.1  |
| Netlify deploy | https://649edb90afee2f0008fd1c66--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 |

**Comment by LukasTy** [comment] 2023-07-06 12:46
Duplicate of https://github.com/mui/mui-x/issues/9547.

**Closed by LukasTy** 2023-07-06 12:46 UTC
Labels: docs, status: needs triage, component: pickers
