### ISSUE TITLE
The `Add Filter` button is closing the filter panel instead of creating a new filter

### ISSUE THREAD

**Issue by nazariykcap** [mui/mui-x#6854] opened 2022-11-15 11:22 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://stackblitz.com/edit/react-bpkfmt?file=demo.tsx 
In the example filter panel state is already preconfigured, so you need just to open the filter panel and press `Add Filter`

Steps:
1. Open the Filter panel
2. Column to filter by - `Country` 
3. Operator  - `is any of`
4. Value - Choose not less than three of any countries 
5. Try to press `Add Filter`

### Current behavior 😯

The Filter panel will be closed and a row with a new filter won't be added. 

### Expected behavior 🤔

The row with a new filter should be added in the Filter panel. The Filter panel should not be closed.

### Context 🔦

The issue appeared when we tried manually to create and apply a set of filters. After creating a filter with `isAnyOf` operator and choosing at least three values the ability to add more filters disappears. By clicking on the `Add Filter` button, it is closed.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

39595

**Comment by cherniavskii** [comment] 2022-11-15 15:00
Looks like duplicate of https://github.com/mui/mui-x/issues/6213

**Closed** 2022-11-15 15:01 UTC
Labels: duplicate, component: data grid
