### ISSUE TITLE
[pickers] Integrating with `Formik`

### ISSUE THREAD

**Issue by erickbandinelli** [mui/mui-x#7250] opened 2022-12-19 13:13 UTC
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

Link: https://codesandbox.io/s/unruffled-orla-opbc94?file=/index.tsx

1. Create a datePicker and clear fields button
2. In the picker add the following code snippet
```
renderInput={(params) => (
        <TextField
          {...params}
          inputProps={{
            ...params.inputProps,
            // The formatDate is from the moment library
            value: value && formatDate(value)
          }}
          size={size}
          helperText={helperText}
          error={error}
          fullWidth={fullWidth}
        />
      )}
```
3. When you don't have input props, when you click on the button to clear the fields it doesn't clean the datepicker, but when you have the inputProps when typing the date it gives invalid date because it only works if you change it in the calendar.

### Current behavior 😯

1. Create a datePicker and clear fields button
2. In the picker add the following code snippet
```
renderInput={(params) => (
        <TextField
          {...params}
          inputProps={{
            ...params.inputProps,
            // The formatDate is from the moment library
            value: value && formatDate(value)
          }}
          size={size}
          helperText={helperText}
          error={error}
          fullWidth={fullWidth}
        />
      )}
```
3. When you don't have input props, when you click on the button to clear the fields it doesn't clean the datepicker, but when you have the inputProps when typing the date it gives invalid date because it only works if you change it in the calendar.

### Expected behavior 🤔

Regardless of whether it has inputProps or not, it needs to allow typing or choosing through the calendar.

### Context 🔦

Show a bug for the team to fix.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
  npmPackages:
    @emotion/react: ^11.7.0 => 11.10.0
    @emotion/styled: ^11.6.0 => 11.10.0
    @mui/base:  5.0.0-alpha.93
    @mui/core-downloads-tracker:  5.10.1
    @mui/icons-material: ^5.2.0 => 5.8.4
    @mui/material: ^5.2.2 => 5.10.1
    @mui/private-theming:  5.9.3
    @mui/styled-engine:  5.10.1
    @mui/styles: ^5.2.2 => 5.9.3
    @mui/system:  5.10.1
    @mui/types:  7.1.5
    @mui/utils:  5.9.3
    @mui/x-date-pickers: ^5.0.0-alpha.5 => 5.0.0-beta.6
    @types/react:  18.0.17
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ^5.3.3 => 5.3.5
```
</details>

**Comment by LukasTy** [comment] 2022-12-19 13:49
Hello @erickbandinelli 
Could you explain what is your end goal you are trying to achieve with `inputProps`?
From what I can understand using your snippets (live code example—like codesandbox would be better) it seems that everything is working as intended.
You are trying to format input value into date, but it will always result in `Invalid date` if you provide it a string with invalid date. I.e. You type `2`, which get's passed to `formatDate` and it clearly is not a valid date.

If my guess is correct and you just want to change the format you want the date to be visible/inserted in—[consider using `inputFormat` prop](https://codesandbox.io/s/distracted-worker-gte2vn?file=/demo.tsx).

**Comment by erickbandinelli** [comment] 2022-12-19 13:52
I'll create a codesandbox and send the link

**Comment by erickbandinelli** [comment] 2022-12-19 14:42
@LukasTy This is the problem when I have inputProps it occurs this NaN and this other problem in the calendar. 

https://codesandbox.io/s/unruffled-orla-opbc94?file=/demo.tsx

**Comment by erickbandinelli** [comment] 2022-12-19 14:50
> Hello @erickbandinelli Could you explain what is your end goal you are trying to achieve with `inputProps`? From what I can understand using your snippets (live code example—like codesandbox would be better) it seems that everything is working as intended. You are trying to format input value into date, but it will always result in `Invalid date` if you provide it a string with invalid date. I.e. You type `2`, which get's passed to `formatDate` and it clearly is not a valid date.
> 
> If my guess is correct and you just want to change the format you want the date to be visible/inserted in—[consider using `inputFormat` prop](https://codesandbox.io/s/distracted-worker-gte2vn?file=/demo.tsx).


@LukasTy This is the problem when I have inputProps it occurs this NaN and this other problem in the calendar. 

I have this inputProps because I have a clear button that only clears the datePicker if it has this inputProps this could also be another error in the datepicker that would be worth looking into.

https://codesandbox.io/s/unruffled-orla-opbc94?file=/demo.tsx

**Comment by erickbandinelli** [comment] 2022-12-19 15:02
> Você poderia confirmar o resultado que está tentando alcançar mais uma vez? Ou você só queria nos informar que permitimos erroneamente `value`ser via `inputProps`, o que interrompe o comportamento do componente?

The issue is that when the onChange occurs from typing in the field and having the InputProps as it is in the codesandbox, a NaN occurs and this needs to be corrected so that when typing, the typed date appears.

**Comment by erickbandinelli** [comment] 2022-12-19 15:03
> Could you confirm the result you are trying achieve once again? Or did you only want to let us know, that we mistakenly allow `value` to be via `inputProps`, which breaks the component behaviour?

The issue is that when the onChange occurs from typing in the field and having the InputProps as it is in the codesandbox, a NaN occurs and this needs to be corrected so that when typing, the typed date appears.

**Comment by LukasTy** [comment] 2022-12-19 15:08
> The issue is that when the onChange occurs from typing in the field and having the InputProps as it is in the codesandbox, a NaN occurs and this needs to be corrected so that when typing, the typed date appears.

Simply replacing `renderInput` with:
```diff
- renderInput={(params) => (
-   <TextField
-     {...params}
-     inputProps={{
-       ...params.inputProps,
-       value: date || ""
-     }}
-   />
- )}
+ renderInput={(params) => <TextField {...params} />}
```
resolves your issue. That's why I'm asking what are you trying to achieve passing custom `value` to the input, when it's is actually the components job to correctly handle it?

**Comment by erickbandinelli** [comment] 2022-12-19 15:12
> > The issue is that when the onChange occurs from typing in the field and having the InputProps as it is in the codesandbox, a NaN occurs and this needs to be corrected so that when typing, the typed date appears.
> 
> Simply replacing `renderInput` with:
> 
> ```diff
> - renderInput={(params) => (
> -   <TextField
> -     {...params}
> -     inputProps={{
> -       ...params.inputProps,
> -       value: date || ""
> -     }}
> -   />
> - )}
> + renderInput={(params) => <TextField {...params} />}
> ```
> 
> resolves your issue. That's why I'm asking what are you trying to achieve passing custom `value` to the input, when it's actually the components job to correctly handle it?

Yes, this solves it in parts, then it generates another bug, which is that I have a button to clean the datepicker that only works if I pass the InputProps to the datePicker, that is, we are back to this error that I cannot type when I have the InputProps

```
renderInput={(params) => (
        <TextField
          {...params}
          inputProps={{
            ...params.inputProps,
            value: value && formatDate(value)
          }}
           />
      )}
```

**Comment by LukasTy** [comment] 2022-12-19 15:32
@erickbandinelli 
Was your final result [something along these lines](https://codesandbox.io/s/winter-firefly-6brthy?file=/demo.tsx)? 🤔

**Comment by erickbandinelli** [comment] 2022-12-19 16:41
> @erickbandinelli Was your final result [something along these lines](https://codesandbox.io/s/winter-firefly-6brthy?file=/demo.tsx)? 🤔

I updated the codesandbox https://codesandbox.io/s/unruffled-orla-opbc94?file=/index.tsx

**Comment by LukasTy** [comment] 2022-12-20 13:55
Hello @erickbandinelli 
Here is [an updated codesandbox](https://codesandbox.io/s/pickers-formik-741013) working without issues. 😉 
You only needed to pass correct initial value of `null` instead of empty string.
If it solves your issue—please close it. 👍

**Closed** 2023-01-13 14:12 UTC
Labels: component: pickers
