### ISSUE TITLE
[DatePicker] Pressing ESC doesn't close DatePicker if it is in a Dialog

### ISSUE THREAD

**Issue by ywongau** [mui/mui-x#4366] opened 2022-03-18 02:26 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When DatePicker is inside a Dialog, pressing ESC doesn't close it

As a result, there is no way to close dialog with the keyboard without changing the day

### Expected behavior 🤔

Pressing ESC closes the DatePicker

### Steps to reproduce 🕹

Steps:

1. Put DatePicker in a Dialog
2. Open DatePicker
3. Press ESC key
4. DatePicker doesn't close

### Context 🔦

This is a fork of the official example that puts all pickers inside a dialog

https://codesandbox.io/s/materialuipickers-material-demo-forked-n6xjtg?file=/demo.js

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment] 2022-04-15 10:10
This is a duplicate of #4489

I close it to avoid duplicates. Should be solved by the same PR

**Closed by alexfauquette** 2022-04-15 10:10 UTC
Labels: bug 🐛, duplicate, component: date picker
