### ISSUE TITLE
Row selection has a slight delay

### ISSUE THREAD

**Issue by LeonSa2404** [mui/mui-x#8880] opened 2023-05-05 09:37 UTC
### Order ID or Support key 💳 (optional)

65695

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

When selecting a row there is a slight delay between clicking the row and the checkbox getting checked. It looks like there is an animation between the two events. Is it possible to speed this up?
I don't think this is a performance issue, because if I display 100 rows instead of 10 the selection only seems to get a tiny bit slower.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 112.0.5615.50
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.68)

Browser: Chrome
</details>

**Comment by cherniavskii** [comment] 2023-05-05 19:05
Hi @LeonSa2404 
Can you see this delay on the recording below?

https://user-images.githubusercontent.com/13808724/236547789-2510cbc4-6d43-4cac-98ce-622bef43d37e.mov

**Comment by LeonSa2404** [comment] 2023-05-08 07:04
Hi,
my delay seems to be a bit more. It is hard to see when selecting but you can clearly see it when deselecting. This is with 29 rows:

https://user-images.githubusercontent.com/63504232/236756067-321dbc3f-1456-4677-8529-143c279ae402.mp4

This is my grid:
```
                                  <DataGridPremium
                                      getRowId={(row) => row.ID}
                                      getRowClassName={getRowClassname}
                                      rows={jobData}
                                      columns={muiColumns}
                                      checkboxSelection
                                      isRowSelectable={(params) =>
                                          params.id
                                              .toString()
                                              .indexOf(
                                                  'auto-generated-row'
                                              ) === -1
                                      }
                                      onRowSelectionModelChange={(
                                          newSelectionModel
                                      ) =>
                                          setSelectionModel(newSelectionModel)
                                      }
                                      rowSelectionModel={selectionModel}
                                      apiRef={apiRef}
                                      density={pagePreferences.rowDensity}
                                      loading={isLoading}
                                      components={{
                                          LoadingOverlay:
                                              DataLoadingAnimation,
                                          NoRowsOverlay: NoDataIndicator,
                                      }}
                                  />
```

**Comment by cherniavskii** [comment] 2023-05-08 11:44
@LeonSa2404 I cannot reproduce it even with 1k rows: https://codesandbox.io/s/mutable-pond-c8hif0?file=/demo.tsx
What version of the data grid are you using?

Can you create a reproduction example of the issue? We need this to be able to investigate it.

**Comment by LeonSa2404** [comment] 2023-05-09 09:45
@cherniavskii Thanks for trying. I am using the latest version of the grid. I just deployed the website to my server and the selection is as fast as in your video. So apparently the delay is caused by my developement enviroment.

**Comment by cherniavskii** [comment] 2023-05-09 10:47
> I just deployed the website to my server and the selection is as fast as in your video. So apparently the delay is caused by my developement enviroment.

Good to hear that it works fine in production!
Closing the issue for now, as there are no actions for us to take.

**Closed by cherniavskii** 2023-05-09 10:47 UTC
Labels: component: data grid, plan: Premium, support: commercial
