### ISSUE TITLE
[core] @mui/x-date-pickers has a peer dependency on both material and system

### ISSUE THREAD

**Issue by pongells** [mui/mui-x#11117] opened 2023-11-21 10:16 UTC
### Steps to reproduce

Link to live example: 

https://github.com/mui/mui-x/blob/81a58020058832592c618c25f67581322831320e/packages/x-date-pickers/package.json#L55-L59

Is this intentional? 

Considering that `@mui/material` already exports `@mui/system`, why do I have to add both to my package.json? feels like a mistake..

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: x-date-pickers peerDependencies

**Comment by michelengelen** [comment] 2023-11-21 10:35
@flaviendelangle could you give a bit of context for this? Thanks! 🙇🏼

**Comment by LukasTy** [comment] 2023-11-21 12:12
As it currently stands, we have both `material` and `system` as peer dependencies, whereas the `base` and `utils` are direct dependencies.
IMHO, it doesn't really make much sense, because the package can not function without `material` and `system` packages same as it can't without the `base` and `utils`.
Was there any logical reason to make the former `peer` dependencies @flaviendelangle @oliviertassinari?

I do understand that in the future, they might become `optional` dependencies, but until then, what reason do we have to keep them as `peer` instead of direct? 🤔 
The only thing I can think of is that by doing this we allow users to keep using an older `material` version with the latest Pickers version if they are using exact dependency versions (i.e. `5.14.18` vs `^5.14.18`).

**Comment by oliviertassinari** [comment] 2023-11-21 12:15
A duplicate of #10427?

**Comment by flaviendelangle** [comment] 2023-11-21 12:18
I don't know the reasons for this choice :+1:

**Comment by LukasTy** [comment] 2023-11-21 12:22
> A duplicate of #10427?

Thanks for pointing it out.
Closing this one as duplicate then. 👌

**Closed by LukasTy** 2023-11-21 12:22 UTC
Labels: core, component: pickers
