### ISSUE TITLE
[DataGrid] Please upgrade `reselect` to `^5.0.1` to be the same as in `@reduxjs/toolkit`

### ISSUE THREAD

**Issue by Semigradsky** [mui/mui-x#11381] opened 2023-12-12 10:00 UTC
### Motivation 🔦

For having one version in bundle

**Search keywords**: datagrid reselect

**Comment by michelengelen** [comment] 2023-12-12 12:57
@cherniavskii not sure if this would include a BC. Please feel free to assign to the v7 project if it does. Thanks 🙇🏼

**Comment by flaviendelangle** [comment] 2023-12-13 14:09
If we did that on our package, would it work?

```json
"dependencies": {
  "reselect": "^4.1.8 || ^5.0.1"
}
```

For me it would solve the problem **IF** we are not impacted by the BCs (https://github.com/reduxjs/reselect/releases)

**Comment by cherniavskii** [comment] 2023-12-13 19:37
We are impacted by the breaking changes.
I don't foresee any breaking changes for our users caused by the `reselect` upgrade.

One notable change is that the default memoization function for selectors has changed, we should be careful with this and check the performance impact of such a change since we use selectors a log 🙂
Anyway, we can do this in v7.

**Comment by egazarian** [comment] 2024-02-21 11:19
I'm trying to migrate to RTK 2.0, but I'm getting this error `The inferred type of 'x' cannot be named without a reference to '@reduxjs/toolkit/node_modules/reselect'. This is likely not portable. A type annotation is necessary.` I think it's due to multiple versions of Reselect in the same project. (5.x.x from RTK 2.O and 4.x.x from mui-x/datagrid).

@Semigradsky, do you have the same error?

**Comment by cherniavskii** [comment] 2024-09-11 21:15
Closed by https://github.com/mui/mui-x/pull/11367

**Closed by cherniavskii** 2024-09-11 21:15 UTC
Labels: dependencies, component: data grid
