### ISSUE TITLE
Bug Scroll Page on mobile devices when there are charts

### ISSUE THREAD

**Issue by YonderUrik** [mui/mui-x#15458] opened 2024-11-17 21:55 UTC
### Steps to reproduce

Steps:
1. Open every kind of browser on mobile
2. Try to scroll the page in horizontal or vertical, resting the finger on the chart 

### Current behavior

If you scroll the page from a mobile device, resting your finger on the chart, the scroll gets stuck.

### Expected behavior

 Instead it should allow the page to scroll or any kind of active overflow

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
  Binaries:
    Node: 18.20.5 - ~/.nvm/versions/node/v18.20.5/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v18.20.5/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.20
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: ^5.15.20 => 5.15.20
    @mui/material-nextjs: ^5.15.11 => 5.15.11
    @mui/private-theming:  5.15.20
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.20
    @mui/types:  7.2.19
    @mui/utils:  5.15.20
    @mui/x-charts: ^7.22.2 => 7.22.2
    @mui/x-charts-vendor:  7.20.0
    @mui/x-data-grid: ^7.7.0 => 7.7.0
    @mui/x-date-pickers: ^7.7.0 => 7.7.0
    @mui/x-internals:  7.21.0
    @mui/x-tree-view: ^7.7.0 => 7.7.0
    @types/react: ^18.3.3 => 18.3.3
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript: ^5.4.5 => 5.4.5
</details>

**Search keywords**: scroll bug charts

**Comment by alexfauquette** [comment] 2024-11-18 08:48
I think it's a duplicate of #13885

**Comment by YonderUrik** [comment] 2024-11-18 11:45
> I think it's a duplicate of #13885

Oh yes, sorry i haven't seen. Should i close the iusse report?

**Closed** 2024-11-18 11:46 UTC
Labels: bug 🐛, component: charts
