### ISSUE TITLE
[DatePicker]: can't change month when views=['year', 'month'] at certain screen sizes

### ISSUE THREAD

**Issue by karendelakaren** [mui/mui-x#10433] opened 2023-09-22 15:26 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/upbeat-bell-z4zjly?file=/Demo.tsx

Steps:
1. Browser window needs to be set to a size where the year picker doesn't fit underneath the second datepicker but the month picker would. (My codesandbox browser window is 697px high)
2. The `format` prop is set to `MM/YYYY`
3. The `view` prop is set to `["year", "month"]`
4. You click on the second date picker and try to choose a new date where the month is different than the current/default month
5. The first date picker does work, it's really about its position on the page

### Current behavior 😯

The month picker is first shown above the field. When you try to click the month the picker shows for a moment underneath the field, then closes, without having changed the month. 

### Expected behavior 🤔

Should be able to change the month no matter my screen size and the space above/below the picker. 

### Your environment 🌎

```
  Browser 
  Google Chrome for Mac - Version 116

 Package
  "@mui/x-date-pickers": "^6.14.0",
```

**Comment by michelengelen** [comment] 2023-09-26 08:29
@LukasTy Could you have a look at this?

I just tested it and could verify that the month popover does flicker to the bottom view before closing without accepting the changed value.

https://github.com/mui/mui-x/assets/32863416/acdbc343-35c9-431a-bc51-993e62528276

**Comment by LukasTy** [comment] 2023-09-26 08:34
@michelengelen Closing this issue as a duplicate of https://github.com/mui/mui-x/issues/5490 that we have already put in our to-do board. 👍

**Closed by LukasTy** 2023-09-26 08:34 UTC
Labels: bug 🐛, component: pickers, component: DatePicker

**Comment by michelengelen** [comment] 2023-09-26 08:35
Thanks @LukasTy! 👍🏼
