### ISSUE TITLE
[pickers][DateRangePicker] support selecting months and years

### ISSUE THREAD

**Issue by aelkadah** [mui/mui-x#13124] opened 2024-05-13 14:05 UTC
### Summary

I want to make Year title and month Title selectable in the header of DateRangePicker component in react-mui

### Examples
![Screenshot 2024-05-13 170635](https://github.com/mui/material-ui/assets/73890344/a1072e51-9ecc-4d58-84da-7d37ff829379)

**Search keywords**: DateRangePicker

**Search keywords**:

**Comment by michelengelen** [comment] 2024-05-14 11:02
Hey @aelkadah 
what is it you want to achieve?
Do you want to include a `Select` component as a replacement for the Month / Year title in the DatePicker component?
Please add a more detailed description of your use case!
thanks!

**Comment by flaviendelangle** [comment] 2024-05-14 13:39
Looks like a duplicate of #4546

**Comment by aelkadah** [comment] 2024-05-14 19:22
> Hey @aelkadah what is it you want to achieve? Do you want to include a `Select` component as a replacement for the Month / Year title in the DatePicker component? Please add a more detailed description of your use case! thanks!

Hi, Yes I want to make year and month clickable so when clicking on them I choose from list of months or years like in DatePicker component after using views={['year', 'month', 'day']}

**Comment by aelkadah** [comment] 2024-05-14 19:29
> Looks like a duplicate of #4546

Hi @flaviendelangle but I don't see a direct react-mui solution in this thread can you help me more simply

**Comment by flaviendelangle** [comment] 2024-05-15 05:47
> Hi @flaviendelangle but I don't see a direct react-mui solution in this thread can you help me more simply

Sorry, my answer wasn't clear

We don't support this feature yet, the issue I linked is the one referring to the feature you are asking for.
You can implement something using a custom [CalendarHeader](https://mui.com/x/react-date-pickers/custom-components/#calendar-header), but this will be a very heavy customization.

**Comment by flaviendelangle** [comment] 2024-05-15 06:42
I don't think anybody tried an implementation with `CalendarHeader` yet
You have example on the doc on how to create a custom header but we don't have an example with the use-case you are looking for.

**Comment by michelengelen** [comment] 2024-05-15 10:17
I guess this can be closed for now.
Thanks for raising an issue here @aelkadah ... and sry that we cannot provide you with hand tailored solution for your use-case.

**Closed by michelengelen** 2024-05-15 10:17 UTC
Labels: support: question, status: waiting for maintainer, component: pickers, customization: extend, enhancement
