### ISSUE TITLE
[data grid] Data grid Master detail scrolling issue

### ISSUE THREAD

**Issue by serche** [mui/mui-x#6502] opened 2022-10-14 09:38 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After I have expanded first row and scrolled down I cant return back to the first row

### Expected behavior 🤔

I'm able to scroll without issues

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/crazy-dew-fxxh6h

Steps:
1. Expand first row
2. Scroll down to the end
3. Try to scroll up to the first row

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by psigns** [comment] 2022-10-14 15:04
This looks like another duplicate of #6378

**Comment by cherniavskii** [comment] 2022-10-17 14:44
Indeed, duplicate of https://github.com/mui/mui-x/issues/6378

**Closed by cherniavskii** 2022-10-17 14:44 UTC
Labels: component: data grid, status: needs triage, feature: Master-detail
