### ISSUE TITLE
[fields]  `autoFocus` is not working as expected

### ISSUE THREAD

**Issue by eglitobias** [mui/mui-x#8329] opened 2023-03-22 09:10 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/kuf37c?file=/demo.js

Steps:

1. Reload the Page
2. Type a Date
3. Nothing happens

### Current behavior 😯

If I set the autoFocus on a DatePicker it selects the whole Date. I cannot directly type in a Date. I have to click on the Arrow Left Key first.
Thats how it looks if you open a DatePicker with autoFocus (Bad):
<img width="270" alt="Screenshot 2023-03-22 at 10 03 39" src="https://user-images.githubusercontent.com/88370686/226853668-f51bb150-1b4c-47aa-950d-e96cd0ce58eb.png">

This is how it looks if you Tab or click in a Date Picker Field (Good):
<img width="270" alt="Screenshot 2023-03-22 at 10 03 45" src="https://user-images.githubusercontent.com/88370686/226853591-1835c4d3-b681-4a05-9ea3-a3fe0aa11b67.png">

### Expected behavior 🤔

If the autoFocus is set on a Date Picket It must be possible to enter a date directly on the keyboard without pressing the arrow keys first.

### Your environment 🌎

"@mui/x-date-pickers": "^6.0.2",

**Comment by flaviendelangle** [comment] 2023-03-22 10:04
Hi,

Thanks for your reproduction case
We have one clear bug: when you select all sections (can be caused by `autoFocus`, navigating with <kbd>Tab</kbd> or using Ctrl + A), the editing is broken.

I'll do a quick fix for this one, it should edit the 1st section:

https://user-images.githubusercontent.com/3309670/226868832-bd5ac30e-aa71-4bb0-8d85-9648ddcfbd9c.mp4


____

As for which sections should be select when focusing the field ?
I went for the "select all" option because it is how regular input works.
But the native date input only selects the 1st section.

@LukasTy any opinion here ?

**Comment by LukasTy** [comment] 2023-03-22 10:54
> LukasTy any opinion here?

IMHO, we could focus only the first section, just for the sake of consistency if and when we eventually refactor to use multiple "spinbutton" elements for sections instead of an input. 🤔

**Closed** 2023-03-28 09:14 UTC
Labels: bug 🐛, component: pickers, feature: Keyboard editing
