### ISSUE TITLE
[data grid] Missing optional peer dependencies

### ISSUE THREAD

**Issue by kris7t** [mui/mui-x#12566] opened 2024-03-26 15:50 UTC
### Steps to reproduce

I can't provide a link to a live example, since the problem stems from the build process itself.

Steps:

1. Use Yarn as a package manager with PnP resolution.
2. Install `@mui/x-data-grid@7.0.0` or any other package with a direct dependency on `@mui/system`.
3. Use `@emotion/react` to style your application.

### Current behavior

Bundling of the application fails, since the optional peer dependency on `@emotion/react` and `@emotion/styled` is no longer resolved in `@mui/system`.

The problem stems from Yarn's dependency isolation, or rather, from MUI-X not declaring enough optional peer dependencies and accidentally forcing Yarn to isolate `@mui/system` from its optional peer dependencies: Yarn PnP sees that `@mui/system` is referenced in a context where its peer dependencies cannot be met, as ``@mui/x-data-grid` doesn't declare them as peer dependencies. Since these peer dependencies are optional, they are silently left unresolved.

### Expected behavior

Bundling the application when `@mui/x-data-grid@6.19.8 is installed succeeds, since that release doesn't contain https://github.com/mui/mui-x/pull/11128. When `@mui/system` is declared as a peer dependency, the resolution of its optional peer dependencies is unaffected.

The resolution should work similarly for `@mui/x-data-grid` (and other MUI-X packages). Either it should re-declare the transitive optional peer dependencies of `@mui/system` (so that they can be also resolved in the context of `@mui/x-data-grid` whenever available), or https://github.com/mui/mui-x/pull/11128 should be reverted to let Yarn resolve `@mui/system` as a peer dependency.

### Context

I'm trying to build an application using with Vite as the bundler/build tool and Yarn 4 PnP as the package manager.

The following workaround in `.yarnrc.yml` works by declaring the peer dependencies (as non-optional ones) explicitly:

```
packageExtensions:
  "@mui/x-data-grid@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
      "@types/react": "*"
```

### Your environment

```
  System:
    OS: Linux 6.8 Arch Linux
  Binaries:
    Node: 20.11.1
    npm: 10.2.4
    pnpm: 8.15.5
    yarn 4.1.1
    vite 5.2.6
```

**Search keywords**: peer dependency, emotion, yarn, pnp

**Comment by michelengelen** [comment] 2024-03-27 15:17
@LukasTy could you have a look, since this is related to your recent PR?

**Comment by LukasTy** [comment] 2024-08-06 13:25
@mui/xgrid isn't this a duplicate of https://github.com/mui/mui-x/issues/13304 and https://github.com/mui/mui-x/issues/14114?
Other packages already declare `@emotion/react` and `@emotion/styled` as `peerDependencies`, it looks like only Data Grid packages are missing it. 🙈

**Comment by cherniavskii** [comment] 2024-08-06 17:58
Closing in favor of https://github.com/mui/mui-x/issues/14114

**Closed by cherniavskii** 2024-08-06 17:58 UTC
Labels: component: data grid, regression
