### ISSUE TITLE
[pickers] Problems after update to date-fns 3.0.1

### ISSUE THREAD

**Issue by Tockra** [mui/mui-x#11470] opened 2023-12-20 09:20 UTC
### Steps to reproduce

Example:
```ts
import { DatePicker, LocalizationProvider } from '@mui/x-date-pickers';
import { useTranslation } from 'next-i18next';
import { FC } from 'react';
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
import { de } from 'date-fns/locale';

type DatePickerInputProps = {};

export const DatePickerInput: FC<DatePickerInputProps> = props => {

    return (
        <LocalizationProvider adapterLocale={de} dateAdapter={AdapterDateFns}>
            <DatePicker
            // stuff
            />
        </LocalizationProvider>
    );
};

```

Before the update the following code worked. After the update it results in :
```bash
MyName@MyPc myProject % npm run build

> @devias/material-kit-pro-react@5.0.2 build
> next build

   Linting and checking validity of types  ..Failed to compile.

./mypath/date-picker.tsx:30:31
Type error: Property 'enUS' is missing in type 'Locale' but required in type 'typeof import("/Users/MyName/myProject/node_modules/date-fns/locale/en-US")'.

  28 |
  29 |     return (
> 30 |         <LocalizationProvider adapterLocale={de} dateAdapter={AdapterDateFns}>
     |                               ^
  31 |             <DatePicker
  32 |                 sx={{ mt: 3 }}
  33 |                 label={t('invoices.edit.invoiceDate')}
```

### Your environment

<details>

```
  System:
    OS: macOS 14.2
  Binaries:
    Node: 21.4.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 120.0.6099.109
    Edge: Not Found
    Safari: 17.2
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.1 
    @emotion/styled: ^11.10.6 => 11.11.0 
    @mui/base:  5.0.0-beta.28 
    @mui/core-downloads-tracker:  5.15.1 
    @mui/icons-material: ^5.14.3 => 5.15.1 
    @mui/material: ^5.11.15 => 5.15.1 
    @mui/private-theming:  5.15.1 
    @mui/styled-engine:  5.15.1 
    @mui/system: ^5.11.15 => 5.15.1 
    @mui/types:  7.2.11 
    @mui/utils:  5.15.1 
    @mui/x-date-pickers: ^6.12.1 => 6.18.5 
    @types/react: ^18.0.32 => 18.2.45 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.0.3 => 5.3.3 
```
</details>

**Search keywords**: date-fns

**Comment by michelengelen** [comment] 2023-12-20 09:33
duplicate of #11454

**Comment by Tockra** [comment] 2023-12-20 10:37
I'm not sure if #11454 covers the above problem. I have a different error message. But it's clearly caused by compatibility problems ...

**Comment by michelengelen** [comment] 2023-12-21 08:05
> I'm not sure if #11454 covers the above problem. I have a different error message. But it's clearly caused by compatibility problems ...

Yes it is... we are currently discussing how we can support the new major, so for now please use `date-fns@^2.25.0` for your project.

**Closed by michelengelen** 2023-12-21 08:05 UTC
Labels: duplicate, external dependency, component: pickers
