### ISSUE TITLE
[pickers] Calendar UI bug when using dayjs and it's daylight savings

### ISSUE THREAD

**Issue by giavinh79** [mui/mui-x#12463] opened 2024-03-15 15:10 UTC
### Steps to reproduce

https://stackblitz.com/edit/react-smshgm-ywvhu3?file=Demo.tsx

Steps:
1. Set local timezone to EST
2. Set `dayjs` timezone to a timezone behind EST
3. Open `dayjs` calendar in March

### Current behavior

When the dayjs timezone (in this case, set to `US/Arizona` in the sandbox) is behind the local timezone, the March calendar for the `DatePicker` component has some UI issues (there are two dates labeled the 9th, the spacing is odd, and the first couple of days are labeled incorrectly).

<img width="532" alt="image" src="https://github.com/mui/mui-x/assets/24909563/a18001be-3ed3-496d-b9f4-4d8d437e4080">

### Expected behavior

This issue cannot be reproduced using the `moment` adapter (the bottom calendar) which has the expected behaviour.

<img width="526" alt="image" src="https://github.com/mui/mui-x/assets/24909563/fe5da3d1-0cbd-46a0-bb5c-8c3b753c84b9">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: dayjs, datepicker, daylight savings, timezones

**Comment by alexfauquette** [comment] 2024-03-19 14:17
Thanks for reporting this. I'm closing because it's a duplicate of #10584

A PR has been open 2 weeks ago to work on this topic, please follow the other issue to get news about the fix

**Closed by alexfauquette** 2024-03-19 14:17 UTC
Labels: duplicate, component: pickers
