### ISSUE TITLE
[pickers][Datepicker] "onChange" event not triggered when selecting the same date

### ISSUE THREAD

**Issue by NaveenTFI** [mui/mui-x#13489] opened 2024-06-15 04:47 UTC
### Steps to reproduce

Link to live example: (required)

1. Open the DatePicker component.
2. Select a date (e.g., June 15).
3. Select the same date again (June 15).
4. Observe that the `onChange` event is not triggered.

https://github.com/mui/mui-x/assets/156289174/33c86cf1-0109-4941-ae0d-446ea6c7b261

### Current behavior

I am using the MUI DatePicker component. When I select a year and month, the `onChange` event triggers properly. However, when I select the same date as the previously selected date, the `onChange` event does not trigger. Selecting a different date triggers the `onChange` event correctly.

## Expected Behavior

The `onChange` event should be triggered even when selecting the same date as the previously selected date.

### Context

I am using the MUI DatePicker component. When I select a year and month, the `onChange` event triggers properly. However, when I select the same date as the previously selected date, the `onChange` event does not trigger. Selecting a different date triggers the `onChange` event correctly.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

## Environment

- MUI Version: "@mui/lab": "^5.0.0-alpha.76",
- Browser: Chrome
- Operating System: Windows 11

**Search keywords**: Datepicker onChange event not triggered when selecting the same date

**Comment by michelengelen** [comment] 2024-06-15 07:53
This is a duplicate of #12903

**Closed by michelengelen** 2024-06-15 07:53 UTC
Labels: duplicate, component: pickers, component: date picker
