### ISSUE TITLE
[DataGrid] Filtering with `0`

### ISSUE THREAD

**Issue by mouhaddou** [mui/mui-x#3374] opened 2021-12-07 14:53 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when i try to filter a column using filter feature of mui datagrid the results with value = 0 not appearing.
https://codesandbox.io/s/datagrid-quick-start-forked-1r5g5?file=/src/App.tsx 
try to filter by column3 enter 0 as value.

### Expected behavior 🤔

to return 2 records

### Steps to reproduce 🕹

Steps:
https://codesandbox.io/s/datagrid-quick-start-forked-1r5g5?file=/src/App.tsx
1. filter column3 
2.enter 0
3.  no result found 
4.

### Context 🔦

dev

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment] 2021-12-08 09:19
Hi, @mouhaddou thanks for raising this! 

I checked the reproduction you provided and maybe I'm missing something but there is no column 3 there. Can you update it with the correct data set so we can reproduce the issue?

**Comment by mouhaddou** [comment] 2021-12-08 09:37
just added it can you check please?

**Comment by DanailH** [comment] 2021-12-08 10:22
Thanks, @mouhaddou. Ah ok, I see what the issue is. It's because you are using numbers as values but the column type is the default one. Making `col3` as `type: 'number'` fixes your issue. You can check it here https://codesandbox.io/s/datagrid-quick-start-forked-2qykr?file=/src/App.tsx. Hope that fixes your problem.

**Comment by alexfauquette** [comment] 2021-12-08 10:39
What you propose is to create a `type="amount"` which extends type "number" and implements `valueGetter`/`valueSetter` to convert from string to number. Such as data are stored by using string, and the end-user sees filtering/sorting as if it is numbers?

**Comment by mouhaddou** [comment] 2021-12-08 11:08
thanks for your collaboration:
the issue is fixed by : 
1- upgrade  @material-ui/data-grid": "4.0.0-alpha.37 to  "@mui/x-data-grid": "^5.0.0-beta.4", 
2- add type:"number" as suggested by @DanailH

**Comment by flaviendelangle** [comment] 2021-12-08 11:11
The bug was fixed in #2528, released in `5.0.0-beta.0`
In `5.0.0-beta.7` you have another fix concerning the filtering of nullish values on the number columns :+1:

**Comment by DanailH** [comment] 2021-12-08 11:49
> What you propose is to create a `type="amount"` which extends type "number" and implements `valueGetter`/`valueSetter` to convert from string to number. Such as data are stored by using string, and the end-user sees filtering/sorting as if it is numbers?

Yes

**Comment by m4theushw** [comment] 2021-12-08 14:03
I don't think that adding a new column type only to pass a default value parser / value setter is worth. Users can do that when configuring the column definition. The same problem would occur with the `boolean` column if the value is "Y" or "N", instead of `true` and `false`.

**Comment by DanailH** [comment] 2021-12-09 09:52
Maybe I'm missing something but with the value parser / setter you will still need to convert from number to string or vice versa. What if I want the option of having the column type as `string` but get the filter options of a `number` column type?

**Comment by flaviendelangle** [comment] 2021-12-09 09:53
Could the number filter operators handle string out of the box ?

**Comment by DanailH** [comment] 2021-12-09 09:54
> Could the number filter operators handle string out of the box ?

But then how would we know when to display the `string` filters and when to display the `number`?

**Comment by m4theushw** [comment] 2021-12-09 13:09
> Could the number filter operators handle string out of the box ?

@flaviendelangle They are supposed to handle strings: https://github.com/mui-org/material-ui-x/blob/986900e5cb443df2fd72d0999ad1f3d2c1d4e2c7/packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts#L10

**Comment by oliviertassinari** [comment] 2021-12-11 14:45
I'm not sure I understand the direction the conversation is going in. From my perspective, this issue is a bug with the column type **string** when the value is `0`. If the column type is a string, then it should handle the cells as if they were strings, doing type casting if necessary.

In the reproduction, we can filter with `'1'` ✅  but not `'0'` ⛔ . Take this as an example: https://plnkr.co/edit/aawqy6NNtMU5wo16. I think that they do it right.

I would propose this fix:

```diff
diff --git a/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts b/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
index 3c72cc60..274b206d 100644
--- a/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
+++ b/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
@@ -13,7 +13,7 @@ export const getGridStringOperators = (): GridFilterOperator[] => [

       const filterRegex = new RegExp(escapeRegExp(filterItem.value), 'i');
       return ({ value }): boolean => {
-        return filterRegex.test((value && value.toString()) || '');
+        return value != null ? filterRegex.test(value.toString()) : false;
       };
     },
     InputComponent: GridFilterInputValue,
@@ -26,7 +26,7 @@ export const getGridStringOperators = (): GridFilterOperator[] => [
       }
       const collator = new Intl.Collator(undefined, { sensitivity: 'base', usage: 'search' });
       return ({ value }): boolean => {
-        return collator.compare(filterItem.value, (value && value.toString()) || '') === 0;
+        return value != null ? collator.compare(filterItem.value, value.toString()) === 0 : false;
       };
     },
     InputComponent: GridFilterInputValue,
@@ -40,7 +40,7 @@ export const getGridStringOperators = (): GridFilterOperator[] => [

       const filterRegex = new RegExp(`^${escapeRegExp(filterItem.value)}.*$`, 'i');
       return ({ value }): boolean => {
-        return filterRegex.test((value && value.toString()) || '');
+        return value != null ? filterRegex.test(value.toString()) : false;
       };
     },
     InputComponent: GridFilterInputValue,
@@ -54,7 +54,7 @@ export const getGridStringOperators = (): GridFilterOperator[] => [

       const filterRegex = new RegExp(`.*${escapeRegExp(filterItem.value)}$`, 'i');
       return ({ value }): boolean => {
-        return filterRegex.test((value && value.toString()) || '');
+        return value != null ? filterRegex.test(value.toString()) : false;
       };
     },
     InputComponent: GridFilterInputValue,
```

This would be consistent with the direction taken when we introduced "value.toString()".

**Comment by flaviendelangle** [comment] 2021-12-13 07:59
What is the performance cost of adding a regexp on filtering, for large amount of rows ?

**Comment by m4theushw** [comment] 2021-12-13 12:36
> What is the performance cost of adding a regexp on filtering, for large amount of rows ?

@flaviendelangle The cost depends of the length of the searched string, but compared to `String.toLowerCase` + `String.startsWith`, the regexp performs better: https://jsbench.me/3lkx4npny5/1. Noticed that it has to be case insensitive.

A small performance improvement can be achieved if we change from `^foo.*$` to `^foo`:

```diff
diff --git a/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts b/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
index 3c72cc607..8d6d8d5ee 100644
--- a/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
+++ b/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
@@ -38,7 +38,7 @@ export const getGridStringOperators = (): GridFilterOperator[] => [
         return null;
       }
 
-      const filterRegex = new RegExp(`^${escapeRegExp(filterItem.value)}.*$`, 'i');
+      const filterRegex = new RegExp(`^${escapeRegExp(filterItem.value)}`, 'i');
       return ({ value }): boolean => {
         return filterRegex.test((value && value.toString()) || '');
       };
```

**Closed** 2022-02-07 16:33 UTC
Labels: bug 🐛, component: data grid, plan: Pro, feature: Filtering
