### ISSUE TITLE
[TreeView] Hydration error from 7.19.0 onwards

### ISSUE THREAD

**Issue by gurkerl83** [mui/mui-x#14980] opened 2024-10-15 13:27 UTC
### Steps to reproduce

Will not provide

### Current behavior

The Tree and TreeItem components **function as expected up until** version @mui/x-tree-view: 7.18.0.

After some investigation, it appears that **starting with version 7.19.0**, the **Tree component now requires a mandatory id attribute for each instance**. If this attribute is not supplied, a **hydration error occurs. In previous versions, this issue did not arise.**

Additionally, we are not using version 2 of the Tree and TreeItem components, which were recently refactored, so we cannot confirm whether this behavior is consistent in those versions.

To avoid confusion, we should update our documentation to reflect this requirement or consider fixing the issue to prevent users from having to investigate the code themselves.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: No duplicate found

**Comment by flaviendelangle** [comment] 2024-10-17 08:59
I can reproduce it, the default id applied differs between server and client due to the double re-rendering in dev mode on client...
It seems to be fixed by #14210, I'll extrated the required changes

**Closed** 2024-10-17 13:53 UTC
Labels: regression, component: tree view
