### ISSUE TITLE
[DatePicker] Changes value after closing it

### ISSUE THREAD

**Issue by mguerrero-ias** [mui/mui-x#4395] opened 2022-04-06 22:14 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Calendar Picker displays a calendar with the current date being highlighted.
If you then select the Year view-mode, and go to the previous year and the exact same date, you'll find out that the same date is selected, and if you exit the menu the date returns to the previous year.

### Expected behavior 🤔

Calendar Picker should either, allow me to select the same day from the previous year, and not overwrite it when the picker is closed.

This doesn't happen, if instead you change each month until you find the one you're looking for.

### Steps to reproduce 🕹

Steps:

1. Select a date.
2. Accept the date.
3. Open the calendar picker once again.
4. Click the arrow next to the Month and Year.
5. Go to any other year.
6. Try to pick the same Month and day from that different year.

I believe with just this you can get the problem to reproduce.
```tsx
export default function Calendar({ onChange, value, maxDate, minDate, title }: CalendarProps): JSX.Element {
    const [isOpen, setIsOpen] = useState(false);
    const [internalDate, setInternalDate] = useState<Date | null>(value);

    const onChangeHandler = (val: Date | null) => {
        // Just a external callback
        onChange(val ?? undefined);

        setInternalDate(val);
    };

    return (
        <LocalizationProvider dateAdapter={AdapterDateFns}>
            <DatePicker
                views={['year', 'month', 'day']}
                openTo={'month'}
                onChange={onChangeHandler}
                value={internalDate}
                minDate={minDate}
                maxDate={maxDate}
                // Added for the sake of being able to manually open the calendar when you click the input.
                open={isOpen}
                onClose={() => setIsOpen(false)}
                onOpen={() => setIsOpen(true)}
                renderInput={({ inputRef, inputProps, InputProps }) => {
                    return (
                        <>
                            <input
                                ref={inputRef}
                                {...inputProps}
                                className={cx('input', 'input-adornment')}
                                onClick={() => setIsOpen(true)}
                                title={title}
                                readOnly
                            />
                            {InputProps?.endAdornment}
                        </>
                    );
                }}
            />
        </LocalizationProvider>
    );
}
```

### Context 🔦

I want to change the date from the same year to the previous year.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment] 2022-04-18 12:27
I can reproduce the issue using this sandbox: https://codesandbox.io/s/basicdatepicker-material-demo-forked-w7wmg4?file=/demo.tsx

https://user-images.githubusercontent.com/13808724/163807992-bd50cdcd-7025-4585-bbff-be4a20ff53bc.mov

**Comment by flaviendelangle** [comment] 2022-04-20 08:40
Right now, our policy on multi-view is to only validate your value when reaching the last step.
So the behavior is intended, even if not satisfying

I intend to improve this behavior in the future, after clarifying how it exactly works in the current version.

**Comment by cherniavskii** [comment] 2022-04-20 08:59
> Right now, our policy on multi-view is to only validate your value when reaching the last step.

What do you mean by "last step" here?

**Comment by flaviendelangle** [comment] 2022-04-20 09:05
When changing a date in the internal picker state you have 3 type of updates:

- `shallow`: do not call `onChange`, only updates the state to update our UI
- `partial`: call `onChange` so that the user updates its state (which will be passed again to `props.value` and update the input value)
- `finish`: like `partial` but also update the reset target (`initialValue` in `usePickerState` on master, `dateState.resetTarget` in #4408). If you click `Reset`, or dismiss (behavior under modification in #4408), we reset to this value. Also closes the picker (on desktop).

The update is `finish` when you are on the last step of the picker currently being used.
Some picker have a prop to customize the view order, but by default it is:

- DatePicker => day
- DateTimePicker => minutes
- DateRangePicker => day of the 2nd date

To be honest, this behavior is not 100% clear to me.
But I think I get the basic idea which is to automatically close and validate a date only when selected its last bit.
>

**Comment by cherniavskii** [comment] 2022-04-20 09:13
Thanks @flaviendelangle 
In the video above you can see that I do select date on day view (last step).
The problem is that selecting already selected day (highlighted with blue background) doesn't commit the change.
And in this specific case, since the year has changed from 2022 to 2021, there should be no highlighted day at all.

**Comment by flaviendelangle** [comment] 2022-04-20 09:24
On the date pickers, the view are `[year, day]` with `day` being the default opened one

So as far as I understand, what we do is

1. Open on day
2. Go on year
3. Select year => go back on day
4. Select day => do nothing because as you said it is the already selected date


> And in this specific case, since the year has changed from 2022 to 2021, there should be no highlighted day at all.

What should be the date according to you after selecting a year ?
Right now we keep the previous date and just change the year

**Comment by cherniavskii** [comment] 2022-04-20 10:52
> Select day => do nothing because as you said it is the already selected date

Yeah, but it's only selected until you close the calendar.

> What should be the date according to you after selecting a year ?
Right now we keep the previous date and just change the year

Hmm, I think my expectation is that changing year from 2022 to 2021 should not change the date until specific day is selected.
Basically, it's the same behaviour as switching between months - the selected date doesn't change:

https://user-images.githubusercontent.com/13808724/164215397-852826d5-16a5-426b-ab95-2c26190bc0e0.mov

**Comment by flaviendelangle** [comment] 2022-04-20 10:53
> Yeah, but it's only selected until you close the calendar.

Because it was never validated
I agree that it is a scenario very ill-managed by the current state management...

**Comment by iMrDJAi** [comment] 2022-04-22 15:40
@cherniavskii @flaviendelangle I have a similar issue!

Changing the DatePicker value programmatically and then opening and closing it again would reset it since the onChange event gets fired and somehow passes `null` to the callback function instead of the new value I gave previously.

Selecting a Date, then changing the value programmatically, then opening and closing it again, would change it back to the value that I selected previously.

Somehow the selected value gets cached internally?

Here is a minimal reproduction for the bug: https://codesandbox.io/s/basicdatepicker-material-demo-forked-c5x09y

**Comment by iMrDJAi** [comment] 2022-04-22 15:55
@flaviendelangle Cool! The reproduction is done, feel free to take a look.

Off-topic: I also have a visual issue. I'm using SSR, look what happens when I reload the page:

https://user-images.githubusercontent.com/42304709/164750327-140f7ceb-323d-47e5-a578-ee046eea8d6e.mp4

 I may open a new issue and provide more info if needed.

**Comment by flaviendelangle** [comment] 2022-04-22 15:57
For the SSR issue, it would be best to open another issue please :+1:

**Comment by iMrDJAi** [comment] 2022-04-22 16:30
> I don't see any way of programmatically change the value in your codesandbox, am I missing something ?

@flaviendelangle My bad! I think I haven't saved my change 😅

Clicking on the "SET DATE" button would update the value.

**Comment by flaviendelangle** [comment] 2022-04-25 08:39
I confirm that #4408 is solving your bug :+1:

**Closed** 2022-04-29 12:15 UTC
Labels: bug 🐛, component: pickers, component: date picker

**Comment by melnik10** [comment] 2022-05-18 15:22
@iMrDJAi Hello! Has your error with changing statistics for 1 year ago been fixed?

**Comment by iMrDJAi** [comment] 2022-05-19 21:37
@melnik10 That PR solved state issues. You should try yourself!
