### ISSUE TITLE
[MobileDatePicker] When in keyboard view, can't clear the input

### ISSUE THREAD

**Issue by KlansPlan** [mui/mui-x#6045] opened 2022-09-06 13:33 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently it is not possible to remove selected date and time with the MobileDateTimePicker by removing the previously chosen date and time by clearing the text-field. onChange does not fire in this case unlike DesktopDateTimePicker.

### Expected behavior 🤔

It should be possible to remove a selected date and time. onChange should fire with value of null as the DesktopDateTimePicker does.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/trusting-hofstadter-fn6bgz?file=/src/App.js

Steps:
1. Choose date and time with DesktopDateTimePicker
2. Delete date and time by clicking in the DesktopDateTimePicker's textfield and delete the string.
3. Notice null value printed in console and DesktopDateTimePicker changes to empty default State
4. Choose date and time with MobileDateTimePicker
5. Click on the pen icon to go to text input mode
6. Delete date and time by emptying the text-field
7. Click OK
8. Notice no null value is printed in the console and the MobileDateTimePicker still shows the previously chosen date and time

### Context 🔦

Users should be able to remove a previously selected date and time on desktop and mobile devices.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser: Firefox 91.13.0esr (64-bit)
```
</details>

**Comment by KlansPlan** [comment] 2022-09-06 13:34
seems to relate to this issue: https://github.com/mui/mui-x/issues/5688

**Comment by flaviendelangle** [comment] 2022-09-12 10:32
Simpler reproduction case https://codesandbox.io/s/date-and-time-pickers-forked-vtepj6?file=/src/App.tsx

Thanks for your detailed example :+1:

**Comment by almostSouji** [comment] 2022-09-16 16:18
This seems to be directly caused by the mobile picker causing an override at `ignoreInvalidInputs` here:
https://github.com/mui/mui-x/blob/4ad1c16ed35e2faf4e5c510beec0e135eee776d1/packages/x-date-pickers/src/internals/components/CalendarOrClockPicker/CalendarOrClockPicker.tsx#L231-L238

Inspection before the condition here:
https://github.com/mui/mui-x/blob/4ad1c16ed35e2faf4e5c510beec0e135eee776d1/packages/x-date-pickers/src/internals/hooks/useMaskedInput.tsx#L109-L116

in the form of
```ts
  console.dir({
      text, finalString, date,
      ignoreInvalidInputs, utils_isValid: utils.isValid(date),
    })
```

<details>
<summary>yields results (click)</summary>

```json
// valid input (mobile)
{
  "text": "17.09.2022 00:01",
  "finalString": "17.09.2022 00:01",
  "date": {
    "$L": "de",
    "$d": "2022-09-16T22:01:00.000Z",
    "$x": {},
    "$y": 2022,
    "$M": 8,
    "$D": 17,
    "$W": 6,
    "$H": 0,
    "$m": 1,
    "$s": 0,
    "$ms": 0
  },
  "ignoreInvalidInputs": true,
  "utils_isValid": true
}
```

```json
// clear (mobile)
{
  "text": "",
  "finalString": "",
  "date": null,
  "ignoreInvalidInputs": true,
  "utils_isValid": false
}
```

```json
// valid input (desktop)
{
  "text": "18.09.2022 15:15",
  "finalString": "18.09.2022 15:15",
  "date": {
    "$L": "de",
    "$d": "2022-09-18T13:15:00.000Z",
    "$x": {},
    "$y": 2022,
    "$M": 8,
    "$D": 18,
    "$W": 0,
    "$H": 15,
    "$m": 15,
    "$s": 0,
    "$ms": 0
  },
  "utils_isValid": true
}
```

```json
// clear (desktop)
{
  "text": "",
  "finalString": "",
  "date": null,
  "utils_isValid": false
}
```

</details>

This suggests that `ignoreInvalidInputs` will always arrive as `undefined` in the desktop datepicker, but always as `true` in the mobile date picker.

Removal of the  `ignoreInvalidInputs ` override on mobile fixes the issue, however, raises another issue, of state persistence (the old value should likely be kept in the mobile popup, if a truly invalid input is provided)

An alternative approach could be to simply declare `null` as valid in the https://github.com/mui/mui-x/blob/next/packages/x-date-pickers/src/internals/hooks/useMaskedInput.tsx#L114
condition, or to adapt the `isValid` method to accept `null` as a valid date.

I am unsure which approach to take here, hence the RFC in the issue vs. a ready-made PR

**Comment by flaviendelangle** [comment] 2023-02-01 13:54
I am closing this issue.

We recently launched the first beta of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` v6.x.
This new version removes the keyboard view.
We added an [example in the migration guide](https://next.mui.com/x/migration/migration-pickers-v5/#remove-the-keyboard-view) to add it back and this version does not seem to have the problem described here :+1:

**Closed by flaviendelangle** 2023-02-01 13:54 UTC
Labels: bug 🐛, component: pickers
