### ISSUE TITLE
[data grid] GridEditInputCell should forward ref

### ISSUE THREAD

**Issue by Zenoo** [mui/mui-x#5630] opened 2022-07-27 09:27 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When the validation method returns an error, those errors show up in the console:

![](https://i.imgur.com/htyKEUI.png)
![](https://i.imgur.com/A8SWQZV.png)
![](https://i.imgur.com/GPPDwor.png)

### Expected behavior 🤔

There shouldn't be any errors.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/jv30c0?file=/demo.tsx

Steps:
1. Input a name that already exists
2. Look at the console

### Context 🔦

I'm implementing validators in my app.

I fixed this issue by adding a `<Box>` that holds the edit component ref between the `Tooltip` and the `GridEditInputCell`

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Version 103.0.5060.134 (Official Build) (64-bit)
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
```
</details>

### Order ID 💳 (optional)

47285

**Comment by alexfauquette** [comment] 2022-07-27 09:41
Thanks for reporting this bug, I assume using ForwardRef on `GridEditInputCell` will solve it.

**Comment by m4theushw** [comment] 2022-07-28 01:55
Duplicate of #5457

**Closed by m4theushw** 2022-07-28 01:55 UTC
Labels: bug 🐛, component: data grid, good first issue, feature: Editing
