### ISSUE TITLE
[docs] Demo PopularFeaturesDemo crashes

### ISSUE THREAD

**Issue by suryateja440** [mui/mui-x#10356] opened 2023-09-15 19:07 UTC
- [ ] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20PopularFeaturesDemo%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-data-grid/demo/
2. ??
3. demo *PopularFeaturesDemo* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.14.0  |
| Netlify deploy | https://65031ce334697c0008bc4e04--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 |

**Comment by oliviertassinari** [comment] 2023-09-16 15:03
Duplicate of #10047

**Closed** 2023-09-16 15:04 UTC
Labels: duplicate
