### ISSUE TITLE
Data grid pro with custom side panel, how to recalculate size on dynamic change of table width?

### ISSUE THREAD

**Issue by Nikita-Shaked-dev** [mui/mui-x#5555] opened 2022-07-21 07:19 UTC
### Order ID 💳

41353

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have custom panel with detailed info of row, when it's opening table don't recalculate it's own width and scroll doesn`t exist

Also last column disappear, and row has not full width
apiRef`s methods like forceUpdate not helping

steps to reproduce in sandbox:
1. resize window to fix columns width
2. click on any row
3. panel from right side will open
4. check horizontal scroll of table
5. resize window
6. check the horizontal scroll of table

[sandbox](https://codesandbox.io/s/datagridprodemo-demo-mui-x-forked-ey1ld1?file=/demo.tsx)
![Снимок экрана 2022-07-21 в 10 11 55 AM](https://user-images.githubusercontent.com/97431881/180152379-5b74d2c6-4409-4f19-a4e6-90eaa38c019c.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
    System:
    OS: macOS 12.4
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 8.13.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @mui/base:  5.0.0-alpha.89 
    @mui/envinfo: 2.0.6 => 2.0.6 
    @mui/icons-material: ^5.6.1 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.77 => 5.0.0-alpha.90 
    @mui/material: ^5.6.1 => 5.9.0 
    @mui/private-theming:  5.9.0 
    @mui/styled-engine-sc:  5.8.0 
    @mui/system:  5.9.0 
    @mui/types:  7.1.4 
    @mui/utils:  5.9.0 
    @mui/x-data-grid: ^5.8.0 => 5.13.0 
    @mui/x-data-grid-pro: ^5.8.0 => 5.13.0 
    @mui/x-license-pro:  5.12.3 
    @types/react: ^18.0.7 => 18.0.15 
    react: ^18.0.0 => 18.2.0 
    react-dom: ^18.0.0 => 18.2.0 
    styled-components: ^5.3.3 => 5.3.5 
    typescript: ^4.3.2 => 4.7.4 
```
</details>

**Comment by DanailH** [comment] 2022-07-21 09:30
Hey, @Nikita-Shaked-dev thanks for raising this!
I checked your reproduction but I wasn't able to see the issue you are describing. Maybe I'm doing something wrong?

Uploading Screen Recording 2022-07-21 at 11.28.15.mov…

**Comment by Nikita-Shaked-dev** [comment] 2022-07-22 15:33
https://user-images.githubusercontent.com/97431881/180473186-d875fee8-1969-4f79-897d-af79e033f6c8.mov

Hey @DanailH, please look at the video

**Comment by alexfauquette** [comment] 2022-07-26 10:40
I'm closing this issue because it has already been fixed by #5566 which will be available in the next release

Here is the cosdesandbox with the fix:
https://codesandbox.io/s/datagridprodemo-demo-mui-x-forked-x25jui?file=/package.json

**Comment by Nikita-Shaked-dev** [comment] 2022-07-26 11:01
@alexfauquette thanks, will it be soon?

**Comment by alexfauquette** [comment] 2022-07-26 11:35
The end of the week or next  week

**Closed by alexfauquette** 2022-07-26 11:35 UTC
Labels: bug 🐛, duplicate, component: data grid, support: commercial, feature: Rendering layout
