### ISSUE TITLE
[RFC] Calendar component is need.

### ISSUE THREAD

**Issue by tiyee** [mui/mui-x#6726] opened 2022-11-01 16:13 UTC
### What's the problem? 🤔

Calendar is the main component of schedular, but MUI is missing.

### What are the requirements? ❓

Change event handle when click or change the calendar cell.

**Comment by oliviertassinari** [comment] 2022-11-03 15:25
Is this a duplicate of #1407?

**Comment by tiyee** [comment] 2022-11-03 16:35
> Is this a duplicate of #1407?

No,  Maybe is more similar than that in  <https://github.com/wix/react-native-calendars>

**Comment by ruiaraujo012** [comment] 2022-11-03 18:30
> > Is this a duplicate of #1407?
> 
> No, Maybe is more similar than that in https://github.com/wix/react-native-calendars

This already exists here https://mui.com/x/react-date-pickers/date-range-picker/

What I think that is missing is what @oliviertassinari  said.

**Comment by tiyee** [comment] 2022-11-03 18:48
> > > Is this a duplicate of #1407?
> > 
> > 
> > No, Maybe is more similar than that in https://github.com/wix/react-native-calendars
> 
> This already exists here https://mui.com/x/react-date-pickers/date-range-picker/
> 
> What I think that is missing is what @oliviertassinari said.

This is  just a picker, but we need a calendar navigator with monthly mode and weekly mode

**Comment by LukasTy** [comment] 2022-11-03 18:53
> This is just a picker, but we need a calendar navigator with monthly mode and weekly mode

Are you by any chance looking for what we call [`static` date picker](https://mui.com/x/react-date-pickers/date-picker/#static-mode)?
There are also [sub-components exposed](https://mui.com/x/react-date-pickers/date-picker/#sub-components)—which might interest you.
As for the `week mode`—isn't [this custom example](https://mui.com/x/react-date-pickers/date-picker/#customized-day-rendering) something you are looking for?

**Comment by tiyee** [comment] 2022-11-04 04:03
> > This is just a picker, but we need a calendar navigator with monthly mode and weekly mode
> 
> Are you by any chance looking for what we call [`static` date picker](https://mui.com/x/react-date-pickers/date-picker/#static-mode)? There are also [sub-components exposed](https://mui.com/x/react-date-pickers/date-picker/#sub-components)—which might interest you. As for the `week mode`—isn't [this custom example](https://mui.com/x/react-date-pickers/date-picker/#customized-day-rendering) something you are looking for?

yeah,most of features is match, but weekly mode is mean just show a week days for select , not select a week days.

**Comment by ruiaraujo012** [comment] 2022-11-04 08:29
> > > This is just a picker, but we need a calendar navigator with monthly mode and weekly mode
> > 
> > 
> > Are you by any chance looking for what we call [`static` date picker](https://mui.com/x/react-date-pickers/date-picker/#static-mode)? There are also [sub-components exposed](https://mui.com/x/react-date-pickers/date-picker/#sub-components)—which might interest you. As for the `week mode`—isn't [this custom example](https://mui.com/x/react-date-pickers/date-picker/#customized-day-rendering) something you are looking for?
> 
> yeah,most of features is match, but weekly mode is mean just show a week days for select , not select a week days.

I really understand you but I think that you can do what you want with the current picker API, you can trigger a week calendar opening (your own component) after clicking on any day/week/month on the picker.

What is really missing on MUI is a calendar component like this but for MUI. https://fullcalendar.io/

**Comment by flaviendelangle** [comment] 2022-11-08 08:05
> What is really missing on MUI is a calendar component like this but for MUI. https://fullcalendar.io/

That's discussed #1407, I do agree that we will have to work on it at some point :+1: 

As for the calendar @tiyee asks for, we would need more details about the missing features and standalone issues for them.
I'm closing this one because there is a calendar component, so the real problem is not to create it but to improve it if needs be.

**Closed by flaviendelangle** 2022-11-08 08:05 UTC
Labels: RFC
