### ISSUE TITLE
[charts] Tooltip causing Page crash, on hovering any chart

### ISSUE THREAD

**Issue by 5war00p** [mui/mui-x#11106] opened 2023-11-20 15:51 UTC
### Steps to reproduce

Link to live example: (required)
https://mui.com/x/react-charts/bars/#basics

### Current behavior

OnHover page is getting crashed due to accessing property of undefined.
<img width="1039" alt="image" src="https://github.com/mui/mui-x/assets/57614947/cf6ccd95-4d22-48d5-a2c1-84e440c2a174">
![Kapture 2023-11-20 at 21 19 56](https://github.com/mui/mui-x/assets/57614947/c18eb248-1c26-4faa-9c96-e40d15eae21c)

### Expected behavior

Default tooltip should showup

### Context

Just rendering a chart with given examples from the docs and it causing page crash on hovering. Something wrong with tooltip.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: crash, hover, tooltip

**Comment by LukasTy** [comment] 2023-11-21 07:57
Hello, thank you for creating this issue. 🙏 
Could you clarify the browser on which you experienced the problem? 🤔 
I'm unable to reproduce the problem in Chrome, Safari, or Firefox on both v6 and v7 (next) docs. 🙈 🤷 

P.S. Have you tried hard reloading the page and/or incognito/private browsing?

**Comment by 5war00p** [comment] 2023-11-21 08:56
<img width="944" alt="image" src="https://github.com/mui/mui-x/assets/57614947/3ca31067-9f3a-421d-a331-45b859ce0e53">
Tried on incognito and other browsers too.

**Comment by LukasTy** [comment] 2023-11-21 10:07
I've tried everything I could think of and also tried Brave browser, but no luck, I'm unable to reproduce your problem. 🙈 
Could you clarify the version of the docs that you are accessing? 🤔 
<img width="294" alt="Screenshot 2023-11-21 at 12 07 23" src="https://github.com/mui/mui-x/assets/4941090/54d560c8-0294-4ccb-a25a-543ef283c80e">

**Comment by 5war00p** [comment] 2023-11-21 11:07
> I've tried everything I could think of and also tried Brave browser, but no luck, I'm unable to reproduce your problem. 🙈 Could you clarify the version of the docs that you are accessing? 🤔 <img alt="Screenshot 2023-11-21 at 12 07 23" width="294" src="https://user-images.githubusercontent.com/4941090/284540061-54d560c8-0294-4ccb-a25a-543ef283c80e.png">

Here are my versions:
<img width="396" alt="image" src="https://github.com/mui/mui-x/assets/57614947/e2d01315-b2a1-4e42-9b3b-482849412ef9">

**Comment by LukasTy** [comment] 2023-11-21 12:16
> Here are my versions:

Mhh, I thought that this was only about the docs. Can you reproduce the problem in your app as well? 🤔 
If you are able to reproduce the problem in your app, could you maybe provide a minimal codesandbox or a repository, where we could reproduce the problem? 🙏

**Comment by 5war00p** [comment] 2023-11-21 12:38
Yes, I'm able to reproduce this in my app. Will create a sandbox sooner.

**Comment by 5war00p** [comment] 2023-11-22 05:32
@LukasTy Here is the codesandbox devbox link: https://codesandbox.io/p/sandbox/mystifying-bartik-7x8spz

**Comment by 5war00p** [comment] 2023-11-22 05:41
Looks like `CssVarsProvider` is causing this, its from `@mui/joy/styles`.

**Comment by LukasTy** [comment] 2023-11-22 08:52
> Looks like `CssVarsProvider` is causing this, its from `@mui/joy/styles`.

Yup, that is the main problem.
Please follow the [Joy UI documentation](https://mui.com/joy-ui/integrations/material-ui/#set-up-the-providers) to resolve your problem.
I've double-checked that wrapping the Joy CSS Vars provider in one from Material fixes the issue. 😉 

I'm closing the issue. If you still encounter problems, please feel free to reopen it. 👌 
Thank you for using MUI libraries and I hope you are enjoying it. 🤞

**Closed as completed by LukasTy** 2023-11-22 08:52 UTC
Labels: scope: charts

**Comment by Gamer08YT** [comment] 2024-11-10 14:24
Having same problem...

`import * as React from "react";
import {RackElement} from "./elements/RackElement";
import "../../css/recode.scss"
import {BrowserElement} from "./elements/BrowserElement";
import Select from '@mui/joy/Select';
import Option from '@mui/joy/Option';
import {CssVarsProvider, useColorScheme} from '@mui/joy/styles';


export default function App() {
    return (
        <CssVarsProvider>
            <div className="editor">
                <ModeToggle/>
                <div className="designer">
                    <RackElement/>
                </div>
                <div className="browser">
                    <BrowserElement/>
                </div>
            </div>
        </CssVarsProvider>
    );
}

function ModeToggle() {
    const {mode, setMode} = useColorScheme();
    const [mounted, setMounted] = React.useState(false);

    // necessary for server-side rendering
    // because mode is undefined on the server
    React.useEffect(() => {
        setMounted(true);
    }, []);
    if (!mounted) {
        return null;
    }

    return (
        <Select
            value={mode}
            onChange={(event, newMode) => {
                setMode(newMode);
            }}
            sx={{width: 'max-content'}}
        >
            <Option value="system">System</Option>
            <Option value="light">Light</Option>
            <Option value="dark">Dark</Option>
        </Select>
    );
}`

Official Tutorial: https://mui.com/joy-ui/customization/dark-mode/#creating-a-mode-toggle-component
