### ISSUE TITLE
QuickFilter: quick filter input is not reflecting data grid filter model

### ISSUE THREAD

**Issue by mauro-ni** [mui/mui-x#4921] opened 2022-05-18 06:50 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using DataGridPro with filterModel (saving the sate in Redux), then quick filter input doesn't work well: records get filtered but quick filter input is not updated when setting / resetting filter model.

### Expected behavior 🤔

Quick filter inout should honor filterModel and reflect what is saved in the model.

### Steps to reproduce 🕹

Cannot work on your DataGrid / DataGridPro templates since they are broken. 

This is the error I get:

    TypeError
    (0 , $csb___mui_utils.unstable_generateUtilityClasses) is not a function

Here is what I'm trying to do:
https://codesandbox.io/s/data-grid-pro-forked-yn7vwj

### Context 🔦

I use DataGridPro in a controlled mode saving filterModel, sortModel, columnVisibilityModel, pinnedColumns in redux, because the interaction with records (details, edit, delete) is managed in different pages. 
When going back to the list the state must be restored.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  I'm using Google Chrome.

  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Edge: Not Found
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.7.0 => 11.9.0
    @emotion/styled: ^11.6.0 => 11.8.1
    @mui/base:  5.0.0-alpha.81
    @mui/icons-material: ^5.2.1 => 5.8.0
    @mui/lab: ^5.0.0-alpha.59 => 5.0.0-alpha.82
    @mui/material: ^5.2.3 => 5.8.0
    @mui/private-theming:  5.8.0
    @mui/styled-engine:  5.8.0
    @mui/styles: ^5.2.3 => 5.8.0
    @mui/system:  5.8.0
    @mui/types:  7.1.3
    @mui/utils:  5.8.0
    @mui/x-data-grid:  5.11.0
    @mui/x-data-grid-pro: ^5.2.0 => 5.11.0
    @mui/x-date-pickers:  5.0.0-alpha.0
    @mui/x-date-pickers-pro: ^5.0.0-alpha.1 => 5.0.0-alpha.3
    @mui/x-license-pro:  5.11.0
    @types/react:  18.0.9
    react: ^17.0.1 => 17.0.2
    react-dom: ^17.0.1 => 17.0.2
    styled-components: ^5.3.0 => 5.3.5
    typescript:  4.6.4
```
</details>

### Order ID 💳 (optional)

#32735

**Comment by alexfauquette** [comment] 2022-05-18 12:51
Hi, about the codesandbox problem, I created a dedicated issue #4924 such that we can focus on the quick filtering.

## What you can do 

I did not have this use case in mind when implementing the quick filter, so for now, it's not possible to control the text field content

So if you need a workaround, you will have to reimplement the component so you can control its value. To do so feel free to copy the provided one:
https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx

I made a codesandbox using `filterModel` selector to listen when the value are reset (`filterModel.quickFilterValues` become an empty array or `undefined`) and then reset TextField content

https://codesandbox.io/s/data-grid-pro-forked-wxmcg7?file=/src/SearchComponent.jsx

```js
// quickFilterValues can be undefined or an empty list
  const nbQuickFilterValues = filterModel.quickFilterValues?.length ?? 0;
  React.useEffect(() => {
    if (nbQuickFilterValues === 0 && searchValue !== "") {
      setSearchValue("");
    }
  }, [nbQuickFilterValues, searchValue]);
  ```


### Component improvement

This reset behavior could be implemented, It solve the most common usecase, but it is not a perfect solution because component value and data grid filterMOdel are still un-sync

To sync them, I see two options:
- Add a formatted function that reverts slicing. But from my experience slicing and joining string ends up with an infinite number of edge cases to deal with
- Save the input value in the `filterModel` and compute the `quickFilterValues` each time this string is updated.

**Comment by alexfauquette** [comment] 2022-05-24 20:04
@eric-personal I move your comment here such that we can continue discussing in the dedicated issue (easier for me to follow and for people coming to get the full information)

> I noticed on your codesandbox link you are using the useEffect to reset but this causes a larger side effect because when user first types into the input field the line nbQuickFilterValues === 0 && searchValue !== "" will be true which will cause the users first letter to be wiped out. You can see this happening in the codesandbox example on first key stroke.

The problem comes from the debounce. You can solve it by either removing it (not recommended, because filtering will be applied after each letter added to the input) or keeping in memory the number of items in the quick filter, and reset only when it moves from greater than 0 to 0. In other words, consider updating the `searchValue` only when the `nbQuickFilterValues` has been modified

I updated the codeSandbox with the second option

```js
const nbQuickFilterValues = filterModel.quickFilterValues?.length ?? 0;
React.useEffect(() => {
  // Check the `nbQuickFilterValues` has been modified since last render
  if (prevNbFilterValue !== nbQuickFilterValues) {
    setPrevNbFilterValue(nbQuickFilterValues);
    if (nbQuickFilterValues === 0 && searchValue !== "") {
      setSearchValue("");
    }
  }
}, [nbQuickFilterValues, searchValue, prevNbFilterValue]);

```

**Comment by matandro** [comment] 2022-05-24 23:37
We have rows, selection model, selection model filter and loading (true / false) managed by react. When we try to reload the data (async thunk -> update rows -> selector) it clears the text from the quick filter text box but doesn't clear it from the selection model.
Notice that we do not control the filter model in redux in our case.

A workaround is to write 1 character into the quick filter text box and delete it to reset the actual filter.

**Comment by alexfauquette** [comment] 2022-05-25 08:48
@matandro could you provide a reproduction. 

From your explanation, I don't know if
- you are using default QuickFilter input or a custom one as proposed in previous comments
- I don't know how you manage the filter model
- I don't know how do you do your row update

For now, the only thing that I can do is pointing the method `apiRef.current.setQuickFilterValues` that can be used to reset the quick filter with `apiRef.current.setQuickFilterValues([])`

**Comment by mauro-ni** [comment] 2022-05-25 08:51
@alexfauquette is there a plan to fix the issue updating the implementation of QuickFilter (also saving input text in filterModel)? 
Thx.

**Comment by alexfauquette** [comment] 2022-05-25 09:20
Yes, we will do what we can to fix this issue, but it is still unclear what would be the correct way

**Comment by alexfauquette** [comment] 2022-05-25 10:34
I made an experimental PR to see if it fixes your problems #5013

You can already test the code by using the generated package in your codesandbox (to do so in package.json replace `"latest"` by the url):

- https://pkg.csb.dev/mui/mui-x/commit/82b81d91/@mui/x-data-grid
- https://pkg.csb.dev/mui/mui-x/commit/82b81d91/@mui/x-data-grid-pro

Here is the codesandox of the initial comment with the proposed solution, which seems to fix the problem. DOn't hesitate if you have feedbacks on improvement, or remaining issues

**Comment by mauro-ni** [comment] 2022-05-27 07:04
@alexfauquette thanks!

I attach a screenshot to show you my situation.

Resetting filterModel now also clear quickFilter input out! 

Persisting problems:

- I act on the list with quickFilter and then open CourseDetails (new page), when I go back to the list the quickFilter input is empty even if quickFilterValues array is set.
- Search input clear icon has a strange icon color (should be white), what am I missing?


<img width="1472" alt="2022-05-27_CoursesList" src="https://user-images.githubusercontent.com/1393996/170647308-212baeb6-d520-405f-8f7a-f776b210e36d.png">

Many thanks for your help.

Mauro

**Comment by alexfauquette** [comment] 2022-05-30 08:22
Thanks for taking time to test the fix

About the cross: It's a default icon added by the browser. You can remove it with [CSS](https://medium.com/@rion.mrk/how-to-remove-x-icon-from-search-input-field-or-input-type-search-db3c808405fb). I assume it will be better to override the native one with a MUI icon. But I need to check what core team is doing first to stay consistent

About the empty field when `quickFilterValues` is not empty because I fixed the case where `quickFilterValues` is modified with a `useEffect`, but not the initialization. It should be fixed with the [new commit](https://github.com/mui/mui-x/pull/5013/commits/08d17ebfa2948cacb20af192b5f5b8aa189bc387)
generated package: https://pkg.csb.dev/mui/mui-x/commit/08d17ebf/@mui/x-data-grid-pro

![quick filter](https://user-images.githubusercontent.com/45398769/170949813-f34cd811-c0a1-4781-b71a-3c8f0ed1e2c7.gif)

For the code sandbox, we can not fix it, that's due to a bug when codesandbox uses its cache to resolve dependencies. I created a new one and copy-pasted your code in it: https://codesandbox.io/s/fullfeatureddemo-material-demo-forked-zz5ju6?file=/demo.tsx

**Comment by mauro-ni** [comment] 2022-05-31 09:09
@alexfauquette many thanks!!! 

With the new version when I go back to the list the quickFilter input get the correct value.

Any news about the cross? It would be nice to have an example in the DOC that tell you how to override default cross with a MUI icon.

Many thanks again, hope to see a new release of MUI X soon.

Mauro

**Comment by matandro** [comment] 2022-06-03 16:27
@alexfauquette 
Is it possible that our issue is with our custom toolbar?
```js
components={{
  Toolbar: () => (
    <CustomToolbar>
      <GridRefreshButton handleRefresh={() => refreshData()} />
    </CustomToolbar>
  ),
}}
```

Custom toolbar is just a toolbar with specific children. additionally we have a custom button for table refresh. Is the way we push is causes this issue?
Do we need to use `componentsProps` and send that under children so it doesn't remount the header?

**Comment by alexfauquette** [comment] 2022-06-03 17:24
@matandro if I get it correctly, when you refresh data, you update `rows` props and the quick filter is unsync.

I assume that when you refresh your data it rerender the QuickFilter. If it's the case, the PR should fix your bug too

**Closed** 2022-06-03 19:13 UTC
Labels: bug 🐛, component: data grid, feature: Filtering
