### ISSUE TITLE
[pickers] Value can be modified independently even though the `value` prop remains unchanged

### ISSUE THREAD

**Issue by john1625b** [mui/mui-x#10476] opened 2023-09-26 00:56 UTC
### The problem in depth 🔍

note in the following code: the `onChange` isn't passed and the `value` remains a static value of "2022-04-18", but you can still select a value from the calendar and the change is reflected in the UI:

```
        <DatePicker
          label="Controlled picker"
          value={dayjs("2022-04-18")}
          // onChange={(newValue) => setValue(newValue)}
        />
```

https://codesandbox.io/s/mui-date-picker-3wnljf?file=/Demo.tsx:715-860

This situation poses a challenge. Suppose a network request fails when attempting to update a value. In that case, the user interface might still display the newly selected value, even though the backend did not successfully save this change. This discrepancy could lead to confusion and inaccuracies.

**Search keywords**: DatePicker, controlled, static value

**Search keywords**: DatePicker, controlled, static value
**Order ID**: 72840

**Comment by LukasTy** [comment] 2023-09-26 07:22
Thank you for opening this issue! 🙏 
I can agree that the behavior is a bit strange, especially when compared to other component's controlled behavior.
We'll have a look at this case.
It also looks awfully similar problem to https://github.com/mui/mui-x/issues/10424

**Comment by 05August** [comment] 2024-01-22 03:55
Has this issue been resolved yet?

**Comment by LukasTy** [comment] 2024-01-22 08:07
> Has this issue been resolved yet?

Thank you for bringing this issue up. 🙏 
It is a duplicate of https://github.com/mui/mui-x/issues/10424.
No, sorry, it has not been resolved yet, we didn't have time to get it yet. 🙈

**Closed by LukasTy** 2024-01-22 08:07 UTC
Labels: support: commercial, component: pickers
