### ISSUE TITLE
[data grid] DataGrid "no rows" overlay missing when autoHeight=true

### ISSUE THREAD

**Issue by ddolcimascolo** [mui/mui-x#15169] opened 2024-10-29 15:59 UTC
### Steps to reproduce

Your own doc reproduces: https://mui.com/x/react-data-grid/layout/#overlay-height

### Current behavior

The overlay is not there

### Expected behavior

The overlay is there

### Context

Trying to make my own customers happy by not breaking their data grids because of a semver-minor update of a dependency :/

**Search keywords**: no rows overlay missing
**Order ID**: 31461 or 78178

**Comment by michelengelen** [comment] 2024-10-30 10:06
Duplicate of #14881

**Comment by michelengelen** [comment] 2024-10-30 10:09
Additional note: the [Auto height](https://mui.com/x/react-data-grid/layout/#auto-height) got deprecated with introduction of the [flex parent container](https://mui.com/x/react-data-grid/layout/#flex-parent-container) approach.

**Comment by ddolcimascolo** [comment] 2024-10-30 12:28
Please reopen. I've changed nothing in my code and this is a regression. Moreover your doc exhibits the issue !

**Comment by ddolcimascolo** [comment] 2024-10-30 12:29
@oliviertassinari @alexfauquette @romgrk @michelengelen Can you ahve a look and explain why this is closed?

**Comment by michelengelen** [comment] 2024-10-30 13:44
@ddolcimascolo yes ... this regression got introduced recently. Sry for closing this too early. I'll have a look at it!

**Comment by michelengelen** [comment] 2024-10-30 15:52
scratch that ... :/ ... found the culprit!

**Comment by ddolcimascolo** [comment] 2024-10-30 18:37
Thanks a lot for confirming the issue and for your work on this.

Cheers,
David

**Closed** 2024-10-31 07:20 UTC
Labels: duplicate, component: data grid, regression, support: pro standard

**Comment by cherniavskii** [comment] 2024-10-31 15:58
Thanks @GBvanDam 
I've opened https://github.com/mui/mui-x/pull/15202 to address the minimum overlay height.
