### ISSUE TITLE
Scrolling Issue on DataGrid with Detail Pane

### ISSUE THREAD

**Issue by conerye** [mui/mui-x#9647] opened 2023-07-11 19:12 UTC
### Order ID

331993142

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Sometimes scrolling on the tables 'gets stuck' when the data grid has a detail pane left open. I have created a code sandbox that shows the issue. It is much more obvious in our app, where there are tables with > 100 rows, but here in the sandbox, I have just 23 rows to show the issue.
https://codesandbox.io/s/flamboyant-taussig-7z7v9x?file=/src/TableScrollingIssue.jsx
steps to reproduce the issue:
scroll part way down table
open a detail panel (or two)
scroll all the way to the bottom of the table
attempt to scroll to the top
* it may not occur on the first try! but after a few attempts, when attempting to scroll back up, the scroll bar 'jumps' down and prevents scrolling up
*** This occurs on Google Chrome browser (tested with Version 114.0.5735.199 (Official Build) (64-bit))
I have been told this issue was also reported on Edge browsers. It has not been reported on Firefox, and I have not done any testing on Firefox yet...

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.67)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3
    @emotion/styled: ^11.8.1 => 11.9.3
    @mui/base:  5.0.0-alpha.87
    @mui/icons-material: ^5.8.0 => 5.8.4
    @mui/material: ^5.8.1 => 5.8.6
    @mui/private-theming:  5.9.1
    @mui/styled-engine:  5.8.7
    @mui/system: ^5.9.1 => 5.9.1
    @mui/types:  7.1.4
    @mui/utils:  5.10.6
    @mui/x-data-grid: ^5.13.1 => 5.14.0
    @mui/x-data-grid-premium: ^5.14.0 => 5.14.0
    @mui/x-data-grid-pro:  5.14.0
    @mui/x-date-pickers: ^5.0.0-beta.1 => 5.0.0-beta.2
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.2
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react:  18.0.14
    react: ^18.1.0 => 18.2.0
    react-dom: ^18.1.0 => 18.2.0
    typescript:  4.7.4
```
</details>

**Comment by cherniavskii** [comment] 2023-07-11 19:29
Hey @conerye
I can reproduce the issue in your codesandbox.
I cannot reproduce it with the latest v5 version (v5.17.26) - can you confirm?
Here's the sandbox: https://codesandbox.io/s/eager-brahmagupta-m5cps7

**Comment by conerye** [comment] 2023-07-12 21:34
we are currently at 5.14... upgrading to 5.17.26 does seem to fix the issue. do you know which version between 5.14 and 5.17.26 includes the fix??? we are about to release our app, so need to determine if this is something we want to update last minute or wait until next release... please lmk

**Comment by cherniavskii** [comment] 2023-07-13 07:42
@conerye It was fixed in https://github.com/mui/mui-x/releases/tag/v5.17.11

**Closed** 2023-07-13 07:42 UTC
Labels: component: data grid, support: commercial

**Comment by conerye** [comment] 2023-07-13 20:10
THANK YOU!
