### ISSUE TITLE
[data grid] `gridFooterElement` is `null` with `hideFooter`

### ISSUE THREAD

**Issue by slashinfty** [mui/mui-x#13273] opened 2024-05-27 23:43 UTC
### Steps to reproduce

Link to live example: [Sandbox](https://codesandbox.io/p/devbox/wq8mn5?migrateFrom=nl4nsy)

### Current behavior

Doing either `<DataGrid hideFooter ... />` or `<GridToolbarExport printOptions={{ hideFooter: true }} />` and then attempting to export to print yields the following error:

```
TypeError: gridFooterElement is null

Call Stack
useGridPrintExport/handlePrintWindowLoad<
    node_modules/@mui/x-data-grid/hooks/features/export/useGridPrintExport.js (127:1)
useGridPrintExport/exportDataAsPrint</printWindow.onload
    node_modules/@mui/x-data-grid/hooks/features/export/useGridPrintExport.js (256:1)
```

Removing `hideFooter` allows it to be printed, but (obviously) with a footer.

### Expected behavior

The print dialog should open with the footer hidden.

### Context

I have not been able to recreate this by editing existing sandboxes. Unsure what in my packages or setup could cause this, though.

**Search keywords**: gridfooterelement hidefooter x-data-grid

**Comment by michelengelen** [comment] 2024-05-28 15:35
This is a duplicate of #13015 and has an open PR #13034 
I did ping the reviewers, so it should be resolved with the new version! 👍🏼

**Closed by michelengelen** 2024-05-28 15:35 UTC
Labels: duplicate, component: data grid, feature: Export
