### ISSUE TITLE
[data grid] Indicate a loading state when searching through quick filter in datagridpro.

### ISSUE THREAD

**Issue by saitejavirupaksha-sureify** [mui/mui-x#13540] opened 2024-06-19 10:46 UTC
### Summary

We have a use case of dataGridPro to operate on a very huge dataset (2M records) and more than 20 columns. 
The problem arises when we start to search using the quick filters, We notice some input lag, and also as the main UI thread is blocked we are not able to provide a good User experience.
also, we can show a loader in the quick filter when the datagridPro is performing a search on the grid?

It would be great if MUI exposed an API like to know if the grid is searching.

**Search keywords**: loading quickfilter search filtering state
**Order ID**: 909090

**Comment by saitejavirupaksha-sureify** [comment] 2024-06-20 10:13
thanks, @michelengelen for responding. Did we have any major improvements in the quick filter or filters after
 ```6.19.4``` version. if yes can you tell me which version I can use so I can see some performance changes until we get that loader done.🤗

**Comment by michelengelen** [comment] 2024-06-20 12:16
@mui/xgrid did we make any major improvements to the searching/filtering feature?

**Comment by romgrk** [comment] 2024-07-03 23:01
No change to filters since then. If we do work on the filters, it would be on the v7 branch.

**Comment by romgrk** [comment] 2024-07-03 23:40
Duplicate of #9657 

Subscribe to that issue for updates.

**Closed by romgrk** 2024-07-03 23:40 UTC
Labels: duplicate, performance, component: data grid, feature: Filtering, enhancement
