### ISSUE TITLE
The same line is repeatedly displayed when scrolling with the master detail expanded.

### ISSUE THREAD

**Issue by kajirikajiri** [mui/mui-x#6379] opened 2022-10-04 08:52 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Master detail can be expanded and scrolled correctly

### Expected behavior 🤔

The same line is repeatedly displayed when scrolling with the master detail expanded.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/7d6dcx?file=/demo.tsx
Link to live example: https://codesandbox.io/s/hroome?file=/demo.tsx
Link to live example: https://codesandbox.io/s/q6s0tn?file=/demo.tsx
Link to live example: https://codesandbox.io/s/t224bu?file=/demo.tsx
  Link to Mui document: https://mui.com/x/react-data-grid/master-detail/

Video: 

https://user-images.githubusercontent.com/37785038/193775598-d81e8c7e-1524-4f0f-81d0-a3184fcf7bd9.mov

Steps:
1. Open all master details in order 6 to 1
2. Scroll to the bottom
3. Scroll up slowly
4. It tries to scroll from 5 to 4, but returns to 5

Try scrolling up quickly in step 3. You can scroll to the top.

### Context 🔦

I found this bug when I was verifying to use the Master detail feature.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#49639

**Comment by DanailH** [comment] 2022-10-05 12:42
@kajirikajiri thanks for raising this bit it is a duplicate of this one https://github.com/mui/mui-x/issues/6378. I'll close this and you can track the progress in the other issue.

**Closed by DanailH** 2022-10-05 12:42 UTC
Labels: status: needs triage
