### ISSUE TITLE
Failure when installing @mui/lab 5.0.0-alpha.143 (Failed to resolve package)

### ISSUE THREAD

**Issue by andrewtremblay** [mui/mui-x#12329] opened 2024-03-04 20:43 UTC
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-fi31t3?file=package.json

Steps:
1. Pin @mui/lab to 5.0.0-alpha.143
2. npm install 

### Current behavior

NPM is unable to install due to 500 error dependency. 
Stackblitz can reproduce this with a dependency warning
<img width="549" alt="image" src="https://github.com/mui/mui-x/assets/954150/2222cf78-8507-42de-babe-5fee9da28857">

Locally this is seen as a 500.
npm http fetch GET 200 https://registry.npmjs.org/@mui%2flab 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@mui%2fbase 26ms (cache hit)
npm http fetch GET 500 https://pkg.csb.dev/mui/mui-x/commit/1f23b33d/@mui/x-tree-view 71572ms attempt #3 (cache skip)
npm verb stack HttpErrorGeneral: 500 Internal Server Error - GET https://pkg.csb.dev/mui/mui-x/commit/1f23b33d/@mui/x-tree-view
npm verb stack     at /Users/you/.nvm/versions/node/v18.19.0/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verb statusCode 500
npm verb pkgid @mui/x-tree-view@https://pkg.csb.dev/mui/mui-x/commit/1f23b33d/@mui/x-tree-view

### Expected behavior

5.0.0-alpha.143 should reliably install. 

### Context

It seems like this alpha version was pinned to a codesandbox commit which now cannot be accessed anymore. I curiously cannot reproduce this on codesandbox.  

This does not happen in the latest version of @mui/lab (5.0.0-alpha.166) or the next 5.0.0-alpha.144. This is merely a pain for those who strictly pin to this alpha version. 

### Your environment

Browsers: n/a.  This occurred during the npm install step on both local and remote machines.

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.6.1
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 122.0.6261.94
    Edge: Not Found
    Safari: 16.2
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.37
    @mui/core-downloads-tracker:  5.15.11
    @mui/icons-material: ^5.14.9 => 5.14.9
    @mui/lab: 5.0.0-alpha.166 => 5.0.0-alpha.166
    @mui/material: ^5.14.9 => 5.15.11
    @mui/private-theming:  5.15.11
    @mui/styled-engine:  5.15.11
    @mui/system:  5.15.11
    @mui/types:  7.2.13
    @mui/utils:  5.15.11
    @mui/x-date-pickers: ^6.14.0 => 6.14.0
    @types/react: 18.2.21 => 18.2.21
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ~5.2.0 => 5.2.2
 ```
</details>

**Search keywords**: npm @mui/lab 5.0.0-alpha.143

**Comment by Linuhusainnk** [comment] 2024-03-05 06:26
Same issue +1

**Comment by LukasTy** [comment] 2024-03-05 06:59
This is a duplicate of https://github.com/mui/material-ui/issues/38819.
Please upgrade to `@mui/lab@5.0.0-alpha.144` or newer to avoid this issue.

If you are serious about using `TreeView`, please consider moving to a [separate dependency of `@mui/x-tree-view`](https://mui.com/blog/mui-x-mid-v6-features/#tree-view-is-moving-to-mui-x).
It has been moved out of the `lab` and its further development will be happening in this package.
Please follow [this migration guide](https://mui.com/x/migration/migration-tree-view-lab/) to migrate your `TreeView` to using the dedicated package. 👍

**Closed by LukasTy** 2024-03-05 06:58 UTC
Labels: status: waiting for maintainer
