### ISSUE TITLE
[pickers][Datepicker][AdapterDateFnsV3] unable to set single digit day of month format

### ISSUE THREAD

**Issue by devChrisho** [mui/mui-x#13250] opened 2024-05-25 17:57 UTC
### Steps to reproduce

Link to live example: (required)

Steps:
1. set LocalizationProvider dateAdapter props to AdapterDateFnsV3
2. insert "d MMM yyyy" into format props of Datepicker

### Current behavior

displayed date format is dd MMM yyyy. 
e.g. "01 Jan 2024"

### Expected behavior

it should be "1 Jan 2024"

### Context

documentation fron date-fns v3 states format for single digit day of month. This has been tested using date-fns module without issues. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
   System:
    OS: macOS 13.6.7
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 125.0.6422.112
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.8 
    @mui/core-downloads-tracker:  5.15.17 
    @mui/icons-material: ^5.15.17 => 5.15.17 
    @mui/lab: ^5.0.0-alpha.137 => 5.0.0-alpha.137 
    @mui/material: ^5.15.17 => 5.15.17 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/styles: ^5.15.17 => 5.15.17 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-date-pickers: ^7.4.0 => 7.4.0 
    @types/react: ^18.3.2 => 18.3.2 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    typescript: ^5.4.5 => 5.4.5 
```
</details>

**Search keywords**: date-fns day of month

**Comment by LukasTy** [comment] 2024-05-27 07:21
Hello @devChrisho, could you confirm if you are actually experiencing this problem only with `AdapterDateFnsV3`? 🤔 
I've tested and it seems to be the same for both `date-fns` adapters. 🤷

This is an intentional feature by design, please check [`shouldRespectLeadingZeros`](https://mui.com/x/react-date-pickers/adapters-locale/#respect-leading-zeros-in-fields) documentation for more information on how to avoid this and the consequences of it. 😉 
Let me know if it helps you solve your problem. 🙏

**Comment by devChrisho** [comment] 2024-05-27 08:10
> Hello @devChrisho, could you confirm if you are actually experiencing this problem only with `AdapterDateFnsV3`? 🤔 I've tested and it seems to be the same for both `date-fns` adapters. 🤷
> 
> This is an intentional feature by design, please check [`shouldRespectLeadingZeros`](https://mui.com/x/react-date-pickers/adapters-locale/#respect-leading-zeros-in-fields) documentation for more information on how to avoid this and the consequences of it. 😉 Let me know if it helps you solve your problem. 🙏

Thank you! I had only tested it with v3. This was exactly what I was looking for. Apologies as I was unaware that the configuration was with the slotProps -> field

**Comment by LukasTy** [comment] 2024-05-27 08:25
I'm closing the issue as the problem is resolved. 👌 
Feel free to reopen it or create a new one if you still experience problems. 😉

**Closed by LukasTy** 2024-05-27 08:25 UTC
Labels: status: waiting for maintainer, component: pickers
