### ISSUE TITLE
[charts] Axis not plot if the domain contains only one value

### ISSUE THREAD

**Issue by Ashiq5** [mui/mui-x#13973] opened 2024-07-24 17:31 UTC
### Steps to reproduce

Link to live example: (required)

Steps:
1. Check out this live link: [codesandbox](https://codesandbox.io/s/priceless-shape-dswf34?file=/src/Demo.tsx:144-470)
After the dependencies are installed, you should see a line chart with no Y-axis label and ticks.
2. However, if one of the data values is changed to something else (other than -1), Y-axis labels and ticks appear fine.

### Current behavior

Missing Y-axis labels and ticks when all the values in a data are equal.

### Expected behavior

Y-axis labels and ticks should appear irrespective of data values.

### Context

Display Y-axis label and ticks irrespective of the data values.

### Your environment

Browser: Google Chrome

**Search keywords**: Y axis ticks and labels missing

**Comment by Ashiq5** [comment] 2024-07-24 17:33
I am not 100% sure whether there is a certain config to enable this. But from looking at the doc, it seems like a bug to me. Please let me know if there is a easy hack to get around this and I will close the issue. Thanks.

**Comment by alexfauquette** [comment] 2024-07-24 22:44
This should solve your issue
```jsx
yAxis={[{ min: -2, max: 1 }]}
```

But effectively it's weird. We should have a deeper look at it to know where it fails

**Comment by alexfauquette** [comment] 2024-07-25 09:56
Seems we have room for improvement.

The reason why no axis is displayed, if this kind of condition

https://github.com/mui/mui-x/blob/0fb15c6f0782cadb08011d3b47a9917f16e5230d/packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx#L147

They got added (in x axis, y axis and useTicks) when we added support for the ["no data" overlay](https://mui.com/x/react-charts/styling/#custom-overlay)

The root cause is that the axis provider correctly compute that there is no data to display. It returns extremums `[null, null]`. But from those extremums, we generate a scale, which will transform that into `scale.domain() = [0, 0]`

https://github.com/mui/mui-x/blob/0fb15c6f0782cadb08011d3b47a9917f16e5230d/packages/x-charts/src/context/CartesianProvider/computeValue.ts#L171-L180

To spot that we use `domain[0] === domain[1]` not having the usecase of this issue in mind.

The best fix might be to add a property to the axis object `noDataAssociated: extremums[0] === null || extremums[1] === null`

**Comment by JCQuintas** [comment] 2024-08-22 12:19
Fixed in https://github.com/mui/mui-x/pull/14191

**Closed** 2024-08-22 12:19 UTC
Labels: bug 🐛, good first issue, component: charts
