### ISSUE TITLE
[data grid] Clipboard copy places unnecessary quotations when copied text contains a quotation

### ISSUE THREAD

**Issue by louisaaron** [mui/mui-x#12638] opened 2024-04-02 15:00 UTC
### Steps to reproduce

Link to live example: https://www.loom.com/share/c38d8abb4a464b3185bafff09eea2939?sid=731700af-53e5-4884-960d-252ff196b419

Steps:
1. Type content into a cell which includes a quotation mark. For example, Test " Text
2. Copy it
3. Paste it into another cell

### Current behavior

Extraneous quotation marks are added

### Expected behavior

Text should be pasted as it was copied

### Context

Trying to copy and paste cells with text which contain a quotation mark

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Copy Paste Quotations
**Order ID**: 85118

**Comment by MBilalShafi** [comment] 2024-04-03 11:56
Thanks @louisaaron for reporting. I can confirm the issue, apparently, it's because of the following code block:
https://github.com/mui/mui-x/blob/e12acf2bf65e0627b52ebed4cc0af8df06285f1a/packages/x-data-grid/src/hooks/features/export/serializers/csvSerializer.ts#L11-L16

Looking at the changelog, it might be a regression introduced in https://github.com/mui/mui-x/pull/12357

I'm adding it to the board for the team to prioritize.

**Comment by louisaaron** [comment] 2024-04-04 00:05
Awesome thanks @MBilalShafi !

**Comment by cherniavskii** [comment] 2024-04-15 13:05
Duplicate of https://github.com/mui/mui-x/issues/12456

**Closed by cherniavskii** 2024-04-15 13:05 UTC
Labels: bug 🐛, component: data grid, feature: Clipboard, support: premium standard
