### ISSUE TITLE
Checkbox selection doesnt work for grouped items.

### ISSUE THREAD

**Issue by gor918** [mui/mui-x#14111] opened 2024-08-05 17:28 UTC
### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: (required)
https://stackblitz.com/edit/react-8o1qer?file=Demo.tsx

Steps:
1. expand first row
2. click to first checkbox (20th Century Fox (3))

### Current behavior

After clicking on the first row (20th Century Fox (3)), only the parent row is selected

### Expected behavior

When rows are grouped, clicking on a parent row should also select all grouped child rows

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: row selection, group
**Order ID**: #76565

**Comment by arminmeh** [comment] 2024-08-05 19:16
Hi @gor918 
There is an [open PR](https://github.com/mui/mui-x/pull/13757) that is adding a behavior that you need

If you are ok with it, I will close this issue as a duplicate of #4248 (point 1) and you can follow the progress in the other ticket/PR

In case you think that this does not fully cover your use case, feel free to reopen the issue and comment with additional details.

**Closed by arminmeh** 2024-08-05 19:16 UTC
Labels: bug 🐛, component: data grid, status: waiting for maintainer, plan: Premium, feature: Selection, feature: Row grouping

**Comment by oliviertassinari** [comment] 2024-08-17 13:02
Duplicate of #4248
