### ISSUE TITLE
[data grid] Lazyloading and sorting crash

### ISSUE THREAD

**Issue by PontusAxelsson** [mui/mui-x#11873] opened 2024-01-31 10:27 UTC
### Steps to reproduce

[Link to live example: (required)
](https://mui.com/x/react-data-grid/row-updates/#lazy-loading)
Steps:
1. Click sorting
2. Drag to bottom
3. Click other sorting
4. Drag to top
5. If no error, repeat from step 1 until crash

### Current behavior

Sorting stops working with this console.log error:
8006-80a35f9dc9f20fe2.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at 8006-80a35f9dc9f20fe2.js:1:307270
    at Array.filter (<anonymous>)
    at Object.unstable_replaceRows (8006-80a35f9dc9f20fe2.js:1:307231)
    at demo-90efa27c4d6f0ff2.js:1:21461
    at tryCatch (_app-186bd6b5d6d26ab4.js:100:43886)
    at b.value (_app-186bd6b5d6d26ab4.js:100:43650)
    at Generator.next (_app-186bd6b5d6d26ab4.js:100:44376)
    at asyncGeneratorStep (_app-186bd6b5d6d26ab4.js:100:39077)
    at _next (_app-186bd6b5d6d26ab4.js:100:39282)

### Expected behavior

Should be able to sort with lazyloading and should not crash

### Context

I get the same error as on the official example page. All settings for mui/x datatable set to "server"

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Chrome Version 120.0.6099.129 (Official Build) (64-bit)
```
</details>

### Order ID or Support key 💳 (optional)

61657

**Search keywords**: lazyloading sorting

**Comment by michelengelen** [comment] 2024-01-31 11:06
duplicate of #11865

**Closed** 2024-02-02 11:40 UTC
Labels: bug 🐛, duplicate, component: data grid
