### ISSUE TITLE
support date-fns 3.x

### ISSUE THREAD

**Issue by AndorLundgren** [mui/mui-x#12758] opened 2024-04-12 08:59 UTC
### Summary

When replacing:
`import { DatePicker } from '@mui/lab';`
with:
`import { DatePicker } from '@mui/x-date-pickers';`

and installing date-fns (to be used as an adapter)

I realized that:
[AdapterDateFns](https://github.com/mui/mui-x/blob/52944585814f555e28d0baf5058d9ab3c13edd18/packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts)

was importing with default export from date-fns:
`import longFormatters from 'date-fns/_lib/format/longFormatters';`

which I belive was removed in date-fns 3.0:
[blog.date-fns.org/v3-is-out/#no-more-default-exports](https://blog.date-fns.org/v3-is-out/#no-more-default-exports)

Had to install date-fns 2.30.0 for it to start working:
`npm i date-fns@^2.30.0`

### Motivation

It would be good to support 3.0 because it is a better (and smaller) version than 2.30.0

**Search keywords**: date-fns x-date-pickers AdapterDateFns

**Comment by LukasTy** [comment] 2024-04-12 09:02
It is [already supported](https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns).
Closing as duplicate of https://github.com/mui/mui-x/issues/12467, https://github.com/mui/mui-x/issues/12144, and https://github.com/mui/mui-x/issues/11864.

**Closed by LukasTy** 2024-04-12 09:02 UTC
Labels: status: waiting for maintainer

**Comment by AndorLundgren** [comment] 2024-04-12 09:08
my bad, thank you
