### ISSUE TITLE
[DataGrid] - CellEdit - Debounce revert value when enter key is pressed quickly

### ISSUE THREAD

**Issue by AditRien** [mui/mui-x#3729] opened 2022-01-25 02:21 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

Cell commit is reversed when Enter key is pressed before debounce timed out, and cell is getting back unwantedly to edit mode.

### Expected behavior 🤔

Commit is persistant and cell stays in view mode.

### Steps to reproduce 🕹

https://codesandbox.io/s/muddy-snow-ljr8g

Steps:

1. Click a cell to edit
2. Edit it and quickly press Enter key to validate
3. Cell goes to view mode and gets back to edit mode 
4. (bonus) Press Escape and you'll lose your edit.

### Context 🔦

I list a lot of storageBoxes which need to be daily updated and use datagrid to manage the display of the data.
When operator makes a lot of changes, some mistakes can be done along the way, and current printed data may be wrong

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

System:
    OS: macOS 12.0
  Binaries:
    Node: 17.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.2 - ~/Documents/Code/ldcb-webapp/node_modules/.bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Not Found
    Firefox: 84.0.2
    Safari: 15.0
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.65 
    @mui/icons-material: ^5.3.0 => 5.3.0 
    @mui/lab: 5.0.0-alpha.65 => 5.0.0-alpha.65 
    @mui/material: ^5.3.0 => 5.3.0 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine:  5.3.0 
    @mui/styles: ^5.3.0 => 5.3.0 
    @mui/system:  5.3.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.3.0 
    @mui/x-data-grid-pro: ^5.3.0 => 5.3.0 
    @mui/x-license-pro:  5.3.0 
    @types/react:  17.0.38 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 

</details>

**Comment by alexfauquette** [comment] 2022-01-25 17:01
Thanks for the example which is really clear.

In brief, the problem is that the denounced introduced in #3617 allows calling `setEditCellValue` after `commitRowChange`

So the commit doe not commit the new value which has been typed just before pressing <kbd>Enter</kbd> and the `setEditCellValue` reopen the input field containing the unsaved data

A simple solution would be to let the `GridEditInputCell` listen to the events about closing the editing mode, such that it stop using debounce.

A second option would be to move the debounce in the API. The `setEditCellValue` could have a `debounce` attribute which if `true` store the new value and wait before dispatching `editCellPropsChange`. The advantage is that `commitRowChange` could directly verify if there is a new value not already denounced

@m4theushw do you have an opinion or another solution I missed

**Comment by m4theushw** [comment] 2022-01-26 02:34
I'm almost sure that this will be fixed by #3612 too. I need to investigate further.

> A second option would be to move the debounce in the API. The setEditCellValue could have a debounce attribute which if true store the new value and wait before dispatching editCellPropsChange. The advantage is that commitRowChange could directly verify if there is a new value not already denounced

This will be possible to implement in `preProcessEditCellProps` with #3612. Basically we also add a debounce to the validation.

**Comment by alexfauquette** [comment] 2022-01-26 08:51
Does your user use a lot the keyboard?

If it is a problem for them, a workaround could be to override the `GridEditInputCell` to remove the debounce, the time we fix it.

The code of the component is [here](https://github.com/alexfauquette/material-ui-x/blob/master/packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx). You can copy it, remove the debounce and use `renderEditCell` in column definition for string and numbers

Here is your demo with the workaround
https://codesandbox.io/s/peaceful-dew-i9jxm?file=/src/App.js

**Comment by AditRien** [comment] 2022-01-26 10:04
Hey, thanks for your answers.
Yep, they are essentially working with the keyboard.

Thanks for the `GridEditInputCell` workaround. I'll definitely try this.

Currently, I just added a timeout to the `CellEditCommit Event` to force the commit after the debounce happens.

```
const handleCellEditCommit = React.useCallback(
    (params) => {
      setTimeout(() => {
        const { id } = params;
        const model = apiRef.current.getEditRowsModel();
        const newRow = model[id];
        const oldRow = apiRef.current.getRow(id);

        const [field] = (newRow && Object.keys(newRow)) || [];

        if (field && newRow[field].value !== oldRow[field]) {
          apiRef.current.commitCellChange({ id, field });
          apiRef.current.setCellMode(id, field, 'view');
        }
      }, 445);
    },
    [apiRef]
  );
```

It's not perfect, but it gets the job done and doesn't override too much of your logic.

**Comment by m4theushw** [comment] 2022-01-26 15:36
Yes, the timeout works. Note that we use 500ms for the debounce. If the user is fast enough to type another character just after the commit the bug will persist.

#3612 won't fix this although it will make easier to do a workaround. To properly fix it I would propose to incorporate into `setEditCellValue` an option to set the debounce time. If > 0ms we wait for the debounce before commiting.

**Closed** 2022-02-09 13:21 UTC
Labels: bug 🐛, component: data grid, regression, feature: Editing

**Comment by xw-Zhou** [comment] 2022-02-10 11:39
When will this problem be fixed
