### ISSUE TITLE
[docs] Page layout on mui.com causes a horizontal scroll bar on content

### ISSUE THREAD

**Issue by dmcgarry-well** [mui/mui-x#4997] opened 2022-05-24 15:18 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Unrelated to the repo, but there's no where else to report it. On https://mui.com/x/api/data-grid/data-grid-pro/ you can't read a prop and its description at the same time, you have to scroll left and right. Tested in latest Mac Chrome, Safari, and Edge.

### Expected behavior 🤔

be able to view the content without scrolling horizontally

### Steps to reproduce 🕹

Steps:

1.
2. view the props section
3. try to read a prop and its description without scrolling horizontally.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

We have a pro plan, but I don't have the number.

**Comment by oliviertassinari** [comment] 2023-01-25 20:48
It looks like a duplicate of https://github.com/mui/material-ui/issues/34085.

**Comment by oliviertassinari** [comment] 2024-07-24 12:24
I'm closing since @alexfauquette fixed this already.

**Closed by oliviertassinari** 2024-07-24 12:24 UTC
Labels: docs, dx, enhancement
