### ISSUE TITLE
[docs] renderInput migration to v6 unclear

### ISSUE THREAD

**Issue by kirill-develops** [mui/mui-x#8540] opened 2023-04-07 04:21 UTC
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/migration/migration-pickers-v5/

### Kind of issue

Unclear explanations

### Issue description

attempting to refactor to v6 method. In migration URL, it suggests using `componentsProp` however it's depreciated according to VSCode. this is my original code:
```JavaScript
 <TimePicker
          // ...
          renderInput={(props) => (
            <TextField
              {...props}
              onBlur={() => setFieldTouched(`${stepName}.time`, true, false)}
              helperText={errors[stepName]?.time}
              error={Boolean(errors[stepName]?.time)}
              required
              fullWidth
            />
          )}
        />
```

tried the following with no luck:
```JavaScript
<DatePicker
          // ...
          TextField={{
            onBlur: () => setFieldTouched(`${stepName}.date`, true, false),
            helperText: `${errors[stepName]?.date}`,
            error: touched[stepName]?.date && Boolean(errors[stepName]?.date),
            required: true,
            fullWidth: true,
          }}
/>
```

as well as:
```JavaScript
 <TimePicker
          // ...
          TextField={(props) => (
            <TextField
              {...props}
              onBlur={() => setFieldTouched(`${stepName}.time`, true, false)}
              helperText={errors[stepName]?.time}
              error={Boolean(errors[stepName]?.time)}
              required
              fullWidth
            />
          )}
        />
```

with no success of recreating same behaviour

**Comment by LukasTy** [comment] 2023-04-07 07:10
Thank you for opening this issue! 🙏 

> In migration URL, it suggests using `componentsProp` however it's depreciated according to VSCode. 

Yes, it is marked as deprecated, but it's not going anywhere during the current major, we plan to drop the `components` props only in v7. If you wish to use the new API, you can by no means do it, they are almost equivalent, except for the fact that `slots` has lowercase items, whereas `components` expect them in uppercase.
You can also use the [provided optional codemod](https://mui.com/x/migration/migration-pickers-v5/#rename-components-to-slots-optional) to help you in migrating to the new API.

FYI: We also have [an open PR](https://github.com/mui/mui-x/pull/8341) investigating the feasibility of replacing `components` references in the migration doc with `slots`. 😉 

In regards to the issue itself—you do not seem to be extending the functionality of the original `TextField` component, thus, on v6 you can probably get away with avoiding the component override and just passing the extra props you need via:
```tsx
componentsProps={{
// or
slotProps={{
  textFIeld: {
    onBlur: () => setFieldTouched(`${stepName}.time`, true, false),
    helperText: errors[stepName]?.time,
    error: Boolean(errors[stepName]?.time),
    required: true,
    fullWidth: true,
  }
}}
```

If you are still having issues, please provide a minimal reproduction example using a CodeSandbox or any similar tool so that we could better investigate your problem. 😉

**Comment by kirill-develops** [comment] 2023-04-09 19:10
Thanks for the clarification, @LukasTy.

[https://mui.com/x/api/date-pickers/date-time-picker/](https://mui.com/x/api/date-pickers/date-time-picker/)
in the API documentation above, I was unaware that slots were meant to nest under `slotProps`.

Your code snippet fixed the problem immediately.

Kudos!

**Comment by LukasTy** [comment] 2023-04-09 20:42
> https://mui.com/x/api/date-pickers/date-time-picker/
> in the API documentation above, I was unaware that slots were meant to nest under `slotProps`, and I thought they were to be treated as a prop.

That's a really good observation, thank you. 👌 Including a small paragraph and/or example on how to use the slots in the API docs `slots` section probably wouldn't hurt. 🙈 



> Additionally, the new Field component works incredibly and my hats go off to you guys for the update.
> 
> Kudos!

It's really nice hearing such praises, we're glad that you are liking it and hope that the end-users will appreciate it as well. 🙌 
The team does feel that the new `field` approach is way superior to the previously used `masked` approach. Of course, nothing is perfect, there are known and possibly unknown issues as well as new challenges that pop up because of the change, but for most users, it should provide an easier way of entering and manipulating dates. 🤞 

I'm closing the issue as the main topic seems to be resolved. If you feel that we are still missing something—feel free to re-open it or create a different issue for a separate topic. 😉

**Closed by LukasTy** 2023-04-09 20:42 UTC
Labels: docs, component: pickers, dx, support: docs-feedback
