### ISSUE TITLE
[DataGrid] Autosizing does not work correctly

### ISSUE THREAD

**Issue by RazbezhkinAV** [mui/mui-x#11329] opened 2023-12-07 10:57 UTC
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/autosizing-mui-data-grid-hfrxgg?file=%2Fsrc%2FApp.tsx%3A30%2C23

Steps:
1. Hover over the text 'Point it at me'

### Current behavior

The grid does not stretch when opened
Even with manual installation of autosize, when you click on the button, not all columns are stretched by context
![image](https://github.com/mui/mui-x/assets/90248363/4745d381-3958-4749-bc2a-60398a023f4e)

### Expected behavior

The grid should be stretched according to the size of the input data

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22621
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (119.0.2151.97)

```
</details>

**Search keywords**: Autosizing , DataGrid
**Order ID**: 70308

**Comment by RazbezhkinAV** [comment] 2023-12-07 13:58
@michelengelen 
I'm sorry, everything should be working now.
https://codesandbox.io/p/sandbox/autosizing-mui-data-grid-hfrxgg?file=%2Fsrc%2FPopUpComponent.tsx%3A64%2C14

**Comment by michelengelen** [comment] 2023-12-07 14:21
Ok, now I can see what's not working.
@cherniavskii could you have a look at this?
The autosize on mount and on click is behaving differently and it does not expand all columns enough to view the values in their entirety!
Thanks! 🙇🏼

**Comment by romgrk** [comment] 2023-12-08 01:40
As for the issue with `autosizeOnMount`, also don't understand the difference for the last two columns.

Note: your columns are constant, you can extract them outside the component instead of memo'ing them.

**Comment by MiLandry** [comment] 2023-12-14 02:52
Any ETA on this fix? The slight buffer seems like that would work. I'd like to note that the calculation is easily thrown off when the cells have borders, or the `showCellVerticalBorder` prop is passed in.

**Comment by romgrk** [comment] 2024-03-07 20:36
The issue is fixed in `7.0.0-beta.5`: https://codesandbox.io/p/sandbox/nifty-einstein-6jzt2y

Is it possible for you to use the v7 version? We're about to release it and we'd rather not port bugfixes. I've adapted your example to one minor breaking change (`valueGetter` args).

**Closed as completed** 2024-03-14 21:11 UTC
Labels: type: bug, scope: data grid, status: waiting for author, feature: Column resize

**Comment by hadeebataj** [comment] 2024-10-21 10:44
What is the final resolution to this? if I use `autosizeOnMount` it still only auto sizes the visible columns and when I scroll right to bring other columns into view, it does not auto resize as expected.

**Comment by romgrk** [comment] 2024-10-29 11:21
Please open a new issue with your code and reproduction steps.
