### ISSUE TITLE
[data grid] First row is 1px taller than other rows

### ISSUE THREAD

**Issue by janeklb** [mui/mui-x#14195] opened 2024-08-13 18:24 UTC
### Steps to reproduce

Link to live example: (required)

Steps:
1. Go to https://mui.com/x/react-data-grid/
2. Measure the height of the 1st row of any of the examples (do not look at css and/or DOM element dimensions, but actually count the pixels)
3. Measure the height of any of the other rows (in the same example)

### Current behavior

The 1st row is one pixel taller / higher than the other rows in the datagrid.

eg. 1st row in [this example](https://mui.com/x/react-data-grid/#mit-license-free-forever) has height 52 pixels (measured by taking a screenshot and uploading to https://pixlr.com/editor/ and then using the marquee to select the row height, and then taking a screenshot of that :phew:)

![image](https://github.com/user-attachments/assets/02592b62-1b8c-4612-862b-fbebddc06664)

and 2nd row has a height of 51 pixels (same as all subsequent rows)

![image](https://github.com/user-attachments/assets/7c0802e3-e695-4c98-b4d6-d9e2922167f5)

### Expected behavior

All rows have an equal height (when not using custom / variable row heights)

(clearly this is a minor issue, if it can even be called an issue.. but imo worth noting nonetheless)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

- Tested with latest version of Chrome and Brave

```
  System:
    OS: macOS 14.5
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    npm: 10.8.2 - ~/xxxxxxxxx/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 127.0.6533.100
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react: 11.11.4 => 11.11.4
    @emotion/styled: 11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.6
    @mui/icons-material:  5.16.4
    @mui/material: ^5.16.6 => 5.16.6
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system: ^5.16.6 => 5.16.6
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-data-grid:  7.12.0
    @mui/x-data-grid-pro: ^7.12.0 => 7.12.0
    @mui/x-date-pickers:  7.12.0
    @mui/x-date-pickers-pro: ^7.12.0 => 7.12.0
    @mui/x-internals:  7.12.0
    @mui/x-license:  7.12.0
    @mui/x-license-pro:  6.10.2
    @types/react: ^17.0.44 => 17.0.80
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: 5.4.5 => 5.4.5
```
</details>

**Search keywords**: datagrid row height
**Order ID**: 50436

**Comment by michelengelen** [comment] 2024-08-14 10:32
Hey @janeklb I am not able to reproduce this.
My screenshots are both at 104px height (retina display), so the values are correct.
Could you maybe re-assess and see if you can do this in a clean browser with no plugins? Sometimes those can mess with the layout.
Thanks!

**Comment by janeklb** [comment] 2024-08-14 21:43
Here's the result with Chrome in incognito mode w/o any extensions (with a retina display)

![image](https://github.com/user-attachments/assets/a185d05a-d6df-4924-9692-3d5f1aa6a0aa)

Im measuring 104px height (_between_ the borders) on the 1st row, and 102px between the subsequent ones.

Same result with safari:

![image](https://github.com/user-attachments/assets/4a5d03ee-e8e3-4c1f-b1bc-660f68ee8db3)

**Comment by arminmeh** [comment] 2024-08-15 04:48
I think that I found the reason why this happens
If you inspect the styles, all rows are 52px, but if you check the cells inside, you can see that in the first row the cell border is transparent, while for the other rows, cells have a visible border.
The first one is transparent to avoid creating double border with the header row.
We might add negative margin to overlap these two, but it should be checked how we calculate render context and if that update will create a case where that calculation might get wrong

**Comment by arminmeh** [comment] 2024-08-16 07:31
@michelengelen that looks fine to me
We can also remove transparent border color from the styles so that it becomes visible why this is done, in case someone want to remove/refactor the margin later

**Comment by michelengelen** [comment] 2024-08-16 13:52
Closing this as we discovered that the issue does not justify the downsides to it.
Reference: https://github.com/mui/mui-x/pull/14229#issuecomment-2293533225

**Closed by michelengelen** 2024-08-16 13:52 UTC
Labels: bug 🐛, component: data grid, support: pro standard

**Comment by janeklb** [comment] 2024-08-16 13:57
Fair enough. Thank you for taking a look!
