### ISSUE TITLE
Custom checkbox column throws warning

### ISSUE THREAD

**Issue by calteran** [mui/mui-x#6067] opened 2022-09-07 13:51 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using a custom checkbox column like

```
{
      ...GRID_CHECKBOX_SELECTION_COL_DEF,
      headerName: 'Checkbox',
},
```

the browser throws a warning:

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/17766868/188890153-bca843d7-c110-4e3d-a3ff-cedafda210cb.png">

### Expected behavior 🤔

There should not be a warning.

### Steps to reproduce 🕹

Link to live example (issue seen in actual example from the MUI-X docs): https://codesandbox.io/s/tu72cu?file=/demo.js

Steps:
1. Follow the documentation on custom checkbox columns
2. Load in browser
3. See warning

### Context 🔦

In my particular case, I'm configuring the checkboxSelection column to have a custom header name because the header appears in the enable/disable Columns menu in the toolbar and I want it to have a more user-friendly name.

But since the warning shows up the the vanilla example, any use-case or context will likely experience this issue.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 17.8.0 - ~/.nvm/versions/node/v17.8.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v17.8.0/bin/yarn
    npm: 8.12.2 - ~/.nvm/versions/node/v17.8.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Edge: Not Found
    Firefox: 104.0.1 <- tested here
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.95 
    @mui/core-downloads-tracker:  5.10.3 
    @mui/icons-material: ^5.10.3 => 5.10.3 
    @mui/lab: ^5.0.0-alpha.97 => 5.0.0-alpha.97 
    @mui/material: ^5.10.3 => 5.10.3 
    @mui/private-theming:  5.10.3 
    @mui/styled-engine:  5.10.3 
    @mui/system:  5.10.3 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.3 
    @mui/x-data-grid:  5.17.1 
    @mui/x-data-grid-pro: ^5.17.0 => 5.17.1 
    @mui/x-license-pro:  5.17.0 
    @types/react:  18.0.14 
    react: ^18.1.0 => 18.2.0 
    react-dom: ^18.0.0 => 18.2.0 
    typescript:  4.7.4
```
</details>

**Comment by m4theushw** [comment] 2022-09-09 00:03
Duplicate of #4769

As a workaround you can try https://github.com/mui/mui-x/issues/4769#issuecomment-1119465559

**Closed by m4theushw** 2022-09-09 00:03 UTC
Labels: status: needs triage
