### ISSUE TITLE
[DataGrid] Ensure `preProcessEditCellProps` runs at least once

### ISSUE THREAD

**Issue by nickraphael** [mui/mui-x#5009] opened 2022-05-25 08:06 UTC
### Order ID 💳

41833

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have a grid where every row enters edit mode when the use clicks on an edit button in the toolbar.

  const handleEditClick = React.useCallback(() => {
    setEditMode(true);
    apiRef.current.getAllRowIds().forEach((id) => {
      apiRef.current.startRowEditMode({ id });
    });
  }, [apiRef]);

This works as expected.  However, when the user clicks on the save button in the toolbar, none of the validations fire.  Specifically, none of the preProcessEditCellProps events fire, which is the way validation is handled in the docs.  If the user clicks into the input controls, then validation fires - but not if they simply click Edit then Save.  

The same occurs when adding a new row.  Since it's a new row, the inputs are empty.  But when the Save is clicked, no validation happens and a blank row gets processed.

Is there a way to loop through all the rows and call preProcessEditCellProps or something?

Thanks

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment] 2022-05-25 12:26
@m4theushw Can you take a look?

**Comment by m4theushw** [comment] 2022-05-25 14:38
`preProcessEditCellProps` is only called when updating the value of the input, not when changing the row mode to `view`.

Could you provide a reproduction to understand how you're saving the rows? [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point.

**Comment by nickraphael** [comment] 2022-05-26 05:40
Hi,
I've set up a sandbox.
https://codesandbox.io/s/data-grid-community-forked-in5rkb

If you click edit, all rows go into edit mode.  If col2 < 3 then it's invalid.  So if you change the col2 value you will see it change colour.  However, row 1 starts in an invalid state since col2 = 2.  But if you were to immediately click save, then we skip validation.  You'll see the save payload in the console.

Same goes for new rows.  Click edit then add and you get a new row that starts in an invalid state because col2 = 0.

So the question really is:  how do I trigger the validation code in preProcessEditCellProps when the user clicks save.

Steps:
1. Click Edit
2. Notice row 1 should be invalid because col2 = 2.
3. Click Add to get a new row.
4. Notice new row should be invalid because col2 = 0.
5. Click Save and see save payload in console.
6. Notice that preProcessEditCellProps was never called and therefore validation was skipped.

**Comment by m4theushw** [comment] 2022-05-27 00:24
Interesting use case. I didn't think about this situation. To close this issue we should verify if all `preProcessEditCellProps` ran at least once before stopping the edit mode. Additionally, I think we should also run them when the inputs are blurred. For this, we need to expose in the API a method to manually trigger the validation, maybe `validateField(field)`. It would be closer to how react-final-form works: https://codesandbox.io/s/data-grid-community-forked-gk0cl8?file=/src/App.tsx In this example, all fields appear as "valid" but once one is clicked it's validated.

As a workaround for now, you can call `apiRef.current.setEditCellValue` immediately after clicking Edit and also when clicking Add. This will simulate the user entering a value and, as consequence, will trigger validation. Here's the updated CodeSandbox: https://codesandbox.io/s/data-grid-community-forked-gk0cl8?file=/src/App.tsx

**Comment by nickraphael** [comment] 2022-05-27 01:00
Thanks,
I'll give that a try.

FYI, I created an example using the 'latest' versions...
https://codesandbox.io/s/data-grid-community-forked-4hegve

**Comment by nickraphael** [comment] 2022-06-03 05:46
Hi again,
I can't get your solution to work on the latest version of the grid.  Your sandbox is using v5.7.0.  I'm trying to get this issue fixed in the same grid as another issue I have raised...
https://github.com/mui/mui-x/issues/5089

So I'm trying to solutions to both these issues using the same version and same setting for experimentalFeatures.

**Comment by m4theushw** [comment] 2022-06-03 22:38
@nickraphael I updated my CodeSandbox to the latest version. You need to use a `setTimeout` if you want all rows in edit mode and still validate them when changing the mode.

**Closed as completed** 2022-12-02 21:59 UTC
Labels: type: bug, scope: data grid, feature: Editing

**Comment by BLiAlPx** [comment] 2023-04-03 09:48
I'm facing this issue too. Instead of validating on clicking add or edit, I want to validate on clicking save. Calling `apiRef.current.setEditCellValue` doesn't work because user input is lost and `apiRef.current.getCellValue` doesn't return the new values since they haven't been committed yet.
Exposing a method to trigger validation on a particular cell (by id and field) and/or fetch the overall error status of a row (by id) should fulfill most use cases.

**Comment by jason-kwon-oneoncology** [comment] 2023-04-18 20:09
I am wondering about the same use case as @BLiAlPx. I would like to run validation on save.

**Comment by Luis-Ramirez21x** [comment] 2023-07-26 23:32
I found a solution to this by adding a `useEffect` to the Custom Edit component show in the Docs, [https://mui.com/x/react-data-grid/editing/#with-debounce](url)  . The `useEffect` checks if the row has prop `row?.isNew`  if so it triggers the `apiRef.current.setEditCellValue({ id, field, value: '' });`. Struggled for a while trying to get that error validation to work.

**Comment by Falven** [comment] 2023-08-12 21:12
Can it be triggered by publishing an event? Like `cellEditStop` or something?
I need to trigger this without changing the value...

**Comment by kno-raziel** [comment] 2024-05-11 03:27
@m4theushw I dont see the documentation or any reference in the repository about `ensurePreProcessEditCellPropsRanOnce` which is being use in the sample you [shared](https://codesandbox.io/s/data-grid-community-forked-gk0cl8?file=/src/App.tsx) , is there a way to trigger the validation on demand in v6?

**Comment by jukkahyv** [comment] 2024-07-01 10:28
It looks like the `ensurePreProcessEditCellPropsRanOnce` feature was never merged. The PR is closed (not merged). I just ran into this myself. It seems like a very basic use case, and using `setEditCellValue` feels hacky. I would really appreciate some API for imperatively triggering the validation.

**Comment by rdalkire** [comment] 2024-09-27 22:07
@m4theushw Is there some way to reopen this?  If we create a new issue, it would be a duplicate of this.  It's a major problem and should not have been closed.

**Comment by rdalkire** [comment] 2024-09-27 22:16
@Luis-Ramirez21x when I re-implement your solution from [the previous comment](https://github.com/mui/mui-x/issues/5009#issuecomment-1652682508) (thanks for the screenshot, but actual code in the form of text would have been much more helpful), and assigned the result to the `renderEditCell` column definition property, I got "Rendered more hooks than in the previous render" and the component wouldn't show.   😐

**Comment by masull** [comment] 2025-04-02 18:04
I am trying to validate required fields on a new row when save is clicked. The ensurePreProcessEditCellPropsRanOnce  does not seem to have been implemented. It is inconsistent to be able to validate everything but new rows using preProcessEditCellProps.

**Comment by oleh-luchnykov** [comment] 2025-04-18 09:40
@m4theushw I need validation on save when trying to save a new row. Is that possible?
