### ISSUE TITLE
"preProcessEditCellProps" callback doesn't work on direct key press / while start editing with keyboard

### ISSUE THREAD

**Issue by atsoy** [mui/mui-x#11071] opened 2023-11-17 15:10 UTC
### Steps to reproduce

Link to live example: https://codesandbox.io/s/distracted-goodall-vfjx2z?file=/src/demo.tsx
Steps:
1. Focus one of the email fields
2. Type "k"
3. Exit edit mode (e.g "Enter", "Tab")

### Current behavior

Validation callback doesn't work on 1st character (direct key press)

### Expected behavior

Validation applies already on 1st character (direct key press)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.6.2
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.58
    Safari: 17.1
  npmPackages:
    @emotion/react: ~11.11.1 => 11.11.1 
    @emotion/styled: ~11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.13 
    @mui/core-downloads-tracker:  5.14.7 
    @mui/material: ~5.14.7 => 5.14.7 
    @mui/private-theming:  5.14.7 
    @mui/styled-engine:  5.14.7 
    @mui/system:  5.14.7 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.7 
    @mui/x-data-grid:  6.12.1 
    @mui/x-data-grid-pro: ~6.12.1 => 6.12.1 
    @mui/x-date-pickers:  6.12.1 
    @mui/x-date-pickers-pro: ~6.12.1 => 6.12.1 
    @mui/x-license-pro:  6.10.2 
    @types/react: 18.2.24 => 18.2.24 
    react: ~18.2.0 => 18.2.0 
    react-dom: ~18.2.0 => 18.2.0 
    typescript: 5.2.2 => 5.2.2 

```
</details>

**Search keywords**: preProcessEditCellProps, cell validation, validation, input validation
**Order ID**: 62555

**Comment by atsoy** [comment] 2023-11-17 15:42
#10930 #11064 seems to be related

**Comment by michelengelen** [comment] 2023-11-20 13:21
Thanks @atsoy ... This is indeed a duplicate of #10930 
I will close this now, but will transfer any additional info you gathered to it.
Thanks again... We appreciate it! 🙇🏼

**Closed by michelengelen** 2023-11-20 13:21 UTC
Labels: status: waiting for maintainer
