### ISSUE TITLE
MUI DataGrid NoResultsOverlay Custom Component Issues

### ISSUE THREAD

**Issue by sampathkumarm** [mui/mui-x#5811] opened 2022-08-16 15:40 UTC
Buttons under the NoResultsOverlay or NoRowsOverlay component are not clickable due to absolute positioning and no z-index.

Also if the data grid is set to autoHeight, the overlay components are cut-off.

Code Sandbox link below to reproduce the issue.

https://codesandbox.io/s/customemptyoverlaygrid-demo-mui-x-forked-6hu6f6?file=/demo.js

**Comment by sampathkumarm** [comment] 2022-08-16 16:00
@oliviertassinari, can anyone help or provide any examples for this?

**Comment by sampathkumarm** [comment] 2022-08-16 17:21
The custom component gets wrapped by an absolutely positioned dub with no z-index. Adding that fixes the issue.

But how to add it through componentProps or css is the question.

Please help.

![image](https://user-images.githubusercontent.com/6489309/184940000-fb8c25c7-1179-40dc-805f-bb57a4b38c20.jpeg)

**Comment by cherniavskii** [comment] 2022-08-17 20:55
Hey @sampathkumarm 
This looks like a duplicate of https://github.com/mui/mui-x/issues/5725
Tomorrow we will release a fix that will make [this workaround](https://github.com/mui/mui-x/issues/5725#issuecomment-1216503548) possible.

In a longer term - I've been working on better overlays layout in https://github.com/mui/mui-x/pull/5808 that would make overlays clickable out of the box.

**Closed** 2022-08-17 20:56 UTC
Labels: duplicate, component: data grid

**Comment by sampathkumarm** [comment] 2022-08-17 22:20
> Hey @sampathkumarm 
> 
> This looks like a duplicate of https://github.com/mui/mui-x/issues/5725
> 
> Tomorrow we will release a fix that will make [this workaround](https://github.com/mui/mui-x/issues/5725#issuecomment-1216503548) possible.
> 
> 
> 
> In a longer term - I've been working on better overlays layout in https://github.com/mui/mui-x/pull/5808 that would make overlays clickable out of the box.

Thank you so much, I am going to try that and confirm. 

Also there is another piece to this, the height of the data grid does not grow based on the overlay content.

Hopefully you are looking at that too? Thanks much.

**Comment by cherniavskii** [comment] 2022-08-18 09:50
> Thank you so much, I am going to try that and confirm.

Great!
Would you also be willing to try out new overlays layout from https://github.com/mui/mui-x/pull/5808 to confirm it resolves your issue and doesn't introduce a breaking change for you? You can install a build from that PR using [this link](https://pkg.csb.dev/mui/mui-x/commit/91c641c4/@mui/x-data-grid) and following [this guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#how-can-i-use-a-change-that-wasnt-released-yet).


> Also there is another piece to this, the height of the data grid does not grow based on the overlay content.

It's by design - overlay should take the height of the grid, not the other way around.
In case of `autoHeight` and no rows - the grid height is set to `2 * rowHeight`.

**Comment by adammartiska** [comment] 2023-06-28 13:57
Hello, is this solved somehow? I am trying to use more complex NoRowsOverlay component that will display button along with some text underneath. I am trying the workaround with styling noRowsOverlay through componentsProps but seems like it is nor working. Is there any workaround that is currently working for this? We are using mui version **5.6.1**

**Comment by rulim34** [comment] 2023-08-19 12:34
> It's by design - overlay should take the height of the grid, not the other way around.
In case of `autoHeight` and no rows - the grid height is set to `2 * rowHeight`.

How can I customize the height then? It's too small for my custom NoRowOverlay.

**Comment by MBilalShafi** [comment] 2023-08-20 13:22
@rulim34 I guess this should be easily customizable by overriding respective CSS selectors. Could you provide a codesandbox example where the issue could be reproduced?

**Comment by rulim34** [comment] 2023-08-21 07:00
@MBilalShafi can you open this? I'm not quite familiar with codesandbox
https://codesandbox.io/p/sandbox/tender-liskov-s8pznf

**Comment by cherniavskii** [comment] 2023-09-01 13:07
Hi @rulim34 
Currently you cannot customize the height, but I've opened a PR that would allow to use CSS variable for this: https://github.com/mui/mui-x/pull/10203
