### ISSUE TITLE
React MUI Date Pickers not picking date for iOS Device

### ISSUE THREAD

**Issue by FarrukhXeb** [mui/mui-x#5031] opened 2022-05-27 08:27 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

So I've implemented the Date picker for my React Web App and It works great for Windows and Android but not for iOs devices. I've tested it on BrowserStack as well. Here is my code
`        <LocalizationProvider dateAdapter={AdapterDateFns}>
          <DatePicker
            label={placeholder}
            value={value}
            onChange={(newValue) => {
              onChange({
                target: {
                  name,
                  value: new Date(newValue).toLocaleDateString(),
                },
              });
            }}
            disabled={disabled}
            showToolbar={false}
            disablePast
            renderInput={(params) => (
              <TextField helperText={_getHelperText(optional, helperText)} error={error} variant="filled" fullWidth {...params} />
            )}
          />
        </LocalizationProvider>`
I've created a common component so don't get confused about how I've used the onChange listener.
It doesn't allow me to pick any date on the iPhone device not sure why. I've researched over the documentation whether some props are missing but couldn't find any,
It should allow any device to pick a date and pass the value to the onChange listener.

The packages I'm using are
@mui/x-date-pickers/AdapterDateFns
@mui/x-date-pickers/LocalizationProvider
@mui/x-date-pickers/DatePicker

 **"@mui/x-date-pickers": "^5.0.0-alpha.4",**

**Comment by cherniavskii** [comment] 2022-05-27 17:48
Hey @FarrukhXeb 
Can you reproduce it with this demo? https://mui.com/x/react-date-pickers/date-picker/#basic-usage
Works for me just fine

https://user-images.githubusercontent.com/13808724/170763969-c36110d2-13de-473d-9289-a23511a4ba25.MP4

**Comment by cherniavskii** [comment] 2022-05-27 17:49
Hey @FarrukhXeb 
Can you reproduce it with this demo? https://mui.com/x/react-date-pickers/date-picker/#basic-usage
For me it works just fine:

https://user-images.githubusercontent.com/13808724/170764095-28cb3c7f-2874-4a34-a517-bd5541777216.MP4

**Comment by FarrukhXeb** [comment] 2022-05-27 17:59
Sure here’s a video the first one works fine which is from the documentation but my web app doesn’t work for iOS although It’s working perfectly for Android and Windows OS

Uploading IMG_3144.MOV…

**Comment by FarrukhXeb** [comment] 2022-05-27 18:12
One more thing the values are being assigned it's just that it's not visible

**Comment by FarrukhXeb** [comment] 2022-05-27 18:57
@cherniavskii I just tested something out by debugging my iPhone with https://inspect.dev/ tool.
Here is what I can see in the inspector tab connected to my iPhone 12 mini. Forgot to mention the device I was using 😅
![Screenshot 2022-05-27 235441](https://user-images.githubusercontent.com/43153347/170773476-29c8432a-64ed-4c9d-bdae-a247da6fb484.png)
The **value** attribute is not populated.

**Comment by FarrukhXeb** [comment] 2022-05-27 19:19
Found the issue! @cherniavskii So the value which I was passing to my Generic Input was parsed into `newValue.toLocaleDateString()`. I don't know why It's not working for iOS but I'll have to format the data once the form is submitted. Y

**Comment by cherniavskii** [comment] 2022-05-27 19:43
Did you manage to resolve the issue?

**Comment by FarrukhXeb** [comment] 2022-05-27 19:44
@cherniavskii Yes

**Comment by cherniavskii** [comment] 2022-05-27 19:45
That's great to hear!
I'm closing the issue then. since there's no action required on our side :)

**Closed** 2022-05-27 19:46 UTC
Labels: component: pickers

**Comment by ShivamChaudhary18** [comment] 2023-07-14 08:34
I still have the issue with updated code , please help

**Comment by ShivamChaudhary18** [comment] 2023-07-14 08:35
<LocalizationProvider dateAdapter={AdapterDateFns}> 
                        <MobileDatePicker                        
                        label="Custom input"
                        views={["year"]}
                        value={date}  
                        maxDate={new Date()}
                        onChange={(newValue) => {
                            setYear(newValue)
                            setYearError("")
                            }}
                        inputRef={dateRef.current}
                        renderInput={({ inputRef, inputProps, InputProps }) => (
                            <Box sx={{ position:'relative'}}>
                            <TextField
                                id="outlined-basic"
                                InputProps={{readOnly: true, }}
                                fullWidth
                                label={'Year'}
                                variant="outlined"
                                ref={inputRef}{...inputProps} 
                                // disabled={true}
                            /> 
                            </Box>
                        )}
                        />  
                    </LocalizationProvider>

**Comment by LukasTy** [comment] 2023-07-14 08:45
@ShivamChaudhary18 Please open a separate issue detailing your use case and the issue you are having.
If you could provide a working live example, it would greatly help in understanding the problem more quickly.
You can use a codesandbox for providing a live example with a minimal reproduction code that is causing you issues.

By the way, have you tried upgrading to v6 or testing if the problem still exists on v6 version? 🤔
