### ISSUE TITLE
[material-ui] Add a Split Pane component

### ISSUE THREAD

**Issue by MartinXPN** [mui/mui-x#13931] opened 2024-02-20 07:17 UTC
### Summary

It would be so great to have MUI-native support for split-pane.
Seems like most libraries out there stopped updating and have many unresolved issues.

### Motivation

I would love to use something like https://github.com/neocturne/react-multi-split-pane built natively into MUI.

**Search keywords**: split-pane

**Search keywords**: 

**Search keywords**:

**Comment by oliviertassinari** [comment] 2024-07-21 15:13
Duplicate of #512

**Closed by oliviertassinari** 2024-07-21 15:13 UTC
Labels: duplicate, new feature, waiting for 👍, package: material-ui
