### ISSUE TITLE
[data grid] `onColumnVisibilityModelChange` event returns empty object on show all columns from columns option in toolbar

### ISSUE THREAD

**Issue by zmirnes** [mui/mui-x#13974] opened 2024-07-24 22:06 UTC
### Steps to reproduce

Link to live example:  [https://codesandbox.io/p/devbox/2nrtmg]( https://codesandbox.io/p/devbox/2nrtmg)

Steps:
1. Run [https://codesandbox.io/p/devbox/2nrtmg]( https://codesandbox.io/p/devbox/2nrtmg)
2. Open console
3. Click on "Columns" in toolbar above DataGrid and then click on show/hide columns

### Current behavior

onColumnVisibilityModelChange event returns empty object on show all columns from columns option in toolbar but on hide all columns return list of all columns with false values

### Expected behavior

The expected behavior is that the onColumnVisibilityModelChange event should return a list of all columns with true values when the "Show all columns" button is pressed, similar to how it returns a list of all columns with false values when the "Hide all columns" button is pressed.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: onColumnVisibilityModelChange, data grid, empty object, hide all columns, show all columns

**Comment by michelengelen** [comment] 2024-07-25 08:26
Hey @zmirnes it is the expected behavior, since "Show all" will return to its initial state. 

Duplicate of #12236

**Closed by michelengelen** 2024-07-25 08:26 UTC
Labels: bug 🐛, component: data grid, status: waiting for maintainer

**Comment by subashthiru3** [comment] 2025-03-05 13:33
The onColumnVisibilityModelChange event returns an empty object when showing all columns using the columns option in the toolbar. I am still facing this issue
