### ISSUE TITLE
[data grid] Performance issue with arrow keys

### ISSUE THREAD

**Issue by bpiggin** [mui/mui-x#5557] opened 2022-07-21 09:49 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

On a Macbook Pro M1 (throttled 6x)

https://user-images.githubusercontent.com/56440821/180182819-3eeb8007-1c80-43e8-93f9-5ed54a599de9.mov

https://mui.com/x/react-data-grid/#commercial-version

### Expected behavior 🤔

We've had to go with an alternative library react-data-grid. This is the same PC again throttled 6x.

https://user-images.githubusercontent.com/56440821/180183106-34670966-6287-40a6-80f7-85c892213d8f.mov

https://adazzle.github.io/react-data-grid/#/common-features

### Steps to reproduce 🕹

Link to live example: https://mui.com/x/react-data-grid/#commercial-version

Steps:
1. Go to example in docs
2. Open the chrome developer tools
3. Go to performance tab
4. Change CPU to "6x slowdown"
5. Navigate around cells by holding arrow keys and see lag

### Context 🔦

Tested prototype product on user laptops which were pretty old and immediately encountered performance issues. Able to replicate by throttling CPU on the performance tab. Unfortunately, this makes the library unsuitable for our purposes.

https://mui.zendesk.com/agent/tickets/4212

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.4
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 3.1.0 - ~/dev/pactio-mvp/node_modules/.bin/yarn
    npm: 8.9.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
```
</details>

![image](https://user-images.githubusercontent.com/56440821/180183787-dad40948-09ce-498d-851d-dd391f6d6904.png)

### Order ID 💳 (optional)

47208

**Comment by oliviertassinari** [comment] 2022-07-21 17:42
@bpiggin Thanks! It seems a bit related to #5547. We will refund your order.

I have taken the data set and display of the "Expected behavior" demo to adapt it to the latest version of the Data Grid Pro in: https://codesandbox.io/s/datagridprodemo-demo-mui-x-forked-cvxwnb?file=/demo.tsx. Now, we can compare the two in production a bit more accurately:

1. MUI X https://csb-cvxwnb.vercel.app/
2. adazzle https://adazzle.github.io/react-data-grid/#/common-features

I can clearly reproduce the problem. When keeping the <kbd>ArrowDown</kbd> with a CPU throttling at x6:

- A. We reach the bottom of the scroll clearly faster on 2. compared to 1. The bug in B. doesn't help.
- B. Sometimes the document.activeElement moves to the `<body>` and the focus ring disappears, and the focus is lost, it blinks. A quick recording of the problem, see how the focus ring blinks while I hold the <kbd>ArrowDown</kbd>  key down. Each time it happens, the speed of the scroll down is interpreted, it pauses a bit, and then resume.

https://user-images.githubusercontent.com/3165635/180275993-1dddb595-1e21-43ca-9f43-696e0c7e444e.mov

**Comment by cherniavskii** [comment] 2022-08-02 12:50
@oliviertassinari 
Interesting, I cannot reproduce the bug in B. and overall performance is better on my Macbook Air M1 with 6x CPU throttle:

https://user-images.githubusercontent.com/13808724/182377885-b1871f7f-8193-44e3-9ff3-ca80190bf355.mov

I'll look for optimization opportunities anyway

**Comment by oliviertassinari** [comment] 2022-08-07 17:10
I have tested it on the device that I used to develop Material UI from the beginning up to 2019.

![Capture d’écran 2022-08-07 à 19 04 04](https://user-images.githubusercontent.com/3165635/183302665-20bcd7f1-e535-46e5-9fe8-5030f8a9eb09.png)

- I can't reproduce A. MUI's data grid scroll faster to the bottom when holding the <kbd>Arrow down</kbd> key than react-data-grid.
- I can reproduce B. It jumps, every few rows.

**Comment by cherniavskii** [comment] 2024-04-09 10:19
The Data Grid [v7 scrolling performance has improved](https://mui.com/blog/mui-x-v7/#sticky-headers-and-improved-scrolling-performance).
You can check it out at https://mui.com/x/react-data-grid/#pro-plan

Here's a 100k rows demo with a 6x CPU throttle on my MacBook Air M2:

https://github.com/mui/mui-x/assets/13808724/4eb0cce7-c1e1-49b8-b2ad-6e23e5bfcf8e

I think we can close the issue now.

**Closed** 2024-04-17 03:06 UTC
Labels: performance, component: data grid, status: waiting for author, plan: Pro
