### ISSUE TITLE
[data grid] Show/Hide All Columns, if all columns are hidden, unable to restore visibility.

### ISSUE THREAD

**Issue by mparsakia** [mui/mui-x#13583] opened 2024-06-21 18:44 UTC
### Search keywords

Datagrid, DataGrid Pro

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: 
https://mui.com/x/react-data-grid/demo/

1. Go to the demo page.
2. Open the custom column menu.
3. Hide all columns.
4. Close the popover.
Note, no columns are visible, and so there is no way to access the columns menu to restore visibility. 

A refresh is required to restore, however for us who export the DataGridPro state to save/restore using local storage, there is no user friendly way to restore the columns.

### Current behavior

All columns are hidden.

### Expected behavior

The column visibility menu should not allow hiding all columns, and enforce the visibility of at least one column at all times, so that the column visibility menu may be accessed.

### Context

The user should not be left in a state where they cannot access this menu.

### Your environment

```System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (126.0.2592.68)
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.4
    @emotion/styled: ^11.11.0 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.19

    @mui/icons-material: ^5.14.1 => 5.15.19
    @mui/material: ^5.15.16 => 5.15.19
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system: ^5.15.15 => 5.15.15
    @mui/types:  7.2.14
    @mui/utils: ^5.15.14 => 5.15.14
    @mui/x-charts: ^7.5.0 => 7.6.2
    @mui/x-data-grid:  7.6.2
    @mui/x-data-grid-pro: ^7.5.0 => 7.6.2

    @mui/x-date-pickers:  7.6.2
    @mui/x-date-pickers-pro: ^7.5.0 => 7.6.2
    @mui/x-license: ^7.2.0 => 7.6.1
    @types/react: ^18.0.0 => 18.3.3
    react: ^18.2.0 => 18.3.1
    react-dom: ^18.2.0 => 18.3.1
    typescript: ^4.4.2 => 4.9.5
```
Chrome  126.0.6478.62 (Official Build) (64-bit) (cohort: Stable) 

### Order ID or Support key 💳 (optional)
85404

**Comment by michelengelen** [comment] 2024-06-22 08:23
Thanks for raising this @mparsakia ... it is a duplicate of #13328 though! 
I'll close this one in favor of the other! 👍🏼

**Closed by michelengelen** 2024-06-22 08:23 UTC
Labels: bug 🐛, component: data grid, status: waiting for maintainer, feature: Column visibility, support: pro standard
