### ISSUE TITLE
[data grid] Row Selection: Select All - checkboxSelectionVisibleOnly doesn't accumulate selection after applying filters. 

### ISSUE THREAD

**Issue by olzhas-kalikhan** [mui/mui-x#14074] opened 2024-08-01 20:08 UTC
### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Both in v6 and v7

Link to live example: 
https://codesandbox.io/s/amazing-architecture-tn8d3h

Steps:
1. Set `checkboxSelectionVisibleOnly` to `true` 
2. Apply any filter (make sure there is more than one page)
3. Click Select All checkbox in frist page
4. Go to the next page (or previous)
5. Click Select All checkbox

![ezgif-7-6ea2b21e8f](https://github.com/user-attachments/assets/d2f4917f-a9a9-4969-a2cf-5c6ad0bb96eb)

### Current behavior

Previously selected rows are deselected and only rows in current page are selected, but if you select rows individually in the next page selected rows count is accumulated, and rows selected in previous pages are not deselected.

### Expected behavior

Previously selected items shouldn't be deselected while filter is applied when clicking on select all checkbox

### Context

Make consistent behaviour with vs without applied filters.
Context: After applying filter and selecting certain pages selection progress is lost because previously selected rows are deselected

### Your environment

Forked docs demo from https://mui.com/x/react-data-grid/row-selection/#visible-rows-selection
Fork: https://codesandbox.io/s/amazing-architecture-tn8d3h

**Search keywords**: DataGrid, Filtered Row Selection

**Comment by michelengelen** [comment] 2024-08-02 13:23
Hey @MBilalShafi ... Could this potentially be fixed with your recent PR #13757 ?

**Comment by MBilalShafi** [comment] 2024-08-02 15:44
> Hey @MBilalShafi ... Could this potentially be fixed with your recent PR #13757 ?

@michelengelen I think it's a separate problem, I'll see if it could be solved along with that one.

One notable thing that will change when `propagateRowSelection` is active is, the unfiltered rows will be automatically deselected on filtering. It could be previewed in this csb [example](https://codesandbox.io/p/sandbox/funny-bardeen-3qvxrz).

@olzhas-kalikhan Do you see a problem with this approach as this is supposed to be the default selection behavior in v8? Do you want to keep the unfiltered rows selected after filtering?

**Comment by olzhas-kalikhan** [comment] 2024-08-05 03:04
correct me if I'm wrong, when filter everytime filter is applied all selections that don't match new filter will be deselected.
If that's the case, it makes sense. 

There is another case where user might want to repeat filter + selection actions. eg Filter -> Select -> Filter ->Select. Im not sure if that will happen often let me know what you think. Some actions are made with this case is bulk edit or bulk download of records (some other actions like changing status of ticket, issuing invoice). 

With the 1st approach it would be: Filter -> Select -> Bulk Action -> Filter -> Select -> Bulk Action -> Filter -> Select -> Bulk Action (Bulk Download - 3 files) 
With the 2nd: Filter -> Select -> Filter -> Select -> Filter -> Select -> Bulk Action (Bulk Download - 1 file)

**Comment by olzhas-kalikhan** [comment] 2024-08-05 03:41
oh wait actually now Im thinking user can apply multiple filters to perform bulk action. Deselecting unfiltered rows should be fine

**Comment by MBilalShafi** [comment] 2024-08-19 14:32
Here's the line of code which which causes the row selection model to reset if some filters are defined:
https://github.com/mui/mui-x/blob/0ee2e6884c1ef7aba46a54b4fe2530aad06d3491/packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts#L456

This issue seems to be a regression introduced in https://github.com/mui/mui-x/pull/11751 while fixing another bug.
The solution done in that PR might be approached in a different way to avoid causing this regression.

Instead of causing a reset selection when there's a filter defined, we might introduce a prop `keepUnfilteredRowsSelected` similar to [`keepNonExistentRowsSelected`](https://mui.com/x/api/data-grid/data-grid/#data-grid-prop-keepNonExistentRowsSelected) that allows users to auto-deselect unfiltered rows, which is the behavior requested in https://github.com/mui/mui-x/issues/11726

Any objections @mui/xgrid ?

**Closed** 2024-09-28 06:33 UTC
Labels: component: data grid, regression, feature: Filtering, feature: Selection
