### ISSUE TITLE
[data grid]When dragging text in cell EditMode, it would be better not to exit EditMode.

### ISSUE THREAD

**Issue by TNohSam** [mui/mui-x#5910] opened 2022-08-26 00:51 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When you drag text in cell EditMode, EditMode is terminated when the range of drag is out of the cell.
This leads to an unexpected exit from EditMode.

### Examples 🌈

![_20220826085638](https://user-images.githubusercontent.com/53901290/186793386-8be5ef58-43fa-4e63-b1bc-77fe32802070.gif)

https://codesandbox.io/s/frosty-pine-g9xced?file=/demo.tsx

### Motivation 🔦

When we drag text in cell EditMode, EditMode is terminated when the range of drag is out of the cell. This leads to an unexpected exit from EditMode. By default, "click" another cell to exit EditMode. However, you should not be able to exit EditMode with a "MouseUP" event.

**Comment by cherniavskii** [comment] 2022-08-26 15:27
Hey @TNohSam 
Thanks for raising this issue, I can reproduce it.
It seems to be a duplicate of https://github.com/mui/mui-x/issues/4333

**Closed by cherniavskii** 2022-08-26 15:27 UTC
Labels: status: needs triage
