### ISSUE TITLE
TreeView captures CTRL + ENTER key

### ISSUE THREAD

**Issue by ilbrando** [mui/mui-x#10577] opened 2023-10-04 15:19 UTC
### Steps to reproduce

The demo's of the component can be used.

### Current behavior

Pressing ENTER selects/deselects an item, but so does CTRL+ENTER.

### Expected behavior

The component to ignore CTRL+ENTER key events.

### Context

This is also a problem in single select, which is my case,.
The user can achieve selection with the SPACEBAR - isn't that enough?
Selection with ENTER is maybe ok, but CTRL+ENTER should not be captured especially not in single select mode. 

I think the issue is in this [codeblock](https://github.com/mui/mui-x/blob/fc7afacff3e8dad390072eb9e73e4aed48fb7bc7/packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts#L179C22-L179C22).

### Your environment

N/A - the component demo's demonstrate the problem

**Search keywords**: ctrl enter

**Comment by ilbrando** [comment] 2023-10-04 15:57
Thank you for at quick response.
I'm using CTRL+ENTER in my app and now I don't recieve the key event.
For reference Outlook also uses CTRL+ENTER to trigger "send email". My usage is something similar.

**Comment by LukasTy** [comment] 2023-10-04 16:04
And here we finally have more reason to prioritise https://github.com/mui/mui-x/issues/10397 🙈

**Comment by alexfauquette** [comment] 2023-10-04 16:08
Thanks @LukasTy For finding this issue :+1: I can only agree that blocking event propagation is not an ideal solution

I'm closing this issue since it's a duplicate of #10397

@ilbrando You can upvote and follow it to get news on this topic

**Comment by ilbrando** [comment] 2023-10-04 16:12
Will #10397 solve my problem? I don’t want The focused item to be selected when the user presses CTRL+ENTER.

**Comment by LukasTy** [comment] 2023-10-10 09:49
Hello @ilbrando 
I think that your desired behavior of custom <kbd>Ctrl</kbd>+<kbd>Enter</kbd> click can be achieved using controlled selection.
Please check this adjusted example executing item select only when <kbd>Ctrl</kbd> is not clicked together. 😉 
Feel free to close the issue if such solution would help you achieve your desired outcome. 👌 

As for the implementation out of the box - I'm not sure we should be providing it like described, because even [the ARIA example](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/) does select the item regardless of <kbd>Ctrl</kbd> being clicked. 🤷

**Comment by ilbrando** [comment] 2023-10-11 17:37
@LukasTy Thanks
I can see that your work around actually works. There is a TypeScript issue though, because the handler for onNodeSelect is supposed to take a `SyntheticEvent` and not a `KeyboardEvent`, but maybe it is only an error in the typings?

See source code: https://github.com/mui/mui-x/blob/87815c04e1bfd8cefe30fd25585fd483044bb6b8/packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts#L46C1-L46C1

**Comment by ilbrando** [comment] 2023-10-11 18:14
I'm not sure it really works because the selection is not done, but I think the event is captured, because it is still processed in the code block I mentioned.
I don't know much about aria, but isn't it strange to capture a keyboard combination that isn't used?

**Closed** 2024-01-10 08:00 UTC
Labels: duplicate, component: tree view
