### ISSUE TITLE
[data grid] Demo LazyLoadingGrid crashes in docs

### ISSUE THREAD

**Issue by PontusAxelsson** [mui/mui-x#11865] opened 2024-01-30 14:10 UTC
- [ ] I have [searched for similar issues](https://github.com/mui/mui-x/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20LazyLoadingGrid%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://next.mui.com/x/react-data-grid/row-updates/#lazy-loading
2. ??
3. demo *LazyLoadingGrid* crashes

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v7.0.0-beta.0  |
| Netlify deploy | https://65b76b6a52f53800081426d7--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 |

**Search keywords**:

**Comment by jyash97** [comment] 2024-01-30 15:10
I was looking into these issue, and the easy way to fix it is to add conditional operator [here](https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid-pro/src/hooks/features/lazyLoader/useGridLazyLoader.ts#L39) but it seems something is off with the `visibleRows` at first its empty which I suppose is correct considering the debounce. 

But on closer inspection I found when we keep scrolling the `visibleRows` count goes to `10000` and we can see a lag in the scroll.

At first it shows `no Rows` shouldnt it be a loading flag ? 

After adding conditional operator this is how it looks:  @MBilalShafi is this correct behavior?

https://github.com/mui/mui-x/assets/22376783/d6d03eaa-8bca-46ab-9d3e-ec71bc6934f3

**Comment by michelengelen** [comment] 2024-01-31 09:14
Hey @jyash97 and thanks for reporting this. We will have a look into this asap! Thanks again! 🙇🏼

**Comment by gitstart** [comment] 2024-02-01 08:20
@michelengelen we would like to pick this up

**Comment by jyash97** [comment] 2024-02-01 08:28
> @michelengelen we would like to pick this up

Hey 👋🏻

I already started looking into it 2 days back just waiting for confirmation from @michelengelen and team on correct behaviour

**Comment by michelengelen** [comment] 2024-02-01 10:57
Hey @jyash97 you can find the correct behavior in the docs for v6: [Layout](https://mui.com/x/react-data-grid/row-updates/#lazy-loading)

If you want I can assign this to you to fix it.

**Comment by jyash97** [comment] 2024-02-01 13:29
@michelengelen sure thing

will take a look at the issue more, any way I can get help from team if needed?

**Comment by michelengelen** [comment] 2024-02-01 14:27
definitely ... You can either comment here (or on the PR that you will open) or via our [Community Discord](https://discord.gg/hTw6DmAPua)

**Comment by romgrk** [comment] 2024-02-01 20:22
Not sure if we already have an issue for this but this started after the sticky PR (#10059), so it's on my tasklist.

@jyash97 If you want to take this you can open a PR. For the correct behavior compare with the v6 version of the docs.

**Comment by jyash97** [comment] 2024-02-01 20:24
> Not sure if we already have an issue for this but this started after the sticky PR (https://github.com/mui/mui-x/pull/10059), so it's on my tasklist

yes I was able to find the PR which caused the regression, I havent started fixing it yet to correct  behaviour, any suggestions to start with or look for?

**Comment by romgrk** [comment] 2024-02-01 22:59
No I haven't touched that code yet, use the v6 equivalent example as the reference: https://mui.com/x/react-data-grid/row-updates/#lazy-loading

**Comment by oliviertassinari** [comment] 2024-02-11 00:54
Duplicate of #11784?

**Comment by romgrk** [comment] 2024-02-11 01:13
Yes it's a duplicate.

@jyash97 I'll pick this one up on Monday unless you're still interested in submitting a PR.

**Comment by jyash97** [comment] 2024-02-11 03:43
Hey @romgrk 

Sorry for the delay, but you can go ahead and work on this one, don’t want to block the issue right now as I may not be able to look into the issue this week

**Closed** 2024-02-27 17:17 UTC
Labels: docs, component: data grid, regression, feature: Row loading, v7.x
