### ISSUE TITLE
Dragging the clock hands doesn't update the time picker value

### ISSUE THREAD

**Issue by tvanrijn** [mui/mui-x#4978] opened 2022-01-25 10:52 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Dragging the clock hands of the TimePicker does not update the value in the TimePicker, only after selection it is updated.

### Expected behavior 🤔

It should update the value in the TimePicker while dragging, like it does in StaticTimePicker.

### Steps to reproduce 🕹

Steps:

1. In the docs https://mui.com/components/time-picker/ using the Basic example, open the time picker and drag the clock hand to a different hour or minute
2. Notice the value in the TimePicker is only updated after selecting, not while dragging
3. Now try the same in the Static mode example
4. Notice the value in the StaticTimePicker is being updated while dragging

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment] 2022-05-23 10:16
@flaviendelangle can you confirm this is expected behaviour?

**Comment by flaviendelangle** [comment] 2022-05-23 10:45
Yes, the way I understand the issue, it is the expected behavior

**Comment by cherniavskii** [comment] 2022-05-23 10:57
I'm closing the issue then, since there are no actions on our side to perform

**Closed by cherniavskii** 2022-05-23 10:57 UTC
Labels: status: expected behavior, component: pickers, component: time picker
