### ISSUE TITLE
onChange is not triggered when clearing an invalid date

### ISSUE THREAD

**Issue by rblackledge-shibumi** [mui/mui-x#5690] opened 2022-08-02 19:59 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When you enter an invalid date (such as 13/02/2022 for MM/DD/YYYY) and then press the clear button, no callback is triggered.

### Expected behavior 🤔

A callback should be triggered in such a way that a controlled input would have the error state and value cleared.

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/objective-water-g8s2ln?file=/src/App.js
Steps:
1. Type 13/02/2022 into the DateInput
2. Open the calendar
3. Press the clear button in the calendar

### Context 🔦

I'm trying to control a date input in a form, and users of the form find the current behavior counterintuitive.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment] 2022-08-03 08:29
Thanks for reporting this bug

The problem seems to come from [those lines](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/hooks/usePickerState.ts#L217:L222). Before calling `onChange` a comparison is made between the the new value `params.value` and the committed one `dateState.committed`
```js
if (
	!params.skipOnChangeCall &&
	!valueManager.areValuesEqual(utils, dateState.committed, params.value)
) {
	onChange(params.value);
}
```

But the committed value is a parsed one, and [the parser returns `null` to invalid value](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/utils/date-utils.ts#L73-L80). So this part of the code do not see the difference between clear from an invalid value and clear from an empty field

**Comment by LukasTy** [comment] 2022-08-09 09:38
I've looked into various possible solutions for this case, but all of them have certain drawbacks.

The most simple one could be adding a flag to `clear` action to always force emitting `onChange`, but we would get a side-effect where anytime `clear` button is clicked -> `onChange` event is fired with empty value, even though it already was empty.

Basically, proceeding with the planned [refactor of date input](https://github.com/mui/mui-x/issues/5531) component would avoid such cases altogether.
What do you @flaviendelangle @alexfauquette thing?
Should we go with mildly hacky workaround for such edge-case or leave it to be resolved/avoided after we migrate to a more robust input component?

**Comment by flaviendelangle** [comment] 2022-08-09 09:44
> Basically, proceeding with the planned https://github.com/mui/mui-x/issues/5531 component would avoid such cases altogether.

Yes that's typically an issue that the new approach seems to solve

I think @alexfauquette have better insights to decide if we should to a fix on the current implementation

**Comment by alexfauquette** [comment] 2022-08-09 10:15
@LukasTy why not using a quick fix. Id on't think it's problem if developers get a `onChange(null)` when the value is already `null`. 

I thought about a second type of quick fix. I the problem is the formatted value that is `null` we could do the comparison on both the formatted value and the raw value


```diff
--- a/packages/x-date-pickers/src/internals/hooks/usePickerState.ts
+++ b/packages/x-date-pickers/src/internals/hooks/usePickerState.ts
@@ -213,10 +213,9 @@ export const usePickerState = <TInputValue, TValue, TDate>(
           }
         }
       });
-
       if (
         !params.skipOnChangeCall &&
-        !valueManager.areValuesEqual(utils, dateState.committed, params.value)
+        !(valueManager.areValuesEqual(utils, dateState.committed, params.value) && valueManager.areValuesEqual(utils, value, params.value))
       ) {
         onChange(params.value);
       }
@@ -231,7 +230,7 @@ export const usePickerState = <TInputValue, TValue, TDate>(
         }
       }
     },
-    [onAccept, onChange, setIsOpen, dateState, utils, valueManager],
+    [onAccept, onChange, setIsOpen, dateState, utils, value, valueManager],
   );
```

**Comment by LukasTy** [comment] 2022-08-09 12:34
@alexfauquette Good point, did not notice the `value` field.
It could solve the issue, but just one note: closing the picker would also work the same as clicking `clear` 🤔 
This in turn causes the following inconsistency, where if you enter invalid date in the input - it shows an error state and what you entered, but if you open and close the picker - the invalid value get's reset...

**Comment by alexfauquette** [comment] 2022-08-09 13:26
Sounds like an edge case not handles. The Popper `onClose` is in fact `onDismiss` with the idea that when you open the popper, you select a date. But in your specific example, you open the popper with the current value `null` and then dismiss it.

Would it make more sense to either have `onDismiss` do not commit if the value is `null` (you never selected a date so we do not commit it) or add a `onClose` such that Poppers can do independently the close an dismiss action

**Comment by LukasTy** [comment] 2022-08-09 13:32
@alexfauquette Please refer to the linked PR for my proposed fix avoiding this previously mentioned edge case by combining my initial idea with your `value` field observation. 😉

**Closed** 2022-08-11 08:17 UTC
Labels: bug 🐛, component: pickers
