### ISSUE TITLE
Add an ability to style Clock component.

### ISSUE THREAD

**Issue by kbuza-fulcrum** [mui/mui-x#5212] opened 2022-06-15 13:36 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Current version of Time picker components is not allowing to add custom styles to them, because of how css in js is used:
https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/ClockPicker/Clock.tsx

Please use predictable class names for it.

### Examples 🌈

Example is any Material UI component, which use overridable classes, for instance:
https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Button/Button.js

### Motivation 🔦

I'm trying to accomplish better developer experience and ability to customize components to match designs, but not the opposite.

**Comment by alexfauquette** [comment] 2022-06-16 08:54
Yes, some sub-components require improvement, on the styling

I'm closing this issue as being a duplicate of #4669 in which we track the remaining components. Feel free to open a PR for one of them. There is an example one in the comments

**Closed** 2022-06-16 08:54 UTC
Labels: status: needs triage
