### ISSUE TITLE
[DataGridPro] Column pinning background not working with cssVariables on hover/select

### ISSUE THREAD

**Issue by lhilgert9** [mui/mui-x#14752] opened 2024-09-27 13:30 UTC
The background of the pinned columns is not correctly styled, when enable the cssVariables in the @mui/material theme.

Steps to reproduce:
1. Go to the [example](https://stackblitz.com/edit/react-haeysj?file=index.tsx,Demo.tsx).
2. Hover over one row.
3. Scroll to the right and you can see through the pinned columns background.

There is no problem if you test the same thing in the repo in the playground, but only if you use the build version of @mui/x-data-grid-pro. In the build version [GridRootStyles.ts](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/components/containers/GridRootStyles.ts) is a different file than in the source code and apply other css to the grid.

**Comment by MBilalShafi** [comment] 2024-09-27 13:51
It seems like the issue has something to do with MUI theme vars, removing the CSS vars from the theme seems to fix it: https://stackblitz.com/edit/react-haeysj-nxn4yb?file=index.tsx,Demo.tsx
I'll move this to board for further inspection.

**Comment by lhilgert9** [comment] 2024-09-27 15:25
@MBilalShafi That's right, but the problem should actually already be solved, since the code is available, which also works if you test it in the @mui/x repository as a playground with css variables. However, this code is somehow not in the version that can be found in npm.
If you compare the [git](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/components/containers/GridRootStyles.ts) (components/containers/GridRootStyles.ts) version and the [npm](https://www.npmjs.com/package/@mui/x-data-grid?activeTab=code) (components/containers/GridRootStyles.js) version of the relevant file, you can see that the corresponding lines of code are missing in the npm file.

**Comment by KenanYusuf** [comment] 2024-09-30 15:14
@lhilgert9 there will be a release later this week which will fix the issue you're describing here. It was fixed in https://github.com/mui/mui-x/commit/d55b1215fb1705b11e8d2688793e51c1aeb3ccbb, which has not been released yet.

**Comment by KenanYusuf** [comment] 2024-09-30 15:17
Closing as also a duplicate of https://github.com/mui/mui-x/issues/12855

**Closed by KenanYusuf** 2024-09-30 15:17 UTC
Labels: bug 🐛, component: data grid, design
