### ISSUE TITLE
[DataGridPro] Unable to scroll back up to open row detail panel

### ISSUE THREAD

**Issue by psigns** [mui/mui-x#6378] opened 2022-10-04 06:38 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I expand a row [detail panel](https://mui.com/x/react-data-grid/master-detail/) and scroll down to view more grid rows, I am unable to scroll back up to the expanded detail panel.

https://user-images.githubusercontent.com/1140141/193750897-bf08b146-fd8b-4e1b-be7b-0f7928cba1c4.mov

### Expected behavior 🤔

I expect to be able to scroll the grid up and down as normal, even when one or more detail panels are expanded.

### Steps to reproduce 🕹

I am only able to reproduce this issue in Chrome.

Link to live example:

https://codesandbox.io/s/rough-wave-xnv5i4?file=/demo.tsx

Steps:
1. Expand a row detail panel and leave it open
2. Scroll down enough rows (~20?) that the detail panel moves well outside of the grid
3. Slowly scroll back up toward the open detail panel
4. Notice that as you approach the detail panel, the scroll location of the grid will jump back down, so that you never actually see it

### Context 🔦

This is blocking adoption of the MUI DataGridPro in our codebase because our existing grids have expandable row details, and our users would perceive this scroll bug as a regression in our product.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 48.52 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.asdf/installs/nodejs/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
  Managers:
    Homebrew: 3.5.1 - /usr/local/bin/brew
    pip3: 21.2.3 - ~/ff/work/dev/shims/python/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 12.1. - /usr/bin/gcc
    Git: 2.36.1 - /usr/local/bin/git
    Clang: 13.0.0 - /usr/bin/clang
  Servers:
    Apache: 2.4.51 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.16 - /usr/local/bin/docker
  IDEs:
    IntelliJ: 2021.2.3
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.18.4 - /Users/phillipsaenz/ff/work/dev/shims/golang/go
    Java: 11.0.16 - /Users/phillipsaenz/.asdf/shims/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python: 3.9.7 - /Users/phillipsaenz/ff/work/dev/shims/python/python
    Python3: 3.9.7 - /Users/phillipsaenz/ff/work/dev/shims/python/python3
    Ruby: 2.6.8 - /usr/bin/ruby
  Databases:
    SQLite: 3.36.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 105.0.1
    Safari: 15.2

```
</details>

### Order ID 💳 (optional)

40131

**Comment by DanailH** [comment] 2022-10-05 12:38
Thanks, @psigns for reporting this. It seems a nasty regression.

**Comment by kajirikajiri** [comment] 2022-10-05 23:45
In my case, I turned on disableVirtualization and it worked fine.

```jsx
<DataGrid {...data} disableVirtualization />
```

docs
https://mui.com/x/react-data-grid/virtualization/#disable-virtualization

codesandbox
https://codesandbox.io/s/pensive-babycat-fr9zi0

**Comment by psigns** [comment] 2022-10-09 05:59
Thank you for the info @kajirikajiri .  Unfortunately, our use case is rendering a very large data grid, and the performance gains from virtualization are one of the main reasons we want to switch to MUI's data grid.

**Comment by cherniavskii** [comment] 2022-10-17 14:58
Few observations:

1. It doesn't seem to be related to Master detail feature, since I can reproduce it without using the feature, even with Community version of `DataGrid`: https://codesandbox.io/s/competent-ganguly-8ucjg7?file=/demo.tsx

	https://user-images.githubusercontent.com/13808724/196209399-4404f3ff-9103-4f53-9327-2efd19e9aca2.mov
	
2. I cannot reproduce the issue if the cell if there's no focused cell that is being scrolled out of view: https://codesandbox.io/s/competent-ganguly-8ucjg7?file=/demo.tsx

	https://user-images.githubusercontent.com/13808724/196210023-04fba662-2b1b-40b8-84f9-76de3df0f779.mov

3. The issue is not reproducible with `disableVirtualization={true}`. So it seems to come from row virtualization + focus management combo.

Given the high impact of the issue, moving it up in our priority list. cc @joserodolfofreitas

**Comment by yaredtsy** [comment] 2022-10-22 20:21
I have figured it out. It's actually `cellFocus` problem. 
Demo: https://codesandbox.io/s/clever-gould-qztsm2?file=/demo.tsx
if no one is working on this. I can send PR.

**Comment by psigns** [comment] 2022-11-04 15:12
Hi Team, we are still blocked from migrating to DataGridPro in our codebase.  I see there is an open PR with some discussion.  Are there any blockers on this, or can we expect this to be fixed soon?

**Comment by cherniavskii** [comment] 2022-11-08 17:23
Closed by https://github.com/mui/mui-x/pull/6622

**Closed by cherniavskii** 2022-11-08 17:23 UTC
Labels: component: data grid, plan: Pro, regression, feature: Other
