### ISSUE TITLE
[data grid] Tooltips are cut off below the last column of the table 

### ISSUE THREAD

**Issue by StephanSProxora** [mui/mui-x#13689] opened 2024-07-01 15:18 UTC
### Search keywords

tooltip data grid

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: [codesandbox.io](https://codesandbox.io/s/eager-cori-fnfmn7)

Steps:
1. add a tooltip in renderCell 
2. add disablePortal=true to the PopperProps (this is necessary for us because the tooltips contain links - further info below)
(3. add whiteSpace: "wrap" to the surrounding element of the title property of the tooltip - otherwise the text of the tooltip does not wrap inside the tooltip)

### Current behavior

The tooltip is cut off below the last column:
![Screenshot_2024-07-01_16-58-58](https://github.com/mui/mui-x/assets/174344865/87049591-f65e-4df5-9392-02c7d54d23a1)

### Expected behavior

The full tooltip is shown (this is possible if we remove disablePortal=true):
![Screenshot_2024-07-01_17-03-27](https://github.com/mui/mui-x/assets/174344865/3444ac17-40e9-4969-a783-f242b5d0da37)

### Context

Our tooltips may contain links and the user has to be able to navigate to these links with the keyboard (as one of the requirements for WCAG).
Therefore, while the tooltip is focused, the containing link should get the focus by pressing the Tab key.
This is currently only the case if we set disablePortal=true, but then we have this issue with the cut of tooltip.

### Your environment

Same behaviour in Firefox and Chrome

**Comment by MBilalShafi** [comment] 2024-09-27 05:20
Duplicate of #14669

**Closed by MBilalShafi** 2024-09-27 05:20 UTC
Labels: duplicate, component: data grid
