### ISSUE TITLE
[charts] Expand text customisation options for axes

### ISSUE THREAD

**Issue by MonstraG** [mui/mui-x#12157] opened 2024-02-21 09:56 UTC
### Summary

How to deal with very long tick labels?

### Problem

See this:
![image](https://github.com/mui/mui-x/assets/17963791/da9a09a6-2667-47f6-83b8-4643d82f33f3)
Middle one is unlabeled because it's too long.

In my case adding angle is really not enough to make it look acceptable:
![image](https://github.com/mui/mui-x/assets/17963791/30fcb1bd-90c7-400f-8171-2c2da554880c)

### Solutions?

I can think of just about 2 options:
A) ellipsis
B) color-coding:
![image](https://github.com/mui/mui-x/assets/17963791/cf867c92-cdf7-43a4-933e-421ea865d564)
C) wrapping

For A), the simplest feature I could think of is to pass `horizontal pixel size of the column` as the argument to `valueFormatter` so I could manually ellipsis the text.

For B) I think I could also use `useDrawingArea` to draw anything below the chart to acheive B), but then I need to manually calculate where each column starts, which could be complicated.

For C) I've just found out that `\n` get wrapped so now I can sort of write a smart algorithm of detecting best wrapping spaces but knowning column width would help a lot.

**Search keywords**: labels ticks ellipsis wrapping canting axes text customisation customization

**Comment by alexfauquette** [comment] 2024-02-21 14:34
It looks like a duplicate of #10928. I'm closing to have a single point of discussion. Feel free to add comment with question/requirement in #10928

To briefly resume the other issue content, we have tow distinct problem to fix:

1. Be able to have finer customization of the text. For now the label is the same in the tooltip and legend, and value formatted are the same in axes and tooltip which is blocking the creation of ellipse
2. Computing the text width because it's the key part to correctly put an ellipse or wrap some text

The first point is my next priority. The second one will probably need more time to get a convincing solution.

**Closed by alexfauquette** 2024-02-21 14:34 UTC
Labels: status: waiting for maintainer, component: charts
