### ISSUE TITLE
DatePicker: Expose `openPicker()` for customization

### ISSUE THREAD

**Issue by DarkTrick** [mui/mui-x#5174] opened 2022-06-10 15:37 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

# Summary 💡

## Subject of this FR:
 `import { DatePicker  } from '@mui/lab';`
<img width="323" alt="image" src="https://user-images.githubusercontent.com/46980694/173100591-4c2a80a2-517f-4871-9128-94572bf05e18.png">

## Introduction:
Through the `renderInput` property it's possible to customize how the date picker is represented.
However, the button to open the actual date picker view is limited to `{InputProps.endAdornment}`, which is this icon: 
<img width="58" alt="image" src="https://user-images.githubusercontent.com/46980694/173099768-9db92195-95f2-4eec-8e5e-30a3a1e643c3.png">

## Problem:
Customizing the `openPicker` action is not easily possible.

## Current Workaround:
You could do something like this:
```
<Button ref={inputRef} onClick={(InputProps as any)?.endAdornment?.props?.children?.props?.onClick}>
 open
</Button>
```
But as this `onClick` call is going deep into the internals, it's probably no stable way of doing things for the future.

## Examples 🌈

https://mui.com/x/api/date-pickers/date-picker/

## Motivation 🔦

I'm trying to run the `openPicker` "action" on the click of a customized element.

# Example

> In a perfect world what would you want to write, and what would be the result for the end user?

This code:
```
<DatePicker
    renderInput={({inputRef, inputProps, InputProps}) => (
        <Button ref={inputRef} onClick={(InputProps.openPicker}> open calender </Button>
    )} 
/>
```
should render as 
![image](https://user-images.githubusercontent.com/46980694/173846082-eb88e4ff-cc7b-4a5e-a578-267ae4144cf0.png)

On click the *date picker dialog* should open:
![image](https://user-images.githubusercontent.com/46980694/173846286-8407b56c-6c28-47c1-b6cc-67dac4dcdd15.png)

**Comment by alexfauquette** [comment] 2022-06-13 08:56
It is not yet documented, but their is a slot to customize the icon

https://codesandbox.io/s/responsivedatepickers-material-demo-forked-b5upjd?file=/demo.tsx:1302-1356
```jsx
<DatePicker
	...
	components={{ OpenPickerIcon: AcUnitIcon }}
/>
```

**Comment by DarkTrick** [comment] 2022-06-14 15:54
Thank you for the feedback!

> It is not yet documented, but their is a slot to customize the icon

Sorry, I guess I should work on my writing skills 💦

This FR is not about the icon, but about the function to open the date picker dialog (`openPicker`)

**Comment by alexfauquette** [comment] 2022-06-14 18:20
Could you explain what you want to do with this `openPicker`?

In a perfect world what would you want to write, and what would be the result for the end user?

**Comment by DarkTrick** [comment] 2022-06-15 14:04
> In a perfect world what would you want to write, and what would be the result for the end user?

Thank you.


This code:
```
<DatePicker
    renderInput={({inputRef, inputProps, InputProps}) => (
        <Button ref={inputRef} onClick={(InputProps.openPicker}> open calender </Button>
    )} 
/>
```
should render as 
![image](https://user-images.githubusercontent.com/46980694/173846082-eb88e4ff-cc7b-4a5e-a578-267ae4144cf0.png)

On click the *date picker dialog* should open:
![image](https://user-images.githubusercontent.com/46980694/173846286-8407b56c-6c28-47c1-b6cc-67dac4dcdd15.png)

**Comment by DarkTrick** [comment] 2022-06-15 14:30
This sounds like *going down to bare metal* to me (I might be wrong, though):
As far as I understand, if I use the sub components, ...
- ... I would have to manage show/hide status myself.
- ... I could not use functionality like `views={["year", "month"]}`
- ... I would have to manage the date receiving manually (it's probably not as easy as `onChange` within `<DatePicker>)

Also, I guess having a simple function

**Comment by DarkTrick** [comment] 2022-06-15 15:01
> Yes you will have to manage the open state yourself

That means the dev would have to re-implement the functionality *that already exists* in `InputProps.endAdornment.props.children.props.onClick`. 

Providing the function currently residing in `InputProps.endAdornment.props.children.props.onClick` to be accessed via an official, documented interface like `InputProps.openPicker` would prevent devs from re-implementing already existing behavior.

This would reduce code duplication, reduce bugs, reduce implementation effort and improve DatePicker DX (DX = *developer experience*)

**Comment by socramm9** [comment] 2022-06-27 11:07
> `InputProps.endAdornment.props.children.props.onClick`

@DarkTrick  Thanks for this. 

@alexfauquette  I also see it als issue that it is not easely possible to change the DatePicker behavior. For example If I don't want to let my users use the keyboard to input Dates I would have to use the MobileDatePicker. But then the issue is that the Picker is rendered als Dialog what I also don't like.

So my solution for now will be:
https://codesandbox.io/s/viewsdatepicker-demo-mui-x-forked-ss99vq?file=/demo.tsx

<img width="818" alt="Bildschirmfoto 2022-06-27 um 13 05 00" src="https://user-images.githubusercontent.com/52098754/175927472-5a1f09ad-8de2-4609-9eda-fe907925cb35.png">

**Comment by alexfauquette** [comment] 2022-07-01 21:39
Answering issue #5368 reminds me that you can control the picker open state with `open`, `onOpen`, and `onClose`

**Comment by DarkTrick** [comment] 2022-07-01 23:12
@alexfauquette on which object?

**Comment by alexfauquette** [comment] 2022-07-02 08:40
On the `DatePicker` component, you can check the issue discussion for more information

**Comment by flaviendelangle** [comment] 2022-09-13 12:29
From what I understand, the `open` / `onOpen` / `onClose` solves the issue
I would be in favor of repurposing this issue for a new doc example where the popper opens on input click instead of icon click.

**Comment by flaviendelangle** [comment] 2022-09-23 14:14
Closing this one

For the immediate solution, `open` / `onOpen` and `onClose` should work (if not feel free to comment and we will re-open if needed)

For the broader topic of how to open the views we have a discussion on https://github.com/mui/mui-x/issues/5549 that we should resume.
I think that we should improve the default behavior and add doc examples of how to achieve other commonly used behaviors (open when clicking on the input being one).

**Closed by flaviendelangle** 2022-09-23 14:15 UTC
Labels: support: question, component: pickers, customization: extend

**Comment by Akshay-Vedak** [comment] 2024-02-01 09:52
I have a usecase where the adornment has to be removed and open/close events are attached to the adornment only not to the textfield. So, with the help of onFocus and onBlur passed to textfield props inside slotProps I should be able to control the open/close behaviour but its malfunctioning when I try to open datepicker so please help.

`<div className="col-md-6 mt-2 pl-1 pr-1">
                    <FormControl fullWidth>
                        <LocalizationProvider dateAdapter={AdapterDayjs}>
                            <DatePicker
                                className="date-filters"
                                autoOk
                                size="small"
                                inputVariant="outlined"
                                format="DD-MM-YYYY"
                                open={state.isEndDate}
                                slotProps={{
                                    inputAdornment: { className: 'd-none' },
                                    textField: {
                                        onFocus: () => setState(prev => ({...prev, isEndDate: true})),
                                        onBlur: () => setState(prev => ({...prev, isEndDate: false})),
                                        size: 'small',
                                        variant: 'outlined'
                                    }
                                }}
                                onChange={date => setState(prev => ({ ...prev, endDate: date }))}
                                label="To"
                                clearable
                                maxDate={dayjs()}
                                value={dayjs(state.endDate)}
                            />
                        </LocalizationProvider>
                    </FormControl>
                </div>`
