### ISSUE TITLE
[data grid] Dropdown of editable 'singleSelect' DataGrid column is not visible until cell is double-clicked

### ISSUE THREAD

**Issue by conerye** [mui/mui-x#6517] opened 2022-10-14 23:06 UTC
### Order ID 💳

331993142

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

browsers: Google Chrome 106.0.5249.103 and Firefox 102.3.0esr

I am using DataGrid with checkboxSelection and editing prop:
experimentalFeatures={{ newEditingApi: true }}

I have defined the columns:
const devGroupsColumns = [
    { field: 'groupName', flex: 1, headerName: 'Device Group' },
    {
        editable: true,
        field: 'accessLevel',
        flex: 1,
        headerName: 'Access',
        type: 'singleSelect',
        valueOptions: ['Read-only', 'Read/Write'],
    },
];

The dropdown for the Access column is not visible when the table is displayed, so it is not obvious that the column is editable. The user needs to double-click the cell in order to see the dropdown. Also, each click in the cell selects/deselects the row. What I would like is for the dropdown to always be visible and a click on the cell or dropdown icon to open the dropdown menu (without selecting the row). Is it possible and if yes, how do I get this behavior?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 106.0.5249.103
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3
    @emotion/styled: ^11.8.1 => 11.9.3
    @mui/base:  5.0.0-alpha.87
    @mui/icons-material: ^5.8.0 => 5.8.4
    @mui/material: ^5.8.1 => 5.8.6
    @mui/private-theming:  5.9.1
    @mui/styled-engine:  5.8.7
    @mui/system: ^5.9.1 => 5.9.1
    @mui/types:  7.1.4
    @mui/utils:  5.10.6
    @mui/x-data-grid: ^5.13.1 => 5.14.0
    @mui/x-data-grid-premium: ^5.14.0 => 5.14.0
    @mui/x-data-grid-pro:  5.14.0
    @mui/x-date-pickers: ^5.0.0-beta.1 => 5.0.0-beta.2
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.2
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react:  18.0.14
    react: ^18.1.0 => 18.2.0
    react-dom: ^18.1.0 => 18.2.0
    typescript:  4.7.4
```
</details>

**Comment by yaredtsy** [comment] 2022-10-15 18:13
@conerye it is visible, the value is just empty, you need to give the default value in data or use  or override `valueGetter` ,`        valueGetter: (e) => {
          return e.value ?? "not-select";
        },`

**Comment by conerye** [comment] 2022-10-15 19:21
I'm not sure what you mean by 'the value is just empty'. The data is pulled from the database, where accessLevel is a required field, so there is always a value. I will attach a screenshot.

**Comment by conerye** [comment] 2022-10-15 19:28
![editableTable](https://user-images.githubusercontent.com/39837891/196004553-5d7b8267-b577-447c-8a8d-1dcf5c0adb0b.png)

**Comment by yaredtsy** [comment] 2022-10-15 20:15
ow sorry, I misunderstood your question. the combo box is shown in the edit mode for singleSelect type.  for view mode, you can customize us as you want by overriding the 'renderCell' field.  and you can control the mode using `useGridApiRef` . check this link if you want to read more about it https://mui.com/x/react-data-grid/editing/. and check this example, if you want to edit the cell with out selecting the row, https://codesandbox.io/s/nostalgic-moore-e1l1s0?file=/demo.tsx:1223-1236

**Comment by cherniavskii** [comment] 2022-10-17 14:34
> The dropdown for the Access column is not visible when the table is displayed, so it is not obvious that the column is editable.

I assume what you mean here is that dropdown **icon** is not visible until you start cell editing.
It's kind of expected, since we have different components for `view` and `edit` state, and Select component is rendered only in `edit` state.
But you can customize it with `renderCell`:

```tsx
{
    field: "country",
    type: "singleSelect",
    editable: true,
    renderCell: ({ value }) => (
      <Box
        sx={{
          display: "flex",
          width: "100%",
          justifyContent: "space-between",
          alignItems: "center"
        }}
      >
        <div>{value}</div>
        <ArrowDropDownIcon />
      </Box>
    )
  }
```

Here's a demo: https://codesandbox.io/s/material-demo-forked-2kl6eq?file=/demo.tsx:759-1176

> What I would like is for the dropdown to always be visible and a click on the cell or dropdown icon to open the dropdown menu (without selecting the row)

You can do that with a custom `renderCell` and controlled editing model.
Here's a demo: https://codesandbox.io/s/material-demo-forked-h0mqu9?file=/demo.tsx

You can also consider single-click editing from https://github.com/mui/mui-x/issues/2186 + dropdown icon in a `renderCell`.

Let me know what you think.

**Comment by yaredtsy** [comment] 2022-10-17 16:17
@cherniavskii why not use `useGridApiContext` in `renderCell`. it makes the code much simpler.
```javascript
const CustomComponent = (params) => {
  const ref = useGridApiContext();

  return (
    <Box
      sx={{
        display: "flex",
        width: "100%",
        justifyContent: "space-between",
        alignItems: "center"
      }}
    >
      <div>{params.value}</div>
      <IconButton size="small" sx={{ padding: 0 }}>
        <ArrowDropDownIcon
          onClick={(event) => {
            event.stopPropagation(); // to not select row
            ref.current.startCellEditMode({
              id: params.id,
              field: params.field
            });
          }}
        />
      </IconButton>
    </Box>
  );
};
```
Here's a demo: https://codesandbox.io/s/material-demo-forked-hh73c2?file=/demo.tsx

**Comment by conerye** [comment] 2022-10-17 17:17
@yaredtsy thank you for your post. I looked at the codesandbox and I am not able to use the keyboard in that editable dropdown cell. It may be that I am not doing something right? but I couldn't figure it out.

**Comment by yaredtsy** [comment] 2022-10-17 17:43
add `tabindex="-1` to the `IconButton`
```javascript
<IconButton size="small" sx={{ padding: 0 }} tabindex="-1">
```

**Comment by conerye** [comment] 2022-10-17 19:21
ok, after clearing up a few warnings, here is what I ended up with for 'CustomComponent':

const DeviceGroupsAccessCell = (params) => {
    const ref = useGridApiContext();

    return (
        <Box
            sx={{
                display: 'flex',
                width: '100%',
                justifyContent: 'space-between',
                alignItems: 'center',
            }}
        >
            <div>{params.value}</div>
            <IconButton
                onClick={(event) => {
                    event.stopPropagation(); // to not select row
                    ref.current.startCellEditMode({
                        id: params.id,
                        field: params.field,
                    });
                }}
                size="small"
                sx={{ padding: 0 }}
                tabIndex={-1}
            >
                <ArrowDropDownIcon />
            </IconButton>
        </Box>
    );
};

It seems to work smoothly! MANY THANKS!!!

BUT now I try to handle the change to the cell using data grid processRowUpdate , and there are errors. Do I need to open a new support item for that?

**Comment by cherniavskii** [comment] 2022-10-17 19:30
> BUT now I try to handle the change to the cell using data grid processRowUpdate , and there are errors. Do I need to open a new support item for that?

Please do!
And if possible - provide a minimal example reproducing the issue to help us investigate :)

**Comment by cherniavskii** [comment] 2022-10-17 19:32
I'm closing this issue since it looks like it's resolved

**Closed by cherniavskii** 2022-10-17 19:32 UTC
Labels: component: data grid, status: needs more information, support: commercial, customization: extend

**Comment by splurgebudget** [comment] 2023-02-20 01:12
Sorry for reviving an old one - this ends up being not much code... but I just wanted to vote for having this directly as a column option!  This is exactly what I needed in my app too.

Thanks to everyone that commented here - especially @yaredtsy !
