### ISSUE TITLE
[question] DataGridPro Expand and Collapse All nodes programmatically

### ISSUE THREAD

**Issue by sbmaggarwal** [mui/mui-x#10025] opened 2023-08-13 12:53 UTC
### Order ID or Support key 💳 (optional)

71425

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

How can I make all rows expand/collapse programmatically in MUI ReactJS `DataGrid`?

**What have I tried?**
I used prop `defaultGroupingExpansionDepth` based on [MUI documentation][1]:
```
export const EXPAND_ALL = -1;
export const COLLAPSE_ALL = 0;
...
const [expandedState, setExpandedState] = useState(COLLAPSE_ALL);
...

return <Stack>
        <Stack spacing={2} direction="row" m={1}>
            <Button variant={"contained"} onClick={() => setExpandedState(EXPAND_ALL)}>Expand All</Button>
            <Button variant={"contained"} onClick={() => setExpandedState(COLLAPSE_ALL)}>Collapse All</Button>
        </Stack>
        <DataGridPro
            treeData
            ...
            apiRef={dataGridApi}
            defaultGroupingExpansionDepth={expandedState}
            ... />
    </Stack>;
```
But the problem is that these buttons only work when tree is **not** already partially expanded.

As soon as I partially expand the tree grid, these buttons don't work any more. How can I make these buttons work irrespective of the current expansion/collapse state of the tree grid?

  [1]: https://mui.com/x/react-data-grid/row-grouping/#group-expansion

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by romgrk** [comment] 2023-08-14 14:47
Have you read that section of the documentation in full? The last part seems to be what you're looking for:

![image](https://github.com/mui/mui-x/assets/1423607/741d94b3-6d65-43db-a3e9-62f98316ad8e)

**Comment by sbmaggarwal** [comment] 2023-08-14 15:29
But I don't want to expand a single row, I want to expand and collapse all rows. Is there a direct way to do this?

**Comment by romgrk** [comment] 2023-08-14 16:44
Duplicate of #8505

**Closed by romgrk** 2023-08-14 16:44 UTC
Labels: duplicate, component: data grid, plan: Pro, support: commercial
