### ISSUE TITLE
[data grid] Production site with Expired Key watermark 

### ISSUE THREAD

**Issue by exosept** [mui/mui-x#13032] opened 2024-05-06 17:07 UTC
### The problem in depth

What is considered a production environment vs a dev environment for the license keys to display the watermark?
I am hosting the react site on firebase and didn't make change for at least 6 months but the watermark appeared on the day that the license expired. I renewed the license but the old keys still seems to be marked as expired. How can I indicate that the build is for production so the watermark will not appear everywhere in prod each year? Thanks a lo.

### Your environment

System:
    OS: macOS 13.5
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 124.0.6367.119
    Edge: Not Found
    Safari: 16.6

**Search keywords**: key expired
**Order ID**: 89823

**Comment by michelengelen** [comment] 2024-05-07 08:30
Hey @exosept 
As stated in [this section](https://v6.mui.com/x/introduction/licensing/#3-expired-license-key) of the docs you need to make sure that the version you are installing was released before your license expires. One possibility is to pin down the specific version in your build scripts.

**Comment by exosept** [comment] 2024-05-07 11:41
Hi Michele, thanks for your reply. I bought the tools in May 2023 and been using that version ever since. The last built occured in october 2023.  It's not been modified,  rebuilt or republished to Firebase ever since. That's why I do not understand why I started to get the expired message on May 2024.

**Comment by michelengelen** [comment] 2024-05-07 12:50
@joserodolfofreitas I am not too familiar with the license implications. Could you jump in here?

**Comment by flaviendelangle** [comment] 2024-05-07 15:45
Here is the description of "annual license", which I guess is the one you have:

![image](https://github.com/mui/mui-x/assets/3309670/ff0ee116-bb73-43f7-a8da-2a1838b1f490)

My guess is that the build your deployed application is using is a development build.

We are using `process.env.NODE_ENV === 'production'` for our checks, if your build is not configured correctly it would explain the problem.

Note that a dev build deployed in production has other implications outside of MUI X, you would be using the dev mode of React which is by far less performant than the prod one, the bundle would probably not be optimized in size etc...

To check this, you could log the following a deploy your website in some test environment:

```js
console.log('ENV', process.env.NODE_ENV)
```

If it logs `production`, then the problem comes from something else :grimacing:

**Comment by exosept** [comment] 2024-05-07 16:18
Thanks a lot, you answered my question.

**Comment by michelengelen** [comment] 2024-05-08 09:45
Thanks @flaviendelangle ... I did not check the license verification 🤦🏼 

@exosept feel free to close this if the issue is resolved for you!

**Closed** 2024-05-15 15:06 UTC
Labels: status: waiting for author, package: x-license, support: commercial, support: premium standard
