### ISSUE TITLE
[DataGrid] Remove headerHeight prop

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#602] opened 2020-11-18 11:26 UTC
The grid has a `headerHeight` that we should be able to remove by moving the AutoSizer down in the DOM tree, to only where we need it: for the rendering zone. It would solve this confusion: https://github.com/mui-org/material-ui-x/pull/597#issuecomment-729577809 and this bug: https://github.com/mui-org/material-ui-x/pull/597#pullrequestreview-531406090. It's also the approach used by ag-Grid.

**Comment by cherniavskii** [comment] 2022-11-23 15:39
AutoSizer has been moved down in the DOM tree and it doesn't contain the columns header anymore:
<img width="342" alt="Screenshot 2022-11-23 at 15 09 07" src="https://user-images.githubusercontent.com/13808724/203567668-14ac47ff-a37d-4ff7-a7c6-b266bda04810.png">

`headerHeight` prop is still being used:
1. By virtual scroller to add a top margin and not overlap with columns header (columns header has position absolute
https://github.com/mui/mui-x/blob/4891eafe516f698fbe3689ba6a3a6c78ed069e85/packages/grid/x-data-grid/src/components/base/GridBody.tsx#L86-L87
2. For density, since it impacts the columns header height as well
https://github.com/mui/mui-x/blob/4891eafe516f698fbe3689ba6a3a6c78ed069e85/packages/grid/x-data-grid/src/hooks/features/density/useGridDensity.tsx#L23-L27
3. For column header grouping, since the same height is used for each "row" of column headers
https://github.com/mui/mui-x/blob/4891eafe516f698fbe3689ba6a3a6c78ed069e85/packages/grid/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx#L322
And some more places.

I don't see any reason to remove the `headerHeight` prop.

---

We can address the confusion raised in https://github.com/mui/mui-x/pull/597#issuecomment-729577809 by removing the `Header` slot:
https://github.com/mui/mui-x/blob/4891eafe516f698fbe3689ba6a3a6c78ed069e85/packages/grid/x-data-grid/src/models/gridSlotsComponent.ts#L79-L84

I've created a separate issue for it https://github.com/mui/mui-x/issues/6977.

**Comment by cherniavskii** [comment] 2022-11-23 15:43
Feel free to point out any other issues related to the `headerHeight` prop.
Otherwise, we can close the issue.

**Comment by cherniavskii** [comment] 2022-11-25 18:58
@m4theushw Thanks for looking into it!

> If the column headers weren't absolute positioned, the marginTop (1.) applied to the virtual scroller could be removed.

I tried to do this in https://github.com/mui/mui-x/pull/7001
It seemed to be very promising at first, but I wasn't able to fix regressions.
Turns out column headers have `position: 'absolute'` for a reason. Without it, the grid exceeds the width of the parent container instead of showing a horizontal scroll in the flex layout:
https://app.argos-ci.com/mui/mui-x/builds/6190/29684941

<img width="1608" alt="Screenshot 2022-11-25 at 19 49 17" src="https://user-images.githubusercontent.com/13808724/204041502-91e4efca-7fce-420e-b792-ebfbb3f6d321.png">


> To summarize, the idea is to fix the AutoSizer so it measures only the content portion. As result, the headerHeight prop will become useless because we won't need to use it to subtract from the grid height.

I think doing that would require a lot of time, while the gain would be minimal.

Furthermore, I find the `headerHeight` prop convenient since it allows changing row and header height in the same way.
If we remove it - it won't be obvious that the header height should be changed with CSS instead.

What do you think?

**Closed** 2023-01-05 20:41 UTC
Labels: breaking change, component: data grid, waiting for 👍, v6.x
