### ISSUE TITLE
DateRangeCalendar - Styling past dates

### ISSUE THREAD

**Issue by mightym** [mui/mui-x#10088] opened 2023-08-19 19:39 UTC
### Order ID or Support key 💳 (optional)

56782

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hey, I'm currently trying to style past dates on my `DateRangeCalendar` and realize that there is no class/Indicator on dates before today. I assumed that there is a class for a date that is the past like when you use `disablePast`. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by noraleonte** [comment] 2023-08-21 14:46
Hey, @mightym 👋 

Thanks for bringing this up! We currently do not differentiate the past or future dates with css classes. I think it might be a good idea to add that in, and I will make sure to bring this up! 

In the meantime, I think there might be a a somewhat hacky solution for styling the day slot conditionally with styled components. One of the props the `DateRangePickerDay` receives is `day` which is basically the value that it represent. You can use that to figure out whether the day you are styling is before or after the current date, and style it accordingly. 

``` javascript
const StyledDay = styled(DateRangePickerDay)(({ day }) => {
  // use the day to apply conditional styling
  return {
    // styles
  };
});
```
And use it like this: 
``` javascript
<DateRangePicker
  slots={{ day: StyledDay }}
/>
```

Let me know if this helps 🛩️

**Comment by noraleonte** [comment] 2023-08-22 09:07
@mightym Could you provide a reproduction case for this? I would like to understand exactly what you are trying to achieve and provide more suitable solution for your problem 😄

**Comment by mightym** [comment] 2023-08-22 09:25
@noraleonte Our Calendar Component basically needs to indicate visually between 3 Date Types -> Today (this is what the current MUI calendar already does), Days before Today, Days after Today. The last 2 can be achieved if you know either which is a past day or a future day. So that you can do something like this: 

<img width="675" alt="Bildschirmfoto 2023-08-22 um 11 19 52" src="https://github.com/mui/mui-x/assets/11863/4dd405cc-b884-4980-acdc-d1b079aa708d">

Which I'm currently doing like you proposed: If a day is older than today give the element a different styling. Which is fine. 
I just wanted to point out that it might be helpful for other people if the past days or future days have by default a class which could be used for styling.

**Comment by mightym** [comment] 2023-08-24 14:24
They are selectable. But maybe my usecase is too special. The purpose in my case is basically giving the user a quick overview what is in the past (not that important) and what is in the future. Don't bother yourself too much with it guys. The workaround works great in my case.

**Comment by flaviendelangle** [comment] 2023-08-24 14:41
We discussed it on Monday.
We will not add a className because it's too specific to be in everybody's bundle.

But we could add the date in the `ownerState` so that you can do :

```tsx
const theme = createTheme({
    components: {
        MuiDateCalendar: {
            styleOverrides: {
                root: ({ ownerState }) => {
                    if (ownerState.day) {
                        return { /* My custom style */}
                    }
                    return {};
                }
            }
        }
    }
});
```

**Comment by flaviendelangle** [comment] 2023-08-24 14:46
We discussed it on Monday.
We will not add a className because it's too specific to be in everybody's bundle.

With the current API, the best solution for you is probably to use the theme style overrides if it's pure CSS (see https://codesandbox.io/s/date-and-time-pickers-forked-zp2j6l?file=/src/App.tsx) or the `day` slot if you need deeper changes.

**Comment by michelengelen** [comment] 2023-10-09 10:36
Since @mightym is OK with the workaround and @mui/explore does not plan to add a `className` I will close this now. Feel free to reopen if you have objections.

**Closed by michelengelen** 2023-10-09 10:36 UTC
Labels: plan: Pro, support: commercial, component: pickers
