### ISSUE TITLE
[docs] Website improvements (API docs)

### ISSUE THREAD

**Issue by yay** [mui/mui-x#5263] opened 2022-06-20 09:47 UTC
For example, the following page https://mui.com/x/api/data-grid/data-grid/#props has a horizontal scrollbar for the whole props section.

It's really confusing with a narrow browser window width and looks as if the right sidebar is overlapping the content.
So you make the browser window wider but it remains to be the case.
No matter how wide the browser window is, the horizontal scroll is always there.

Can you please make the UI more responsive and get rid of the horizontal scrolling in cases where there's absolutely no need for it?

**Comment by oliviertassinari** [comment] 2022-12-19 16:03
Duplicate of https://github.com/mui/material-ui/issues/34085

**Closed by oliviertassinari** 2022-12-19 16:03 UTC
Labels: docs, duplicate, dx
