### ISSUE TITLE
[license] Issue with MUI X Pro license

### ISSUE THREAD

**Issue by genovic-serviceuser** [mui/mui-x#9674] opened 2023-07-14 05:29 UTC
Hi MUI X Support,

We've purchased a single developer MUI X Pro licence and our developer is trying to deploy a second site with MUI X code and she is getting a watermark in the database table saying we don't have a license. There were no problems with deploying the first site. Is there any reason why this is coming up, given it's the single developer that has build and deployed both sites?

Thanks,
Tim Bakker
Melbourne Genomics Health Alliance

**Comment by joserodolfofreitas** [comment] 2023-07-14 09:30
Hi Tim, 
If the error states "missing license", that means it hasn't received any license as input.

You can get more information about the license validation messages at: 
https://mui.com/x/introduction/licensing/#validation-failures

In case you're using a Next application and you're passing the license through an environment variable, you must prefix it with "NEXT_PUBLIC_" as stated in [NextJs docs](https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser).

**Comment by oliviertassinari** [comment] 2024-09-12 11:55
Closing as the issue is one year old and we have no enough information to act on it.

**Closed by oliviertassinari** 2024-09-12 11:55 UTC
Labels: package: x-license, support: commercial
