### ISSUE TITLE
DateTimePicker in v6 does not format time correctly in "fr" locale using Luxon adapter

### ISSUE THREAD

**Issue by ddolcimascolo** [mui/mui-x#8128] opened 2023-03-04 14:30 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

This CSB reproduces: https://codesandbox.io/s/practical-chatterjee-vbdrh2

### Current behavior 😯

Time is formatted as `4‎⁩ / ⁨3‎⁩ / ⁨2023⁩⁩ ⁦⁨4‎⁩:⁨1‎`

### Expected behavior 🤔

Time is formatted as `4‎⁩ / ⁨3‎⁩ / ⁨2023⁩⁩ ⁦⁨16:0⁨1‎`

### Context 🔦

Found during an upgrade from latest v5 to v6.0.0

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

31461

**Comment by snoop088** [comment] 2023-03-04 20:05
I have the same issue with 'en-gb' and controlled input:
https://codesandbox.io/s/snowy-firefly-pthmwe
thought I was missing something.

**Comment by flaviendelangle** [comment] 2023-03-05 18:04
Hi,

It's probably the same problem as in https://github.com/mui/mui-x/issues/7615
You can try to manually pass the format (which is not a great solution of course), to do better we need the fix from Luxon :/

**Comment by ddolcimascolo** [comment] 2023-03-05 22:26
Thx for replying @flaviendelangle.

How come v6 was released with this issue? Luxon is advertised as supported or I missed something... Clearly in locales using a 24h time format (@snoop088 confirmed for en-GB, I did for fr) the pickers are not working properly. Not even considering time **input**, the picker here is not even **showing** the right time

If you need any other information from me, feel free to ask. Premium customer here, hoping for a fix soon. 

Cheers, 
David

**Comment by ddolcimascolo** [comment] 2023-03-05 22:34
I commented https://github.com/moment/luxon/issues/1197

**Comment by flaviendelangle** [comment] 2023-03-06 17:27
> How come v6 was released with this issue?

I think post-poning the release would not be the solution given that it would prevent most users to have access to the new features.
But we should have stated clearly in the doc the limitations with Luxon, sorry for that.

I doubt it will be doable, but I'll check if it's doable to implement the fix on our side, but it's not very likely.

**Comment by ddolcimascolo** [comment] 2023-03-06 18:58
Thx for trying @flaviendelangle

**Comment by ddolcimascolo** [comment] 2023-03-07 06:49
I see some progress on the linked Luxon issue, which is nice. I'm afraid it only fixes it for the _hours_ though, can you check @flaviendelangle? In my reproduction above the _minutes_ are also wrong

Thx,
David

**Comment by flaviendelangle** [comment] 2023-03-07 14:09
For the minute, I guess the problem is the `expandFormat` is returning `m` instead of `mm` for your format.

Is it causing any weird behavior to have `1` instead of `01` ?
I'm asking, because at some point, we thought about adding leading zeroes even when the format don't have them, which would mean that Luxon would be as precise as the other libraries on that topic.
If we do want Luxon to differentiate `m` and `mm` in `expandFormat`, I guess we can tweak the function (if they agree), but the value seems a lot lower than for hours (where it's basically unusable).

**Comment by ddolcimascolo** [comment] 2023-03-07 19:57
No, it's not causing any trouble but users are confused. Please note that I didn't try to _input_ minutes as we're using the clock (I followed the migration guide to add it back in v6)

**Comment by ddolcimascolo** [comment] 2023-03-10 07:00
Hi all,

Can we get an update on this issue? Also I still see the needs triage label, but this is definitely a bug, a regression from v5.

Thx,
David

**Comment by LukasTy** [comment] 2023-03-10 11:33
Changed the labels, but the cause of the issue was discussed, is external, and is being worked on, by the looks of an open PR in "luxon" repository.
The ideal solution would be to wait until the fix is released on their side to avoid any hacky solutions on our side.

**Comment by flaviendelangle** [comment] 2023-03-15 08:59
I'm closing this issue in favor of #7615 and adding a warning in the doc until we have a fix from Luxon

**Closed by flaviendelangle** 2023-03-15 09:00 UTC
Labels: bug 🐛, external dependency, component: pickers
