### ISSUE TITLE
v5 with <DataGridPro> worked fine inside "display: 'grid'" but v6 doesn't work properly.

### ISSUE THREAD

**Issue by luan-dang-techlabs** [mui/mui-x#8547] opened 2023-04-07 21:35 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Change version to v5 and v6
2. Add the 'display: 'grid' option in v6 and notice width is stretched.

https://codesandbox.io/s/datagrid-6-0-0-in-grid-forked-plbm9p?file=/demo.tsx

### Current behavior 😯

1. Working in v5.

https://user-images.githubusercontent.com/91907117/230681570-de6deafb-21c9-42ab-b2d5-88a073b262b0.mov

2. Doesn't work properly in v6

https://user-images.githubusercontent.com/91907117/230681755-d296390f-53c3-4c23-8bab-ee7ce66e2be5.mov

### Expected behavior 🤔

I expected v6 to work the same way as it did for v5.

### Context 🔦

Toggle Version v5 and v6 , notice in v5 there is a proper horizontal at parent's width.

```
import * as React from "react";
import { DataGrid } from "@mui/x-data-grid";
import { Box, Card, CardContent, Container, Grid } from "@mui/material";

const rows = [
  {
    id: 1,
    username: "@MUI",
    age: 20
  }
];

export default function ColumnFluidWidthGrid() {
  return (
    <Container maxWidth="sm" component="main">
      <Box sx={{ width: "100%", display: "grid" }}>
        <DataGrid
          autoHeight
          columns={[
            {
              field: "id",
              flex: 1,
              minWidth: 500
            },
            {
              field: "username",
              flex: 0.5,
              minWidth: 400
            },
            {
              field: "age",
              flex: 0.3,
              minWidth: 400
            }
          ]}
          rows={rows}
        />
      </Box>
    </Container>
  );
}


```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by luan-dang-techlabs** [comment] 2023-04-07 21:45
One Workaround is to declare DataGridPro style to use 'grid' and set the proper row sizing. But unsure if this is correct way of fixing it. 

```
    sx={{display: 'grid', gridTemplateRows: 'auto 1f auto'}}
```

```
import * as React from "react";
import { DataGrid } from "@mui/x-data-grid";
import { Box, Card, CardContent, Container, Grid } from "@mui/material";

const rows = [
  {
    id: 1,
    username: "@MUI",
    age: 20
  }
];

export default function ColumnFluidWidthGrid() {
  return (
    <Container maxWidth="sm" component="main">
      <Box sx={{ width: "100%", display: "grid" }}>
        <DataGrid
        sx={{display: 'grid', gridTemplateRows: 'auto 1f auto'}}
          autoHeight
          columns={[
            {
              field: "id",
              flex: 1,
              minWidth: 500
            },
            {
              field: "username",
              flex: 0.5,
              minWidth: 400
            },
            {
              field: "age",
              flex: 0.3,
              minWidth: 400
            }
          ]}
          rows={rows}
        />
      </Box>
    </Container>
  );
}


```

**Comment by cherniavskii** [comment] 2023-04-11 09:56
Thanks, @m4theushw!
I'll submit a PR to check if it causes any regressions.

**Comment by cherniavskii** [comment] 2023-04-12 13:50
@luan-dang-techlabs 
> Have you seen issue where using <DataGrid sx={{ overflow: "hidden" }} /> doesn't work ?

Yes, https://github.com/mui/mui-x/issues/8182 for example. But it's already fixed.

> I have same problem using <DataGrid sx={{ overflow: "hidden" }} /> in my environment.

Can you provide a reproduction example?

**Comment by luan-dang-techlabs** [comment] 2023-04-12 20:45
> @luan-dang-techlabs
> 
> > Have you seen issue where using <DataGrid sx={{ overflow: "hidden" }} /> doesn't work ?
> 
> Yes, #8182 for example. But it's already fixed.
> 
> > I have same problem using <DataGrid sx={{ overflow: "hidden" }} /> in my environment.
> 
> Can you provide a reproduction example?


Sorry should have been more clear, it appears that when inside TabPanel doesn't work well. I think there might be a bug with TabPanel, TabPanel doesn't have {overflow: 'hidden'}. Using Tabs without TabPanel works well with ```<DataGrid/ sx={{overflow: 'hidden'>```


e.g. https://codesandbox.io/s/data-grid-community-forked-0m572v?file=/src/App.tsx

```
import React from "react";
import { DataGrid, GridRowsProp, GridColDef } from "@mui/x-data-grid";
import { Box } from "@mui/material";
import Tab from "@mui/material/Tab";
import TabContext from "@mui/lab/TabContext";
import TabList from "@mui/lab/TabList";
import TabPanel from "@mui/lab/TabPanel";

const rows: GridRowsProp = [
  { id: 1, col1: "Hello", col2: "World" },
  { id: 2, col1: "XGrid", col2: "is Awesome" },
  { id: 3, col1: "Material-UI", col2: "is Amazing" },
  { id: 4, col1: "Hello", col2: "World" },
  { id: 5, col1: "XGrid", col2: "is Awesome" },
  { id: 6, col1: "Material-UI", col2: "is Amazing" }
];

const columns: GridColDef[] = [
  { field: "id", width: 500 },
  { field: "col1", headerName: "Column 1", width: 500 },
  { field: "col2", headerName: "Column 2", width: 500 }
];

export default function App() {
  const [value, setValue] = React.useState("1");

  const handleChange = (event: React.SyntheticEvent, newValue: string) => {
    setValue(newValue);
  };
  return (
    <div style={{ height: "100vh", width: "100%", display: "grid" }}>
      <TabContext value={value}>
        <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
          <TabList onChange={handleChange}>
            <Tab label="Item One" value="1" />
          </TabList>
        </Box>
        <TabPanel value="1">
          <DataGrid
            rows={rows}
            columns={columns}
            sx={{
              overflow: "hidden",
              ".MuiDataGrid-main": { borderLeft: "1px solid red" }
            }}
          />
        </TabPanel>
      </TabContext>
    </div>
  );
}

```

e.g.

https://user-images.githubusercontent.com/91907117/231579967-11a98354-81ae-47d2-90e0-40285a6294d2.mov

**Comment by oliviertassinari** [comment] 2023-04-12 23:44
To me, this looks like the classic `display: 'grid'` min-width issue. See https://css-tricks.com/preventing-a-grid-blowout/. It solves the problem in each reproduction.

**Comment by cherniavskii** [comment] 2023-04-22 14:37
@luan-dang-techlabs 
I think the behavior of grid v6 with the `overflow: hidden` is the correct one.
To prove it, I created a simple `GridMock` component, which consists of two elements:

```tsx
<div style={{ overflow: "auto" }}>
  <div
    style={{
      width: "2000px",
      height: "200px",
      backgroundColor: "green"
    }}
  ></div>
</div>
```

You can see that the GridMock is not scrollable and is rendered in full width: https://codesandbox.io/s/data-grid-community-forked-g9eqnt?file=/src/App.tsx
I believe that the data grid should behave in the same way, and it will after https://github.com/mui/mui-x/pull/8577 is merged.

**Comment by luan-dang-techlabs** [comment] 2023-04-25 17:08
> @luan-dang-techlabs I think the behavior of grid v6 with the `overflow: hidden` is the correct one. To prove it, I created a simple `GridMock` component, which consists of two elements:
> 
> ```tsx
> <div style={{ overflow: "auto" }}>
>   <div
>     style={{
>       width: "2000px",
>       height: "200px",
>       backgroundColor: "green"
>     }}
>   ></div>
> </div>
> ```
> 
> You can see that the GridMock is not scrollable and is rendered in full width: https://codesandbox.io/s/data-grid-community-forked-g9eqnt?file=/src/App.tsx I believe that the data grid should behave in the same way, and it will after #8577 is merged.

@cherniavskii - thanks I see what you saying.

**Comment by oliviertassinari** [comment] 2023-04-25 21:41
Would it make sense to add the min width style to the base style of the data grid? I suspect that it will be the default behavior that most developers want with display grid. We might save developers the hassle to find this issue.

**Comment by luan-dang-techlabs** [comment] 2023-04-28 16:53
> 

This will actually work by having minWidth: 0 as baseline styles of TabPanel.

**Closed** 2023-05-11 11:58 UTC
Labels: component: data grid, plan: Pro, regression, v6.x, feature: Rendering layout

**Comment by noherczeg** [comment] 2023-05-11 16:55
Is there anything MUI users should do now, or is this fixed internally? If so do we have a specific release version?

**Comment by cherniavskii** [comment] 2023-05-12 10:20
@noherczeg We plan to release it today 🙂

**Comment by luan-dang-techlabs** [comment] 2023-05-12 17:33
@cherniavskii @noherczeg - I opened up a jira bug https://github.com/mui/material-ui/issues/37255 to add "minWidth: '0'" as default for TabPanel to fix the scrolling issue too.

e.g. https://github.com/mui/material-ui/issues/37255

**Comment by luan-dang-techlabs** [comment] 2023-05-12 17:33
@cherniavskii @oliviertassinari - thanks for your help.

**Comment by cherniavskii** [comment] 2023-05-12 18:22
@luan-dang-techlabs Thank you!

**Comment by oliviertassinari** [comment] 2023-05-16 18:12
> I struggle to find a use case where minWidth: 0 applied to the data grid could be useful.

@cherniavskii I was thinking as an alternative so we can avoid `overflow: hidden`. I rarely had a positive outcome with this style, I'm always suspicious about it. For instance on https://mui.com/x/ under "A level of performance and quality that hasn't been seen before" with the "Selection" feature demo selected, you will find that this style truncate the scrollbar.

**Comment by oliviertassinari** [comment] 2023-05-31 14:04
@cherniavskii Another bug with overflow: hidden

<img width="474" alt="Screenshot 2023-05-31 at 16 02 55" src="https://github.com/mui/mui-x/assets/3165635/bafccb19-597b-4169-b5b8-d0f973dcf8c2">

https://mui.com/x/react-data-grid/filtering/#customize-the-filter-panel-content

**Comment by cherniavskii** [comment] 2023-05-31 15:52
Damn, I didn't expect it to backfire like this! 😅
Thanks for spotting it, I'll take a look 👍

**Comment by mfalthaw** [comment] 2023-08-30 19:20
> One Workaround is to declare DataGridPro style to use 'grid' and set the proper row sizing. But unsure if this is correct way of fixing it
> ...

Thank you @luan-dang-techlabs, this solved it for me 🎊 
```jsx
<Box sx={{ width: "100%", display: "grid" }}>
  <DataGrid />
</Box>
```

**Comment by eltaurito** [comment] 2024-03-11 08:57
> One Workaround is to declare DataGridPro style to use 'grid' and set the proper row sizing. But unsure if this is correct way of fixing it.
> 
> ```
>     sx={{display: 'grid', gridTemplateRows: 'auto 1f auto'}}
> ```
> 
> ```
> import * as React from "react";
> import { DataGrid } from "@mui/x-data-grid";
> import { Box, Card, CardContent, Container, Grid } from "@mui/material";
> 
> const rows = [
>   {
>     id: 1,
>     username: "@MUI",
>     age: 20
>   }
> ];
> 
> export default function ColumnFluidWidthGrid() {
>   return (
>     <Container maxWidth="sm" component="main">
>       <Box sx={{ width: "100%", display: "grid" }}>
>         <DataGrid
>         sx={{display: 'grid', gridTemplateRows: 'auto 1f auto'}}
>           autoHeight
>           columns={[
>             {
>               field: "id",
>               flex: 1,
>               minWidth: 500
>             },
>             {
>               field: "username",
>               flex: 0.5,
>               minWidth: 400
>             },
>             {
>               field: "age",
>               flex: 0.3,
>               minWidth: 400
>             }
>           ]}
>           rows={rows}
>         />
>       </Box>
>     </Container>
>   );
> }
> ```
> 
> e.g.
> 
>  v6-fix-scrolling.mov

Ehi @luan-dang-techlabs, thanks for your solution! 😀

I had to adjust a bit the sx prop in this way:
`sx={{ display: 'grid', minWidth: 0, overflow: 'hidden' }}`

Now it works perfectly 👍
