### ISSUE TITLE
[charts] 'log' axes & zoom cause warnings and grid breakdown due to non-unique child keys

### ISSUE THREAD

**Issue by qwyble** [mui/mui-x#15853] opened 2024-12-11 18:56 UTC
### Steps to reproduce

Steps:
1. Open this link to live example: [https://codesandbox.io/p/sandbox/fast-cloud-pwx7wp](https://codesandbox.io/p/sandbox/fast-cloud-pwx7wp)
2. Open preview console
3. Observe warnings
4. Usage with 'zoom' for LineChartPro results in grid breakdown due to this issue.

### Current behavior

Console sprays warnings.

![Screenshot 2024-12-11 at 10 50 15 AM](https://github.com/user-attachments/assets/850443e0-c214-46d7-917b-a765f6b29ab1)

Using 'zoom' parameters in LineChartPro causes complete grid breakdown due to this same issue.

### Expected behavior

Console should not spray warnings, child elements should have unique keys.
Zoom should not break the grid.

### Context

This occurs when using 'log' axes and when modifying axes using zoom parameters, likely due to ticks being used to provide keys to the grid.

### Your environment

ENV: Chromium

**Search keywords**: LineChart, LineChartPro, grid, GridChart, log, zoom

**Comment by michelengelen** [comment] 2024-12-12 11:18
Hey @qwyble ... I am not able to reproduce this locally, but it does reproduce in the codesandbox. This may be a problem with CSB 🤷🏼 

Did any of you encounter this before @JCQuintas or @alexfauquette ?

https://github.com/user-attachments/assets/23a7b041-5c89-400f-bb51-e2b4a6177c26

**Comment by JCQuintas** [comment] 2024-12-12 11:52
@michelengelen I believe we fixed it here: https://github.com/mui/mui-x/pull/15463

But it wasn't properly cherrypicked, might explain why you are not seeing it locally

**Comment by JCQuintas** [comment] 2024-12-12 13:11
Fixed on https://github.com/mui/mui-x/pull/15864

Thanks for reporting 👍

**Closed by JCQuintas** 2024-12-12 13:11 UTC
Labels: bug 🐛, status: waiting for author, component: charts
