### ISSUE TITLE
[DataGrid] When columns are pinned, memoized rows always rerender

### ISSUE THREAD

**Issue by ludvigeriksson** [mui/mui-x#9105] opened 2023-05-24 11:07 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://mui.com/x/react-data-grid/performance/#memoize-inner-components-with-react-memo

Steps:
1. Try the demo linked above
2. Pin a column
3. Select cells, make changes to the table, select/deselect rows

### Current behavior 😯

The entire table rerenders

### Expected behavior 🤔

Only the rows that are interacted with should be rerendered

### Context 🔦

I have a large table where the rows needs to be memoized for performance reasons. Since the table is so large, the pinning function is very useful, since horizontal scrolling will be necessary in my scenario.

### Your environment 🌎

Problem appears in your own example page.

### Order ID or Support key 💳 (optional)

64636

**Comment by martinhonza** [comment] 2023-05-24 11:39
I think its duplicate of this this ticket https://github.com/mui/mui-x/issues/9013

**Closed** 2023-05-24 15:18 UTC
Labels: duplicate, component: data grid, plan: Pro
