### ISSUE TITLE
longFormatters is not exported from package date-ins

### ISSUE THREAD

**Issue by landymore** [mui/mui-x#12282] opened 2024-03-01 17:30 UTC
### Steps to reproduce

Update dependencies to current on a next js app using ncu:
```
 @azure/msal-browser                        ^3.7.1  →          ^3.10.0
 @azure/msal-react                         ^2.0.10  →          ^2.0.12
 @babel/preset-env                         ^7.23.9  →          ^7.24.0
 @emotion/react                            11.11.3  →          11.11.4
 @mui/icons-material                       ^5.15.6  →         ^5.15.11
 @mui/lab                          5.0.0-alpha.162  →  5.0.0-alpha.166
 @mui/material                              5.15.6  →          5.15.11
 @mui/system                                5.15.6  →          5.15.11
 @mui/x-data-grid                          ^6.19.2  →          ^6.19.5
 @mui/x-data-grid-generator                ^6.19.2  →          ^6.19.5
 @mui/x-date-pickers                       ^6.19.2  →          ^6.19.5
 @testing-library/react                    ^14.1.2  →          ^14.2.1
 @types/node                              ^20.11.6  →        ^20.11.24
 @types/react                             ^18.2.48  →         ^18.2.61
 @types/react-dom                         ^18.2.18  →         ^18.2.19
 @typescript-eslint/eslint-plugin          ^6.19.1  →           ^7.1.0
 @typescript-eslint/parser                 ^6.19.1  →           ^7.1.0
 apexcharts                                 3.45.2  →           3.46.0
 axios                                      ^1.6.6  →           ^1.6.7
 date-fns                                  ^2.30.0  →           ^3.3.1
 eslint                                     8.56.0  →           8.57.0
 eslint-config-next                         14.1.0  →           14.1.1
 next                                      ^14.0.4  →          ^14.1.1
 react-router-dom                          ^6.21.3  →          ^6.22.2
 react-tooltip                             ^5.26.0  →          ^5.26.3
```

Execute `npm run build`

next.config.js:
```
module.exports = {
  reactStrictMode: true,
  distDir: 'dist',
  staticPageGenerationTimeout: 1000,
  output: 'export'
};
```

### Current behavior

```
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types    
   Creating an optimized production build ...
   Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.json" https://nextjs.org/docs/messages/swc-disabled
   Using external babel configuration from [redacted]/babel.config.json
   Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.json" https://nextjs.org/docs/messages/swc-disabled
   Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.json" https://nextjs.org/docs/messages/swc-disabled
   Using external babel configuration from [redacted]/babel.config.json
Failed to compile.

./node_modules/@mui/x-date-pickers/AdapterDateFns/AdapterDateFns.js
Module not found: Package path ./_lib/format/longFormatters is not exported from package [redacted]/node_modules/date-fns (see exports field in [redacted]/node_modules/date-fns/package.json)

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@mui/x-date-pickers/AdapterDateFns/index.js
./src/pages/_app.js


> Build failed because of webpack errors
```

### Expected behavior

Successful compile

### Context

Trying to keep dependencies current.

### Your environment

```
  System:
    OS: macOS 14.3.1
  Binaries:
    Node: 20.8.0 - /usr/local/bin/node
    npm: 10.4.0 - /usr/local/bin/npm
    pnpm: 8.15.4 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.94
    Edge: Not Found
    Safari: 17.3.1
  npmPackages:
    @emotion/react: 11.11.4 => 11.11.4 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.37 
    @mui/core-downloads-tracker:  5.15.11 
    @mui/icons-material: ^5.15.11 => 5.15.11 
    @mui/lab: 5.0.0-alpha.166 => 5.0.0-alpha.166 
    @mui/material: 5.15.11 => 5.15.11 
    @mui/private-theming:  5.15.11 
    @mui/styled-engine:  5.15.11 
    @mui/system: 5.15.11 => 5.15.11 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.11 
    @mui/x-data-grid: ^6.19.5 => 6.19.5 
    @mui/x-data-grid-generator: ^6.19.5 => 6.19.5 
    @mui/x-data-grid-premium:  6.19.5 
    @mui/x-data-grid-pro:  6.19.5 
    @mui/x-date-pickers: ^6.19.5 => 6.19.5 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.2.61 => 18.2.61 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^5.3.3 => 5.3.3 
```

**Search keywords**: exports AdapterDateFns

**Comment by Farzin-Firoozi** [comment] 2024-03-02 12:03
I have this issue too.

**Comment by tugayRad** [comment] 2024-03-03 13:16
Using worked for me.
`import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFnsV3';`

**Comment by LukasTy** [comment] 2024-03-04 07:26
It's a duplicate of #12144.
Please check https://github.com/mui/mui-x/issues/12144#issuecomment-1953729205 for more information. 🙏

**Closed by LukasTy** 2024-03-04 07:26 UTC
Labels: status: waiting for maintainer
