### ISSUE TITLE
This import breaks build via rsbuild

### ISSUE THREAD

**Issue by iCoderXXI** [mui/mui-x#13764] opened 2024-07-08 15:18 UTC
https://github.com/mui/mui-x/blob/8acc14171ae216d5d538f94c87816047a3ebbade/packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts#L46

There is no need to import longFormatters from _lib/format/longFormatters because it is reexported in /format.

![image](https://github.com/mui/mui-x/assets/1162841/5b4e5c76-4a95-43ba-8d2a-bb57760ef52c)

**Search keywords**:

**Comment by LukasTy** [comment] 2024-07-08 20:13
Hello, you are probably checking the `AdapterDateFns` code, which is designed to work with date-fns v2.
It does not export `longFormatters`: https://github.com/date-fns/date-fns/blob/v2/src/format/index.ts

`AdapterDateFnsV3` is designed to work with date-fns v3 and is using this export:
https://github.com/mui/mui-x/blob/8acc14171ae216d5d538f94c87816047a3ebbade/packages/x-date-pickers/src/AdapterDateFnsV3/AdapterDateFnsV3.ts#L15

You can read more about this [in the documentation](https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns).

I'm closing it as this looks like a duplicate of #12758, https://github.com/mui/mui-x/issues/12467, https://github.com/mui/mui-x/issues/12282, https://github.com/mui/mui-x/issues/12144.

Feel free to reopen this issue if you still see a problem. 😉

**Closed by LukasTy** 2024-07-08 20:13 UTC
Labels: status: waiting for maintainer, component: pickers
