### ISSUE TITLE
[pickers] Unable to set timezone in DatePicker

### ISSUE THREAD

**Issue by SatendraRaghav** [mui/mui-x#12195] opened 2024-02-23 15:03 UTC
### Steps to reproduce

Link to live example: (required)

Steps:
1. Develop a date component with MUI X DatePicker in a form
2. Call an api and send api formdata in api payload , Open payload in network  tab  , you can see previous date is coming in payload.

### Current behavior

Previous date is coming in payload and also there is no props available to set timezone in DatePicker.

### Expected behavior

Selected date should be come and there should be timezone props to change date according to timezone.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: timezone,datepicker, UTC,

**Search keywords**:

**Comment by michelengelen** [comment] 2024-02-26 10:28
Hey @SatendraRaghav,

Could you please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

Also there is a `timezone` prop on the DatePicker ([API docs](https://mui.com/x/api/date-pickers/date-picker/#props)).

It does indeed seem to be a bit off @LukasTy ... 🤔 Any idea where that would come from? Or is this expected behaviour?

**Comment by shaharyar-shamshi** [comment] 2024-02-26 13:35
@LukasTy this seems indeed a bug but one major observation that I made is this happen when we switch to any American timezone. This works fine for switching from UTC to Asia/Calcutta. But when we switch from UTC to any American timezone this bug occur. Also Luxon give same issue.

**Comment by shaharyar-shamshi** [comment] 2024-02-28 06:25
@LukasTy This seems to be duplicate of https://github.com/mui/mui-x/issues/10804

**Comment by LukasTy** [comment] 2024-02-28 09:30
> This seems to be duplicate of #10804.

Good observation. Maybe it is, we'd need more information from the issue author to confirm it. 👍 

> If we plan to fix this can I pick this issue.

Oh yes, that was one of the more immediate things on the agenda.
Timezone management issues could be non-trivial to solve and we need reliable tests to cover those problems.
If you are up for the challenge - feel free to look into it. 😉

**Comment by shaharyar-shamshi** [comment] 2024-02-28 09:52
> > This seems to be duplicate of #10804.
> 
> Good observation. Maybe it is, we'd need more information from the issue author to confirm it. 👍
> 
> > If we plan to fix this can I pick this issue.
> 
> @shaharyar-shamshi Oh yes, that was one of the more immediate things on the agenda. Timezone management issues could be non-trivial to solve and we need reliable tests to cover those problems. If you are up for the challenge - feel free to look into it. 😉

Timezone 😭 I am up for the challenge but I might require some more context. let me explore this more

**Comment by michelengelen** [comment] 2024-02-28 09:57
@shaharyar-shamshi let me know if you are still up for the challenge. If not we can just take it from here. Thanks for looking into it and don't hesitate to reach out for help! 💪🏼

**Closed** 2024-03-04 12:14 UTC
Labels: status: waiting for author, component: pickers
