### ISSUE TITLE
Actions list in data grid doesn't work with dialogs

### ISSUE THREAD

**Issue by Baribj** [mui/mui-x#12775] opened 2024-04-13 00:47 UTC
### Steps to reproduce

Link to live example: (required)
this example from the live example on https://mui.com/x/react-data-grid/column-definition/
https://stackblitz.com/edit/react-jbgb7s?file=Demo.tsx
Steps:
1. change closeMenuOnClick to true
2. clicking on the "delete" now opens the dialog and then it is immediately closed

### Current behavior

dialog closes automatically

### Expected behavior

dialog shouldn't close automatically

### Context

open a dialog when user clicks on action item. Happens on v6, didn't test on v7

### Your environment

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (123.0.2420.81)
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.6
    @mui/core-downloads-tracker:  5.15.14
    @mui/icons-material: ^5.11.16 => 5.13.7
    @mui/lab: ^5.0.0-alpha.130 => 5.0.0-alpha.135
    @mui/material: ^5.13.0 => 5.15.14
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.14
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid: ^6.19.10 => 6.19.10
    @types/react: 18.2.14 => 18.2.14
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^5.4.2 => 5.4.2

**Search keywords**: closeMenuOnClick

**Search keywords**:

**Comment by michelengelen** [comment] 2024-04-16 09:12
duplicate of #11579 and fixed in #11909 

This behavior is as expected for performance reasons. When closing the menu it gets unmounted and therefore the dialog disappears as well. The only way to prevent that is with the `closeMenuOnClick` provided by @cherniavskii

**Closed by michelengelen** 2024-04-16 09:12 UTC
Labels: component: data grid, status: waiting for maintainer

**Comment by cherniavskii** [comment] 2024-04-16 09:44
See this [actions demo](https://mui.com/x/react-data-grid/column-definition/#system-ActionsWithModalGrid.tsx)
