### ISSUE TITLE
MuiDataGrid-row--dynamicHeight not added to pinned column rows

### ISSUE THREAD

**Issue by mainfraame** [mui/mui-x#5825] opened 2022-08-17 16:16 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Given i have `getRowHeight={() => auto}`
And a pinned column
When the grid renders
Then `MuiDataGrid-row--dynamicHeight` is applied to non-pinned rows
And `MuiDataGrid-row--dynamicHeight` IS NOT applied to pinned rows

### Expected behavior 🤔

Given i have `getRowHeight={() => auto}`
And a pinned column
When the grid renders
Then `MuiDataGrid-row--dynamicHeight` is applied to non-pinned rows
And `MuiDataGrid-row--dynamicHeight` IS applied to pinned rows

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/dynamicrowheightgrid-demo-mui-x-forked-5pus2b?file=/demo.js

Steps:
1. Using DataGridPro create a grid with one pinned column and getRowHeight={() => 'auto' }
2. Observe that the dynamic row height class is not applied to the pinned column row

### Your environment 🌎

see codesandbox example

**Comment by cherniavskii** [comment] 2022-08-18 09:56
Duplicate of #5137, should be fixed by https://github.com/mui/mui-x/pull/5782

**Closed by cherniavskii** 2022-08-18 09:56 UTC
Labels: status: needs triage
