### ISSUE TITLE
[pickers] `DatePicker` end adornment overflow

### ISSUE THREAD

**Issue by lajerca** [mui/mui-x#5634] opened 2022-07-27 15:15 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when `TextField`  variant is `standard`  the icon button goes beyond the width of the component. It gets cropped if parent component has overflow: hidden

### Expected behavior 🤔

the icon should stay within the bounds of the component.

### Steps to reproduce 🕹

you can check it here:

[https://codesandbox.io/s/peaceful-platform-85z4is?file=/src/App.js](https://codesandbox.io/s/peaceful-platform-85z4is?file=/src/App.js)

### Context 🔦

![image](https://user-images.githubusercontent.com/47744877/181275967-7a85ae4a-b451-4060-836b-5e2cd04da950.png)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment] 2022-07-28 07:45
Thanks for reporting this issue. 

Here are two `TextFiled` with the same props. one wrapped by a `DateInput` and the other alone.
https://codesandbox.io/s/loving-jasper-vwtceg?file=/src/App.js

It appears that the `DateInput` endAdorment add to the `<button />` a `margin-right: -12px`. I did not found yet why this is added 

![image](https://user-images.githubusercontent.com/45398769/181450007-2c8490bd-f95c-4a86-80f3-bfd2b05b46fd.png)

A workaround is to remove it with `OpenPickerButtonProps={{ style: { margin: 0 } }}`

**Comment by flaviendelangle** [comment] 2022-12-13 09:29
We don't seem to have the issue on the v6 pickers anymore

See [this reproduction](https://codesandbox.io/s/dazzling-ioana-ouhedo)

**Comment by flaviendelangle** [comment] 2023-02-01 14:08
Closing this issue since the v6 pickers are in beta.
Feel free to comment if you have troubles with this new version :+1:

**Closed** 2023-02-01 14:08 UTC
Labels: bug 🐛, component: pickers, customization: css
