### ISSUE TITLE
Timefield shows regular keyboard instead of numeric on Firefox for android

### ISSUE THREAD

**Issue by Crownie88** [mui/mui-x#14959] opened 2024-10-14 12:37 UTC
### Steps to reproduce

Link to live example: (required)

Steps:
1. Install Firefox for android on an android device.
2. Go to https://mui.com/x/react-date-pickers/time-field/ and select the input shown in Basic usage
3. The regular keyboard is shown
Bonus:
4. Tap the button to switch applications
5. Reselect Firefox for android
6. Suddenly the correct keyboard is shown

### Current behavior

When you focus a timefield the default keyboard is used

### Expected behavior

The numeric keyboard is shown

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: timefield numeric

**Comment by LukasTy** [comment] 2024-10-14 14:11
Thank you for opening this issue. 🙏 
This is a duplicate of https://github.com/mui/mui-x/issues/13854.
The only reliable workaround, for now, is to use the [new accessible DOM structure](https://mui.com/x/react-date-pickers/fields/#accessible-dom-structure). 😉

**Closed by LukasTy** 2024-10-14 14:11 UTC
Labels: bug 🐛, status: waiting for maintainer, component: pickers
