### ISSUE TITLE
[data grid] Column Order State not saved on navigate away using link

### ISSUE THREAD

**Issue by SMoon-beckman** [mui/mui-x#12352] opened 2024-03-06 19:27 UTC
### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/state/#save-and-restore-the-state-from-external-storage
I've linked to the example on your site because the behavior is clearly observable there.

Steps:
1. Using a configured tables, such as the one in the provided link, change the column order
2. Navigate away from the page by clicking a link (i.e. not using either refresh or the back button)
3. Navigate back to your DataGrid. 
4. Observe the column order 

related: [Controlled Column Ordering](https://github.com/mui/mui-x/issues/5704)

### Current behavior

Column order does not persist when navigating away (using a click, as opposed to either refresh or the back button)

### Expected behavior

Column order state should be maintained when user clicks away. 

### Context

Using the pattern demonstrated in [Restore the state from Storage](https://mui.com/x/react-data-grid/state/#save-and-restore-the-state-from-external-storage), I see that my column order state successfully persists when using the back button or hitting refresh on my browser, but it does not do so when navigating to another location. All other state does persist (column visibility, filters, etc.). The `beforeunload` event does occur, but what I'm seeing is that the `api.current.exportState()` object does not contain the updated column order state.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD   
    pnpm: Not Found
  Browsers:
    Chrome: 122.0.6261.71
    Edge: Chromium (122.0.2365.66)
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-alpha.127
    @mui/core-downloads-tracker:  5.15.6
    @mui/icons-material: 5.11.16 => 5.11.16
    @mui/lab: 5.0.0-alpha.128 => 5.0.0-alpha.128
    @mui/material: ^5.15.6 => 5.15.6
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/system:  5.12.1
    @mui/types:  7.2.13
    @mui/utils:  5.12.0
    @mui/x-data-grid:  6.19.4
    @mui/x-data-grid-premium: ^6.19.4 => 6.19.4
    @mui/x-data-grid-pro:  6.19.4
    @mui/x-license-pro:  6.10.2
    @types/react:  18.0.9
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    styled-components: 5.2.3 => 5.2.3
</details>

**Search keywords**: column state persistence restore
**Order ID**:

**Comment by oliviertassinari** [comment] 2024-03-06 20:46
Duplicate of #11576?

**Closed** 2024-03-07 09:31 UTC
Labels: duplicate, component: data grid
