### ISSUE TITLE
The datagrid breaks whenever we define column flex value

### ISSUE THREAD

**Issue by gswebdev07** [mui/mui-x#9531] opened 2023-06-30 13:38 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Create a custom data grid component that can be used as a generic component with `filtering` and sorting
 `import {
    DataGrid,
    GridColDef,
    GridSortModel,
    GridToolbar,
} from '@mui/x-data-grid'
import { useContext, useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { GridContext } from './GridContext'
import { nanoid } from 'nanoid'
import { Button } from '@mui/material'
import { GridInitialStateCommunity } from '@mui/x-data-grid/models/gridStateCommunity'
interface CustomDataGridProps {
    columns: any[]
    rows: any[]
    loadMore?: () => void
    onRowDoubleClick?: (row: any) => void
    initialState?: GridInitialStateCommunity | undefined
}

const CustomDataGrid: React.FC<CustomDataGridProps> = ({
    columns,
    rows,
    loadMore,
    onRowDoubleClick,
    initialState,
}) => {
    const { states, setState } = useContext(GridContext)
    const router = useRouter()
    const { asPath } = router
    const pageState = states[asPath] || {
        sort: '',
        pageModel: { page: 0, pageSize: 10 },
        filter: '',
    }

    const [filteredRows, setFilteredRows] = useState<any[]>(rows)
    const [sortedRows, setSortedRows] = useState<any[]>(filteredRows)

    useEffect(() => {
        setFilteredRows(rows)
        setSortedRows(rows)
    }, [rows])

    const handleSortChange = (sortModel: GridSortModel) => {
        if (sortModel && sortModel.length > 0) {
            const field = sortModel[0].field
            const sortDirection = sortModel[0].sort

            // Sort the rows based on the field and sort direction
            let sortedData = [...filteredRows]
            sortedData = sortedData.sort((a, b) => {
                const aValue = a[field]
                const bValue = b[field]
                if (aValue < bValue) {
                    return sortDirection === 'asc' ? -1 : 1
                }
                if (aValue > bValue) {
                    return sortDirection === 'asc' ? 1 : -1
                }
                return 0
            })

            setSortedRows(sortedData)

            const newSort = `${field}:${sortDirection}`
            const newState = { ...pageState, sort: newSort }
            setState(asPath, newState)
        } else {
            setSortedRows(filteredRows)

            const newState = { ...pageState, sort: '' }
            setState(asPath, newState)
        }
    }

    const handlePageModelChange = (params: {
        pageSize: number
        page: number
    }) => {
        const newState = { ...pageState, pageModel: params }
        setState(asPath, newState)
    }

    const handleFilterChange = (filterModel: any) => {
        const filteredData = rows.filter(row => {
            for (const field in filterModel) {
                if (
                    filterModel[field].filterValue &&
                    filterModel[field].filterValue !== ''
                ) {
                    const cellValue = row[field] as string
                    const filterValue =
                        filterModel[field].filterValue.toLowerCase()

                    if (!cellValue.toLowerCase().includes(filterValue)) {
                        return false
                    }
                }
            }
            return true
        })

        setFilteredRows(filteredData)
        setSortedRows(filteredData)

        const newFilter = JSON.stringify(filterModel)
        const newState = { ...pageState, filter: newFilter }
        setState(asPath, newState)
    }
    useEffect(() => {
        if (
            loadMore &&
            pageState.pageModel.page + 1 ===
                Math.ceil(rows.length / pageState.pageModel.pageSize)
        ) {
            loadMore()
        }
    }, [pageState.pageModel])
    const getTogglableColumns = (columns: GridColDef[]) => {
        return columns
            .filter(column => column.field !== 'viewButton')
            .map(column => column.field)
    }
    return (
        <DataGrid
            columnHeaderHeight={40}
            columns={columns}
            density={'comfortable'}
            disableRowSelectionOnClick
            filterModel={
                pageState.filter ? JSON.parse(pageState.filter) : undefined
            }
            getRowId={() => nanoid()}
            initialState={{
                pagination: {
                    paginationModel: {
                        page: pageState.pageModel.page,
                        pageSize: pageState.pageModel.pageSize,
                    },
                },
                ...initialState,
            }}
            onFilterModelChange={handleFilterChange}
            onPaginationModelChange={handlePageModelChange}
            onRowDoubleClick={params =>
                onRowDoubleClick ? onRowDoubleClick(params.row) : ''
            }
            onSortModelChange={handleSortChange}
            pageSizeOptions={[5, 10, 25, 50]}
            rows={sortedRows}
            slotProps={{
                columnsPanel: {
                    getTogglableColumns,
                },
                toolbar: {
                    printOptions: { disableToolbarButton: true },
                    csvOptions: { disableToolbarButton: true },
                },
            }}
            slots={{ toolbar: GridToolbar, baseButton: Button }}
            sortModel={[
                {
                    field: pageState.sort.split(':')[0],
                    sort: pageState.sort.split(':')[1] as 'asc' | 'desc',
                },
            ]}
        />
    )
}

export default CustomDataGrid
`
2. Defining columns to use in the tables.
` import { GridColTypeDef } from '@mui/x-data-grid'
import SeverityBox from '../SeverityBox'

export const widthSizes = {
    xs: 90,
    sm: 120,
    md: 140,
    lg: 200,
    xl: 380,
}

export const defaultColumnOptions = {
    sortable: true,
    filterable: true,
    groupable: true,
}

export const xlCol: GridColTypeDef = {
    ...defaultColumnOptions,
    minWidth: widthSizes.xl,
    flex:1.
}

export const lgCol: GridColTypeDef = {
    ...defaultColumnOptions,
    minWidth: widthSizes.lg,
}
export const mdCol: GridColTypeDef = {
    ...defaultColumnOptions,
    minWidth: widthSizes.md,
}

export const smCol: GridColTypeDef = {
    ...defaultColumnOptions,
    minWidth: widthSizes.sm,
}
export const xsCol: GridColTypeDef = {
    ...defaultColumnOptions,
    minWidth: widthSizes.xs,
}
export const buttonCol: GridColTypeDef = {
    ...defaultColumnOptions,
    width: widthSizes.xs,
    sortable: false,
    filterable: false,
    hideable: false,
}
export const booleanCol: GridColTypeDef = {
    ...mdCol,
    align: 'center',
    headerAlign: 'center',
}

export const countCol: GridColTypeDef = {
    ...smCol,
    type: 'number',
    align: 'center',
    headerAlign: 'center',
}

export const severityCol: GridColTypeDef = {
    ...mdCol,
    align: 'center',
    headerAlign: 'center',
    renderCell: ({ row }: { row: any }) => (
        <SeverityBox severity={row.severity} />
    ),
}`

3.Define Context to store the searching and sorting per page according to the path name
`// GridContext.tsx
import { createContext, ReactNode, useState } from 'react'

interface PageState {
    sort: string
    pageModel: { page: number; pageSize: number }
    filter: string
}

interface GridContextProps {
    states: Record<string, PageState>
    setState: (pathname: string, state: PageState) => void
}

export const GridContext = createContext<GridContextProps>({
    states: {},
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    setState: () => {},
})

export const GridProvider = ({ children }: { children: ReactNode }) => {
    const [states, setStates] = useState<Record<string, PageState>>({})
    const setState = (pathname: string, state: PageState) => {
        setStates(prevStates => ({
            ...prevStates,
            [pathname]: state,
        }))
    }

    return (
        <GridContext.Provider value={{ states, setState }}>
            {children}
        </GridContext.Provider>
    )
}
`

### Current behavior 😯

Whenever i define flex in the columns application gives error 'Max stack size exceeded'

### Expected behavior 🤔

The data grid should adjust dimensions automatically for xl column.  Right now it is not working with dynamic sizing

### Context 🔦

My code breaks whenever i add flex definition to the column. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

69762

**Comment by cherniavskii** [comment] 2023-06-30 13:53
Duplicate of https://github.com/mui/mui-x/issues/9510
We just released a fix for it in https://github.com/mui/mui-x/releases/tag/v6.9.1
Thanks for letting us know!

**Closed by cherniavskii** 2023-06-30 13:53 UTC
Labels: status: needs triage
