### ISSUE TITLE
CustomToolbar give an error 

### ISSUE THREAD

**Issue by arifannosh** [mui/mui-x#7572] opened 2023-01-16 10:18 UTC
### Order ID 💳

54600

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

function CustomToolbar() {
  return (
    <GridToolbarContainer>
      <GridToolbarColumnsButton />
      <GridToolbarFilterButton />
      <GridToolbarDensitySelector />
      <GridToolbarExport />
    </GridToolbarContainer>
  );
}

Type '{}' is missing the following properties from type 'Pick<GridToolbarFilterButtonProps, "id" | "color" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | ... 272 more ... | "PopperProps">': nonce, onResize, 

### Your environment 🌎

<details>
  "@mui/x-data-grid-premium": "^5.17.13",

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by arifannosh** [comment] 2023-01-16 10:25
https://mui.com/x/react-data-grid/components/#CustomToolbarGrid.tsx

this is not working in a premium grid

**Comment by cherniavskii** [comment] 2023-01-16 15:13
Hey @arifannosh 
Could you provide a minimal reproduction example of the issue?
This demo seems to work fine with the premium package: https://codesandbox.io/s/sad-farrell-fw54u4?file=/demo.tsx

**Comment by arifannosh** [comment] 2023-01-16 15:25
@cherniavskii
In demo you used x-grid v 5.0.0
This issue is  related to v 5.17
Please check with leatest version

**Comment by cherniavskii** [comment] 2023-01-16 15:36
It uses the latest version - `^5.0.0` resolves to the latest `5.17.19`

**Comment by arifannosh** [comment] 2023-01-16 15:51
@cherniavskii is this issue is resolved in 5.17.19?

**Comment by cherniavskii** [comment] 2023-01-16 15:55
I'm closing the issue since there's no reproduction example.
Feel free to reopen once we can reproduce the issue.

**Closed by cherniavskii** 2023-01-16 15:55 UTC
Labels: component: data grid, plan: Premium, support: commercial

**Comment by arifannosh** [comment] 2023-01-16 16:05
0kay I will open it will a screen shot

**Comment by arifannosh** [comment] 2023-01-23 11:51
![muiXgridCustomtoolbar](https://user-images.githubusercontent.com/35531768/214032671-1e7e9eb6-6dcb-4ccd-9c35-0c95abd0d82d.PNG)

**Comment by arifannosh** [comment] 2023-01-23 11:53
@cherniavskii please have a look to above screen short

**Comment by arifannosh** [comment] 2023-01-25 04:54
@m4theushw where to add this 35287?
