### ISSUE TITLE
last columns disappear when the previous ones are strongly enlarged

### ISSUE THREAD

**Issue by PascalStehling** [mui/mui-x#3745] opened 2022-01-26 12:19 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When scrolling to the last column, if one of the last columns is greatly enlarged, the last columns will no longer be displayed.

### Expected behavior 🤔

The columns should slide to the right and continue to be displayed.

### Steps to reproduce 🕹

Steps:
[MUI Documentation](https://mui.com/components/data-grid/) or [CodeSanbox](https://codesandbox.io/s/zwerr?file=/demo.tsx)
1. Scroll horizontally to the right as fas as possible
2. Enlarge "Counterparty City" column as wide as it gets
3. Scroll further right
4. "Updated on" and "Created on" are no longer Visible 

![BrokenColumns](https://user-images.githubusercontent.com/33455644/151161366-b6c5b212-1fd9-45aa-a332-e908c00d3506.gif)

### Context 🔦

When working with many columns with long content, many columns end up not being visible.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 17.3.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Brave: V1.34.81 Chromium 97.0.4692.99
```
</details>

**Comment by alexfauquette** [comment] 2022-01-26 12:56
Hi @PascalStehling 

This seems to be a duplicate of #3436 But the white space occurs at the end so it appears as the column disappear.

You have two work arounds solutions.
- set `columnThreshold={0}` which will refresh the virtualization after each scroll. It solves the bug, but can lead to performance issues
- You can limit the column width when user resize it with a new property of the `GridColDef`: [`maxWidth`](https://mui.com/components/data-grid/columns/#resizing)

**Comment by flaviendelangle** [comment] 2022-02-07 09:32
I'm closing this one in favor of #3436

**Closed by flaviendelangle** 2022-02-07 09:32 UTC
Labels: duplicate, component: data grid, feature: Rendering layout
