### ISSUE TITLE
[data grid] Column not hidden when using `GridColDef.hide`

### ISSUE THREAD

**Issue by OliverWall** [mui/mui-x#4356] opened 2022-04-03 09:07 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I use @mui/x-data-grid-pro
I have implemented the ability to display skeletons in a table, but have encountered amazing behavior.
I have a loading state - that's when I display the skeleton. Skeletons are displayed as cells with the skeleton component. As soon as the loading flag goes to false, we display real columns and data. I noticed that after displaying the skeleton, the column-hide prop is completely ignored. I have attached a video demonstrating the problem. I assure you that there are no transformations with columns. These are the same columns with the hide props.

/* ========================================================================== */
// VIDEO LINK
/* ========================================================================== */
https://drive.google.com/file/d/1xuAQGisMPiPn-wwmeiFUNyYlVOnTim4p/view?usp=sharing

![image](https://user-images.githubusercontent.com/33131980/161420263-e761e2dc-c40d-455c-a13b-6ab7dd0ea82d.png)
![image](https://user-images.githubusercontent.com/33131980/161420271-efb9f25d-f38b-4d8f-ad43-3fe037a951a6.png)

### Expected behavior 🤔

The column should be hidden

### Steps to reproduce 🕹

Steps:

Couldn't reproduce in other conditions. I tried to do something similar here, but everything worked out correctly
https://codesandbox.io/s/datagriddemo-material-demo-forked-1e4r7w?file=/demo.tsx:1750-2714

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 2.15 GB / 15.93 GB
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.24.1. - C:\Program Files\Git\cmd\git.EXE
  Virtualization:
    Docker: 20.10.10 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    VSCode: 1.62.3 - C:\Users\DelisInfo\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Browsers:
    Chrome: 99.0.4844.84
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.36)
    Internet Explorer: 11.0.22000.120


    "@emotion/react": "^11.8.2",
    "@emotion/styled": "^11.8.1",
    "@mui/material": "^5.5.3",
    "@mui/x-data-grid-pro": "^5.7.0",
```
</details>

### Order ID 💳 (optional)

32677

**Comment by OliverWall** [comment] 2022-04-03 09:26
Another video that confirms that the column is formally hidden, but it is still displayed.

https://drive.google.com/file/d/1yJduf-bsnbBvhKDFl_uVt9BF-tS3GY8f/view?usp=sharing

**Comment by alexfauquette** [comment] 2022-04-04 10:09
Here is a reproduction of your problem.
https://codesandbox.io/s/datagriddemo-material-demo-forked-zxplvm?file=/demo.tsx:1533-1534

The bug occurs only when you add new columns

**Comment by OliverWall** [comment] 2022-04-04 13:15
Thanks for the quick response. The new api is suitable and it looks like it is working correctly.

**Comment by alexfauquette** [comment] 2022-04-04 14:15
I keep the issue open to track this bug

**Comment by OliverWall** [comment] 2022-04-05 09:45
it seems to me that with this api, the table has become initialized much longer on big data. I use controlled behavior. I even began to show a complete hang of the table. As soon as I turn it off, everything works fast again.

**Comment by flaviendelangle** [comment] 2022-10-17 12:38
Closing since we are dropping this property on v6

**Closed by flaviendelangle** 2022-10-17 12:38 UTC
Labels: bug 🐛

**Comment by ZeeshanAhmadKhalil** [comment] 2023-03-11 13:40
then how we will hide the col?

**Comment by flaviendelangle** [comment] 2023-03-12 14:38
You cand find the documentation [here](https://mui.com/x/react-data-grid/column-visibility/)

**Comment by Kkinod** [comment] 2023-03-15 13:28
> You cand find the documentation [here](https://mui.com/x/react-data-grid/column-visibility/)

- "hideable: true" - does not work
- using "columnVisibilityModel={{}}" disables Column visibility panel, cannot be hidden/unhidden with this panel when using "columnVisibilityModel".
- the only thing that works very well is to use "hide: true"

**Comment by adrianadaria** [comment] 2023-12-08 08:20
hide:true does not work anymore too

**Comment by flaviendelangle** [comment] 2023-12-08 08:38
Did you find a place on the doc saying that `hide: true` was used to hide a column?
If so we must fix it.

The hidden columns are defined using the `columnVisibilityModel` prop

**Comment by adrianadaria** [comment] 2023-12-08 14:18
I just referred to the comment from _Kkinod_ (the last bulletpoint). This thing does not work anymore, but the `columnVisibilityModel `works well, so thank you. And no, I did not find information about `hide:true` in the document so you can ignore the alert.

**Comment by kiswayODG** [comment] 2024-02-16 16:09
we talk about GridColDef Interface bros !!
This interface doesn't have hide property
