### ISSUE TITLE
[fields] Non-Ascii chars in field value makes testing and access from `FormData` complicated

### ISSUE THREAD

**Issue by reichhartd** [mui/mui-x#8150] opened 2023-03-06 15:44 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

[https://codesandbox.io/s/mui-non-ascii-chars-ygq7kn?file=/demo.tsx](https://codesandbox.io/s/mui-non-ascii-chars-ygq7kn?file=/demo.tsx)

### Current behavior 😯

When I submit mit form with version 6, I receive the following values on the server side:
```
[
    [ 'birthCountry', 'ET' ],
    [ 'birthDate', '⁦⁨17⁩.⁨04⁩.⁨2022⁩⁩' ],
    [ 'birthPlace', 'asdfadsf' ],
]
```
While this looks ok, there are some non-visible unicode chars as part of the `birthData` values. Encoded with `encodeURIComponent` it looks like the following:
```
[
    [ 'birthCountry', 'ET' ],
    [ 'birthDate', '%E2%81%A6%E2%81%A817%E2%81%A9.%E2%81%A804%E2%81%A9.%E2%81%A82022%E2%81%A9%E2%81%A9' ],
    [ 'birthPlace', 'asdfadsf' ],
]
```
This didn't happened with version 5.

### Expected behavior 🤔

That there aren't non-ascii chars in the string.

### Your environment 🌎

Browser: Chrome

```
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 18.14.2 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.3
  npmPackages:
    @mui/x-date-pickers: ^6.0.0 => 6.0.0 
```

**Comment by flaviendelangle** [comment] 2023-03-06 17:55
Hi,

We are using non-ascii charactersmainly  to support RTL in the new field components.
Could you describe what is your use case for using directly the `FormData` instead of using the `onChange` callback ?

**Comment by reichhartd** [comment] 2023-03-07 08:44
My example does not represent the use of `FormData` in our application. I only chose this example because it was easier to reproduce in CodeSandbox.

We use Remix as a framework, which heavily relies `form` components and `FormData` for `action` functions:
http://remix.run/docs/en/1.14.0/route/action

**Comment by flaviendelangle** [comment] 2023-03-07 14:30
We could expose the method cleaning the input value since we have one internally.
@reichhartd if we expose a method called `cleanFieldValue` that removes those characters, would you be able to run it on the value extracted from the `FormData` (on the backend I guess) ?

```tsx
export const cleanFieldString = (dirtyString: string) =>
  dirtyString.replace(/[\u2066\u2067\u2068\u2069,\u200e]/g, '');
```

It would something like it

**Comment by blumendorf** [comment] 2023-03-07 16:30
This also seems to be an issue in tests that work with the display value.

Querying a DatePicker by value (e.g. `await screen.findByDisplayValue('01-01-2020')`) fails in our tests in v6.0.0.
The actual value of the element contains the above mentioned control characters and thus string matching fails.

![image](https://user-images.githubusercontent.com/2630943/223485587-126699ad-5232-48a5-9f15-b468c5f7a454.png)

Since the characters are invisible, it is not immediately obvious why the string matching is failing after the update.

**Comment by flaviendelangle** [comment] 2023-03-07 17:44
We definitely need to better document those characters.

**Comment by reichhartd** [comment] 2023-03-09 08:44
@flaviendelangle Yes, that would improve the workflow a little bit. Right now we solve it similar with the following function:
```
export const removeNonAsciiChars = (str: string): string => str.replace(/[^\x00-\x7F]/gu, '');
```
But in my opinion, this workflow is not perfect. May I ask, why the invisible chars are necessary?

**Comment by lnhrdt** [comment] 2023-03-14 16:16
I encountered these same issues today. I've appreciated the conversation here, it really helped me understand the issue and what options I currently have.

I've been trying to test the current value of a DatePicker component using React Testing Library. This assertion was failing because of the invisible characters:

```typescript
expect(screen.getByLabelText('Start')).toHaveValue('01 / 01 / 2020')
```

Based on the conversation here, I'm currently using this as a workaround:
```typescript
const removeInvisibleCharacters = (value: string) => value.replace(/[\u2066\u2068\u2069]/g, '')
expect(removeInvisibleCharacters(screen.getByLabelText<HTMLInputElement>('Start').value)).toEqual('01 / 01 / 2020')
```

It's not an easily maintainable pattern for our codebase because now we all have to remember this "special thing" about DatePicker, but I'm happy to have a working solution for now.

---

@flaviendelangle while I can appreciate the context on the two problems the invisible characters solve, it's awfully cumbersome for 2 reasons:
- it's surprising: I haven't often seen an input's value differ from the "real" value for formatting reasons. it goes against conventions.
- it's hard to debug: the surprise is literally invisible. until you've found this github issue it's hard to understand what's going on.

>We need to work to provide good utility functions (that are testing framework agnostic) for the fields.
Working with the raw value can be a pain.

Looking forward to this! Perhaps in addition to providing testing framework agnostic utility functions you'd consider providing React Testing Library custom matchers to simplify their use, given React Testing Library's popularity.

While that could work, it doesn't solve the problem for me of this being unintuitive

**Comment by flaviendelangle** [comment] 2023-03-14 16:33
To give a little more context,
In order to build an interactive field (with interactions like "pressing `ArrowUp` increases the selected section"), we need to be able to split the input value into sections (the day, the month, the year, etc...).

In order to do that, we have basically two solutions:

## Have several HTML inputs

Here, we have one input per section and apply some style to have a "fake input" container that looks like an input (this is what *Spectrum* is doing).

With this approach, no more invisible characters for the RTL, we just put the HTML input in the right order.
But we still have the invisible character to make sure that pressing "1" on a section equal to "1" fires `onChange` (maybe there is a work-around possible here though).

This approach is better for accessibility (it's closer from the aria spin-button date picker example).
But it's a lot harder to style (if you have a custom input, you have to re-invent basically all your custom style for the fake container that looks like an input).

## Have a single HTML input

Here, we have one input for the full date and we add some hidden characters in it to respect the order (visually and for the keyboard navigation).
This approach is the one Telerik took.

This approach is more complicated to make accessible, but it's super easy to style since we have a regular HTML input that can be overriden.

___

We are still considering supporting both or even changing for a multi input approach at some point (the accessibility issue is a big one for us).
For with several HTML inputs, the `toHaveValue` won't work either (unless you check each input one by one).

We would like to come with a set of testing utils, that let you easily test what's inside the field, no matter the amount of HTML inputs.
We did not start to work on them yet (we're focusing on regressions and bugs around the release for now), so we don't know if it make sense to have custom matchers for some testing libraries (e.g: React Testing Libraries) but we will definitely consider it.

**Comment by flaviendelangle** [comment] 2023-03-27 07:40
In #8325; we are removing the RTL characters when RTL is not needed.
You will still have the `\u200e` character that we will treat in another PR (hopefully in the coming weeks).

**Comment by flaviendelangle** [comment] 2023-05-16 13:07
I think we can close this one
We don't have hidden chars anymore, except if you manually set props that adds them (and the JSDoc warrns you of this downside).

**Closed by flaviendelangle** 2023-05-16 13:07 UTC
Labels: component: pickers

**Comment by flaviendelangle** [comment] 2023-05-16 13:22
We have a new prop `shouldRespectLeadingZeros` that is `true` by default.
When equal to `true`, we have leading zeroes on all digit sections, so you should never end up with a `\u200e` which is only here for sections without leading zeroes :+1: .
