### ISSUE TITLE
preProcessEditCellProps doesn't validate on direct key press

### ISSUE THREAD

**Issue by mclarsson** [mui/mui-x#11064] opened 2023-11-17 08:17 UTC
### Steps to reproduce

Link to live example: https://codesandbox.io/s/adoring-chaum-pp2dq4?file=/src/demo.tsx 

Steps:
1. Make a cell editable and add validation to make sure the user enters a number using the preProcessEditCellProps attribute
2. Highlight a cell and press any key, e.g. 'k'
3. Press enter, the row will update even though it should fail validation

### Current behavior

We have a percentage field that is editable by the user. In order to make sure the user only enters a value between 0 and 100 we use `preProcessEditCellProps` which works great if the user has double clicked the cell in order to edit. However, if the user highlights the cell and presses a key, such as `k`, then it for foregoes the validation and proceeds to trigger `processRowUpdate`.

### Expected behavior

The `preProcessEditCellProps` method should always trigger when user makes a change.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid editing validation

**Comment by michelengelen** [comment] 2023-11-20 13:22
As mentioned in #11071 I will close this as duplicate of #10930 as well.
The issue is related (a duplicate as well).
Thanks for raising it... We appreciate any contribution! 🙇🏼

**Closed by michelengelen** 2023-11-20 13:22 UTC
Labels: status: waiting for maintainer
