### ISSUE TITLE
The border lines should be consistent while zooming in/out #14486.

### ISSUE THREAD

**Issue by code-priyanka** [mui/mui-x#11208] opened 2023-11-27 11:16 UTC
### Steps to reproduce

Link to live example: (required)

Steps:
![DataGriddemo](https://github.com/mui/mui-x/assets/152159983/7add7e33-94ac-4714-b4e2-172e15f0345b)

### Current behavior

The border line is messed up.

### Expected behavior

The border line should be consistent

### Context

On clicking **Pin to right** column and zooming in browser screen resolution to 75% or zooming out to 110% screen resolution the border line is inconsistent

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser:- Google Chrome, Edge
```
</details>

**Search keywords**: Datagrid column border
**Order ID**: 14486

**Comment by michelengelen** [comment] 2023-11-27 11:25
@romgrk could you check if this would be fixed with #10059 ?

**Comment by DanailH** [comment] 2023-11-30 10:10
@code-priyanka following the vague description that you have provided I wasn't able to reproduce it on Mac (Chrome). I tested it on the first example here https://mui.com/x/react-data-grid/column-pinning/. It would be great if you could provide more detail regarding the reproduction or where did you saw the inconsistency. Even a screenshot will do. Until then I can't validate that it's truly a bug.

**Comment by DanailH** [comment] 2023-11-30 10:12
@code-priyanka this is a duplicate of https://github.com/mui/mui-x/issues/10238. You can follow it regarding the status of the fix.

**Closed by DanailH** 2023-11-30 10:12 UTC
Labels: bug 🐛, component: data grid, feature: Row pinning
