### ISSUE TITLE
[data grid] Using GRID_CHECKBOX_SELECTION_COL_DEF to set column hideable:false causes console warning

### ISSUE THREAD

**Issue by conerye** [mui/mui-x#6519] opened 2022-10-14 23:50 UTC
### Order ID 💳

331993142

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

browsers: Google Chrome 106.0.5249.103 and Firefox 102.3.0esr

I am using DataGrid with checkboxSelection.

I have defined the columns:
const devicesColumns = [
    { ...GRID_CHECKBOX_SELECTION_COL_DEF, hideable: false },
    { field: 'serialNumber', headerName: 'Serial Number', flex: 1, hideable: false },
    { field: 'softwareVersion', headerName: 'Version', flex: 1 },
    { field: 'ptIpAddress', headerName: 'IP Address', flex: 1 },
    { field: 'esn', headerName: 'ESN', flex: 1, hide: true },
    { field: 'systemName', headerName: 'Device Name', flex: 1, hide: true },
];

When the page with the table is displayed, I observe the following warning:
react_devtools_backend.js:4026 MUI: The column type "checkboxSelection" you are using is not supported.
Column type "string" is being used instead. 
    at DataGridPremium (http://localhost:3000/static/js/bundle.js:89946:98)
    at http://localhost:3000/static/js/bundle.js:48026:66
    at div
    at CustomTable (http://localhost:3000/static/js/bundle.js:1251:5)
    at form
    at div
    at http://localhost:3000/static/js/bundle.js:48026:66
    at DialogContent (http://localhost:3000/static/js/bundle.js:62622:82)
    at div
    at http://localhost:3000/static/js/bundle.js:48026:66
    at Paper (http://localhost:3000/static/js/bundle.js:73254:82)
    at http://localhost:3000/static/js/bundle.js:48026:66
    at div
    at http://localhost:3000/static/js/bundle.js:48026:66
    at Transition (http://localhost:3000/static/js/bundle.js:201269:30)
    at Fade (http://localhost:3000/static/js/bundle.js:64134:77)
    at TrapFocus (http://localhost:3000/static/js/bundle.js:54054:5)
    at div
    at http://localhost:3000/static/js/bundle.js:48026:66
    at Portal (http://localhost:3000/static/js/bundle.js:52213:5)
    at ModalUnstyled (http://localhost:3000/static/js/bundle.js:51406:5)
    at Modal (http://localhost:3000/static/js/bundle.js:72038:82)
    at http://localhost:3000/static/js/bundle.js:48026:66
    at Dialog (http://localhost:3000/static/js/bundle.js:63038:83)
    at CustomModal (http://localhost:3000/static/js/bundle.js:8613:5)
    at AddUpdateAlertModal (http://localhost:3000/static/js/bundle.js:16693:5)
    at div
    at http://localhost:3000/static/js/bundle.js:48026:66
    at Box (http://localhost:3000/static/js/bundle.js:86348:72)
    at AlertConfigurationTab (http://localhost:3000/static/js/bundle.js:30880:61)
    at div
    at http://localhost:3000/static/js/bundle.js:48026:66
    at Box (http://localhost:3000/static/js/bundle.js:86348:72)
    at TabPanel (http://localhost:3000/static/js/bundle.js:3113:5)
    at div
    at http://localhost:3000/static/js/bundle.js:48026:66
    at Box (http://localhost:3000/static/js/bundle.js:86348:72)
    at AlertActionSystem (http://localhost:3000/static/js/bundle.js:30560:86)
    at Routes (http://localhost:3000/static/js/bundle.js:200634:5)
    at div
    at http://localhost:3000/static/js/bundle.js:48026:66
    at Stack (http://localhost:3000/static/js/bundle.js:77178:87)
    at http://localhost:3000/static/js/bundle.js:48026:66
    at Admin (http://localhost:3000/static/js/bundle.js:30245:5)
    at Routes (http://localhost:3000/static/js/bundle.js:200634:5)
    at LocalizationProvider (http://localhost:3000/static/js/bundle.js:125177:81)
    at SnackbarProvider (http://localhost:3000/static/js/bundle.js:166064:24)
    at App (http://localhost:3000/static/js/bundle.js:77:70)
    at InnerThemeProvider (http://localhost:3000/static/js/bundle.js:85559:70)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:85029:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:85579:5)
    at Router (http://localhost:3000/static/js/bundle.js:200567:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:199376:5)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 106.0.5249.103
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3
    @emotion/styled: ^11.8.1 => 11.9.3
    @mui/base:  5.0.0-alpha.87
    @mui/icons-material: ^5.8.0 => 5.8.4
    @mui/material: ^5.8.1 => 5.8.6
    @mui/private-theming:  5.9.1
    @mui/styled-engine:  5.8.7
    @mui/system: ^5.9.1 => 5.9.1
    @mui/types:  7.1.4
    @mui/utils:  5.10.6
    @mui/x-data-grid: ^5.13.1 => 5.14.0
    @mui/x-data-grid-premium: ^5.14.0 => 5.14.0
    @mui/x-data-grid-pro:  5.14.0
    @mui/x-date-pickers: ^5.0.0-beta.1 => 5.0.0-beta.2
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.2
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react:  18.0.14
    react: ^18.1.0 => 18.2.0
    react-dom: ^18.1.0 => 18.2.0
    typescript:  4.7.4
```
</details>

**Comment by cherniavskii** [comment] 2022-10-18 11:18
Duplicate of https://github.com/mui/mui-x/issues/4769

**Closed** 2022-10-18 11:18 UTC
Labels: duplicate, component: data grid, support: commercial

**Comment by conerye** [comment] 2022-11-08 21:45
adding the columnTypes prop:
columnTypes={{ [GRID_CHECKBOX_SELECTION_COL_DEF.type]: GRID_CHECKBOX_SELECTION_COL_DEF }}
prevents the warning
BUT
I just realized that it causes the columns order, sizing, etc to be reset on each render. so adding that prop is not a solution. Please advise. Is there another way or do we just ignore the warning for now? looks like there will be some changes under #4769

**Comment by cherniavskii** [comment] 2022-11-10 11:25
@conerye Could you try this instead and let me know if it solves the issue?

```tsx
const columnTypes = {
  [GRID_DETAIL_PANEL_TOGGLE_COL_DEF.type]: GRID_DETAIL_PANEL_TOGGLE_COL_DEF
}

function Component() {
  return (
    <DataGrid
      // ...
      columnTypes={columnTypes}
    />
  )
}
```
Demo: https://codesandbox.io/s/customizedetailpaneltoggle-material-demo-forked-6i8fot?file=/demo.tsx

**Comment by conerye** [comment] 2022-11-11 22:56
It did not work. It must be something I am doing wrong??? I created this to show you the issue: https://codesandbox.io/s/pensive-kilby-w4wvyd?file=/src/ExampleTable.jsx

If you move the right column to be the first column on the left and select any row in the table, you will see the column move back to right... If you comment out the columnTypes prop, you will see this issue of the column moving does not happen.

**Comment by conerye** [comment] 2022-11-21 16:01
Since the solution from #4769 did not work for this GRID_CHECKBOX_SELECTION_COL_DEF issue, should/could we reopen this support ticket in order to investigate the problem with the columns changing?

**Comment by cherniavskii** [comment] 2022-11-23 17:09
Hey @conerye 
Sorry for the late reply.
Can you reproduce it with this demo https://codesandbox.io/s/customizedetailpaneltoggle-material-demo-forked-f4qz41?file=/demo.tsx ?

The problem you experience might be coming from `columns` reference change - see https://github.com/mui/mui-x/issues/5812#issuecomment-1220550273

**Comment by conerye** [comment] 2022-11-28 16:37
@cherniavskii  - the demo you provided a link to does not use GRID_CHECKBOX_SELECTION_COL_DEF and therefore does not show the issue I am having. Please see the demo I provided with instructions above, showing this issue. Here it is again:
https://codesandbox.io/s/pensive-kilby-w4wvyd?file=/src/ExampleTable.jsx

**Comment by cherniavskii** [comment] 2022-11-28 17:34
Thanks @conerye 
The solution from https://github.com/mui/mui-x/issues/6519#issuecomment-1310139392 seems to be working in your demo:
https://codesandbox.io/s/optimistic-hermann-ffwoqi 
Can you check it and let me know?

**Comment by conerye** [comment] 2022-11-29 00:11
ah, OK, I see you moved the columnTypes const outside of the component... and that is working.
Thank you.

**Comment by Koli14** [comment] 2023-01-26 10:24
But it's still a bug, isn't it? It should be solved from the MUI side, without needing to add any code from our side.
Or?

**Comment by Koli14** [comment] 2023-01-26 10:28
This official demo also shows this warning: https://mui.com/x/react-data-grid/selection/#custom-checkbox-column
