### ISSUE TITLE
[DatePicker] text in input field is selected after picking a date (iOS)

### ISSUE THREAD

**Issue by sodenn** [mui/mui-x#8145] opened 2023-03-05 21:33 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://mui.com/x/react-date-pickers/date-picker/#basic-usage

Steps:
1. Open the date picker on an iOS device
2. Select a date
3. Press "OK"

### Current behavior 😯

After picking a date, a part of the text in the input field is selected.
![2023-03-05 22 15 04](https://user-images.githubusercontent.com/232054/222987023-5d9afb75-f1da-4033-8389-3ab567b3fe81.gif)

### Expected behavior 🤔

The behavior should be the same as in v5.x. No text should be selected after picking the date.

### Your environment 🌎

OS: iOS 16.2
@mui/x-date-pickers: 6.0.0

**Comment by BC-M** [comment] 2023-03-06 07:19
Also on chrome with "Mobile variant".

https://user-images.githubusercontent.com/40334865/223043605-ae376c31-c4b6-407a-adb4-d3766cbaa05a.mov

**Comment by flaviendelangle** [comment] 2023-03-06 17:59
Hi,

I do agree this behavior is weird, we'll look into, thanks for the feedback :+1:

**Comment by BC-M** [comment] 2023-03-10 07:41
Until it is fixed by the great MUI team (or anyone else who can find the cause of this problem), here is a workaround for the MobilePicker:

```typescript
slotProps={{
  textField: {
    onSelect: (e) => {
      // workaround for https://github.com/mui/mui-x/issues/8145
      if (e.target instanceof HTMLInputElement) {
        e.target.selectionStart = e.target.selectionEnd;
      }
    },
  },
}}
```

**Closed** 2023-03-16 09:50 UTC
Labels: bug 🐛, component: pickers
