### ISSUE TITLE
[data grid] Implement Quick Filter

### ISSUE THREAD

**Issue by m4theushw** [mui/mui-x#2842] opened 2021-10-11 16:42 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Upvote this issue if you want it to be implemented natively.

It's worth to be noted that we have a demo showing how to add this functionality to the grid: https://mui.com/components/data-grid/filtering/#quick-filter.

### Examples 🌈

<img width="922" alt="Screenshot 2022-03-28 at 20 17 13" src="https://user-images.githubusercontent.com/3165635/160461260-4ca139eb-6dae-449f-8d06-64bc85af699c.png">

- https://ag-grid.com/javascript-grid-filter-quick/
- https://material-table.com/#/docs/features/search
- https://demos.telerik.com/kendo-ui/grid/search-panel
- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/searching/
- https://ej2.syncfusion.com/react/demos/#/material/grid/searching
- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/

**Comment by LaurentDelteil** [comment] 2021-10-18 11:04
I'm sorry,

I'm wondering why create a new issue about a native implementation, when the main purpose of the last issue was a native implementation.
Everyone who voted after 9 August is already aware that a demo exists...
The votes for the last issue have been reset, which means it will be released in a longer time frame, I guess?

![image](https://user-images.githubusercontent.com/40438463/137718302-03e183fb-7452-4dfc-832c-c628ac407030.png)

![image](https://user-images.githubusercontent.com/40438463/137719184-bf9a16c3-dfe5-46fb-892d-bc56786b31c2.png)

**Comment by m4theushw** [comment] 2021-10-19 01:44
@LaurentDelteil We can't reset the votes in #202. For some users, the demo is sufficient, but the votes from these users were still being counted. About it taking more time to be implemented, that could be a yes or no. This feature was not in the roadmap before, so we didn't have a estimation for its release. However, we can consider adding it to next quarters if we find we will have enough capacity, even if it doesn't have as many upvotes as the closed issue.

**Comment by wahajStar** [comment] 2021-12-08 12:02
Implement Quick Filter in codesandBox not working.

`[](https://codesandbox.io/s/7qi3m?file=/demo.js)`



![image](https://user-images.githubusercontent.com/87648709/145205025-88aee9dc-52ba-48fc-bf11-4bf04ba48bd2.png)

**Comment by wahajStar** [comment] 2021-12-09 07:11
Hello I am Faciing issue in implement Quick Filter.
TextField loose focus in onChange...
In the below example, You will get the data on click of "getData" button .
please have a look if I am doing something wrong.
[__](https://codesandbox.io/s/distracted-resonance-6wedv?file=/src/App.js)

**Comment by juliushuck** [comment] 2021-12-11 12:07
@wahajStar Is this working for you? I moved the textbox component out of the data grid component. https://codesandbox.io/s/jolly-roman-tw20g I guess that, when you define it inside the data grid component, you are recreating it on each render, so the component changes and gets unfocused.

**Comment by RyanIgo** [comment] 2021-12-13 15:13
This would be nice.

**Comment by wahajStar** [comment] 2021-12-17 07:17
@juliushuck sorry for the late reply.....
its working fine thank you so much for your valuable time.

**Comment by Misiu** [comment] 2022-02-16 07:56
A quick filter per grid columns (as shown here: https://material-table.com/#/docs/features/filtering, or here: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/) would be awesome 💪

**Comment by agnel** [comment] 2022-02-28 21:26
@juliushuck I tried accessing your sandbox, it doesn't exists - https://codesandbox.io/s/jolly-roman-tw20g

**Comment by juliushuck** [comment] 2022-03-05 18:59
> @juliushuck I tried accessing your sandbox, it doesn't exists - https://codesandbox.io/s/jolly-roman-tw20g

Restored it

**Comment by eebbann** [comment] 2022-03-22 07:24
@juliushuck  try the one @agnel  posted : https://codesandbox.io/s/ddlv8?file=/demo.tsx

**Comment by icambron** [comment] 2022-04-19 23:40
I know there's a PR in progress for adding native support, but I wanted to point out that the demo seems broken. It doesn't filter, and this appears in the console:
<img width="717" alt="Data_Grid_-_Filtering_-_MUI_X" src="https://user-images.githubusercontent.com/244988/164118414-62abc533-a6ba-4503-9ed2-c7814d088f1e.png">
.

**Comment by alexfauquette** [comment] 2022-04-20 06:58
@icambron Just tried the [demo](https://mui.com/x/react-data-grid/filtering/#quick-filter) and could not reproduce your bug

Few questions to reproduce it:
- What are you typing in the filter input
- Are you using directly the doc example or a modified version of the code?
- If it is a modified version, could you send a codesandbox link with the minimal reproduction?

**Comment by icambron** [comment] 2022-04-21 09:23
@alexfauquette I was also just using the demo directly, was just typing in names I expected to match. Each time I typed something I got another error (hence the 10 in the console)

I can't reproduce it now either, and I hadn't thought at the time to see if it was an ephemeral thing. I guess we can chalk it up to cosmic rays until there's a clear, reproduceable way to get it into that state.

**Comment by porwal-ayush** [comment] 2022-04-29 08:55
The filter via search bar works differently than the search bar that is there within the Filter option.
So this is what I tested, I added `checkboxSelection` and `hideFooter` props to `DataGrid` and found out that the originally implemented search within the filter doesn't lose the selected data on making a new query but this proposed one does.

Steps:
1. Select any two or three items via the checkbox
2. Type a query to filter row
3. Select a new row
4. Delete the filter
5. All the three or four selections are retained (for search within filter)
5. The previous selection are lost and only new one is retained (for the proposed search)

Already existing search within filer: https://codesandbox.io/s/customfilterpanelposition-material-demo-forked-uzu9qk?file=/demo.js
Newly Proposed/Example shown on mui website: https://codesandbox.io/s/quickfilteringgrid-material-demo-forked-qfwmyy

If possible, please reply to this comment, I need this search functionality and the old behavior in case of checkbox selection. Thanks

**Comment by alexfauquette** [comment] 2022-04-29 09:50
@porwal-ayush That's normal, the quick filter proposed in the demo modifies the rows, so if you want to keep selected rows, you should also control the selection to be able to restore it.

You can test on the ongoing PR, this edge case should not occur with the new feature

**Comment by porwal-ayush** [comment] 2022-04-29 10:23
> @porwal-ayush That's normal, the quick filter proposed in the demo modifies the rows, so if you want to keep selected rows, you should also control the selection to be able to restore it.
> 
> You can test on the ongoing PR, this edge case should not occur with the new feature

How do we control selection and restore it back? if possible can u show me one example? I don't see it literally anywhere.

**Closed** 2022-05-10 09:16 UTC
Labels: component: data grid, enhancement, feature: Filtering

**Comment by eric-personal** [comment] 2022-05-23 23:28
Is there a way to clear the quick search filter input field. I tried the following but it didn't clear the input itself. 

After giving my GridToolbarQuickFilter an id of "search" I tried using. 
`   api.current.deleteFilterItem({ id: "search", value: undefined });`

I also tried 
`api.current.setQuickFilterValues([]);`

Neither of the above cleared the input itself. The only hack I can think of is to add a key to the input and when I want to clear the input set the key to a different key which is a bad hack but it would work by rendering the input. 

Please let me know if if there is another  more cleaner way.

**Comment by alexfauquette** [comment] 2022-05-24 12:38
@eric-personal There is a related issue #4921

In a few words, you need to create a custom QuickFilter input to to such a thing. More details in the issue

**Comment by eric-personal** [comment] 2022-05-24 18:39
> @eric-personal There is a related issue #4921
> 
> In a few words, you need to create a custom QuickFilter input to to such a thing. More details in the issue

Thanks @alexfauquette I noticed on your codesandbox link you are using the useEffect to reset but this causes a larger side effect because when user first types into the input field the line nbQuickFilterValues === 0 && searchValue !== "" will be true which will cause the users first letter to be wiped out. You can see this happening in the codesandbox example on first key stroke.  

```
 const nbQuickFilterValues = filterModel.quickFilterValues?.length ?? 0;
  React.useEffect(() => {
    if (nbQuickFilterValues === 0 && searchValue !== "") {
      setSearchValue("");
    }
  }, [nbQuickFilterValues, searchValue]);
```
