### ISSUE TITLE
[DataGrid] Option to open filter menu under the specific column in Data Grid

### ISSUE THREAD

**Issue by BalaVJ** [mui/mui-x#11548] opened 2024-01-02 13:25 UTC
### The problem in depth 🔍

Hi Team,

I don't see an option to position the filter menu. 
It always opens left end of the Data Grid. 

As per my design, I need to open it under the specific column.

<img width="923" alt="Screenshot 2024-01-02 at 5 38 40 PM" src="https://github.com/mui/mui-x/assets/126600634/04ce8601-88cc-45f9-854c-8d35bb45c8aa">

Refer the attached image, filter menu is in left end. When I click some other column like **Status**, it should open under the **Status**  column, not to the left end.

Please check and provide me a workaround or let me know if I missed something.

Thanks,
Balavignesh. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Data Grid Filter Menu Custom Position
**Order ID**: 77584

**Comment by michelengelen** [comment] 2024-01-02 15:07
Possible duplicate of #10415 
@BalaVJ Feel free to reopen if this is unrelated.

**Closed by michelengelen** 2024-01-02 15:07 UTC
Labels: component: data grid, status: waiting for maintainer, feature: Filtering, support: commercial
