### ISSUE TITLE
MUI DataGrid : After using print to pdf (Export option), 'Rows per page' got hidden in chrome browser.  Is there any fix coming up?

### ISSUE THREAD

**Issue by amolnavghare** [mui/mui-x#7630] opened 2023-01-20 05:40 UTC
After using print to pdf, 'Rows per page' got hidden in chrome browser. 
Is there any fix coming up?

**- Before print to pdf**: Rows per page is present on webpage.

![image](https://user-images.githubusercontent.com/84384133/213624627-93fc078d-71bf-4104-a485-59fff4200dad.png)

**- After print to pdf** : Rows per page got hidden.

![image](https://user-images.githubusercontent.com/84384133/213624692-4cb85793-aba9-4261-b620-0ab6779123e6.png)

**And also getting below error while print to pdf on chrome browser.**

useGridLoggerFactory.js:26 MUI: useResizeContainer - The parent DOM element of the data grid has an empty height.
Please make sure that this element has an intrinsic height.
The grid displays with a height of 0px.

More details: https://mui.com/r/x-data-grid-no-dimensions.

**Comment by TanujSinghal** [comment] 2023-01-20 10:28
facing the same issue

**Comment by cherniavskii** [comment] 2023-01-20 13:21
Hi,
Can you provide an example demo where the issue is reproducible?
I tried with https://mui.com/x/react-data-grid/export/#default-toolbar and it seems to work correctly - the page size selector is back after closing the print window:

https://user-images.githubusercontent.com/13808724/213704682-90beb9f3-ce05-45b6-aa68-a46a68e7bd8a.mov

**Comment by TanujSinghal** [comment] 2023-01-20 15:32
Have you tried this on chrome browser?

If yes, which version of Chrome browser have you tried?


For me it was working on edge but not on chrome.
--
Thanks

Tanuj Singhal
9971702131

**Comment by cherniavskii** [comment] 2023-01-20 16:24
I've used Chromium 108, but now I've upgraded to Chromium 109 and I can reproduce the issue.
Looks like a browser regression, I'll see what we can do.

**Closed** 2023-01-23 19:59 UTC
Labels: bug 🐛, component: data grid, feature: Export
