### ISSUE TITLE
Passing InputProps to textField in DatePicker removes component button

### ISSUE THREAD

**Issue by rolias4031** [mui/mui-x#8452] opened 2023-03-30 21:11 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/billowing-forest-7xbmfj?file=/src/App.js

Steps:

1. Create a DatePicker with a LocalizationProvider, with no other props.
2. In slotProps, pass an object with `textField: { InputProps: {} }`. 
3. Note that button for the DatePicker is gone.

With InputProps (screenshot)
![Broken with InputProps](https://user-images.githubusercontent.com/67522045/228964654-b9ebe7b1-a70b-4107-8f57-a488986f1b90.png)

Without InputProps (screenshot)
![Without InputProps](https://user-images.githubusercontent.com/67522045/228964542-144814b1-3539-4d4d-80ef-76cf8bc8e54c.png)

### Current behavior 😯

The DatePicker does not display a button when `textField` receives `InputProps` from the `slotProps` prop.

### Expected behavior 🤔

The button should be visible when passing InputProps.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

Using Chrome v 108.0.5359.124
```
System:
    OS: macOS 13.1
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: Not Found
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.2
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base: 5.0.0-alpha.121 => 5.0.0-alpha.121 
    @mui/core-downloads-tracker:  5.11.13 
    @mui/lab: 5.0.0-alpha.123 => 5.0.0-alpha.123 
    @mui/material: ^5.11.13 => 5.11.13 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/styles: ^5.2.3 => 5.2.3 
    @mui/system: ^5.4.1 => 5.11.13 
    @mui/types: ^7.1.0 => 7.1.0 
    @mui/utils:  5.11.13 
    @mui/x-date-pickers: ^6.0.2 => 6.0.2 
    @types/react: ^17.0.37 => 17.0.37 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.3 => 5.3.3 
    typescript: ^4.5.4 => 4.5.4 
```
</details>

**Comment by alexfauquette** [comment] 2023-03-31 12:27
I'm closing this issue because it's a duplicate of #8322

You can subscribe to its notification to get updates on progress. SHoudl be closed quickly

**Closed by alexfauquette** 2023-03-31 12:27 UTC
Labels: status: needs triage, component: pickers
