### ISSUE TITLE
[docs] Demo LazyLoadingGrid crashes

### ISSUE THREAD

**Issue by Hussein-Ali-6** [mui/mui-x#10264] opened 2023-09-07 12:39 UTC
- [ ] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20LazyLoadingGrid%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-data-grid/row-updates/
2. ??
3. demo *LazyLoadingGrid* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.12.1  |
| Netlify deploy | https://64f0bc1d0e1fe40008f85d43--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 |

**Comment by DanailH** [comment] 2023-09-11 09:57
I can't seem to reproduce the issue but I'm on Mac. @mui/xgrid anyone with windows to check this?

**Comment by romgrk** [comment] 2023-09-11 12:56
@Hussein-Ali-6 Can you be more specific about what you mean by "crashes"?

**Comment by cherniavskii** [comment] 2023-09-11 16:29
Duplicate of https://github.com/mui/mui-x/issues/10047
I can reproduce it on MacOS

**Closed as not planned** 2023-09-11 16:29 UTC
Labels: duplicate, scope: data grid
