### ISSUE TITLE
[data grid] `setRows` does not update the state correctly

### ISSUE THREAD

**Issue by experimarketing** [mui/mui-x#5742] opened 2022-08-09 14:55 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

This is the demo:
https://codesandbox.io/s/3hceoe?file=/demo.tsx

This is the source:
https://mui.com/x/react-data-grid/editing/#full-featured-crud-component

When you delete an element in the demo and then click on the header, it throws an error: 
```
Error
No row with id #0b2d2706-c4b2-540f-b0fd-affd3e98ca42 found
```

Also, if you click delete, then click on the edit icon for another one, then save that, then click on the header, it won't throw the error.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/fullfeaturedcrudgrid-demo-mui-x-forked-9eis2n

Steps:
1. Click Delete Icon
2. Click on "Date Created"

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

34169

**Comment by DanailH** [comment] 2022-08-11 08:36
Hi, @experimarketing thanks for raising this!

I can reproduce the problem. It seems to be related to the fact that the row's state is not being updated correctly after the deletion of a row. The sorting uses the rows state to apply the sorting model to all the rows.

**Comment by DanailH** [comment] 2022-08-11 08:41
I'll close this one because it looks like a duplicate. You can track the progress in the linked issue -> https://github.com/mui/mui-x/issues/5736

**Comment by cherniavskii** [comment] 2022-09-02 11:32
I'm reopening it, as it doesn't seem to be a duplicate since the demo doesn't use `apiRef.current.setRows` method

**Closed** 2022-09-22 08:24 UTC
Labels: bug 🐛, component: data grid, plan: Pro, feature: State management
