### ISSUE TITLE
Flex columns in datagrid resize error with vite

### ISSUE THREAD

**Issue by dk-xbsoftware** [mui/mui-x#9520] opened 2023-06-29 12:35 UTC
### Order ID

52531

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Repo with minimal reproducible example: https://github.com/dk-xbsoftware/muix-datagrid-issue

I'm using using vite+ts+@mui/x-data-grid-premium (and some other deps, but they are not included in repo above) in one of our projects, if I set "flex" property and try to resize the page - I'm getting this error

```
Uncaught RangeError: Maximum call stack size exceeded
    at computeFlexColumnsWidth (gridColumnsUtils.js:18:29)
    at hydrateColumnsWidth (gridColumnsUtils.js:140:34)
    at Object.handleGridSizeChange [as current] (useGridColumns.js:249:27)
    at EventManager.enhancedHandler (useGridApiEventHandler.js:62:97)
    at EventManager.emit (EventManager.js:57:18)
    at useGridApiInitialization.js:67:40
    at Proxy.publishEvent (useGridApiMethod.js:14:20)
    at Object.current (useGridDimensions.js:114:22)
    at EventManager.enhancedHandler (useGridApiEventHandler.js:62:97)
    at EventManager.emit (EventManager.js:51:18)
```

You may need to resize page to 150-250% and go back to 100%, when I found this issue - it happened on 1920/1080 breakpoint, outside of all containers it happens on different resolutions that I wasn't able to figure out yet

![NVIDIA_Share_0TMZuYwLGj](https://github.com/mui/mui-x/assets/82053670/dc8c2b09-533e-44d4-9d66-a19c58f1a00f)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
I was using Chrome (no idea why it wasnt found), v114.0.5735.199

Also Windows version is wrong

```
Edition		Windows 11 Pro
Version		22H2
OS build	22621.1848
```

```
System:
  OS: Windows 10 10.0.22621
Binaries:
  Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Chrome: Not Found
  Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.58)
npmPackages:
  @emotion/react: ^11.11.1 => 11.11.1
  @emotion/styled: ^11.11.0 => 11.11.0
  @mui/base:  5.0.0-beta.5
  @mui/core-downloads-tracker:  5.13.4
  @mui/material: ^5.13.6 => 5.13.6
  @mui/private-theming:  5.13.1
  @mui/styled-engine:  5.13.2
  @mui/system:  5.13.6
  @mui/types:  7.2.4
  @mui/utils:  5.13.6
  @mui/x-data-grid:  6.9.0
  @mui/x-data-grid-premium: ^6.9.0 => 6.9.0
  @mui/x-data-grid-pro:  6.9.0
  @mui/x-license-pro:  6.9.0
  @types/react: ^18.2.13 => 18.2.13
  react: ^18.2.0 => 18.2.0
  react-dom: ^18.2.0 => 18.2.0
  typescript: ^5.1.3 => 5.1.3
```
</details>

**Comment by cherniavskii** [comment] 2023-06-29 20:55
Duplicate of https://github.com/mui/mui-x/issues/9510

**Closed** 2023-06-29 20:56 UTC
Labels: component: data grid, status: needs triage, plan: Premium, support: commercial

**Comment by cherniavskii** [comment] 2023-06-30 13:55
This issue should be fixed in https://github.com/mui/mui-x/releases/tag/v6.9.1
