### ISSUE TITLE
[pickers][DatePicker] Incorrect display of value in input field when Controlled component

### ISSUE THREAD

**Issue by mseweryn45** [mui/mui-x#14519] opened 2024-09-06 10:58 UTC
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-4eslb9?file=Demo.tsx

Steps:
1. Choose any date
2. Again select any other day from the same month again

[DatePickerValue-demo-—-MUI-X---StackBlitz.webm](https://github.com/user-attachments/assets/bdfede45-48b5-4da1-a773-9a9e1103207e)

### Current behavior

After first select input displays the first day of the selected month,  but after second select the selected one is displayed, even though the one of the first day of the month is passed in the variable

### Expected behavior

DatePicker after the change will take the value that was passed using the variable

### Context

When creating a component with a lock on the need to select the date of the first day of the month, there is an inconsistency between the displayed date and the one we have stored

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datepicker value controlled

**Search keywords**:

**Comment by LukasTy** [comment] 2024-09-09 15:36
Thank you for opening this issue and providing a great reproduction example. 🙏 
This looks like a duplicate of https://github.com/mui/mui-x/issues/10424.
I'm closing this issue as a duplicate.
If you think that my assumption is incorrect, feel free to comment or reopen the issue. 😉

**Closed by LukasTy** 2024-09-09 15:36 UTC
Labels: bug 🐛, component: pickers, component: date picker
