### ISSUE TITLE
GridToolbar - flickering and weird behavior

### ISSUE THREAD

**Issue by MustafovaSemra** [mui/mui-x#3919] opened 2022-02-10 16:16 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Menu appears in top right corner of the screen, does a quick flickering move before it anchors right under the toolbar.

https://user-images.githubusercontent.com/77024737/153449407-77d32637-65f7-4b28-838f-3a26be50faf5.mov

### Expected behavior 🤔

The menu needs to appear right below the toolbar.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MustafovaSemra** [comment] 2022-02-10 17:21
Hi @cherniavskii 
Thank you for getting back to me so quickly. 
[code](https://codesandbox.io/s/datagrid-v5-quick-start-forked-e1phk?file=/src/App.tsx)

**Comment by cherniavskii** [comment] 2022-02-10 17:50
@MustafovaSemra is it a working demo? It looks like a lot of modules are missing.
It also helps if demo is as minimal as possible.

**Comment by cherniavskii** [comment] 2022-02-10 18:49
@MustafovaSemra I've made a working demo out of the code you provided and cannot reproduce the issue - see https://codesandbox.io/s/datagrid-v5-quick-start-forked-6zsmn?file=/src/App.tsx

Can you create one that clearly shows the issue you're seeing?

**Comment by MustafovaSemra** [comment] 2022-02-10 19:51
I'm not using the MUI custom theme, I even removed all the styling. It's still happening.

**Comment by cherniavskii** [comment] 2022-02-11 09:45
Then it's something else.
We need a working demo reproducing the issue, otherwise we can't do much here.

**Comment by m4theushw** [comment] 2022-02-11 12:06
Could you share your `yarn.lock` and confirm that the application has no CSS transitions? My supposition is that the anchor of the panel is wrong.

**Comment by MustafovaSemra** [comment] 2022-02-11 14:40
@m4theushw @cherniavskii I removed the global transitions and that fixed the issue. Thank you so much for your help.

**Comment by m4theushw** [comment] 2022-02-11 14:48
Which transition you have in your application? Can you share part of the code? It would be nice to see if this is not a bug related to the anchor of the panel.

**Comment by cherniavskii** [comment] 2022-02-14 19:14
Looks like it's how `Popper` works - see https://codesandbox.io/s/simplepopper-material-demo-forked-3g9z3?file=/public/index.html:436-478

**Comment by m4theushw** [comment] 2022-03-01 22:54
I'll close this issue because there's nothing we can do to fix it. This weird behavior is happening because, by default, the Popper first mounts in the top-left corner, then it moves the content to the right position. Using `*` to apply transition to every element in a page may cause side effects like this one. If you still need to animate the panel I would suggest to [override](https://mui.com/components/data-grid/components/#components) the 
`components.Panel` slot passing a custom Panel but with transitions [compatible](https://mui.com/components/popper/#transitions) with the Popper.

**Closed by m4theushw** 2022-03-01 22:54 UTC
Labels: component: data grid
