### ISSUE TITLE
Current meridiem in time clock

### ISSUE THREAD

**Issue by capi20** [mui/mui-x#10574] opened 2023-10-04 11:41 UTC
### Summary 💡

For 12 hour format, in time picker/clock, am/pm should get active as per the current time.

### Examples 🌈

Suppose in a time picker, disablePast and ampm both props are true then in this case if I open time picker at 02:00 PM then it should not show disable AM time. There in no point of showing disable time to user.

### Motivation 🔦

This is necessary to improve user experience specially if we are disabling past time.

**Search keywords**: time picker

**Comment by LukasTy** [comment] 2023-10-04 13:26
Hello. Thank you for opening this issue.
This looks like a duplicate of https://github.com/mui/mui-x/issues/10316.
Closing this one to keep one source of truth.
Feel free to follow the mentioned issue to keep track of it's progress. 😉

**Closed by LukasTy** 2023-10-04 13:26 UTC
Labels: status: needs triage

**Comment by capi20** [comment] 2023-10-05 04:28
Thanks! got the fix in #10316
