### ISSUE TITLE
[docs] Demo BasicDetailPanels crashes

### ISSUE THREAD

**Issue by f-neto** [mui/mui-x#9549] opened 2023-06-27 13:48 UTC
- [x] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20BasicDetailPanels%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-data-grid/master-detail/
2. Scroll down to the first `DataGrid` demo section
3. Select the third row in the grid
    - Should be the `Order ID: 3` and `Customer: Flavien`
4. Click on the `+` for the selected row
5. demo *BasicDetailPanels* crashes

See video
https://github.com/mui/material-ui/assets/100794299/7ac7730e-a5ca-4e69-8c58-ee9bcddbe063

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.9.0  |
| Netlify deploy | https://649554f2422b830008c6ee03--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 |

**Comment by LukasTy** [comment] 2023-07-03 07:59
Hello @f-neto 
Could you confirm if the problem is still relevant?
We have released v6.9.1 on Friday and the problem does not seem to happen anymore. 🤷

**Comment by f-neto** [comment] 2023-07-03 13:20
@LukasTy I tried many times here again exercising the same scenario (with variations) and issue seems to be fixed, I couldn't reproduce it anymore 👍🏼

**Comment by LukasTy** [comment] 2023-07-03 15:26
Closing the issue then. Feel free to re-open it if you are able to reproduce it. 😉

**Closed by LukasTy** 2023-07-03 15:26 UTC
Labels: component: data grid
