### ISSUE TITLE
[question] QuickFilter on visible columns only

### ISSUE THREAD

**Issue by Shinji22** [mui/mui-x#6583] opened 2022-10-21 08:59 UTC
### Order ID 💳

#45796

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have an DatagridPro, with hidden columns by default, and a Grid Toolbar QuickFilter.
Is there a way to make a search from the QuickFilter only on visible columns?

To me it's not very understandable for users to display data that has been filtered via a a field in a hidden column...

Thanks

**Comment by cherniavskii** [comment] 2022-10-21 13:39
Duplicate of https://github.com/mui/mui-x/issues/6559
See https://github.com/mui/mui-x/issues/6559#issuecomment-1283886640 for a workaround

**Closed by cherniavskii** 2022-10-21 13:39 UTC
Labels: status: needs triage, support: commercial
