### ISSUE TITLE
[data-grid] Components within custom `ErrorOverlay` are not clickable

### ISSUE THREAD

**Issue by sebastianfrey** [mui/mui-x#6294] opened 2022-09-26 09:07 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Components (e.g. Button) within a custom `ErrorOverlay` are not clickable.

### Expected behavior 🤔

When rendering a custom `ErrorOverlay`, the components rendered within the overlay should be clickable.

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Go to: https://stackblitz.com/edit/react-ivj9ef?file=demo.tsx
2. Try to click reset.

### Context 🔦

We use the Grid with server side filtering and sorting. In order to give users the ability to recover from unexpected backend errors, we used a custom `ErrorOverlay` to render a reset button.

We recently upgraded from 5.12.3.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

22075

**Comment by cherniavskii** [comment] 2022-09-26 16:48
Duplicate of https://github.com/mui/mui-x/issues/5725

**Closed by cherniavskii** 2022-09-26 16:48 UTC
Labels: duplicate, component: data grid, feature: Rendering layout, customization: css
