### ISSUE TITLE
DataGrid docs cut off

### ISSUE THREAD

**Issue by s-e1** [mui/mui-x#6173] opened 2022-09-15 20:20 UTC
The DataGrid api docs at the section Props, in the column "description" are cut off at the end. 
This is caused by the column inheriting from the table the ".css-1thecvj table" rule of `word-break: normal;`
This problem exists also in DataGridPro and DataGridPremium.

**Comment by cherniavskii** [comment] 2022-09-19 12:05
Thanks @s-e1 
I'm closing it as a duplicate of https://github.com/mui/mui-x/issues/5263

**Closed by cherniavskii** 2022-09-19 12:05 UTC

**Comment by oliviertassinari** [comment] 2022-12-19 16:04
Duplicate of https://github.com/mui/material-ui/issues/34085
