### ISSUE TITLE
[data grid] Row Reorder and row virtualisation don't mix

### ISSUE THREAD

**Issue by camnealie** [mui/mui-x#6078] opened 2022-09-08 08:46 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When working with over 100 rows in a datagrid (so, when you're working with some virtualised rows), if you try to reorder the rows and one of the rows is virtualised, the onRowOrderChange prop doesn't fire.

For example, if you grab the top row and drag it down to the bottom of the table to start scrolling the table further down, once you hit previously-virtualised rows, dropping on one of those rows appears to perform the reorder - but the function that is supposed to fire at that stage never does. (So, the change doesn't get saved, in my case).

This happens if you drag and use the scrollwheel, AND if you drag and let the table slowly scroll down itself. 

### Expected behavior 🤔

In all circumstances, a row reorder should fire the onRowOrderChange prop.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-issue-template-forked-wnp4g4?file=/src/App.tsx

Steps:
1. Follow the steps outlined in the sandbox excample
2.
3.
4.

### Context 🔦

I am storing row order as an index next to each row - so every time there's a row reorder, I parse that into a PATCH request I send to the backend, updating all of the rows indexes. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: macOS 12.2.1
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.3
  npmPackages:
    @emotion/react:  11.10.0 
    @emotion/styled: ^11.3.0 => 11.8.1 
    @mui/base:  5.0.0-alpha.74 
    @mui/icons-material: ^5.0.1 => 5.5.1 
    @mui/lab: ^5.0.0-alpha.48 => 5.0.0-alpha.75 
    @mui/material: ^5.0.1 => 5.5.3 
    @mui/private-theming:  5.5.3 
    @mui/styled-engine:  5.5.2 
    @mui/styles: ^5.0.1 => 5.5.3 
    @mui/system:  5.5.3 
    @mui/types:  7.1.3 
    @mui/utils:  5.10.3 
    @mui/x-data-grid:  5.17.1 
    @mui/x-data-grid-premium: ^5.14.0 => 5.17.1 
    @mui/x-data-grid-pro:  5.17.1 
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.0 
    @mui/x-license-pro:  5.17.0 
    @types/react:  17.0.43 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
</details>

### Order ID 💳 (optional)

47345

**Comment by m4theushw** [comment] 2022-09-09 23:31
@DanailH could you take a look? I checked and `rowDragEnd` is not being fired.

**Comment by cherniavskii** [comment] 2022-10-19 11:16
Duplicate https://github.com/mui/mui-x/issues/6165 ?

**Comment by MBilalShafi** [comment] 2022-11-08 13:19
Closing as duplicate of #6165

**Closed by MBilalShafi** 2022-11-08 13:19 UTC
Labels: bug 🐛, component: data grid
