### ISSUE TITLE
[pickers] The monthly label moves up with quickly switch between months

### ISSUE THREAD

**Issue by svidskiy** [mui/mui-x#14203] opened 2024-08-14 09:00 UTC
### Steps to reproduce

Link to live example: (required)

[Example](https://codesandbox.io/s/7hdm68?file=/src/Demo.tsx)

### Current behavior

With a quick switch between months, the label flies up endlessly

https://github.com/user-attachments/assets/7e16dd37-f642-43c5-b988-9d952818370f

### Expected behavior

Regardless of the number of clicks, it should appear from the same position with a smooth animation, coming in from the  top.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.17
    @mui/icons-material: ^5.15.17 => 5.15.17
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: ^5.15.17 => 5.15.17
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system:  5.16.7
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-charts: ^7.12.1 => 7.12.1
    @mui/x-charts-vendor:  7.12.1
    @mui/x-data-grid:  7.3.2
    @mui/x-data-grid-pro: ^7.3.2 => 7.3.2
    @mui/x-date-pickers: ^7.4.0 => 7.4.0
    @mui/x-date-pickers-pro: ^7.4.0 => 7.4.0
    @mui/x-license:  7.2.0
    @types/react: ^18.2.66 => 18.2.79
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.4.5
```
</details>

**Search keywords**: date pickers, pickers
**Order ID**: 89766

**Comment by flaviendelangle** [comment] 2024-08-14 09:07
I can't reproduce it on the link you provided.
@michelengelen @LukasTy do you have the same behavior as on the video?

**Comment by michelengelen** [comment] 2024-08-14 09:18
@flaviendelangle I can sometimes see it flashing briefly.
So I did run it in my local instance and throttle the CPU I can reproduce this any time.
My guess is that the label gets added before the old element is unmounted.

**Comment by svidskiy** [comment] 2024-08-15 05:57
> @flaviendelangle I can sometimes see it flashing briefly. So I did run it in my local instance and throttle the CPU I can reproduce this any time. My guess is that the label gets added before the old element is unmounted.

Yes, it turns out that I had a build running at that moment, which caused a CPU load, so I noticed it clearly. This can also happen with rapid clicking, though not to the same extent. Should we treat this as a non-issue and close it?

**Comment by michelengelen** [comment] 2024-08-15 14:05
I assume we cannnot do anything about this. It's just the way the Transitiongroup works.
I'll close this here.

To prevent this you can always use the `reduceAnimations` prop, since that will not use the transition

**Closed by michelengelen** 2024-08-15 14:05 UTC
Labels: bug 🐛, status: waiting for maintainer, component: pickers, support: pro standard
