### ISSUE TITLE
[DateRangePicker] Check-in and check-out date refresh after choosing a check-in date with the keyboard (only when the date picker is active) and try to choose a checkout date with the keyboard 

### ISSUE THREAD

**Issue by MahmoudMans** [mui/mui-x#4543] opened 2022-02-28 18:48 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After choosing a check-in date with the keyboard and the date picker appear and you try to choose a check-out date, both the dates will be reset.
But when choosing a check-in date with the keyboard and the date picker does not appear(which is not logical), it works correctly.

### Expected behavior 🤔

After choosing a check-in date with the keyboard and the date picker appear and when you try to choose a check-out date, both the dates should stays and do not reset so that we can see the ouput of the component.

### Steps to reproduce 🕹

Steps:

1. Go to the Mui website
2. Select Docs 
3. Open the Date Range Picker
4. And try to add a date in the check-in field with the keyboard
5. Try to add a check-out date with keyboard

### Context 🔦

I wanted to contribute to this repository while trying to fix an issue and I came across this bug so I wanted to report it.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  Browser Used: Google Chrome

 System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD  
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD    
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.62)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.67
    @mui/codemod:  5.3.0
    @mui/docs:  5.3.0
    @mui/envinfo:  2.0.4
    @mui/icons-material:  5.3.1
    @mui/joy:  5.0.0-alpha.13
    @mui/lab:  5.0.0-alpha.67
    @mui/markdown:  5.0.0
    @mui/material:  5.4.0
    @mui/material-next:  6.0.0-alpha.21
    @mui/private-theming:  5.3.0
    @mui/styled-engine:  5.3.0
    @mui/styled-engine-sc:  5.3.0
    @mui/styles:  5.3.0
    @mui/system:  5.4.0
    @mui/types:  7.1.0
    @mui/utils:  5.3.0
    @mui/x-data-grid:  5.2.2
    @mui/x-data-grid-generator:  5.2.2
    @mui/x-data-grid-pro:  5.2.2
    @mui/x-license-pro:  5.2.2
    @types/react: ^17.0.38 => 17.0.38
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components:  5.3.3
    typescript: ^4.5.4 => 4.5.4

</details>

**Comment by cherniavskii** [comment] 2022-04-18 17:49
Duplicate of #4314

**Closed by cherniavskii** 2022-04-18 17:49 UTC
Labels: status: needs triage, component: date range picker
