### ISSUE TITLE
[pickers] Add ability to set a default time for DateTime pickers

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#6870] opened 2022-11-16 09:22 UTC
# Summary

With the new pickers, and without the Clock interface on Desktop, [once the user picks a date on the calendar view](https://codesandbox.io/s/date-and-time-pickers-forked-ilt3t2?file=/src/App.tsx), the focus of the component is immediately moved to the hour, which is great. However, developers might need to set an initial or default "time" for a DateTime picker, to improve further UX when filling this input.

We can consider adding either a new prop or a recipe (based on onChange treatment).

**Comment by flaviendelangle** [comment] 2022-11-16 10:23
For the recipe, we could add some additional information to the `onChange` context to let people do things like:

```tsx
<DatePicker 
  value={value}
  onChange={(newValue, ctx) => {
    if (ctx.sourceViewType === 'UI' && ['year', 'month', 'day'].includes(ctx.sourceView)) {
      return setValue(newValue.set('hours', 5))
    }

    return setValue(newValue);
  }}
/>
```

**Comment by michelengelen** [comment] 2023-09-12 09:53
After a bit of investigation I found a possible cause (albeit rid of a solution for now). The selection of a day in the picker will pass a complete (formatted) Date object to the `onChange`, which is in turn causing the time-value to be updated to `00:00` (aka 12:00 AM) as well.

I can imagine 2 different ways to improve this:
1. remove the time from the formatted day-value passed to the `Day` component. It is receiving its value from this adapter https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts
2. manually removing the time (maybe guarded by a prop?) from the onChange handling

I would very much prefer the first approach

WDYT @flaviendelangle ?

**Comment by flaviendelangle** [comment] 2023-09-12 10:02
I'm not sure to understand your solutions.
What do you mean by "remove the time from the formatted day-value passed to the Day component.".

For me the problem is that, when you select a value in a view, we generate a date which is passed to `onChange` and so we have a full date that will populate all the views, even the one not visited yet.
You select a date => you have a time
You select a year => you have a month, a date and a time
etc...


If we are trying to fix the following:

> However, developers might need to set an initial or default "time" for a DateTime picker, to improve further UX when filling this input.

Then I think the date returned by `DayCalendar` should respect the `referenceDate` prop of `DateCalendar` just like `MonthCalendar` and `YearCalendar` are doing.

____

If we are trying to fix the following:

> But my dream would be that, when people click on a date on a DateTimePicker, it only feels the date part in the field, letting the time empty.


Then it's a massive change.

**Comment by michelengelen** [comment] 2023-09-12 10:30
Sry if I did not made my suggestion clear enough.
I was suggesting to remove the `time` from the `date` value passed into the `onChange` function. I did some more digging and as you said: this is a massive change. 

There might be a different solution to this though:
We do trigger a `PickerValueUpdateAction` whenever a value is selected from within the `Picker`. We could potentially hook into this and provide a new action property which defines which part of the picker will receive an update and base the UI changes, so e.g. prevent updating the time.

Not sure if this can be a viable change though ... just exploring options for now.

---

I do agree that respecting the `referenceDate` prop is easier

**Comment by flaviendelangle** [comment] 2023-09-12 10:34
> I was suggesting to remove the time from the date value passed into the onChange function.

But since it's a date object, how do you remove the time from it?
And if we take a step back, how do you remove the month and day when picking a year?
For me, as soon as `onChange` is fired, all the views should be populated because the user will most likely update it's `value` prop and therefore we have a full date-time that we should visually respect.

If we want to keep the next views empty when filling a view (do not select any month when entering the month view after selecting a year), then we need some internal state that says "I chose year X" instead of storing a date and that only fires `onChange` once the last view has been filled.
This would make the view editing coherent with the field editing, but it's indeed a very big change.

**Comment by flaviendelangle** [comment] 2023-09-12 11:29
Well, it already works :laughing: 
See https://codesandbox.io/s/date-and-time-pickers-forked-9pvxzr?file=/src/App.tsx
If you select a date, the time is set to 3:45PM

I'm closing the issue

**Closed by flaviendelangle** 2023-09-12 11:29 UTC
Labels: new feature, component: pickers, component: DateTimePicker, dx, design
