### ISSUE TITLE
[MobileTimePicker] doesn't call `onAccept` when date is unchanged

### ISSUE THREAD

**Issue by violabg** [mui/mui-x#4898] opened 2022-05-16 08:21 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm using onAccept event to check the date before submitting the value to the interface, in order to validate the time.
It was working fine until version @mui/x-date-pickers 5.0.0-alpha.2, but after updating to @mui/x-date-pickers 5.0.0-alpha.3
MobileTimePicker  doesn't call onAccept

### Expected behavior 🤔

to call onAccept method

### Steps to reproduce 🕹

https://codesandbox.io/s/responsivetimepickers-material-demo-forked-3zxr2e?file=/demo.tsx

**Comment by alexfauquette** [comment] 2022-05-16 09:03
`onAccept` is not called in your demo because the value is when accepting the date is the same as when opening the picker

You can see [this comment](https://github.com/mui/mui-x/issues/4438#issuecomment-1098816661) for more information

The global idea is to use `value`, `onChange` to control the local state of the picker. And to use `onAccept` for the global one. If the user validates the same date as before, it is not required to call `onAccept`.

**Comment by flaviendelangle** [comment] 2022-05-16 10:12
If you can give us more details about your use case and why you need the `onAccept` callback to be fired even if the value did not change.

Depending on who we are asking to, some people do want, or don't want it to happen.
We plan in the future to provide APIs to let user override those behaviors.
But it will probably take some months.

**Comment by violabg** [comment] 2022-05-16 14:37
ok, I'll try to explain my use case, but first I want to point out, that is was working prior to 5.0.0-alpha.3, and that there is a discrepancy in the behaviour of MobileTimePicker, which is the case of this issue and DescktopTimePicker/TimePicker, that still work as before even on the latest version.

What I need is to validate the time before submitting it to the UI and to the services, this is the way I solved this issue (works with 5.0.0-alpha.3)

```ts
  function _onChange(
    date: Moment | undefined | null,
    keyboardInputValue?: string | undefined
  ) {
    const _date = date;

    if (checkIsTwoHoursFromNow) {
      // console.log("name :>> ", name);
      const twoHoursFromNow = moment().subtract(2, "hours");
      const twoHoursAfterNow = moment().add(2, "hours");

      if (
        !isAccount &&
        (_date?.isBefore(twoHoursFromNow) || _date?.isAfter(twoHoursAfterNow))
      ) {
        toast.error(
          "it is not possible to mark 2 hours before or after the current date.",
          {
            position: toast.POSITION.TOP_CENTER
          }
        );
        return;
      }
    }
    setSelectedTime(_date);
  }

  const onAccept = (
    date: Moment | undefined | null,
    keyboardInputValue?: string | undefined
  ) => {
    // committing changes to the parent
    onChange(date as Moment | null, name);
  };

  return (
    <MobileTimePicker
      onChange={_onChange}
      onAccept={onAccept}
      disabled={disabled}
      label={label}
      minutesStep={minuteStep}
      value={selectedTime}
      renderInput={(params) => <TextField {...params} />}
    />
  );
```

before (many version ago, I don't remember exactly which) it wasn't working using "onChange" so I had  to do the check on the onAccept method, now with the latest version onAccept is not called if you don't set the value first (but it is on DesktopTimePicker), so I have changed my code as per above.

The only thing I don't like is that, this part of the code, is called twice, once when I pick the ours and once when I pick the minutes. Before it was called only once when I pressed the OK button, using the onAccept method.

```ts
if (
        !isAccount &&
        (_date?.isBefore(twoHoursFromNow) || _date?.isAfter(twoHoursAfterNow))
      ) {
        toast.error(
          "it is not possible to mark 2 hours before or after the current date.",
          {
            position: toast.POSITION.TOP_CENTER
          }
        );
        return;
      }
```

**Comment by violabg** [comment] 2022-05-16 15:14
I have updated the example.

https://codesandbox.io/s/date-and-time-pickers-forked-tzctfi?file=/src/App.tsx,

the example uses  @mui/x-date-pickers 5.0.0-alpha.2, and is working as aspected, if the date is not valide the TimePick won't show the new value and you'll only one working after you press ok, is you chance to  @mui/x-date-pickers 5.0.0-alpha.3 it won't work anymore and you need to use the code from my previous post, but you'll have 2 console logs

please note that I'm still using react 17.

**Comment by flaviendelangle** [comment] 2022-05-17 07:10
Here is [the same example with the alpha.3](https://codesandbox.io/s/date-and-time-pickers-forked-bwnxdc?file=/src/App.tsx)

I have the following behavior:

1. Open the picker
2. Click on "4" (which is invalid) => onChange is called
3. Click on "OK" => onAccept is called and log an error instead of updating the state

Which is what you are describing for alpha.2 no ?

But I would do the opposite: always update the `selectedTime` in `onChange` and reset it in `onAccept` if not valid according to your criteria
Like [on this example](https://codesandbox.io/s/date-and-time-pickers-forked-73if8n?file=/src/App.tsx)

**Comment by violabg** [comment] 2022-05-17 08:26
> 3. Click on "OK" => onAccept is called and log an error instead of updating the state

in your example onAccept is not called, which is exactly the point of the issue.

but your second option works. So I will use it.

I still think the issue remains, since the onAccept is not always called from MobileTimePicker

**Comment by flaviendelangle** [comment] 2022-05-17 08:32
Please give an exact reproduction case, which date you click in which order.
In the video below I click on "4" and `onAccept` is called (it is the 1st link of my previous message)

https://user-images.githubusercontent.com/3309670/168767103-341f3975-ec74-45d1-98b0-9c5583ea43cd.mp4

**Comment by violabg** [comment] 2022-05-17 08:57
this is weird, is working now, but the weird part is that even my first example that reproduced the problem (and it was confirmed), is working now.
https://codesandbox.io/s/responsivetimepickers-material-demo-forked-3zxr2e?file=/demo.tsx

I'm confused

**Comment by flaviendelangle** [comment] 2022-05-17 09:18
It is weird indeed
Well better that way than the other

I'm closing the issue, but if you can reproduce the problem again, I will re-open it to investigate :+1:

**Closed by flaviendelangle** 2022-05-17 09:18 UTC
Labels: status: incomplete, component: pickers

**Comment by yamila-fraiman** [comment] 2022-05-25 13:22
Same issue.
On the other hand, I don't understand why I should persist a selected date that won't be confirmed instead of receiving the date in the onAccept.
