### ISSUE TITLE
[StaticDatePicker] When selecting a month, it switches to year selection

### ISSUE THREAD

**Issue by rwieruch** [mui/mui-x#4975] opened 2022-03-09 13:49 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I am using the StaticDatePicker the following way:

```
	<StaticDatePicker
		orientation="portrait"
		openTo="month"
		views={['month', 'year']}
		value={date}
		onChange={setDate}
		onClose={onClose}
	/>
```

When I select a month, the date picker automatically changes to the year view. Since I have custom buttons that enable a user to switch between month and year, I'd like to prevent the automatic change from month to year when selecting a month. I think the previous version supported this, because we didn't have this automatic change of views.

**Comment by flaviendelangle** [comment] 2022-05-23 09:38
I think it's a duplicate of #4444 

@alexfauquette I think the feature make sense, and it was asked twice recently
We could probably implement it in the coming weeks

**Comment by alexfauquette** [comment] 2022-05-23 14:57
The view can be contyroled by `view`/`onViewChange`

`disableOpenNext` would be equivalent to not updating the `view` prop.

In this demo, the view can be modified by some buttons, but is not impacted by the selection of the month

https://codesandbox.io/s/basicdatepicker-material-demo-forked-r3oc69?file=/demo.tsx

**Comment by alexfauquette** [comment] 2022-05-23 16:30
Adding a reason sounds more flexible, and according to the feedback we could add `disableOpenNext` which will do nothing else than a shortecut for 

```js
onviewChange={(newView, reason) => reason!=='selection' && setView(newView)}
```

**Comment by flaviendelangle** [comment] 2022-09-15 11:05
Closing in favor of #4444

**Closed by flaviendelangle** 2022-09-15 11:05 UTC
Labels: new feature, component: pickers
