### ISSUE TITLE
[DataGridPro] Column pinning not working on Safari

### ISSUE THREAD

**Issue by danra2** [mui/mui-x#3960] opened 2022-02-15 14:54 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Pinning of columns not working properly in Safari browsers. It works as expected on IE, Firefox, and Chrome. However, in Safari the grid only stickies the column headers, but not the row data. Implemented it the way of the bug fix from earlier thread:
https://github.com/mui/mui-x/issues/3885#issuecomment-1031688279

### Expected behavior 🤔

Grid when stickied should sticky both the column headers and the row data correlated. 

### Steps to reproduce 🕹

Steps:

1.Safari 

### Context 🔦

<img width="1016" alt="Screen Shot 2022-02-15 at 9 53 21 AM" src="https://user-images.githubusercontent.com/18181205/154087029-dfc593d4-986f-4321-958e-4701c9324e53.png">

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System: OS: macOS Mojave 10.14.6 Binaries: Node: 16.9.1 - /usr/local/bin/node Yarn: 1.22.17 - /usr/local/bin/yarn npm: 7.21.1 - /usr/local/bin/npm Browsers: Chrome: 97.0.4692.99 Edge: Not Found Firefox: Not Found Safari: 12.1.2 npmPackages: @emotion/react: ^11.4.1 => 11.7.0 @emotion/styled: ^11.3.0 => 11.3.0 @mui/base: 5.0.0-alpha.65 @mui/core: 5.0.0-alpha.47 @mui/icons-material: ^5.0.0 => 5.3.0 @mui/lab: ^5.0.0-alpha.47 => 5.0.0-alpha.47 @mui/material: ^5.0.0 => 5.3.0 @mui/private-theming: 5.3.0 @mui/styled-engine: 5.3.0 @mui/styles: ^5.0.0 => 5.0.0 @mui/system: 5.3.0 @mui/types: 7.1.0 @mui/utils: ^5.0.0 => 5.3.0 @mui/x-data-grid: ^5.0.0-beta.1 => 5.0.0-beta.1 @mui/x-data-grid-generator: 5.2.2 @mui/x-data-grid-pro: ^5.0.1 => 5.0.1 @mui/x-license-pro: 5.0.1 @types/react: 17.0.14 react: ^17.0.2 => 17.0.2 react-dom: ^17.0.2 => 17.0.2 typescript: ^4.3.5 => 4.3.5
```
</details>

### Order ID 💳 (optional)

32640

**Comment by m4theushw** [comment] 2022-02-15 18:51
The workaround from https://github.com/mui/mui-x/issues/3885#issuecomment-1031688279 is not necessary. A fix was released in v5.5.1. Could you verify if you're using this version? I can't reproduce the bug in Safari. It would help to debug the issue if you could add a live example. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. 

<img width="400" src="https://user-images.githubusercontent.com/42154031/154128733-5efc5bd5-7090-49d2-aa53-f42faa87dc4a.png" alt="image" style="max-width: 100%;">

**Comment by danra2** [comment] 2022-02-15 21:37
https://codesandbox.io/s/fullfeaturedcrudgrid-material-demo-forked-pb8k6w?file=/demo.js:0-22250

Confirmed update to  5.5.1, unfortunately still not working in Safari.

**Comment by m4theushw** [comment] 2022-02-15 21:53
> I'm also using the mianimals.cc framework though if that makes a difference.

Could you check if removing this dependency it works?

**Closed** 2022-02-23 00:39 UTC
Labels: status: incomplete
