### ISSUE TITLE
[docs] Demo PopularFeaturesDemo crashes

### ISSUE THREAD

**Issue by minchaej** [mui/mui-x#8429] opened 2023-03-29 05:07 UTC
- [X] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20PopularFeaturesDemo%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-data-grid/demo/
2. Go to '[Lazy loading](https://mui.com/x/react-data-grid/demo/)' demo.
3. Scroll the demo to the bottom quickly
4. demo *PopularFeaturesDemo* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.0.3  |
| Netlify deploy | https://641c796331192e0008a231d3--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 |

**Comment by minchaej** [comment] 2023-04-03 01:24
@varunmulay22  sure no problem!
Here I have attached the location of the demo table `PopularFeaturesDemo `.
If you scroll really fast up and/or down, it will return the crash log that I have also attached. 
Much thanks! MUI rocks!

![demo](https://user-images.githubusercontent.com/24214138/229391495-1020169a-59a5-42a8-ac31-ca23ccd49df8.png)
![crash](https://user-images.githubusercontent.com/24214138/229391502-efc87f0f-f546-40df-9c92-8f7c738b0aad.png)

**Comment by varunmulay22** [comment] 2023-04-03 07:26
@minchaej Maybe this is a machine specific thing? I'm on a Mac M1 Pro, I don't seem to be able to reproduce this bug. Here's a video recording of what I see

https://user-images.githubusercontent.com/35381801/229440222-a962971e-fc74-4f3b-aa4f-a58842ed5578.mov

**Comment by minchaej** [comment] 2023-04-05 02:03
@varunmulay22 Hmm, well then yes I assume it is a machine specific thing. Glad that it doesn't occur on other browsers (because at least for me it is easily Reproducible). Thanks so much for the support, I was just trying to be helpful! I think this issue is solved???

**Comment by oliviertassinari** [comment] 2023-09-16 15:05
Duplicate of #10047

**Closed by oliviertassinari** 2023-09-16 15:05 UTC
Labels: docs, duplicate, component: data grid
