### ISSUE TITLE
[question] Pagination support with row grouping

### ISSUE THREAD

**Issue by nehabansal-90** [mui/mui-x#10226] opened 2023-09-04 14:30 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am getting grouped data from backend and want to utilize it render the data grid since it removes manipulations on frontend. also during pagination we don't need to group again on frontend. I have looked at tree grid but that doesn't fit perfectly since we need to provide path. could you please let me know how to enable MUI data grid to use nested JSON data?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment] 2023-09-06 10:54
@nehabansal-90 as far as I'm aware you can't use nested JSON data with the grid, you need to transform it so it is in an acceptable format for the data grid.

CC @cherniavskii

**Comment by MBilalShafi** [comment] 2024-09-07 13:30
This issue seems to be a duplicate of https://github.com/mui/mui-x/issues/10859 which will cover the root-level pagination support with the row grouping.
I'll go ahead and close this one in favor of #10859. Please feel free to track the progress on there.

**Closed by MBilalShafi** 2024-09-07 13:30 UTC
Labels: support: question, component: data grid, feature: Pagination, feature: Row grouping
