### ISSUE TITLE
MUI fails to use new column definition if a column is aggregated on

### ISSUE THREAD

**Issue by scamden** [mui/mui-x#10895] opened 2023-11-04 01:56 UTC
### Steps to reproduce

Link to live example: https://codesandbox.io/s/heuristic-butterfly-nc3khc?file=/src/Demo.tsx

Steps:
1. Make a grid with a numeric column
2. Set a the column to be aggregated
3. Cause the columns to be recreated somehow with some noticeable difference

### Current behavior

updated columns are not reflecting in the datagrid

### Expected behavior

updated columns are reflected (and they are if the column isn't aggregated on right now)

### Your environment

  System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 98.72 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nodenv/versions/18.12.1/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.5.1 - ~/.nodenv/versions/18.12.1/bin/npm
    pnpm: 6.32.11 - ~/.nodenv/versions/18.12.1/bin/pnpm
  Managers:
    Cargo: 1.63.0 - ~/.cargo/bin/cargo
    Homebrew: 4.1.18 - /opt/homebrew/bin/brew
    pip3: 22.2.2 - ~/.pyenv/shims/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.40.0 - /opt/homebrew/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.1.2 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    VirtualBox: 7.0.8 - /usr/local/bin/vboxmanage
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
  IDEs:
    VSCode: 1.84.0 - /opt/homebrew/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.19.2 - /opt/homebrew/bin/go
    Perl: 5.30.3 - /usr/bin/perl
    Python: 3.9.9 - /Users/scamden/.pyenv/shims/python
    Python3: 3.9.9 - /Users/scamden/.pyenv/shims/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.63.0 - /Users/scamden/.cargo/bin/rustc
  Databases:
    PostgreSQL: 14.8 - /opt/homebrew/opt/postgresql@14/bin/postgres
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.1

**Search keywords**: datagrid v6 aggregation
**Order ID**: 77647

**Comment by scamden** [comment] 2023-11-04 02:09
note even adding this to attempt to update imperatively fails:

```ts
  useEffect(() => {
    gridApiRef.current.updateColumns([valueColumn]);
  }, [gridApiRef, valueColumn]);
```

**Comment by romgrk** [comment] 2023-11-07 17:03
Duplicate of #10864, subscribe there for notifications.

**Closed by romgrk** 2023-11-07 17:03 UTC
Labels: component: data grid, status: waiting for maintainer
