### ISSUE TITLE
[DataGrid] Support column density when storing/restoring state

### ISSUE THREAD

**Issue by Neonin** [mui/mui-x#1441] opened 2021-04-19 13:25 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I would like to be able to save the row density state and display the visible columns 🙏, saving their state somewhere and not losing it after page reloads.
There is a prop for density, but there is no callback in the documentation.
I also tried digging around and subscribing to the `apiRef` events, but unfortunately, I couldn't find that either.😢

## Examples 🌈
There is already a `density` or `hide in columns` - present as part of the table but need to expose those as event handlers.

## Motivation 🔦

This will help users customize the view of the table , because when we reload the page, we still show the same view.

## Order id 💳

19652

**Comment by oliviertassinari** [comment] 2021-04-19 14:21
It looks like a duplicate of #820. Would it work for you if the whole state of the grid is persisted? (instead of having to cherry-pick each state)

**Comment by dtassone** [comment] 2021-04-19 15:38
there should be an `onDensityChange` handler in options.
We should always build features with 
1. a model
2. onModelChange handler

**Comment by oliviertassinari** [comment] 2021-04-19 15:39
@dtassone Then it's also related to #190 since it's at the core of the pain.

**Comment by flaviendelangle** [comment] 2022-06-29 10:40
Duplicates https://github.com/mui/mui-x/issues/4572

**Closed by flaviendelangle** 2022-06-29 10:40 UTC
Labels: component: data grid, design: ux
