### ISSUE TITLE
[DataGrid] An empty line above pinnedRows in the latest version

### ISSUE THREAD

**Issue by RazbezhkinAV** [mui/mui-x#11334] opened 2023-12-07 13:38 UTC
### Steps to reproduce

Link to live example: (required)
Grid version 6.18.3
https://codesandbox.io/p/sandbox/confident-grothendieck-spg5tt?file=%2Fsrc%2Findex.tsx%3A1%2C1-27%2C1

Grid version 6.5.0
https://codesandbox.io/p/sandbox/exciting-grass-qts75r?file=%2Fsrc%2FDemo.tsx%3A22%2C6

### Current behavior

In the latest version, an empty line appeared above the pinned line
v 6.18.3
![image](https://github.com/mui/mui-x/assets/90248363/ba8d84cc-1cfb-44fd-be76-d4a93f790149)

v6.5.0
![image](https://github.com/mui/mui-x/assets/90248363/f6beef77-2517-4812-966d-17dc8c30fe57)

### Expected behavior

should be
![image](https://github.com/mui/mui-x/assets/90248363/f6beef77-2517-4812-966d-17dc8c30fe57)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22621
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (119.0.2151.97)
```
</details>

**Search keywords**: pinnedRows
**Order ID**: 70308

**Comment by michelengelen** [comment] 2023-12-07 14:03
Hey @romgrk this seems to be a slight regression, since we introduced sticky behavior on the aggregation rows. The calculation seems to still take the aggregation row into account, since it deducts a single rows height from the `minHeight` property of the pinned columns container

<img width="2053" alt="Screenshot 2023-12-07 at 15 01 55" src="https://github.com/mui/mui-x/assets/32863416/f722a61f-de40-4da3-aa75-52708bcc022a">

Could you have a look and provide a diff? This does seem like an easy fix great for the `first good issue` label! 👍🏼 

Thanks! 🙇🏼

**Comment by romgrk** [comment] 2023-12-08 01:45
Do we want to provide a fix for this in v6? In v7 the issue is very likely to be gone as we're redoing the whole layout.

@RazbezhkinAV Is there a previous v6 version that works for you?

**Comment by RazbezhkinAV** [comment] 2023-12-08 06:55
@romgrk Yes, this was not the case in version 6.5.0

**Comment by cherniavskii** [comment] 2024-01-30 13:48
@romgrk The issue is fixed in v7: https://codesandbox.io/p/sandbox/trusting-tree-pv8mp2
I'm closing the issue for now, but feel free to reopen if you need a fix for v6.

**Closed by cherniavskii** 2024-01-30 13:48 UTC
Labels: component: data grid, regression, feature: Column pinning, feature: Aggregation
