### ISSUE TITLE
[RFC] Support for Next JS

### ISSUE THREAD

**Issue by R5dan** [mui/mui-x#15759] opened 2024-12-05 20:41 UTC
### What's the problem?

- Add support for Next JS in MUI X like MUI Material

### What are the requirements?

- Adding notes in docs for when things have to be server or client components (Next specific tools)
- Changing some objects to be able to be rendered

### What are our options?

- Adding support for all uses
- Adding support for some uses and saying in docs where a feature is not possible or feasible
- Changing nothing other than the docs to explain whats possible in next or not

### Proposed solution

I would prefer to have full compatibility with Next JS, with some minor adjustments in the code vs Reacts code in codebases however staying very similar. 

### Resources and benchmarks

Current errors from the docs example:
`[ Server ] Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.` and it keeps generating errors as you fix it.

**Search keywords**:

**Comment by michelengelen** [comment] 2024-12-06 11:43
Hey @R5dan ... thanks for opening this issue.

I think that we are currently not able to support server side rendering, as nearly all of our components are using state internally.

This topic comes up form time to time and we had a vivid discussion (and some backlinks) around it here: https://github.com/mui/mui-x/issues/7599

Closing this as a duplicate.

Duplicate of #7599

**Closed by michelengelen** 2024-12-06 11:43 UTC
Labels: status: waiting for maintainer, RFC
