### ISSUE TITLE
[DataGridPro] Override indeterminate checkbox state default behaviour when clicking to select all instead of deselecting all rows

### ISSUE THREAD

**Issue by alvinb** [mui/mui-x#3309] opened 2021-11-30 20:12 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡
Intent: 

- My intent is to have all the rows be selected when i click on the data grid's header checkbox when it is at its indeterminate state. Right now, it is deselecting all rows. I noticed this can be achieved in the `Table` Component but not in the `DataGridPro` component

In the `Table` component, one can override the handler for clicking the indeterminate checkbox:
```<TableHead>
      <TableRow>
        <TableCell padding="checkbox">
          <Checkbox
            color="primary"
            indeterminate={numSelected > 0 && numSelected < rowCount}
            checked={rowCount > 0 && numSelected === rowCount}
            onChange={onSelectAllClick}
            inputProps={{
              'aria-label': 'select all desserts',
            }}
          />
        ...
        </TableCell>
    </TableRow>
...
```

I cant find a way do to this on the `DataGridPro` component. At least not from the docs. Are there any efforts on adding this?

### Examples 🌈
codesandbox link [here](https://codesandbox.io/s/datagrid-v5-quick-start-forked-er1qe?file=/src/App.tsx)
_No response_

### Motivation 🔦

- UX enhancement to cover a specific use case highlighted above under "intent"

**Comment by alvinb** [comment] 2022-01-03 17:07
@DanailH here is the [codesanbox](https://codesandbox.io/s/datagrid-v5-quick-start-forked-er1qe?file=/src/App.tsx)

Steps to Reproduce:
1. click on any checkbox rows except for the header checkbox. (note: this will make the header checkbox be on indeterminate state)
2. now click the header checkbox.

notice that this will deselect all rows that have been selected. I want a different behavior which is clicking the indeterminate checkbox results in selecting all rows.

**Comment by alvinb** [comment] 2022-01-03 18:04
Update:

- i updated the [codesandbox](https://codesandbox.io/s/datagrid-v5-quick-start-forked-er1qe?file=/src/App.tsx) but i couldnt find a way to implement it

**Comment by jonathanrtuck** [comment] 2022-01-06 16:28
not sure a sandbox is needed here… you can already see the current behavior in all the [examples with checkboxes](https://mui.com/components/data-grid/#mit-version).

to clarify, if the checkbox in the table head is in the indeterminate state, clicking it should _check_ all rows, not _uncheck_ all rows, in order to be consistent with how it works (almost?) everywhere else, including [mui core's own checkbox](https://mui.com/components/checkboxes/#indeterminate)!

**Comment by alexfauquette** [comment] 2022-01-07 09:17
@jonathanrtuck I'm not convinced that "clicking it should check all rows". For example on Gmail it unselects, and [material design spec](https://material.io/components/checkboxes#behavior) does not specify the behavior. Moreover changing the default behavior implies it will change for all the users, even those who preferred the previous one.

As @alvinb noticed, the [Table component](https://mui.com/components/tables/#sorting-amp-selecting) allows choosing between the two behaviors. I'm in favor of allowing the same for DataGrid by overriding the header checkbox selection behavior.

To do so, the [event](https://mui.com/components/data-grid/events/) seems to be `headerSelectionCheckboxChange`.

Surprisingly, its equivalent prop `onHeaderSelectionCheckboxChange` is not implemented. I wrote an [example](https://codesandbox.io/s/datagrid-v5-quick-start-forked-797q5?file=/src/App.tsx:731-766) with the imperative event handler. But it appears that setting `event.defaultMuiPrevented = true` does not disable the default event handler. I don't know if I miss something, or if it is a bug.

**Comment by flaviendelangle** [comment] 2022-01-07 12:39
If possible, I'm in favor of doing it is user-land and adding a demo on the doc as it is quite a complex example and not really an edge case.

**Comment by jonathanrtuck** [comment] 2022-01-07 15:20
ok, i'll investigate implementing `onHeaderSelectionCheckboxChange`.

in the meantime, should we update the [Checkbox example](https://mui.com/components/checkboxes/#indeterminate) to uncheck all for consistency? or does the (potential) presence of pagination in this case warrant the unique UX? (i.e. if it checks all, would the user expect it to check only all of the currently displayed rows or including other pages?)

**Comment by flaviendelangle** [comment] 2022-01-07 16:36
The core example for the Checkbox is a good point, we should be consistent I think (@michaldudak)

**Comment by michaldudak** [comment] 2022-01-25 12:07
It seems more intuitive for me to select all sub-options when an indeterminate checkbox is clicked. That's also the behavior I found on a few other sites:

https://www.w3.org/TR/wai-aria-practices-1.1/examples/checkbox/checkbox-2/checkbox-2.html
https://chakra-ui.com/docs/form/checkbox#indeterminate
https://css-tricks.com/indeterminate-checkboxes/
https://material.angular.io/components/checkbox/overview
https://ant.design/components/checkbox/#components-checkbox-demo-check-all

Obviously, it's not a universal solution, as @alexfauquette noticed, but my feeling is that selecting all is more common. I'm not keen on changing the behavior on the Core Checkbox demo.

**Comment by flaviendelangle** [comment] 2022-01-25 12:13
I don't have a strong preference for what the behavior should be.
If the X team agrees that selecting all is a better behavior, we can change it in v6 for the grid.
And still allow to easily override it on the user side (which is a broader subject, we also have a topic when the rows are paginated on the server and the user wants to have a "Select all" status).

**Comment by cherniavskii** [comment] 2023-07-04 14:57
Duplicate of https://github.com/mui/mui-x/issues/7753

**Closed by cherniavskii** 2023-07-04 14:57 UTC
Labels: component: data grid, feature: Selection
