### ISSUE TITLE
Datagrid onGridFocus crashes when there are no rows left to highlight

### ISSUE THREAD

**Issue by DerkSchooltink** [mui/mui-x#15150] opened 2024-10-28 13:33 UTC
### Steps to reproduce

Link to live example: https://github-o8xf8g.stackblitz.io

Steps:
1. Have a datagrid with a single row
2. Delete the row
3. Crash

### Current behavior

The datagrid crashed because it appears it's trying to focus a row that doesn't exist. It only happens when no rows are in the datagrid, during the action of removing, which triggers the useGridFocus hook. Loading a component with no rows doesn't crash.

### Expected behavior

The datagrid should not attempt to highlight a row when no rows are present.

Additionally, it might be worth turning on the TS compiler flag `noUncheckedIndexedAccess`, such that these kind of issues are flagged. 

<img width="720" alt="image" src="https://github.com/user-attachments/assets/5bd53426-aa6c-4a1c-bcaf-14a4b75890fb">

### Context

I think this is related to a recent change made here:

https://github.com/mui/mui-x/commit/a01b8998e22220997a6d001af8bda4bec63a54da

It attempts to highlight a previous row when a row is deleted. But it doesn't take into account that there might be no rows at all to select. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 15.0.1
  Binaries:
    Node: 23.0.0 - ~/.nvm/versions/node/v23.0.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v23.0.0/bin/npm
    pnpm: 9.12.2 - ~/.nvm/versions/node/v23.0.0/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.70
    Edge: Not Found
    Safari: 18.0.1
```
</details>

**Search keywords**: datagrid, focus, row

**Comment by DerkSchooltink** [comment] 2024-10-28 13:35
After searching through PR's, I've found one that likely fixes this issue: https://github.com/mui/mui-x/pull/15146

**Comment by KenanYusuf** [comment] 2024-10-28 16:24
Thanks for raising the issue @DerkSchooltink, that PR has now been merged and will be included in a release later this week. I will close this issue now as it is a duplicate of #15145.

**Closed by KenanYusuf** 2024-10-28 16:24 UTC
Labels: bug 🐛, component: data grid, status: waiting for maintainer
