### ISSUE TITLE
onResize and onResizeCapture error in GridActionsCellItem

### ISSUE THREAD

**Issue by karolis-666** [mui/mui-x#8011] opened 2023-02-22 13:50 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Import <GridActionsCellItem /> from "@mui/x-data-grid-pro"
2. Use <GridActionsCellItem />

### Current behavior 😯

Component `<GridActionsCellItem />` raises TS error, that props `onResize`, `onResizeCapture` and `nonce` are not provided. Proving them with values `undefined` raises erros in browser and our build.

### Expected behavior 🤔

No TS error when not using these props

### Context 🔦

Seems that this issue was fixed https://github.com/mui/material-ui/issues/35287 only for `<Popper />`, but not for `<GridActionsCellItem />`  as we also encountered issues with `<Popper />` that are now fixed

### Your environment 🌎

    "@mui/base": "^5.0.0-alpha.90",
    "@mui/icons-material": "^5.8.4",
    "@mui/lab": "^5.0.0-alpha.86",
    "@mui/material": "^5.11.10",
    "@mui/styles": "^5.8.4",
    "@mui/system": "^5.8.4",
    "@mui/x-data-grid": "^5.12.2",
    "@mui/x-data-grid-premium": "^5.17.24",
    "@mui/x-data-grid-pro": "^5.17.24",
    "@mui/x-date-pickers-pro": "^5.0.0-alpha.7",
    "@mui/x-license-pro": "^5.13.1",
    "@types/react": "^17.0.47",
    "react": "^17.0.2",

### Order ID 💳 (optional)

46744

**Comment by bagoette** [comment] 2023-03-28 21:11
This same issue appears to be on the components `GridPagination` and `GridToolbarDensitySelector`

**Comment by jacksonlauder** [comment] 2023-04-04 22:17
This issue also appears with `GridToolbarColumnsButton`

**Comment by cherniavskii** [comment] 2023-04-07 11:20
Can anyone provide a reproduction example for this issue?
I tried to reproduce it using `react@17` and `@types/react@17`, but don't see any errors here: https://codesandbox.io/s/nifty-rosalind-xvxju4?file=/index.tsx

**Comment by karolis-666** [comment] 2023-04-07 12:05
Codesandbox can't find `@mui/x-data-grid-premium` package, but here is link anyways: https://codesandbox.io/s/admiring-yalow-76xglk?file=/index.tsx

Issue can be seen using premium or pro package

**Comment by cherniavskii** [comment] 2023-04-07 14:51
@karolis-666 I've forked your sandbox, installed `@mui/x-data-grid-premium`, but there are no TS errors: https://codesandbox.io/s/confident-hooks-50b6jh?file=/index.tsx

<img width="586" alt="Screenshot 2023-04-07 at 16 42 39" src="https://user-images.githubusercontent.com/13808724/230627959-36928551-2da1-48a6-ac90-f98512ff4628.png">

Same in my local project with the same setup:

<img width="532" alt="Screenshot 2023-04-07 at 16 47 31" src="https://user-images.githubusercontent.com/13808724/230628599-26fc16a3-2901-4e83-902d-7eabe783ee1c.png">

We need a reproduction to take an action on it.
Can you setup a repo with a reproduction example maybe?

**Comment by karolis-666** [comment] 2023-04-11 13:35
I setup repo, but while setting it up encountered other TS errors with same component in question.
Link: https://github.com/karolis-666/mui-1

**Comment by cherniavskii** [comment] 2023-04-28 15:26
Since the issue is solved in v6, I'm going to close this issue as there's no action to be taken on our end.

**Closed** 2023-04-28 15:26 UTC
Labels: component: data grid, typescript, v5.x

**Comment by nouman91** [comment] 2023-05-30 22:09
I am using version 5 and I can't upgrade, can we do a bug fix for v5?
