### ISSUE TITLE
[DataGridPro] can't use TextField in header

### ISSUE THREAD

**Issue by mnavoizat** [mui/mui-x#3599] opened 2022-01-12 09:06 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In case you customize the DataGrid header with renderHeader and render a TextField, the TextField does not work, it is impossible to change its value.

### Expected behavior 🤔

It should be possible to change TextField value.

### Steps to reproduce 🕹

Repro: [link to code sandbox](https://codesandbox.io/s/renderheadergrid-material-demo-forked-kk2jb)

Steps:

1. try to write something in the TextField in the header --> not possible

### Context 🔦

I need custom TextFields in the header to perform a custom filtering.

### Your environment 🌎

see code sandbox

### Order ID 💳 (optional)

34462

**Comment by igor-serzhan** [comment] 2022-01-13 09:10
I think this bug was introduced in this PR https://github.com/mui-org/material-ui-x/pull/3275/, but not sure

**Comment by alexfauquette** [comment] 2022-01-14 11:21
Well done @igor-serzhan 
The bug seems to come from this `event.preventdefaults()`
https://github.com/alexfauquette/material-ui-x/blob/e2376d22afba27f7aa32be49e30786532a75b2d0/packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts#L164

Before it was applied to navigation keys, to prevent the page to scroll when pressing an arrow key. Now it is applied to every key, preventing the input text to be filled

**Comment by wahajStar** [comment] 2022-01-14 13:24
may be this one would help you last 3 comment 
I also face same issue
[link](https://github.com/mui-org/material-ui-x/issues/2842)

**Comment by alexfauquette** [comment] 2022-01-14 14:39
@mnavoizat If you need a quick fix, you can stop the propagation of the keyDown event
https://codesandbox.io/s/renderheadergrid-material-demo-forked-lwlw5?file=/demo.tsx

**Comment by jaballogian** [comment] 2022-01-17 08:09
I also face the same problem here
https://codesandbox.io/s/stackoverflow-mui-data-grid-render-header-xmwf0?file=/src/App.js

**Comment by alexfauquette** [comment] 2022-01-17 09:06
@jaballogian Your problem is not related to this issue. The solution 2 provided in the StackOverflow link you provided would solve your problem

**Comment by jaballogian** [comment] 2022-01-17 09:28
> @jaballogian Your problem is not related to this issue. The solution 2 provided in the StackOverflow link you provided would solve your problem

hello @alexfauquette 
I have updated my comment above, sorry no to mention it before.
If you click the filter icon in the top right of the `Data Grid` component, the `Text Field` components in the `Data Grid` header will appear.

**Comment by alexfauquette** [comment] 2022-01-17 10:36
@jaballogian 
Your problem is that you control the input from its parent. As you can see, when the `onChange` and `value` props are commented your problem disappears.

You can make your input controllable by defining it outside of its parent as explained in your StackOverflow link.

See the email filter input : https://codesandbox.io/s/stackoverflow-mui-data-grid-render-header-forked-jbkgt?file=/src/App.jsx

**Comment by jaballogian** [comment] 2022-01-18 02:11
> @jaballogian Your problem is that you control the input from its parent. As you can see, when the `onChange` and `value` props are commented your problem disappears.
> 
> You can make your input controllable by defining it outside of its parent as explained in your StackOverflow link.
> 
> See the email filter input : https://codesandbox.io/s/stackoverflow-mui-data-grid-render-header-forked-jbkgt?file=/src/App.jsx

wow great, you're right about defining the controlled components outside of its parent
thanks a lot

**Comment by oliviertassinari** [comment] 2022-01-20 13:48
This one feels like a regression, I recall we worked on this problem with @DanailH in the past https://github.com/mui-org/material-ui-x/pulls?q=is%3Apr+author%3ADanailH+is%3Aclosed+input

**Comment by oliviertassinari** [comment] 2022-01-29 18:45
@alexfauquette I knew I had already seen something on this problem. A duplicate of #1915?

**Closed** 2022-03-02 14:14 UTC
Labels: bug 🐛, component: data grid
