### ISSUE TITLE
[data grid] Uploading files to mui x datagrid making it understand that cell is updated after file upload

### ISSUE THREAD

**Issue by catdalf** [mui/mui-x#12011] opened 2024-02-09 13:31 UTC
I have 2 columns that are for file upload. I have used 
const FileUploadCell = ({ onChange, field, id }) => (
  <input type="file" onChange={(event) => onChange(event, field, id)} name={field} accept=".pdf, .doc, .docx, .xls, .xlsx, .csv" required />
);
this const to assign it to columns. Under my fields i use
renderCell: (params) =>
<FileUploadCell field={params.field} id={params.id} onChange={handleFileChange} />
this code to create a custom cell which is for file uploading. However row never gets updated after i make the file upload. I also need to save this file to database but since the row does not even recognize this change in react side i also can not send it to backend side to save it to database.

**Comment by michelengelen** [comment] 2024-02-12 08:46
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

**Comment by catdalf** [comment] 2024-02-13 08:25
I guess i have solved this via this code:
const handleFileChange = (event, params, field) => {
  event.persist();
  const file = event.target.files[0];
  console.log('File changed:', file);

  
  params.api.updateRows([{ id: params.id, [field]: file }]);
};

{
          field: 'datasheet',
          headerName: 'Datasheet',
          width: 150,
          headerAlign: 'center',
          renderCell: (params) => {
            return (
              <input
                type="file"
                onChange={(event) => handleFileChange(event, params, 'Datasheet')}
                name="Datasheet"
                accept=".pdf, .doc, .docx, .xls, .xlsx, .csv"
                required
              />
            );
          },
        },
now when i upload the file in cell i can see that row is being updated. Previously the value i see related to datasheet column was this -> "" now i can see the file related properties.

**Comment by michelengelen** [comment] 2024-02-13 14:36
Great! Is this resolved for you now?

**Comment by catdalf** [comment] 2024-02-14 08:17
I guess it is resolved. However can i ask something related to pagination?
I know that in MIT version one page can hold at most 100 rows. How about when it comes to number of pages? Can i have unlimited number of pages in my mui x datagrid?

**Comment by michelengelen** [comment] 2024-02-21 15:20
> I guess it is resolved. However can i ask something related to pagination? I know that in MIT version one page can hold at most 100 rows. How about when it comes to number of pages? Can i have unlimited number of pages in my mui x datagrid?

Yes, there are no limitations on the number of pages afaik.

Since the original issue is resolved I will close this now. Thanks! 🙇🏼

**Closed by michelengelen** 2024-02-21 15:20 UTC
Labels: component: data grid
