### ISSUE TITLE
[docs] Searching for `KeyboardDatePicker` brings no result.

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#10702] opened 2023-10-17 13:56 UTC
## Summary

`@material-ui/pickers` (but also some competitors) used to have a`KeyboardDatePicker`.

We addressed the removal of the component on our [migration guide](https://mui.com/material-ui/guides/pickers-migration/#imports). But Algolia can't find the references on our code snippets, and therefore people searching for this component won't find anything and might get lost during migration.

We may need to have a specific section using this name (perhaps under a FAQ page) so it can be found by Algolia and forwarded to fields.

**Search keywords**: 
KeyboardDatePicker

**Comment by noraleonte** [comment] 2023-11-28 11:21
Duplicate of https://github.com/mui/mui-x/issues/10887

**Closed by noraleonte** 2023-11-28 11:21 UTC
Labels: docs, duplicate, component: pickers
