### ISSUE TITLE
[charts][ESM] `@mui/x-charts` does not work with jest

### ISSUE THREAD

**Issue by Notalifeform** [mui/mui-x#11568] opened 2024-01-03 19:15 UTC
### The problem in depth 🔍

Link to  example: https://github.com/rocsys/mui-x-charts-jest-issue-minimal-reproduction/

Steps:
1. run `yarn test --watchAll=false `

jest will fail with
```
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/rbakker/work/rocsys/code/t/test-mui-chart/node_modules/d3-scale/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export {
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { ChartContainer, BarPlot } from '@mui/x-charts';
        | ^
      2 |
      3 | const uData = [4000, 3000, 2000, 2780, 1890, 2390, 3490];
      4 | const xLabels = [

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/@mui/x-charts/context/CartesianContextProvider.js:11:16)
      at Object.<anonymous> (node_modules/@mui/x-charts/context/index.js:18:33)
      at Object.<anonymous> (node_modules/@mui/x-charts/index.js:24:16)
      at Object.<anonymous> (src/TinyBarChart.tsx:1:1)
      at Object.<anonymous> (src/App.tsx:4:1)
      at Object.<anonymous> (src/App.test.tsx:3:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.677 s

```

I attempted to  transpile the mui/x-chart module, but it does not seem to work?

https://github.com/rocsys/mui-x-charts-jest-issue-minimal-reproduction/tree/feature/attempt-to-transpile

our project uses without any issue:
```
   "@mui/icons-material": "^5.14.18",
    "@mui/material": "^5.14.18",
    "@mui/x-data-grid-pro": "^6.18.1",
    "@mui/x-date-pickers-pro": "^6.18.1",
    "@mui/x-license-pro": "^6.10.2",
```
but jest breaks when adding

```
    "@mui/x-charts": "^6.18.4",
```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: macOS 14.0
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.1/bin/yarn
    npm: 9.7.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Edge: Not Found
    Safari: 17.0
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.29 
    @mui/core-downloads-tracker:  5.15.2 
    @mui/material: ^5.15.2 => 5.15.2 
    @mui/private-theming:  5.15.2 
    @mui/styled-engine:  5.15.2 
    @mui/styles: ^5.15.2 => 5.15.2 
    @mui/system:  5.15.2 
    @mui/types:  7.2.11 
    @mui/utils:  5.15.2 
    @mui/x-charts: ^6.18.4 => 6.18.4 
    @types/react: ^18.0.0 => 18.2.46 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.4.2 => 4.9.5 

```
</details>

### Contextn

Related issue: https://github.com/jestjs/jest/issues/9430

**Search keywords**: x-charts jest
**Order ID**: 70120

**Comment by michelengelen** [comment] 2024-01-04 13:11
@alexfauquette it seems `d3-scale` uses modules in its build files. Any idea how we can support that?

**Comment by alexfauquette** [comment] 2024-01-04 13:29
Seems similar to https://github.com/mui/mui-x/issues/9826#issuecomment-1658333978

I also found other issues on this topic, but did not manage to fix the reproduction example with them

- https://github.com/d3/d3-interpolate/issues/96
- https://github.com/jestjs/jest/issues/12036

**Comment by michelengelen** [comment] 2024-01-04 14:26
Hi @Notalifeform could you try using this fix: https://github.com/d3/d3-interpolate/issues/96#issuecomment-885372126 please?

**Comment by Notalifeform** [comment] 2024-01-04 16:19
> Hi @Notalifeform could you try using this fix: [d3/d3-interpolate#96 (comment)](https://github.com/d3/d3-interpolate/issues/96#issuecomment-885372126) please?

Hi @michelengelen ,

Thanks for getting back to me.

I did try to transpile the module as in this brach, but it did not help:

https://github.com/rocsys/mui-x-charts-jest-issue-minimal-reproduction/pull/1/files

moving the config to package.json did not help either:

https://github.com/rocsys/mui-x-charts-jest-issue-minimal-reproduction/pull/2/files

**Comment by michelengelen** [comment] 2024-01-09 09:16
@alexfauquette I did assign this to you to keep track of it. Could you comment here when the addition of tests provides a solution for this? Thanks! 🙇🏼

**Comment by leonid1976** [comment] 2024-01-25 01:59
My way to fix the issue
1) Editing  node_modules/@mui/x-charts/package.json with follow changes (plus patch)
   "exports": {
    ".": {
      **"require": "./index.js",**
      "types": "./index.d.ts",
      "import": "./esm/index.js",
      "default": "./esm/index.js"
    },
    "./*": {
      **"require": "./*",**
      "types": "./*/index.d.ts",
      "import": "./esm/*/index.js",
      "default": "./esm/*/index.js"
    }
  },
  2) in jest.config.js
        moduleNameMapper: {
        '^d3-shape$': '<rootDir>/node_modules/d3-shape/dist/d3-shape.min.js',
        '^d3-path$': '<rootDir>/node_modules/d3-path/dist/d3-path.min.js',
        '^d3-scale$': '<rootDir>/node_modules/d3-scale/dist/d3-scale.min.js',
        '^d3-array$': '<rootDir>/node_modules/d3-array/dist/d3-array.min.js',
        '^d3-interpolate$': '<rootDir>/node_modules/d3-interpolate/dist/d3-interpolate.min.js',
        '^d3-color$': '<rootDir>/node_modules/d3-color/dist/d3-color.min.js',
        '^d3-format$': '<rootDir>/node_modules/d3-format/dist/d3-format.min.js',
        '^d3-time$': '<rootDir>/node_modules/d3-time/dist/d3-time.min.js',
        '^d3-time-format$': '<rootDir>/node_modules/d3-time-format/dist/d3-time-format.min.js',
      },
3) mock window.matchMedia.addEventListener.

**Comment by GazitLior1** [comment] 2024-02-19 13:18
I had the same issue and adding this mock:
```
jest.mock("@mui/x-charts", () => ({ 
  BarChart: jest.fn().mockImplementation(({ children }) => children)
}));
```

to the tests solved it 
(from https://stackoverflow.com/questions/77202795/mui-x-charts-error-syntaxerror-unexpected-token-export)

**Comment by cstephens-cni** [comment] 2024-02-27 14:32
This in my jest config got me going again,  but obviously it's alot
```
transformIgnorePatterns: [
    '/node_modules/(?!@mui/x-charts|@mui/material|@babel/runtime|d3-(color|format|interpolate|scale|shape|time|time-format|path|array)|internmap)',
  ],
```

**Comment by Hosoo8861** [comment] 2024-04-16 08:25
SyntaxError: Unexpected token 'export'  does not work with remix.run

**Comment by cstephens-cni** [comment] 2024-05-15 20:15
> This in my jest config got me going again, but obviously it's alot
> 
> ```
> transformIgnorePatterns: [
>     '/node_modules/(?!@mui/x-charts|@mui/material|@babel/runtime|d3-(color|format|interpolate|scale|shape|time|time-format|path|array)|internmap)',
>   ],
> ```

I just updated to v7 charts had to add a few more. 

add "robust-predicates|delaunator"

**Comment by TVDharma** [comment] 2024-05-21 22:26
Currently, I am having the same problem with my project and I followed all the cases mentioned above but my problem is not resolved. can someone and @alexfauquette  help me out with this?

used:
@mui/x-chart: 7.1.0
"@mui/icons-material": "^5.15.19",
"@mui/material": "^5.14.18",


I am using babel-plugin-module-resolver to resolve the absolute path in my project. so my file looks like

module.exports: {
root:["./src"]
plugins: {
["module-resolver":{
alias: {
//some other alias
"@mui/x-charts/Piechart$":"./node_modules/@mui/x-charts/esm/PieChart/index.js"
}
}]
}
}


jest config file:
// some other configuration here
transformIgnorePatterns: [
    '/node_modules/(?!@mui/x-charts|@mui/material|@babel/runtime|d3-(color|format|interpolate|scale|shape|time|time-format|path|array)|internmap)',
  ],


setup ts file:
//jsdom here
jest.mock("@mui/x-charts", () => ({ 
  PieChart: jest.fn().mockImplementation(({ children }) => children)
}));

**Comment by TVDharma** [comment] 2024-06-04 01:00
> I had the same issue and adding this mock:
> 
> ```
> jest.mock("@mui/x-charts", () => ({ 
>   Piechart: jest.fn().mockImplementation(({ children }) => children)
> }));
> ```
> 
> to the tests solved it (from https://stackoverflow.com/questions/77202795/mui-x-charts-error-syntaxerror-unexpected-token-export)

Dear Team and @alexfauquette 

The above solution resolved the export token issue encountered while running Jest test cases for my project. However, one component in my project extensively uses the `PieChart`. When attempting to run Jest for that component, I encountered a few more issues: Could you please review and guide this matter?

Warning React.jsx type is invalid --expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

and also 

console.warn
{
componentStack: '\n' + 
+ at div\n'  +
+ (path like ../a/b.js)\n' +
+ at div\n'  +
+ at div\n'  +
+ (path like ../a/b.js)\n' +
+ at div\n'  +
+ at div\n'  +
+ (path like ../a/b.js)\n' +
-----similary----- and it stopped in one file


console.error
the above error occurred in the <div> component: 

at div
at metircvalue (path)
at div
at div
at forward Ref (path)
at div
at forward Ref (path)
at div
at forward Ref (path)
at div
at forward Ref (path)
at div
at fontcl
at div
at forward Ref (path)
at div
at forward Ref (path)
--------stopeed at one file-------
React fill try to recreate this component tree from scratch using this error boundary you provided, e.

**Comment by TVDharma** [comment] 2024-06-05 05:51
> > I had the same issue and adding this mock:
> > ```
> > jest.mock("@mui/x-charts", () => ({ 
> >   Piechart: jest.fn().mockImplementation(({ children }) => children)
> > }));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the tests solved it (from https://stackoverflow.com/questions/77202795/mui-x-charts-error-syntaxerror-unexpected-token-export)
> 
> Dear Team and @alexfauquette
> 
> The above solution resolved the export token issue encountered while running Jest test cases for my project. However, one component in my project extensively uses the `PieChart`. When attempting to run Jest for that component, I encountered a few more issues: Could you please review and guide this matter?
> 
> Warning React.jsx type is invalid --expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> and also
> 
> console.warn { componentStack: '\n' +
> 
> * at div\n'  +
> * (path like ../a/b.js)\n' +
> * at div\n'  +
> * at div\n'  +
> * (path like ../a/b.js)\n' +
> * at div\n'  +
> * at div\n'  +
> * (path like ../a/b.js)\n' +
>   -----similary----- and it stopped in one file
> 
> console.error the above error occurred in the
> 
> component:
> at div at metircvalue (path) at div at div at forward Ref (path) at div at forward Ref (path) at div at forward Ref (path) at div at forward Ref (path) at div at fontcl at div at forward Ref (path) at div at forward Ref (path) --------stopeed at one file------- React fill try to recreate this component tree from scratch using this error boundary you provided, e.

Dear @cstephens-cni @Notalifeform and @oliviertassinari and @alexfauquette and @michelengelen, Could anyone in this thread please reply to help me with this? I am stuck in the middle. Thanks.

**Comment by alexfauquette** [comment] 2024-06-05 07:10
@TVDharma Without a minimal reproduction example, it's hard to say why the workaround does not work for you

**Comment by si-saaref** [comment] 2024-07-10 04:52
`
 Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    Chart-example\node_modules\@babel\runtime\helpers\esm\extends.js:10
    export { _extends as default };
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      10 | import {chartsGridClasses, BarChartProps} from '@mui/x-charts';
      11 | import {axisClasses} from '@mui/x-charts/ChartsAxis';
    > 12 |
         | ^
      13 | export default function CustomChart({
      14 |   titleChart,
      15 |   type,

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (node_modules/@mui/x-charts/esm/BarChart/BarChart.js:11:57)
      at Object.<anonymous> (node_modules/@mui/x-charts/esm/BarChart/index.js:5:14)
`
The d3 bug was resolved, but I encounter another bug..
Would you mind to help me to figure out how to solve this?

**Comment by onkartme** [comment] 2024-07-11 04:18
Still facing the issue with BarChart. 

`SyntaxError: Unexpected token 'export'

      1 | import { Box,Typography } from "@mui/material";
    > 2 | import { BarChart } from "@mui/x-charts/BarChart";
        | ^`

here is my jest config

`module.exports = {
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["<rootDir>/setupTests.ts"],
  transform: {
    "^.+\\.(js|jsx|ts|tsx)$": "babel-jest",
  },
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
  },
  transformIgnorePatterns: [
    "/node_modules/(?!@mui/x-charts|@mui/material|@babel/runtime)",
  ],
};`

**Comment by konrazem** [comment] 2024-07-16 07:09
We have the same issue with ChartsAxis, as there is an export in ESM module

```log
..  \node_modules\@mui\x-charts\esm\ChartsAxis\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './ChartsAxis';
                                                                                                                                            ^^^^^^

    SyntaxError: Unexpected token 'export'

      2 |
      3 | import { Box } from '@mui/material';
    > 4 | import { axisClasses } from '@mui/x-charts/ChartsAxis';
        | ^
      5 | import { LineChart } from '@mui/x-charts/LineChart';
      6 |
      7 | import { ChartLegend } from '@uniteam/iamu-framework';
```

None of the given solutions did solve it 😔

**Comment by alexfauquette** [comment] 2024-07-16 07:34
@konrazem @onkartme Could you test if by using the following package version in your `package.json` the problem get solved?

```
"@mui/x-charts": "https://pkg.csb.dev/mui/mui-x/commit/b7ffe8e1/@mui/x-charts",
"@mui/x-charts-vendor": "https://pkg.csb.dev/mui/mui-x/commit/b7ffe8e1/@mui/x-charts-vendor",
```

Those are preview of https://github.com/mui/mui-x/pull/13608

**Comment by konrazem** [comment] 2024-07-16 08:57
@onkartme  thank you for taking care of this issue. Unfortunatelly it didn't help. 

The only solution that is working right now for as is to add this conditions to moduleNameMapper

```
moduleNameMapper: {
      //////////////////////////////////////
      /// X-CHARTS
      //////////////////////////////////////
      '@mui/x-charts': '<rootDir>/node_modules/@mui/x-charts/index.js',

      //////////////////////////////////////
      /// D3 BASED ON X-CHARTS
      //////////////////////////////////////
      '^d3-array$': '<rootDir>/node_modules/d3-array/dist/d3-array.min.js',
      '^d3-color$': '<rootDir>/node_modules/d3-color/dist/d3-color.min.js',
      '^d3-delaunay$':
        '<rootDir>/node_modules/d3-delaunay/dist/d3-delaunay.min.js',
      '^d3-format$': '<rootDir>/node_modules/d3-format/dist/d3-format.min.js',
      '^d3-interpolate$':
        '<rootDir>/node_modules/d3-interpolate/dist/d3-interpolate.min.js',
      '^d3-path$': '<rootDir>/node_modules/d3-path/dist/d3-path.min.js',
      '^d3-scale$': '<rootDir>/node_modules/d3-scale/dist/d3-scale.min.js',
      '^d3-shape$': '<rootDir>/node_modules/d3-shape/dist/d3-shape.min.js',
      '^d3-time$': '<rootDir>/node_modules/d3-time/dist/d3-time.min.js',
      '^d3-time-format$':
        '<rootDir>/node_modules/d3-time-format/dist/d3-time-format.min.js',
      //////////////////////////////////////
    },
```

**Comment by alexfauquette** [comment] 2024-07-16 09:46
@konrazem could you share a reproduction of your issue? Because your issue is probably different than the one in this issue, because using the PR commit solves the intial reproduction

**Comment by onkartme** [comment] 2024-07-16 23:57
> "@mui/x-charts": "https://pkg.csb.dev/mui/mui-x/commit/b7ffe8e1/@mui/x-charts",
> "@mui/x-charts-vendor": "https://pkg.csb.dev/mui/mui-x/commit/b7ffe8e1/@mui/x-charts-vendor",

hey @alexfauquette 

unfortunately this didn't solve the issue. The issue still there. :(

**Comment by alexfauquette** [comment] 2024-07-17 09:13
My bad, I doubled check and it seems the ix is broken. The vendor package is empty 🙈

**Comment by tonyhallett** [comment] 2024-07-23 11:24
This is really poor.

**Comment by konrazem** [comment] 2024-07-24 05:21
### I think it is strongly related to [this issue](https://stackoverflow.com/questions/69226759/jest-unexpected-token-export-when-using-d3). 

As I mentioned, we were able to fix our tests with this solution

> @alexfauquette thank you for taking care of this issue. Unfortunatelly it didn't help.
> 
> The only solution that is working right now for as is to add this conditions to our jest.config.js to moduleNameMapper
> 
> ```
> moduleNameMapper: {
>       //////////////////////////////////////
>       /// X-CHARTS
>       //////////////////////////////////////
>       '@mui/x-charts': '<rootDir>/node_modules/@mui/x-charts/index.js',
> 
>       //////////////////////////////////////
>       /// D3 BASED ON X-CHARTS
>       //////////////////////////////////////
>       '^d3-array$': '<rootDir>/node_modules/d3-array/dist/d3-array.min.js',
>       '^d3-color$': '<rootDir>/node_modules/d3-color/dist/d3-color.min.js',
>       '^d3-delaunay$':
>         '<rootDir>/node_modules/d3-delaunay/dist/d3-delaunay.min.js',
>       '^d3-format$': '<rootDir>/node_modules/d3-format/dist/d3-format.min.js',
>       '^d3-interpolate$':
>         '<rootDir>/node_modules/d3-interpolate/dist/d3-interpolate.min.js',
>       '^d3-path$': '<rootDir>/node_modules/d3-path/dist/d3-path.min.js',
>       '^d3-scale$': '<rootDir>/node_modules/d3-scale/dist/d3-scale.min.js',
>       '^d3-shape$': '<rootDir>/node_modules/d3-shape/dist/d3-shape.min.js',
>       '^d3-time$': '<rootDir>/node_modules/d3-time/dist/d3-time.min.js',
>       '^d3-time-format$':
>         '<rootDir>/node_modules/d3-time-format/dist/d3-time-format.min.js',
>       //////////////////////////////////////
>     },
> ```

**Comment by sterlingdcs-damian** [comment] 2024-07-24 12:42
@https://github.com/alexfauquette using 
```
 "@mui/x-charts": "https://pkg.csb.dev/mui/mui-x/commit/b7ffe8e1/@mui/x-charts",
    "@mui/x-charts-vendor": "https://pkg.csb.dev/mui/mui-x/commit/b7ffe8e1/@mui/x-charts-vendor",
   
   ```
   doesnt fix it for me ,. i get
   
   ```
   Test suite failed to run

    Cannot find module '@mui/x-charts-vendor/d3-scale' from 'node_modules/@mui/x-charts/context/CartesianProvider/computeValue.js'

    Require stack:
      node_modules/@mui/x-charts/context/CartesianProvider/computeValue.js
      node_modules/@mui/x-charts/context/CartesianProvider/index.js
      node_modules/@mui/x-charts/BarChart/BarPlot.js
      node_modules/@mui/x-charts/BarChart/BarChart.js
      node_modules/@mui/x-charts/BarChart/index.js
      src/app-project/features/cost-plan-lifecycle/presentation/components/cost-summary/CostSummaryBarChart.tsx
```

**Comment by alexfauquette** [comment] 2024-07-24 13:27
@sterlingdcs-damian You copied the one with `b7ffe8e1` commit which as [explained here](https://github.com/mui/mui-x/issues/11568#issuecomment-2232826766) are broken (due to missing `.npmignore` file)


Could you try with either 
```
// The initial working fix

"@mui/x-charts": "https://pkg.csb.dev/mui/mui-x/commit/0a35124a/@mui/x-charts",
"@mui/x-charts-vendor": "https://pkg.csb.dev/mui/mui-x/commit/0a35124a/@mui/x-charts-vendor",

// The last step of the PR

"@mui/x-charts": "https://pkg.csb.dev/mui/mui-x/commit/fca1af4e/@mui/x-charts",
"@mui/x-charts-vendor": "https://pkg.csb.dev/mui/mui-x/commit/fca1af4e/@mui/x-charts-vendor",
```

**Comment by LukasTy** [comment] 2024-07-24 14:31
This is where https://github.com/mui/material-ui/pull/42984 would provide a bit nicer UX/DX for users in such cases with the ability to reference packages by GH PR number. 🤔 
cc @oliviertassinari @alexfauquette

**Comment by alexfauquette** [comment] 2024-07-24 15:22
For users, yes but not for developers. Being able to retry the build of previous commits helped me to narrow down which commit introduced the regression

**Comment by LukasTy** [comment] 2024-07-24 15:31
> For users, yes but not for developers. Being able to retry the build of previous commits helped me to narrow down which commit introduced the regression

You can use [both identifiers](https://blog.stackblitz.com/posts/pkg-pr-new/#what-is-pkgprnew). 😉

**Closed** 2024-07-29 15:22 UTC
Labels: test, external dependency, support: commercial, component: charts

**Comment by alexfauquette** [comment] 2024-07-29 16:07
The fix will be available in the next release at the end of the week

**Comment by serg-kirienko-d8corp** [comment] 2025-04-16 15:51
Stll doesn't working for me:

![Image](https://github.com/user-attachments/assets/b98cc262-6b4c-4628-9c78-55a3873dd961)

**Comment by LukasTy** [comment] 2025-04-17 06:32
@serg-kirienko-d8corp, which package version are you using?

**Comment by jesscleeCH** [comment] 2025-12-09 21:36
Hello, I seem to be getting the same issue on version 8.21.0. I've tried to add the fixes suggested above in my jest config but it doesn't seem to be fixing the errors.

<img width="1368" height="971" alt="Image" src="https://github.com/user-attachments/assets/eca40d20-2e54-469c-a568-53ba9831b64d" />

**Comment by bernardobelchior** [comment] 2025-12-10 12:15
@jesscleeCH opened a PR to fix this issue [here](https://github.com/mui/mui-x/pull/20610). You can install `@mui/x-charts` using `npm i https://pkg.pr.new/mui/mui-x/@mui/x-charts@7a83f3f` for the time being. We should have a release that fixes this issue by this week.
