### ISSUE TITLE
[DataGrid] Issue in datagrid drop down options z-index

### ISSUE THREAD

**Issue by gaurav7576** [mui/mui-x#11418] opened 2023-12-15 07:05 UTC
### Steps to reproduce

Link to live example: (required)

Steps:
1. Open https://mui.com/x/react-data-grid/
2. Scroll to Commercial versions | Pro Plan
3. Click on Unit Price Currency
4. Scroll left/right - Options will overlap with other sections and not hiding with datagrid

### Current behavior

In data grid, editable drop down options is not hiding when parent column is hiding.
Overlapping with other right or left components not part of data grid.

### Expected behavior

During scroll, options of select drop down will hide in data grid with parent select box.

### Context

We are using MUI-X and option is overlapping with other components blocking to perform other operations not part of data grid.

### Your environment

  System:
    OS: Windows 11 10.0.22621
  Binaries:
    Node: 14.21.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (119.0.2151.97)
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/icons-material: ^5.14.14 => 5.14.19 
    @types/react:  18.2.42
    react: ^17.0.0 => 17.0.2
    react-dom: ^17.0.0 => 17.0.2

**Search keywords**: datagrid editable dropdown z-index
**Order ID**: 59921

**Comment by michelengelen** [comment] 2023-12-18 09:01
Hey @gaurav7576 ... I can confirm this bug. I know that the team is working on improving scrolling in general and this might already be fixed with that effort and to be released in `v7`. 

@romgrk could you check if this still happens with the new scrolling approach? If not we can move this to the board. Thanks! 🙇🏼

**Comment by michelengelen** [comment] 2023-12-18 09:06
@gaurav7576 one possible workaround for your implementation could be to set the `disablePortal` prop on the `AutoComplete` component (if you are using `@mui/material/Autocomplete`)

**Comment by gaurav7576** [comment] 2023-12-18 11:00
Dear Concerned,

Already tried disablePortal property in autocomplete but it disables
complete drop down.

Regards,
Gaurav

**Comment by michelengelen** [comment] 2023-12-18 12:57
@gaurav7576 here is [a little demo](https://codesandbox.io/p/sandbox/jolly-cherry-zgn4kq?file=%2Fsrc%2FDemo.tsx%3A12%2C6) on how that can look like. It is basically the same as the demo in the docs. I just changed the props a bit to also accept `disablePortal` and now it works. This should work the same with the default `AutoComplete` component

**Comment by romgrk** [comment] 2023-12-18 21:00
Sorry I don't understand the issue, can you clarify how to reproduce or show screenshots? The preview deployment for that PR is here if you want to verify it directly: https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/#pro-plan

**Comment by michelengelen** [comment] 2023-12-19 08:48
Hey @romgrk I took the liberty to show it in a short video.

https://github.com/mui/mui-x/assets/32863416/b2a87bbd-2b99-4643-a5c9-df07a439622a

**Comment by romgrk** [comment] 2023-12-19 11:03
This will not be handled by the sticky PR.

@mui/xgrid What behavior do we expect in the example above? I see a few ways to fix things but it could be messy. It could be adding a parent with only `overflow-x`, and put the portal inside the grid (but still outside the viewport). It could be adding a [`clip-path`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) that covers the vertical region of the grid only. For the headers' menu, we close any popover when the user starts scrolling.

**Comment by michelengelen** [comment] 2023-12-19 12:27
> This will not be handled by the sticky PR.

I suspected that much, but wanted to ask anyways.

> @mui/xgrid What behavior do we expect in the example above? 

IMO we should probably copy the behavior from the header menus. This feels the most logical to me, since when I am scrolling away from the dropdown I normally don't want to interact with it anyways. On the other hand: users might want to scroll away to look for additional information and come back to select an option.
So we need a tradeoff for one use-case and the first option seems to me as the better one, since it ...
1. feels more like what I would expect
2. will naturally "prevent" this bug from appearing again

WDYT?

**Comment by cherniavskii** [comment] 2023-12-19 22:21
Interestingly, the issue is not reproducible with the cells that use the `Select` component - try editing the `Status` column cells and scroll.
The difference is that `Select` uses [`Popover`](https://mui.com/material-ui/react-popover/) that blocks the scroll, while `Autocomplete` uses [`Popper`](https://mui.com/material-ui/react-popper/) that doesn't 🙂

Maybe there's a way for `Autocomplete` to block the scroll too?

**Comment by romgrk** [comment] 2023-12-19 23:34
But which behavior do we think is best? Let's first agree on that, then we can look for solutions. I'm not sure what's the best option, I think scrolling can be useful if the user needs to look at some information, so it would be nice to preserve that, but I'm not entirely sure what should happen to the popups.

On the select vs autocomplete, maybe it's because select's popup menu doesn't require user input anywhere else on the page while it's open, whereas autocomplete can be interacted with both in its input component and in its popup.

**Comment by cherniavskii** [comment] 2023-12-20 12:55
I find closing the popover on scroll the best option here

**Comment by michelengelen** [comment] 2023-12-20 16:54
> I find closing the popover on scroll the best option here

me too

**Comment by gaurav7576** [comment] 2023-12-21 05:48
Closing the popover is the only solution because not closing popover will drag over other component which may have primary buttons to work on screen.
We must block component inside provided space.

**Comment by gaurav7576** [comment] 2023-12-21 05:59
According to me, scrolling the popover is best option because we are using click to open and close. If we close it, we are performing click which user is not performing and system is working on behalf of user.
And we must hide popover so that it will not overlap over other component which may have primary actions to work on screen.
We must block component inside provided space.

**Comment by gaurav7576** [comment] 2023-12-21 06:00
@michelengelen Provided demo link [Demo Link](https://codesandbox.io/p/sandbox/jolly-cherry-zgn4kq?file=%2Fsrc%2FDemo.tsx%3A12%2C6) is working fine when scroll towards right but issue is there when scrolling towards left.

**Comment by michelengelen** [comment] 2023-12-21 08:01
> @michelengelen Provided [Demo Link](https://codesandbox.io/p/sandbox/jolly-cherry-zgn4kq?file=%2Fsrc%2FDemo.tsx%3A12%2C6) is working fine when scroll towards left but issue is there when scrolling towards right.

@gaurav7576 Pardon me. I forgot to set a certain modifier on the Popper props. I adjusted the [demo](https://codesandbox.io/p/sandbox/jolly-cherry-zgn4kq?file=%2Fsrc%2FrenderEditCurrency.tsx%3A88%2C73) and for additional reference: [Popper component docs](https://mui.com/material-ui/react-popper/) and [Popper API](https://mui.com/material-ui/api/popper/).

**Closed** 2023-12-28 08:24 UTC
Labels: component: data grid, status: waiting for author, plan: Pro, feature: Editing

**Comment by escbooster12-dev** [comment] 2025-02-28 10:28
Hello, I’m facing the same issue. Could someone reopen it and provide a solution?
