### ISSUE TITLE
DataGrid column resize called too many times and is too slow

### ISSUE THREAD

**Issue by yannours** [mui/mui-x#8168] opened 2023-03-07 16:50 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Hi, you can see the bug there -> https://codesandbox.io/s/data-grid-community-forked-j9eco9?file=/src/App.tsx

1. You toggle the button and it pop in a div that cause the datagrid to rerender a lot lot of times (it's even worst on our side).
2. I find out that it's about override theGrid Main width in % that trigger an unwanted behaviour to resize multiple time until it finally get the correct size, which is weird because it should be done in 2 iteration as it's done when the div pop out (toggle the button again).

regards,

### Current behavior 😯

DataGrid resize with lots and lots of call and is so slow that you can see it rerender a lot.

### Expected behavior 🤔

Should not rerender more than twice and should be done like in a few 100~1000ms like it does on expend.

### Context 🔦

Discussion started here https://github.com/mui/mui-x/issues/3894

It looks like it goes wild when we override the style of Mui-Main, I provide a code sandbox here https://codesandbox.io/s/data-grid-community-forked-j9eco9?file=/src/App.tsx

### Your environment 🌎

Running with latest version of DataGrid pro and Mui 6.

### Order ID or Support key 💳 (optional)

31461

**Comment by ddolcimascolo** [comment] 2023-03-07 20:01
Thx @yannours for opening this 👍

Premium customer here. I want to link this issue with #8128 which makes two regressions compared to v5.

I know you guys are busy, but I'd really appreciate updates on these issues.

Keep up the good work! 

Cheers,
David

**Comment by ddolcimascolo** [comment] 2023-03-08 12:10
Thx for the suggestion, we'll definitely try that!

**Comment by yannours** [comment] 2023-03-09 16:24
After a quick look override `.MuiDataGrid-root` instead of `.MuiDataGrid-main` does not trigger a resize at all, which is not what we want. We expect the Datagrid to fit the 100% or less, not expend out of the box.

**Comment by yannours** [comment] 2023-03-13 09:24
Ok so we end up with a user fix (that you can see in action here https://codesandbox.io/s/data-grid-community-forked-ywqgcz?file=/src/App.tsx

`"& .MuiDataGrid-main": {
    width: 0,
    minWidth: "95%"
  }`

We use it as a "hack" but it's working fine for us.

**Comment by cherniavskii** [comment] 2023-05-12 18:20
@yannours can you check out the latest release https://github.com/mui/mui-x/releases/tag/v6.4.0 ?
It seems to be fixed now: https://codesandbox.io/s/data-grid-community-forked-92zw7m

**Closed** 2023-05-19 18:23 UTC
Labels: component: data grid, status: needs more information, plan: Pro
