### ISSUE TITLE
[LocalizationProvider] changing locale doesn't update DatePicker content

### ISSUE THREAD

**Issue by soolidtech** [mui/mui-x#5243] opened 2022-06-17 23:17 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Current behavior is visible in this example : [https://mui.com/x/react-date-pickers/localization/#date-engine-locale](https://mui.com/x/react-date-pickers/localization/#date-engine-locale)

- Open this codesandbox.
- Change DatePicker component by adding this prop `views={["year", "month"]}`
- Refresh CodeSandbox
- Swap language to fr
- content isn't updated, and remains in russian

![image](https://user-images.githubusercontent.com/96774530/174411472-3c974804-a5eb-4b49-a962-dfb47c23d46a.png)

### Expected behavior 🤔

after swaping locale,
i would expect to see 
![image](https://user-images.githubusercontent.com/96774530/174411556-b943bcf5-23ce-4dfd-8ac6-0045e9559e21.png)

### Steps to reproduce 🕹

Explained above

### Context 🔦

if you display a form with initial data, and then switch from a language to another, DatePicker content remains the same.
Which, I think, should not be the case.

### Your environment 🌎

Browser : Chrome  102.0.5005.115

<details>
  <summary><code>npx @mui/envinfo</code></summary>

 System:
    OS: Linux 4.19 Ubuntu 18.04.6 LTS (Bionic Beaver)
  Binaries:
    Node: 12.22.12 - /usr/bin/node
    Yarn: Not Found
    npm: 8.3.1 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: 11.9.3 => 11.9.3 
    @emotion/styled: 11.9.3 => 11.9.3 
    @mui/base:  5.0.0-alpha.85 
    @mui/icons-material: 5.8.4 => 5.8.4 
    @mui/material: 5.8.4 => 5.8.4 
    @mui/private-theming:  5.8.4 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.4 
    @mui/types:  7.1.4 
    @mui/utils:  5.8.4 
    @mui/x-data-grid: 5.12.1 => 5.12.1 
    @mui/x-date-pickers: 5.0.0-alpha.6 => 5.0.0-alpha.6 
    @types/react: 17.0.39 => 17.0.39 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.7.3 => 4.7.3 
</details>

**Comment by alexfauquette** [comment] 2022-06-20 09:50
The reproduction example:
https://codesandbox.io/s/localizeddatepicker-demo-mui-x-forked-vk285m?file=/demo.tsx

### The reason why

In the demo the `maskInput` is valid, so when you modify the locale, it updates the mask and so the input value is updated to match the new mask when you modify the locale

In your case, the `maskInput` is invalid because we do not support format with literal format (In your case months `Jun`). Since masked input is disabled, the user can do whatever he wants. Notice that as soon as you modify the date the format s called again


### Solutions

This should be fixed if we manage to support input format with literal

A simpler solution could be to generate a new input value when the locale is modified (if the provided date is a valid one of course)

**Comment by flaviendelangle** [comment] 2022-06-21 11:43
@alexfauquette I let you add the adequate labels

**Closed** 2022-08-09 11:43 UTC
Labels: new feature, l10n, component: pickers
