### ISSUE TITLE
[fields] The input loses focus after pressing on clear button

### ISSUE THREAD

**Issue by CyanoFresh** [mui/mui-x#12574] opened 2024-03-26 18:57 UTC
### Steps to reproduce

Link to live example: (required)
https://mui.com/x/react-date-pickers/date-picker/#clearing-the-value
Steps:
1. Type in some date
2. Press on clear button
3. Try to type again
4. Grey text (placeholder?) is shown and you couldn't type in numbers. Only for some amount of time (~2 seconds) or until some other random event - couldn't figure it out yet

Focusing on something else and focusing the field again helps

https://github.com/mui/mui-x/assets/4249082/abd2e69d-e474-43e4-af5c-727cdfc14e68

### Current behavior

Grey text (placeholder?) is shown and you couldn't type in new date

### Expected behavior

Value is changable

### Context

Issue appeared after upgrading to v7.0.0 from ^6.19.2. Before upgrade everything works as expected

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser: latest Chrome
```
</details>

**Search keywords**: clear, focus lost, couldn't type

**Comment by LukasTy** [comment] 2024-03-27 11:30
Hello @CyanoFresh
Could you clarify if you have problems typing into the Field after the value is cleared?
Or is the problem that Field is no longer focused after clearing the value?

For me it seems that it is more of a visual problem, if I focus on the field after clearing it, the editing works, it's just that the section is not marked as selected.

In any case, there seems to be a regression in the behavior of re-focusing the field after it is cleared—it used to be the case in v6.

**Comment by CyanoFresh** [comment] 2024-03-27 11:35
@LukasTy I have problems typing in a new value after field is cleared. On the video you can see that placeholder mask is light-grey and I am trying to type - but no value is getting in.
Maybe that's related to the focus - I feel like field container is focused (label is animated to the top), but the actual text input is not focused

**Comment by LukasTy** [comment] 2024-03-27 11:53
@CyanoFresh Ok, I can confirm that this is quite a nasty bug.
After clearing the value, you can modify the newly focused input with arrows, but not numbers. 🙈

**Comment by c1oneman** [comment] 2024-03-27 21:53
We are having the same issue! Can not enter text into date pickers after clear when we tab into the date fields. The textfield does not fill the value "MM/DD/YYYY" like it normally does and the user can not type.

**Closed** 2024-03-28 09:09 UTC
Labels: regression, component: pickers, feature: Keyboard editing

**Comment by LukasTy** [comment] 2024-03-28 09:11
@CyanoFresh, @c1oneman the fix has been merged and will be released with the next version (today or tomorrow).

**Comment by c1oneman** [comment] 2024-03-28 18:42
Thank you!
