### ISSUE TITLE
[question] If you set one filter for a column, then disable the ability to set another filter for this column

### ISSUE THREAD

**Issue by mimaxm** [mui/mui-x#6006] opened 2022-09-02 13:12 UTC
### Order ID 💳

37162

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello!
We need the ability to change columns in the filter panel.
We don't want the user to get a "No results found" message if they didn't set the filters correctly.
If the user has already set one filter for this column, then prevent him from adding another filter for this column. This is needed when using the "And" linkOperator.
Tell me how can we do this?

### Your environment 🌎

System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 2.4.2 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: 11.7.1 => 11.7.1 
    @emotion/styled: 11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.74 
    @mui/icons-material: 5.5.1 => 5.5.1 
    @mui/lab: 5.0.0-alpha.75 => 5.0.0-alpha.75 
    @mui/material: 5.5.3 => 5.5.3 
    @mui/private-theming:  5.5.3 
    @mui/styled-engine:  5.5.2 
    @mui/styles: 5.5.3 => 5.5.3 
    @mui/system:  5.5.3 
    @mui/types:  7.1.3 
    @mui/utils:  5.5.3 
    @mui/x-data-grid:  5.8.0 
    @mui/x-data-grid-pro: 5.8.0 => 5.8.0 
    @mui/x-date-pickers: 5.0.0-alpha.6 => 5.0.0-alpha.6 
    @mui/x-license-pro:  5.7.0 
    @types/react: 17.0.16 => 17.0.16 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.2.3 => 4.2.3

**Comment by m4theushw** [comment] 2022-09-07 00:42
Duplicate of #4872 

Please subscribe to #4872 to get notified when it lands.

**Closed by m4theushw** 2022-09-07 00:42 UTC
Labels: duplicate, support: commercial
