### ISSUE TITLE
[DataGridPremium] Filtering on aggregated column with row grouping

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#9876] opened 2023-08-01 18:11 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/frosty-burnell-smdsgs?file=/Demo.tsx

### Current behavior 😯

The error is thrown:

```
TypeError
Cannot read properties of null (reading 'type')
```

### Expected behavior 🤔

No errors thrown

### Context 🔦

This is only reproducible on aggregated columns with row grouping or tree data.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment] 2023-08-01 18:14
This is a regression introduced in https://github.com/mui/mui-x/releases/tag/v6.9.1

6.9.0: https://codesandbox.io/s/frosty-burnell-smdsgs
6.9.1: https://codesandbox.io/s/twilight-firefly-nfms36

Most probably coming from https://github.com/mui/mui-x/pull/9254
cc @romgrk

**Comment by romgrk** [comment] 2023-08-03 15:13
Maybe duplicate of #9859.

**Closed** 2023-08-04 09:39 UTC
Labels: component: data grid, regression, feature: Filtering, feature: Row grouping, feature: Aggregation
