### ISSUE TITLE
Default hover style not visible on Chrome (Ubuntu 22.04, KDE Neon)

### ISSUE THREAD

**Issue by sagrawal-code** [mui/mui-x#8247] opened 2023-03-15 13:11 UTC
### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/w4u5zi?file=/demo.tsx (Example from docs, https://mui.com/x/react-data-grid/)

### Current behavior 😯

Here, the default hover style isn't visible in latest Chrome:

![Screenshot_20230315_183319](https://user-images.githubusercontent.com/1567103/225317785-928e999c-27fc-4b31-98a1-39d296d30e9c.png)

But it is visible in Firefox:

![Screenshot_20230315_183453](https://user-images.githubusercontent.com/1567103/225317820-313ec188-e882-4582-beca-5c764dcb6d71.png)

### Expected behavior 🤔

Default hover style should be visible in Chrome, as it does in Firefox. I can customize the style for `"& .MuiDataGrid-row.Mui-hovered"` via `sx`, which then works in Chrome.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 5.19 KDE neon 5.27 5.27
  Binaries:
    Node: 18.15.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.0 - /usr/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 110.0.1
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.121 
    @mui/core-downloads-tracker:  5.11.13 
    @mui/icons-material: ^5.11.11 => 5.11.11 
    @mui/material: ^5.11.13 => 5.11.13 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.13 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @mui/x-data-grid:  6.0.1 
    @mui/x-data-grid-generator: ^6.0.1 => 6.0.1 
    @mui/x-data-grid-premium:  6.0.1 
    @mui/x-data-grid-pro: ^6.0.1 => 6.0.1 
    @mui/x-license-pro:  6.0.1 
    @types/react: ^18.0.27 => 18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.9.3 => 4.9.5```
</details>


OS: 


Distributor ID:	Neon
Description:	KDE neon 5.27
Release:	22.04
Codename:	jammy
```

**Comment by sagrawal-idrc** [comment] 2023-03-17 02:35
> I can't reproduce the issue in Chrome. Could you share a video?



### No hover styling visible in Chrome:

[Untitled_ Mar 17, 2023 7_56 AM.webm](https://user-images.githubusercontent.com/16095774/225797587-e9c53ec1-22e3-4f52-9753-4f8c680ba242.webm)

### Hover styling visible in Firefox:

[screen-recorder-fri-mar-17-2023-07-59-26.webm](https://user-images.githubusercontent.com/16095774/225797666-cc1fd57b-9262-45c4-8bf3-9d4a9858e6e4.webm)

**Comment by flaviendelangle** [comment] 2023-03-17 15:09
Can't reproduce it on Ubuntu 22.04 Chrome Gnome

**Comment by sagrawal-code** [comment] 2023-03-18 03:19
Thanks for looking into this.

I investigated bit further and somehow my Chrome on Desktop Linux is reporting the hover media query to be `none` rather than `hover` and that seems to be the source of this issue.

![image](https://user-images.githubusercontent.com/1567103/226081686-e804b3d3-356b-42d7-83c5-2c16d00cc0c1.png)

I seem to be having the same issue as [this commentator](https://bugs.chromium.org/p/chromium/issues/detail?id=441613#c8). However, I am unable to fix this.

Please feel free to close this issue.

**Comment by oliviertassinari** [comment] 2024-01-10 15:00
In https://github.com/mui/mui-x/issues/10039#issuecomment-1732563283 I propose a different media query to accommodate mobile phones that return wrong values for these media queries, but looking at https://github.com/mui/mui-x/issues/8247#issuecomment-1474656074, it won't make much differences. 

I'm closing, it does look like an issue that should be fixed down the stack, and not in MUI X, e.g. https://bugs.chromium.org/p/chromium/issues/detail?id=441613#c8. Thanks for the report

**Closed by oliviertassinari** 2024-01-10 15:00 UTC
Labels: component: data grid, plan: Pro, external dependency
