### ISSUE TITLE
I can't access the 5v page of MUI-X

### ISSUE THREAD

**Issue by andreperegrina** [mui/mui-x#8155] opened 2023-03-07 03:12 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Go to [https://mui.com/x/react-data-grid/](https://mui.com/x/react-data-grid/)
2. Click on the v5 version

### Current behavior 😯

In redirect's you to version 6 of the page

### Expected behavior 🤔

Been able to go to the 5v

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment] 2023-03-07 06:04
Hey @andreperegrina, thank you for reporting the issue, the issue is known and will be fixed with this PR: https://github.com/mui/material-ui/pull/36421

Meanwhile, you can use this link to access v5 documentation: https://v5.mui.com/x/react-data-grid/

**Closed by MBilalShafi** 2023-03-07 06:04 UTC
Labels: status: needs triage
