### ISSUE TITLE
Format the Date to DD MM YYYY, entering the 31 to Jan, March, May, ..., Dec, but it falls back to 01 of the month

### ISSUE THREAD

**Issue by kianjun0929** [mui/mui-x#8539] opened 2023-04-07 01:07 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Change the format to DD MM YYYY
2. Enter from DD then MM then YYYY
3. Console the output while onChange
4. Result seems out of boundary and fall back to first day of the month
5. However, if the MM is set, then it will not fall back

### Current behavior 😯

![image](https://user-images.githubusercontent.com/41623077/230519928-d4952962-94c9-4cb1-8fd4-25cb692107df.png)

### Expected behavior 🤔

Should stay at 31st of Jan in onChange method

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment] 2023-04-07 06:59
Thank you for opening this issue! 🙏 
It seems to be a duplicate of https://github.com/mui/mui-x/issues/8485 which we are already looking into.
Closing this issue as a duplicate. Feel free to follow the mentioned issue for more information. 👌

**Closed by LukasTy** 2023-04-07 06:59 UTC
Labels: status: needs triage
