### ISSUE TITLE
[DatePicker] field/textField slotProps are not working as expected

### ISSUE THREAD

**Issue by jake-collibra** [mui/mui-x#8322] opened 2023-03-21 21:20 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Pass `slotProps={{ textField: { InputProps: { size: 'small' } } }}`.
2. Observe that the OpenPickerIcon no longer renders.
3. Pass `slotProps={{ field: { InputProps: { size: 'small' } } }}`.
4. Observe that the DatePicker renders as expected.
5. Observe that there is a type error because field.InputProps is typed to only take `ref`, `startAdornment`, and `endAdornment`.

### Current behavior 😯

If you pass InputProps in to the textField slot props it no longer renders the default end adornment.

`field.InputProps` has an extremely narrow (and inaccurate) type definition.

### Expected behavior 🤔

I should be able to pass in `InputProps.size` in either `field` or `textField` slot props without issue.

### Context 🔦

We are trying to properly style a "small" size date picker. It's entirely possible that we're just misusing slotProps, but from the source code it seems like the field props are in an in-between state.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser: Chrome

  System:
    OS: macOS 13.0.1
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: Not Found
    Firefox: 110.0.1
    Safari: 16.1
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.121
    @mui/core-downloads-tracker:  5.11.13
    @mui/icons-material: ^5.11.11 => 5.11.11
    @mui/lab: ^5.0.0-alpha.123 => 5.0.0-alpha.123
    @mui/material: ^5.11.13 => 5.11.13
    @mui/private-theming:  5.11.13
    @mui/styled-engine:  5.11.11
    @mui/system: ^5.11.13 => 5.11.13
    @mui/types:  7.2.3
    @mui/utils:  5.11.13
    @mui/x-date-pickers:  6.0.2
    @mui/x-date-pickers-pro: ^6.0.0 => 6.0.2
    @mui/x-license-pro: ^6.0.0 => 6.0.2
    @types/react: ^18.0.28 => 18.0.28
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5
```
</details>

**Comment by flaviendelangle** [comment] 2023-03-27 16:56
> One solution could be to move everything in the slotsProps as follow

I moved away for the `slotsProps` because they make custom field a lot harder to reason with.
The less we have in them, the better imho.

> // TODO: Move to useSlotProps when https://github.com/mui/material-ui/pull/35088 will be merged

The issue is that `useSlotProps` is only doing a shallow merge of the props (and some smart merge for `classname`, `ref` and some others).
The linked PR adds a way to say "the props A should be merged one level deeper".
My work-around was to manually to the merge outside of `useSlotProps` for those props.

___


For me the issue comes, as @alexfauquette said from the fact that you are using `props.slotProps.textField.InputProps`, which takes the precedence over `props.InputProps` that the field receives.

The solution can be do to like with my comment above and do a manual merge, while we wait for the core PR.

```diff
--- a/packages/x-date-pickers/src/DateField/DateField.tsx
+++ b/packages/x-date-pickers/src/DateField/DateField.tsx
@@ -19,7 +19,7 @@ const DateField = React.forwardRef(function DateField<TDate>(
     name: 'MuiDateField',
   });
 
-  const { components, componentsProps, slots, slotProps, ...other } = themeProps;
+  const { components, componentsProps, slots, slotProps, InputProps, ...other } = themeProps;
 
   const ownerState = themeProps;
 
@@ -31,6 +31,8 @@ const DateField = React.forwardRef(function DateField<TDate>(
     ownerState,
   });
 
+  textFieldProps.InputProps = { ...textFieldProps.InputProps, ...InputProps };
+
   const {
     ref: inputRef,
     onPaste,
```

But, as @alexfauquette said, in most scenario, you probably want to use `slotProps.field.InputProps`.

**Comment by flaviendelangle** [comment] 2023-03-29 09:27
> The first one is the typing of slotProps.field which for now is typed to get only the required props, but not all the customization possibility (slotProps.field.size is not recognized)

Indeed, adding the correct typing will be more complex because we will need to do it on each component (`useDesktopPicker` and the other equivalent hooks can't differentiate the props of `DateField` and `TimeField`).

**Comment by vincentp** [comment] 2023-04-11 16:46
Hi, I tried to upgrade @mui/lab to @mui/x-date-pickers today with the latest. Using the component DesktopDatePicker, I'm trying to set the slotProps.textField.InputProps.endAdornment parameter but it's never rendering it (startAdornment is working though). Is this ticket about this issue? Thanks

**Comment by LukasTy** [comment] 2023-04-12 05:46
> I'm trying to set the slotProps.textField.InputProps.endAdornment parameter but it's never rendering it (startAdornment is working though). Is this ticket about this issue? Thanks

Hi, could you please provide more details on what are you trying to achieve with the adornment?
If you would like to replace the icon itself, consider using `slots.openPickerIcon`, but if you only want to pass some additional props, then `slotProps.openPickerIcon` or `slotProps.inputAdornment` could do the trick, depending on which component you want to provide props for. 😉 
P.S. You can find the slots available for a component in the [API docs](https://mui.com/x/api/date-pickers/date-picker/#slots) and in turn, most components would have the same options for `slotProps`. 😉

**Comment by vincentp** [comment] 2023-04-12 06:24
My design is a bit more complicated than that as I have timezone and calendar icons on the left, clear or loading icons on the right. All working fine since several years using mui/lab by the way.

**Comment by LukasTy** [comment] 2023-04-12 07:09
Have you tried using both `startAdornment` (forthe timezone and calendar icons) as well as `slots.inputAdornment` to achieve this mentioned behavior?

**Comment by flaviendelangle** [comment] 2023-04-12 07:16
I'd be curious to have a reproduction case with the `@mui/lab` API to try migrating it to v6
Maybe we made some use cases harder along the way

**Comment by vincentp** [comment] 2023-04-12 08:19
Thanks for your help @LukasTy I managed to make it work using slotProps.textField.InputProps.startAdornment and slots.inputAdornment for the endAdornment.

**Comment by simplecommerce** [comment] 2023-04-12 10:21
I have the same issue on my end, I need to be able to use both start and end adornments and the reasoning was because my date field picker looks like this: 

![image](https://user-images.githubusercontent.com/31987945/231427044-4acce6dd-6244-40f4-992b-301db033a6a1.png)

When I click on the icon at the start, it gives me options:

![image](https://user-images.githubusercontent.com/31987945/231427170-8c720eea-ac37-4761-9317-2c210cfc3ade.png)

When I select one of the two last options it gives me the option to select a start and end date individually.

![image](https://user-images.githubusercontent.com/31987945/231427226-f5afc0fd-39d8-44bf-ab34-55fc5b4d1ae1.png)

I mainly use this for filtering my DataTable.
I didn't want to separate the action buttons because I wanted to save space and this way was best for us in our use case.

**Comment by JeomJeom** [comment] 2023-05-26 02:18
> Thanks for your help @LukasTy I managed to make it work using slotProps.textField.InputProps.startAdornment and slots.inputAdornment for the endAdornment.

@vincentp Are you using the `DatePicker` component? How did you manage to change the endAdornment on it? 
I have tried several ways, but none of it works. Could you provide a workaround?

**Comment by LukasTy** [comment] 2023-05-26 07:20
> Could anyone help me with this?

DatePicker and other single select pickers have [a separate slot](https://mui.com/x/api/date-pickers/date-picker/#:~:text=picker%20on%20desktop.-,OpenPickerIcon,-elementType) for that particular button and icon because they are designed to have a functioning icon.

This should do the trick. 🤞 
```tsx
<DatePicker
  slots={{
    openPickerIcon: BugReportIcon
  }}
/>
```

**Comment by JeomJeom** [comment] 2023-05-26 08:20
> > Could anyone help me with this?
> 
> DatePicker and other single select pickers have [a separate slot](https://mui.com/x/api/date-pickers/date-picker/#:~:text=picker%20on%20desktop.-,OpenPickerIcon,-elementType) for that particular button and icon because they are designed to have a functioning icon.
> 
> This should do the trick. 🤞
> 
> ```tsx
> <DatePicker
>   slots={{
>     openPickerIcon: BugReportIcon
>   }}
> />
> ```

Thanks @LukasTy for your prompt reply. That works perfectly fine on Material Icons.

But for my actual case, I need to use an icon that is saved in `.svg` format and I'm using `SvgIcon` wrapper. `openPickerIcon` seems to only accept `elementType`.

**Comment by LukasTy** [comment] 2023-06-02 10:56
> But for my actual case, I need to use an icon that is saved in `.svg` format and has converted into React Component. I used to pass it to `SvgIcon` wrapper, like `<SvgIcon component={XXX} />`, but `openPickerIcon` seems to accept `elementType` only.

Sorry for the late reply @JeomJeom.
I failed to understand what exactly are you trying to achieve.
Do you want to use `@mui/material/SvgIcon` component to wrap your imported svg file? How do you exactly do that, then expects svg props to be spread on the component? 🤔 
Could you provide a working example idea of what you are trying to achieve?
[Here is a demo](https://codesandbox.io/s/condescending-keller-zdjs6l?file=/demo.tsx) using `createSvgIcon` and passing that component ref to the slot.

**Comment by JeomJeom** [comment] 2023-06-02 11:01
> > But for my actual case, I need to use an icon that is saved in `.svg` format and has converted into React Component. I used to pass it to `SvgIcon` wrapper, like `<SvgIcon component={XXX} />`, but `openPickerIcon` seems to accept `elementType` only.
> 
> Sorry for the late reply @JeomJeom. I failed to understand what exactly are you trying to achieve. Do you want to use `@mui/material/SvgIcon` component to wrap your imported svg file? How do you exactly do that, then expects svg props to be spread on the component? 🤔 Could you provide a working example idea of what you are trying to achieve? [Here is a demo](https://codesandbox.io/s/condescending-keller-zdjs6l?file=/demo.tsx) using `createSvgIcon` and passing that component ref to the slot.

@LukasTy All good. I've sorted it out.  Thank you for your help.

**Comment by devChrisho** [comment] 2023-08-04 02:24
> 

I'm also facing a similar issue on changing the endAdorment icon. Previously in v4 date picker, I was able to pass a .svg via
```
endAdornment: <img src={DatePickerIcon} alt="Date Picker" />
```
Does it mean that for every svg, we will need to extract the path and create a new svg using `createSvgIcon`?

**Comment by LukasTy** [comment] 2023-08-04 09:06
> Does it mean that for every svg, we will need to extract the path and create a new svg using `createSvgIcon`?

No, you can provide any component that works for you. It's just that SVG is one of the best options.
In your case, consider creating a component for your icon and passing it as a reference to the slot.
This avoids any [remounting/performance issues](https://mui.com/x/react-date-pickers/custom-components/#recommended-usage).

```tsx
const CustomOpenPickerIcon = () => <img src="your_svg_path" alt="Date picker icon" width={24} />;
...
slots={{
  openPickerIcon: CustomOpenPickerIcon
}}
```

**Closed** 2023-09-01 07:39 UTC
Labels: bug 🐛, component: pickers

**Comment by Haridharan20** [comment] 2023-10-03 12:00
Hi,
I'm using react mui-x v6, i tried to use both onchange and slots props but the dropdown is not placed correctly on second touch


` const handleEventDateChange = (event) => {
    setInputEventDate(event);
  };

  const renderDateInputTextField =
    (showDateTooltip = false) =>
    (props) => {
      if (props && props.label === 'Time') {
        const timeToDisplay = props?.value + ' ' + timeZone;
        props = {
          ...props,
          value: timeToDisplay,
        };
      }

      return <TextField {...props} size="small" fullWidth />;
    }; 
<TimePicker
          label="Time"
          value={inputEventDate}
          onChange={(e) => handleEventDateChange(e)}
          slots={{
            textField: renderDateInputTextField(false),
          }}
  />
`

<img width="634" alt="Screenshot 2023-10-03 at 5 28 21 PM" src="https://github.com/mui/mui-x/assets/66022257/6020e276-ca66-4ddb-983f-219b28c9cc54">
<img width="458" alt="Screenshot 2023-10-03 at 5 26 59 PM" src="https://github.com/mui/mui-x/assets/66022257/76dc9549-e4df-4f84-a1dc-0698eea372ae">

in the second image, it is not relative to its parent  if I remove the onchange its works fine

**Comment by heath-freenome** [comment] 2024-09-26 18:18
@flaviendelangle I believe that closing this is not a good idea. We also using a `DatePicker` with a `component that wraps `TextField` and the `slotProps` passed from the `DatePicker` do not get passed through to the `TextField` via the `text` slotProps. Doing some debugging I am not seeing `slotProps` actually being passed into our text field, but rather `inputProps` and `InputProps`. It seems like the MUI 6 upgrade to `slotProps` isn't fully supported by the `x-date-pickers` library yet. This isn't good and closing it as not reproducible is clearly the wrong approach. I will try creating a minimal reproducible test case for you to work with. Please REOPEN

**Comment by satt-hri** [comment] 2025-03-06 07:05
i dont understand why
working 
```javascript
              slots={{
                        textField: TextField,
                      }}

```
and not working
```javascript
              slots={{
                        textField: (params) => {
                          return <TextField {...params} />;
                        },
                      }}
```
