### ISSUE TITLE
[DataGridPro] Pinned table header misalignment

### ISSUE THREAD

**Issue by sjobergjim** [mui/mui-x#10816] opened 2023-10-26 17:25 UTC
### Steps to reproduce

Link to live example: [sandbox demo](https://codesandbox.io/s/compassionate-chaplygin-m88rg6?file=/DemoTable.tsx)

Steps:
1. Open sandbox.
2. Mouse over the table headers.
3. Click any of the menu icons related to the headers (which should appear on mouse-over).
4. Pin any column to the right.
5. Notice the misalignment of the pinned column's header and its accompanying body cells.

### Current behavior

When you pin a column, the header will suffer a 17px misalignment compared to the rest of the column cells.

### Expected behavior

When you pin a column, the column's header and accompanying body cells should stay aligned.

### Context

I'm rendering a fairly simple table consisting of data rows with data corresponding to hours. I generate some of the columns and rows dynamically by mapping over an array containing which hours to include; other columns are name and total.

I've created a minimal implementation of this in the sandbox mentioned above (attaching image for better context).
![image](https://github.com/mui/mui-x/assets/67777321/fce6d44c-c7e6-4472-bd0c-a890cce786f3)

What appears to happen is that when the column is pinned, a `div` wraps its `header` and applies a padding of `17 pixels`. This is true regardless whether I use the `initialState`-prop to pin it or if done manually. The 17 pixels match the width of the `scrollbar` which would appear if the table were limited in height but it happens regardless of boundary limitations.

While troubleshooting, I managed to establish that it seems like the misaligned table cell renders multiple times and that the extra padding is attached during an update after the initial render.
In my application, I have a selection of zones and generate rows depending on that selection and noticed a peculiar behaviour where if I select let's say two zones, the table bugs out, if I remove one of them, it renders fine.

The pattern is as follows:
- select any number of zones => header misaligns
- remove any number of zones (corresponds to rows in the table) => header aligns nicely again
- if you select all zones, the header misaligns every time.
- every time you select more zones than a prior selection, the header misaligns

example:
```
select two zones => misalignment
remove one zone => aligns well
select one more zone => misalignment is back
select an additional extra zone => still misaligned
remove the additionally selected zone => aligns fine again
```
Using the pattern from the above example, it's possible to predictably determine when the header will or won't misalign.

Furthermore, the header seems to "flicker" in a sense that it renders in either of the two positions (aligned or misaligned) and then shifts to the incorrect position afterwards.
The rows and columns are memoized in my application.

### Your environment

env:
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 118.0.5993.90
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.61)
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-beta.21
    @mui/core-downloads-tracker:  5.14.15
    @mui/icons-material: ^5.14.12 => 5.14.14
    @mui/material: ^5.14.15 => 5.14.15
    @mui/private-theming:  5.14.15
    @mui/styled-engine:  5.14.15
    @mui/system:  5.14.15
    @mui/types:  7.2.7
    @mui/utils:  5.14.15
    @mui/x-data-grid:  6.16.3
    @mui/x-data-grid-pro: ^6.16.3 => 6.16.3
    @mui/x-date-pickers:  6.16.3
    @mui/x-date-pickers-pro: ^6.16.3 => 6.16.3
    @mui/x-license-pro:  6.10.2
    @types/react: ^18.0.15 => 18.0.15
    react: ^18.1.0 => 18.2.0
    react-dom: ^18.1.0 => 18.2.0
    typescript: ^5.1.6 => 5.2.2
```
</details>
Browsers were both Chrome and Firefox

**Search keywords**: datagrid, pinned, column
**Order ID**: 62012

**Comment by DanailH** [comment] 2023-11-01 09:45
Hi @sjobergjim this seems to be a duplicate of https://github.com/mui/mui-x/issues/10238. I'm closing this one in favor of the other issue. You can follow the status of the bugfix there.

**Closed by DanailH** 2023-11-01 09:45 UTC
Labels: status: waiting for maintainer
