### ISSUE TITLE
[data grid] Page row count to be set on child rows when row grouping is applied

### ISSUE THREAD

**Issue by dassoumyashree** [mui/mui-x#13639] opened 2024-06-26 16:21 UTC
### Summary

I am using the row grouping feature with mui premium. By default the total row count is calculated based on number of parent rows (top level rows). I need a way to set the page row count based on the number of child rows. Is there currently any way to do that?

**Search keywords**: page count count based on child rows with row grouping

**Comment by DanailH** [comment] 2024-07-04 09:37
@KenanYusuf this seems like it's a duplicate of https://github.com/mui/mui-x/issues/13638 and I just answered it. you can check how to do what you are requesting in the linked issue.

In future, I would advise you to check the docks before raising issues that are more like general questions instead of usability issues or bug reports.

**Closed by DanailH** 2024-07-04 09:37 UTC
Labels: component: data grid, status: waiting for maintainer, feature: Row grouping
