### ISSUE TITLE
[Datagrid] Can not close the menu with the menu icon button. 

### ISSUE THREAD

**Issue by mrishabh062** [mui/mui-x#8350] opened 2023-03-23 10:28 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. I opened the menu which contains field like show column, hide column, filtering, sorting using icon button which is present in the header.
2. When I again click the same button, so it should close that panel but it is not happening.
3. I want same menu icon button to use for opening and closing the panel.
![image](https://user-images.githubusercontent.com/112873983/227175612-428511ce-965c-47a6-adae-f17ac38267b2.png)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by joserodolfofreitas** [comment] 2023-03-23 14:37
Thanks for the report.
It's a duplicate of https://github.com/mui/mui-x/issues/8251.

**Closed by joserodolfofreitas** 2023-03-23 14:37 UTC
Labels: component: data grid, status: needs triage
