### ISSUE TITLE
[pickers] Let mask support variable number of digits

### ISSUE THREAD

**Issue by Filipeue** [mui/mui-x#4760] opened 2021-10-08 15:27 UTC
checkMaskIsValidForCurrentFormat is not respecting formats with variable number of digits
https://github.com/mui-org/material-ui/blob/e0cdcd130db60d252c4382570844ea7278649a08/packages/mui-lab/src/internal/pickers/text-field-helper.ts#L79

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

mask "\_\_/\_\_/\_\_\_\_" is marked as invalid if it doesn't match "\_/\_/\_\_\_\_" **and** "\_\_/\_\_/\_\_\_\_"

## Expected Behavior 🤔

mask "\_\_/\_\_/\_\_\_\_" is marked as invalid if it doesn't match "\_/\_/\_\_\_\_" **or** "\_\_/\_\_/\_\_\_\_"

## Steps to Reproduce 🕹

Follow the link and open console https://codesandbox.io/s/loving-monad-zut3e?file=/src/Demo.tsx

## Context 🔦

I am using default DatePicker with LocalizationProvider (date-fns adapter). It uses `format(new Date(), "P")` under the hood to get `utils.formats.keyboardDate`. So the dates rendering should be localized and masks automatically generated. But I am getting warning "The mask *"\_\_/\_\_/\_\_\_\_"* you passed is not valid for the format used *P*. Falling down to uncontrolled not-masked input." Even if I use my own mask respecting the localized format warning persists.
So we have 2 issues:
1. Masks are not generated according to locale settings (https://github.com/mui-org/material-ui/issues/28871)
2. Masks with variable digits raise warning and disable masked input

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    Memory: 1.30 GB / 19.89 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 21.1.3 - D:\Program Files\Programs\Python\Python39\Scripts\pip3.EXE
  Utilities:
    Git: 2.32.0.
  Virtualization:
    Docker: 20.10.8 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.19041.0
  IDEs:
    VSCode: 1.60.0 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\Windows\system32\bash.EXE
    Python: 3.9.6
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.38)
    Internet Explorer: 11.0.19041.1202
```
</details>

**Comment by alexfauquette** [comment] 2022-05-04 11:35
This issue is related to #4487

It is not a bug, be an enhancement. Mask does not support variable number of digits to avoid edge cases such as the user enters "01/03/1" and then it switches to "1/3/1" because the date engine recognized `Date(0001, 3, 1)` which will be formatted

The portion of code which has been pointed is here to inactivate mask if your format has variables digit number

**Comment by flaviendelangle** [comment] 2023-02-01 13:53
I am closing this issue.

We recently launched the first beta of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` v6.x.
This new version contains a full rework of the input editing.
You can have a look at [the v6 doc](https://next.mui.com/x/react-date-pickers/time-picker/) which is currently in beta and the [related blog post](https://mui.com/blog/v6-beta-pickers/).

We won't apply complicated (and not always doable) fixes to the v5 version, I hope this new version solves your problem.

**Closed by flaviendelangle** 2023-02-01 13:53 UTC
Labels: new feature, component: pickers, feature: Mask editing
