### ISSUE TITLE
Hey Mui Community! Requesting your support for a lifetime license of X-Data-Grid-Pro. Let's show Mui how valuable this option would be for dedicated users like us! 🙌

### ISSUE THREAD

**Issue by mishal-z** [mui/mui-x#9123] opened 2023-05-26 08:42 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The lifetime license for X-Data-Grid-Pro should provide users with perpetual access to the software, including all future updates, enhancements, and technical support. It ensures uninterrupted usage and allows users to maximize productivity in the long term without the need for recurring license renewals. This option demonstrates Mui's commitment to customer satisfaction and fosters a strong and enduring partnership with their dedicated user base.

**Comment by oliviertassinari** [comment] 2023-05-26 10:07
Duplicate of https://mui.zendesk.com/agent/tickets/8749

**Closed by oliviertassinari** 2023-05-26 10:07 UTC
Labels: duplicate

**Comment by mishal-z** [comment] 2023-05-26 12:12
> Duplicate of https://mui.zendesk.com/agent/tickets/8749

@oliviertassinari The page doesn't exist. Can you please reshare the link

**Comment by oliviertassinari** [comment] 2023-05-26 13:13
Right, this link is only accessible to MUI's staff. For requester, once you logging with your account you can access https://support.mui.com/hc/requests/8749 (open by a Mishal Z.)
